### ISSUE TITLE
Unable to start Homestead nginx after installing Laravel Valet

### ISSUE THREAD

**Issue by ligne13** [laravel/homestead#1004]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.1.3
  - Provider: Virtualbox 5.2.22 r126460 (Qt5.6.3)
  - Homestead: 6.3.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Mac OS 10.14.2 Mojave

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Documents/Work/_Sites
      to: /home/vagrant/code

sites:
    - map: home
      to: /home/vagrant/code

backup: true
```

Hi
since I installed Laravel Valet on my Mac, my Homestead nginx, which I installed and used with success before, does not start anymore :

> homestead-7: Job for nginx.service failed because the control process exited with error code.
    homestead-7: See "systemctl status nginx.service" and "journalctl -xe" for details.

And here's what the output of `systemctl status nginx.service` :

> vagrant@homestead:~$ systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-12-14 16:22:21 +01; 22s ago
     Docs: man:nginx(8)
  Process: 4570 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
  Process: 4563 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
Dec 14 16:22:19 homestead nginx[4570]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 14 16:22:19 homestead nginx[4570]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 14 16:22:20 homestead nginx[4570]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 14 16:22:20 homestead nginx[4570]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 14 16:22:20 homestead nginx[4570]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 14 16:22:20 homestead nginx[4570]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 14 16:22:21 homestead nginx[4570]: nginx: [emerg] still could not bind()
Dec 14 16:22:21 homestead systemd[1]: nginx.service: Control process exited, code=exited status=1
Dec 14 16:22:21 homestead systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 14 16:22:21 homestead systemd[1]: Failed to start A high performance web server and a reverse proxy server.

I suspect a conflict between ports... Still the problem remains even if I run `valet stop` and 'homestead up`.

Please help ?

**Comment by svpernova09** [comment]
I think it's `brew services` where you can manually start/stop the services that valet is using. I would give that a try.

**Comment by svpernova09** [comment]
Closing until we get more / better info for debugging.
