### ISSUE TITLE
No input file specified with apache

### ISSUE THREAD

**Issue by Paviluf** [laravel/homestead#1010]
I use apache and on master I have this error when I try to go to my site: "No input file specified"
There is this error on provisionning
``` 
homestead-7: Job for nginx.service failed because the control process exited with error code.
homestead-7: See "systemctl status nginx.service" and "journalctl -xe" for details.
```
It work well on tag v7.19.2 (tag v7.20.0 doesn't exist)
Thanks !

**Comment by Paviluf** [comment]
I was on v7.19.2 and tried master when the error occured. Should we do `bash init.sh` again when we change branch ?

**Comment by svpernova09** [comment]
> I was on v7.19.2 and tried master when the error occured. Should we do bash init.sh again when we change branch ?

No.

**Comment by svpernova09** [comment]
Please open a new issue and fill out the issue template as requested. There is no way to help you until you help _us_ help *you*
