### ISSUE TITLE
Feature request: Allow using environment variables in Homestead.yaml

### ISSUE THREAD

**Issue by vernondegoede** [laravel/homestead#1012]
It would be awesome if we could use environment variables within our `Homestead.yaml` file. Our use case is: we use SSH keys and specify them in our homestead file:

```
# Homestead.yaml

[...]
authorize: ~/.ssh/id_rsa_my_key.pub

keys:
    - ~/.ssh/id_rsa_my_key
[...]
```

This works great, but doesn't scale well across multiple team members. Since all of our employees have a different SSH key name, it would be nice if we could use an environment variable and inject those in our Homestead file.

It would be great if our file would look like this:

```
# .env
SSH_KEY_NAME=id_rsa_my_key
```

```
# Homestead.yaml

[...]
authorize: ~/.ssh/${SSH_KEY_NAME}.pub

keys:
    - ~/.ssh/${SSH_KEY_NAME}
[...]
```

**Comment by browner12** [comment]
Is this on a per-project install, or the global install?

**Comment by vernondegoede** [comment]
It would make sense to either load from `'./.env` or load the globally set env variables.

**Comment by svpernova09** [comment]
If you're wanting access to env variables in the Homestead VM itself you should set (and make sure they're persisted) via your shell of choice utilizing `after.sh`
