### ISSUE TITLE
Can't install Phpmyadmin with after.sh

### ISSUE THREAD

**Issue by Paviluf** [laravel/homestead#1015]
I try to install phpmyadmin with after.sh but the provisioning hang when the system ask to keep or to overwrite what it seem to be php7.2 original configuration. I use `Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"` to avoid this, it work well for phpmyadmin itself but not for the dependency. I hope you can help me. Thanks !
```
mysqlpassword="secret"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password $mysqlpassword"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-user string root"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password $mysqlpassword"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password $mysqlpassword"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install phpmyadmin
```

**Comment by svpernova09** [comment]
With such limited info, I'm not going to be much help. We use `sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew"` in places to get around the config file changes.

You always (I'm yet to run into a case where you wouldn't) want to keep the existing config changes.
