### ISSUE TITLE
8.0.0 tag should be v8.0.0

### ISSUE THREAD

**Issue by brandonkelly** [laravel/homestead#1044]
Homestead 8.0.0 was tagged as `8.0.0` instead of `v8.0.0` like all the other tags.

Even the [Updating Homestead docs](https://laravel.com/docs/5.7/homestead#updating-homestead) assume the tag name was `v8.0.0`. Copying that exact code will result in a `pathspec 'v8.0.0' did not match any file(s) known to git.` error.

**Comment by svpernova09** [comment]
Resolved via https://github.com/laravel/homestead/releases/tag/v8.0.1

**Comment by svpernova09** [comment]
I didn't want to re-tag the release so we didn't confuse anyone. Since we already had some pending changes I just tagged v8.0.1
