### ISSUE TITLE
vagrant up: [ErrorException]  rename(/home/vagrant/.composer/cache/composer-temp.phar,/usr/local/bin/composer): Permission denied

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/homestead#1049]
## Versions
  - Vagrant: Vagrant 2.2.3
  - Provider: hyper-v
  - Homestead: v8.0.1

## Host operating system
Windows 10 Pro x64

## Vagrant up output
[ErrorException] rename(/home/vagrant/.composer/cache/composer-temp.phar,/usr/local/bin/composer): Permission denied

## Expected behavior
Composer should be updated

## Steps to reproduce
1. https://laravel.com/docs/5.7/homestead#installation-and-setup
2. `vagrant up`

**Comment by svpernova09** [comment]
Please fill out the issue template entirely so there is a chance that someone can help you.
