### ISSUE TITLE
DNS queries do not work from inside Homestead

### ISSUE THREAD

**Issue by browner12** [laravel/homestead#1054]
## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox 6.0.4
  - Homestead: 7.0.0

## Host operating system
MacOS Mojave 10.14.3

## Homestead.yaml
I don't believe this is relevant for the issue.

## Vagrant destroy & up output
This is not a provisioning issue.

## Expected behavior
PHP functions that make DNS queries, like `dns_get_record()` should be able to retrieve results from inside the Homestead guest machine.

## Actual behavior
The PHP functions return `false` or an error.

## Steps to reproduce

If you're running a Laravel app, I've found the easiest thing to do is create a console command. This gives us the ability to run the code in both the host and guest.

1. `php artisan make:command DnsCheck`
2. Use the following code in the `handle()` method of your new command:

```php

foreach(['laravel.com', 'google.com', 'github.com'] as $index => $referrer) {

    $nameservers = dns_get_record($referrer, DNS_A | DNS_NS);

    $records[] = [
        'index'       => $index,
        'domain'      => $referrer,
        'a'           => $nameservers[0]['ip'] ?? 'N/A',
        'nameserver1' => $nameservers[1]['target'] ?? 'N/A',
        'nameserver2' => $nameservers[2]['target'] ?? 'N/A',
    ];
}

$this->table(['#', 'Domain', 'A', 'NS1', 'NS2'], $records);
```

3. Run the command in both your host and guest to compare the differences:

```sh
php artisan dnscheck
```

## References
@svpernova09 and I discussed this briefly on Slack, opening an issue so we have a record of it.

**Comment by svpernova09** [comment]
Ah!

https://www.vagrantup.com/docs/virtualbox/common-issues.html

>  DNS Not Working
>
>If DNS is not working within your VM, then you may need to enable a DNS proxy (built-in to VirtualBox). Please see the StackOverflow answers here for a guide on how to do that.

Apparently it's a Virtualbox thing. I wasn't able to find anything that would look like a fix :(
