### ISSUE TITLE
Per project installation fails due to missing PHP extensions.

### ISSUE THREAD

**Issue by kevindecapite** [laravel/homestead#1062]
## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox 5.2.22 r126460 (Qt5.6.3)
  - Homestead: Installation attempted with `composer require laravel/homestead --dev` which displays __Using version ^8.1 for laravel/homestead__.

## Host operating system
macOS Mojave 10.14.2

## Homestead.yaml
N/A

## Vagrant destroy & up output
N/A

## Expected behavior
According to the docs (https://laravel.com/docs/5.7/homestead#per-project-installation), I should be able to install Homestead via composer into my project's directory, then issue the `make` command to configure.

## Actual behavior
Full output from the composer require command:

```
Using version ^8.1 for laravel/homestead
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-calendar ^7.2 has the wrong version (7.1.19) installed. Install or enable PHP's calendar extension.
  Problem 2
    - The requested PHP extension ext-json ^1.6 has the wrong version (1.5.0) installed. Install or enable PHP's json extension.
  Problem 3
    - cakephp/cakephp 3.7.3 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.7.3 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.7.3 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - Installation request for cakephp/cakephp (locked at 3.7.3, required as 3.7.*) -> satisfiable by cakephp/cakephp[3.7.3].


Installation failed, reverting ./composer.json to its original content.
```

## Steps to reproduce
1. Require either of the extensions listed above in your `composer.json` file.
2. Run `composer require laravel/homestead --dev`.

**Comment by kevindecapite** [comment]
I assume this is because composer is trying to satisfy the requirements within my host system (macOS), which does not contain the updated versions of those extensions. So this appears to be a "chicken or the egg" situation where I'm required to have the updated dependencies _before_ installation the box that has the updated dependencies.

**Comment by svpernova09** [comment]
Yes, for the per project installation method you will *have* to have everything your `composer.json` requires installed and configured for PHP.

**Comment by kevindecapite** [comment]
Makes sense technically, but sort of prevents having a portable dev environment. I was able to get around it by using the `--ignore-platform-reqs` option in composer.

**Comment by svpernova09** [comment]
Glad you got around it. 

Per project was never meant to be about portability, it was meant to be a way to easily ship your environment with your code to your contributors.
