### ISSUE TITLE
Random blank page

### ISSUE THREAD

**Issue by JmRy** [laravel/homestead#1063]
Hello,

Since the Homestead 8.1 update, the server is sending randomly blank pages. Never the same, 5 minutes without problems, then send a blank on any page.

No error message in Nginx and fpm logs

When the page is blank, you need at least 5 reminders (F5 browser) to get a full complete page

Updated VirtualHost Addition 6.0.4 version -> Same result
Updated Enable cgi.fix_pathinfo to 1 -> Same result
Network test -> OK
Add nameservers on box -> Same results

Thank you for your help, because here I dry ;-)

## Versions
  - Vagrant 2.2.3
  - Virtualbox 6.0.4
  - Homestead 8.1

## Host operating system
OSx Mojave 10.14.3 on Mac Mini i7 3.2Ghz RAM 32Go

## Homestead.yaml
ip: 192.168.56.6  # IP principale de votre box
networks:
    - type: public_network
      ip: 192.168.10.18
      bridge: "en0: Ethernet"
memory: 3092
cpus: 2
provider: virtualbox
natdnshostresolver: off # Corrige l'erreur IPV6 sur la règle de validation active_url
mariadb: true
postgresql: false
backup: false
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: ~/Projets/hpa.guide/
        to: /home/vagrant/code/hpaguide/
    -
        map: ~/Projets/Dolibarr/dolibarr-8.0.3/
        to: /home/vagrant/code/dolibarr/
sites:
    -
        map: hpaguide.local
        ip: 192.168.10.18
        to: /home/vagrant/code/hpaguide/www/public
    -   
        map: pro.hpaguide.local
        ip: 192.168.10.18
        to: /home/vagrant/code/hpaguide/pro/public
    -
        map: dolibarr.local
        ip: 192.168.10.18
        to: /home/vagrant/code/dolibarr/htdocs
databases:
    - homestead
    - hpagv10
    - hpagwp
    - dolibarr
    

## Vagrant destroy & up output
https://gist.github.com/JmRy/d642db71aa10934141733884f721701c

**Comment by svpernova09** [comment]
I don't see anything alarming in your logs. I would try to remove your public network interface and ip on the sites and run `vagrant destroy && vagrant up` again to see if the issue remains.

**Comment by JmRy** [comment]
I delete network line. Now only directly Box IP 192.168.56.6.
destroy and up -> Same result ...

**Comment by JmRy** [comment]
Test downgrade php 7.2 -> Same result

**Comment by JmRy** [comment]
**Problem solved.**

Possible cause: 
- Update corruption Mojave 10.14.3
- Incompatibility with Virtualbox 6.0.4 or bad brew virtualbox 6 install

After many tests, I got stability with this solution:
- Reinstall Mojave with network system to get the latest image
- Virtualbox downgrade 5.26 version
- Homestead 7.20.0 downgrade version
