### ISSUE TITLE
how to change the ngrok to other ngrok

### ISSUE THREAD

**Issue by qingchendelaike** [laravel/homestead#1065]
## how to change the ngrok to other ngrok?

i change  the ngrok to other people deploy's ngrok, but port 4040 isn't access in outside browser. only access the port 4040 in homestead.

**Comment by svpernova09** [comment]
You can add ports via info in the docs: https://laravel.com/docs/homestead#ports

**Comment by qingchendelaike** [comment]
I had watched the doc. I had added  the ports like this:
![image](https://user-images.githubusercontent.com/13976813/53095830-b5807680-3558-11e9-8ac2-958e6d35e7d4.png)
but http://192.168.10.10:4040 or http://domain:4040 don't work.

**Comment by svpernova09** [comment]
You have too many spaces between `ports:` and the next line `- send: 4040`

Try this:

```
ports:
  - send: 4040
    to: 4040
```

or

```
ports:
    -
        send: 4040
        to: 4040
```

**Comment by jonnywilliamson** [comment]
I thought this was already done? One of the ports already configured?

https://github.com/laravel/homestead/pull/685/files
