### ISSUE TITLE
Ruby version error when using Rails CLI

### ISSUE THREAD

**Issue by fitztrev** [laravel/homestead#1067]
## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox
  - Homestead: 8.1.0
  - Settler box: 7.1.0

Brand new, fresh Homestead box. I'm getting a Ruby version error when I try to use a Rails app:

### Steps to Reproduce

```
$ rails new test-app
$ cd test-app

// These all fail with the below error message
$ rails console
$ rails test
$ rails generate
```

### Error Output

```
rbenv: version `ruby-2.5.1' is not installed (set by /home/vagrant/testapp/.ruby-version)
```

**Comment by svpernova09** [comment]
I'm far from a rails expert. We don't install ruby 2.5.1 anymore, we install 2.6.1. I poked a bit and wasn't able to sort out anything. PRs from anyone who can resolve this is welcome.
