### ISSUE TITLE
Pagespeed module

### ISSUE THREAD

**Issue by MrRoco** [laravel/homestead#1072]
I would love to see nginx pagemodule in the homestead.
https://github.com/apache/incubator-pagespeed-ngx

**Comment by svpernova09** [comment]
Go for it. Let's see what a PR looks like. Bonus points if it's something we can easily toggle on or off on a per site basis.

**Comment by svpernova09** [comment]
Closing as inactive but to be clear: I am interested in a PR that would implement this.
