### ISSUE TITLE
New 6.4.1 box to fix blackfire repo error

### ISSUE THREAD

**Issue by Paviluf** [laravel/homestead#1074]
Would it be possible to have a tiny update to the 6.4.0 box like 6.4.1 to fix the blackfire repo error ? https://github.com/laravel/settler/pull/184
For those who have to keep using 6.4.0 for php 5.6 and 7.0 it will avoid to manually "fix" the problem every time they create a new vm. Thank you.

**Comment by svpernova09** [comment]
The Laravel Homestead project will only ever support current versions of PHP supported by php.net.

What you're looking for sounds like a side project I just launched: https://www.joeferguson.me/homestead-fifty-six/
