### ISSUE TITLE
Argon

### ISSUE THREAD

**Issue by thferreira** [laravel/homestead#1077]
Latest Version
- Vagrant
- Homestead
- Virtual Box
- Windows 10
- PHP 7.3

The problem is
Use of undefined constant PASSWORD_ARGON2ID - assumed 'PASSWORD_ARGON2ID'

**Comment by svpernova09** [comment]
We can't help you until you fill out the entire issue template. Please fill out the template properly and completely if you require assistance.

**Comment by thferreira** [comment]
My template is default. I use documentation laravel 5.8 to install
