### ISSUE TITLE
Homestead yml have a problem with restarting nginx and inserting a php in it

### ISSUE THREAD

**Issue by Nebojsaa** [laravel/homestead#1083]
So I am trying to get to have a fully functioning site, but once as I start vagrant with this command " vagrant up || vagrant reload --provision" all I have from the 
**Edit**: I was probably ambigious and vague. So I am using one of those commands at the time. To be clear, I am going to add in here "vagrant reload --provision".
After I do as svpernova09 suggested vagrant destroy && vagrant up - 
I have this: 
https://gist.github.com/Nebojsaa/1e17858eb4301b37bc7a5c8768646d67
I believe that this is coming from vagrant which isn't installed properly. I have created the ~/symfony-01 and I have followed and installed the ifupdown .

So when I restart my vagrant it "as described in the second line" it is unable to unmount which means that I probably don|t have a connection between vagrant and my machine, but my machine can see that this is online.

I am using ubuntu 18.04 as my localhost with virtualBox "as suggested".
https://gist.github.com/Nebojsaa/e88a68c77a3838199e2db931bf3c4dad
~                    

## Vagrant destroy & up output
https://gist.github.com/Nebojsaa/10290006e44e7a875f33b68432589056

## Expected behavior
I would like if i can access my site from this address in the google chrome: 192.168.10.10

## Actual behavior
No input file specified.

**Comment by svpernova09** [comment]
Don't do this: `vagrant up || vagrant reload --provision`

Instead do this:

`vagrant destroy && vagrant up` and paste the *entire* contents to a new gist.github.com please.

Also paste the contents of your `after.sh` here, but surround the block with three `

**Comment by Nebojsaa** [comment]
Thanks svpernova09 for the suggestions.

**Comment by svpernova09** [comment]
You're also using a really old version of vagrant which may be the issue. Try downloading and installing a newer version from vagrantup.com (as opposed to what your OS is providing)

**Comment by Nebojsaa** [comment]
So this is vagrant look after I upgrade it. 
https://gist.github.com/Nebojsaa/1abe54bb315b994b3e7d27640026e300

**Comment by svpernova09** [comment]
@Nebojsaa 

Here's the clue to what's wrong: https://gist.github.com/Nebojsaa/1abe54bb315b994b3e7d27640026e300#file-vagrant-after-upgrading-L71-L72

```
homestead-7: Failed to restart php5.6-fpm.service: Unit php5.6-fpm.service not found.
homestead-7: Failed to restart php7.0-fpm.service: Unit php7.0-fpm.service not found.
```

This means your Homestead version (The Homestead repo) is older than the base box version (the base box version can be seen via `vagrant box list`.

I would update to v8.2.0 (or whatever the latest tagged version is) and then run `vagrant destroy && vagrant up` again.

**Comment by browner12** [comment]
please run this command inside your Homestead folder and reply with the output

```sh
vagrant box list
```

**Comment by Nebojsaa** [comment]
nebo@nebo: vagrant box list
laravel/homestead (virtualbox, 7.1.0)

**Comment by svpernova09** [comment]
From the folder you're running `vagrant up` from

```
vagrant destroy -f
rm -rf .vagrant
```

Open up Virtualbox. Right click and remove (delete all files) the virtual machine.

Go back to Vagrant:

```
vagrant up
```

and show us the log from `vagrant up`

**Comment by browner12** [comment]
ok, so if I'm following correctly, you have

- Virtualbox 6.0
- Vagrant 2.2.4
- Homestead 7.1.0

which are all the latest versions of thing.  Makes me confused why you're still getting PHP 5.6 and 7.0.

@svpernova09 s suggestion is probably the fix.  Occasionally Vagrant/Virtualbox can get some junk left behind that causes issues.  I've definitely run into this before, and just have to manually delete some files to get it to provision correctly again.

**Comment by Nebojsaa** [comment]
nebo@nebo-ThinkPad-L560:~/homestead$ vagrant destroy -f
==> homestead-7: Destroying VM and associated drives...
nebo@nebo-ThinkPad-L560:~/homestead$ rm -rf .vagrant
nebo@nebo-ThinkPad-L560:~/homestead$ vagrant up
https://gist.github.com/Nebojsaa/ba3d53fca3c1f2abaabc2ed3b4ee7dec

In the meantime, after doing vagrant destroy, I couldn`t see the machine in virtual box. Is this maybe my trouble ?

**Comment by browner12** [comment]
When you destroy it, it should be completely removed from your system, so you wouldn't see it in the Virtualbox GUI.

**Comment by Nebojsaa** [comment]
@browner12 and @svpernova09 do you know what happened here since I can`t find solution to my problem ?

**Comment by browner12** [comment]
another suggestion. destroy your virtual machine, and then restart your computer. then try provisioning homestead again.

whenever I run into these weird virtualbox/vagrant issues, this fixes is more times than I can count.

**Comment by svpernova09** [comment]
When you did this process:

```
nebo@nebo-ThinkPad-L560:/homestead$ vagrant destroy -f
==> homestead-7: Destroying VM and associated drives...
nebo@nebo-ThinkPad-L560:/homestead$ rm -rf .vagrant
```
THIS IS where you should have opened Virtualbox and deleted any VMs that show (that are homestead).

Can you confirm no VMs were showing in the Virtualbox GUI
```
nebo@nebo-ThinkPad-L560:/homestead$ vagrant up
https://gist.github.com/Nebojsaa/ba3d53fca3c1f2abaabc2ed3b4ee7dec
```

> then try provisioning homestead again.

When we're trying to debug VM start up issues it will be helpful to note we don't want or intend people to do `vagrant provision`, we want them to do `vagrant destroy && vagrant up` that way we're 1,000% sure of the start condition of the box.

> another suggestion. destroy your virtual machine, and then restart your computer. then try provisioning homestead again.

Agreed. Possibly would go so far as to remove Virtualbox, Vagrant, reboot, reinstall virtualbox, vagrant, make sure no `.vagrant` folder is in Homestead. Then reboot and try `vagrant up`.

If you're feeling especially froggy you can follow these steps and show me the output. You'll likely get errors but this will tell us if Virtualbox is funcitonal on your system or not:

```
cd path/to/homestead
cd ..
mkdir teststead
cd teststead
vagrant init laravel/homestead --provider=virtualbox
vagrant up
```
Paste a gist of the output.

**Comment by Nebojsaa** [comment]
Once as I remove everything in an order as suggested above, I come to the same message as the last time. 
https://gist.github.com/Nebojsaa/ba3d53fca3c1f2abaabc2ed3b4ee7dec

And once I do the last suggested by @svpernova09 
https://gist.github.com/Nebojsaa/6723448cb8616e976c63c0744b9be5d4

**Comment by svpernova09** [comment]
> And once I do the last suggested by @svpernova09
https://gist.github.com/Nebojsaa/6723448cb8616e976c63c0744b9be5d4

Oops, try that again but you don't need `--provider=virtualbox`

**Comment by Nebojsaa** [comment]
It`s the same message as the last time. 
https://gist.github.com/Nebojsaa/47112677086a1212afa539600266881c

**Comment by Nebojsaa** [comment]
@svpernova09 and @browner12 Please, help!

**Comment by svpernova09** [comment]
@Nebojsaa,

Unfortunately this tells me that Virtualbox is not running correctly on your system. I can't help much here. Since vagrant is operating correctly on the teststead folder we can see that the source of the issue is Virtualbox. My suggested next steps for you would be to run searches looking for this error message + your OS + OS version and see if anyone else is running into these issues. Sorry we couldn't be more help.

Once you get Virtualbox sorted out let us know if you continue having any issues with Homestead.

**Comment by browner12** [comment]
You could try switching back to Virtualbox v5
