### ISSUE TITLE
When installing oh-my-zsh, it should set the default terminal to zsh too ?

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1099]
When installing oh-my-zsh, it should set the default terminal to zsh too, or it should remain the bash ?
If it should be set to zsh, I'm happy to provide a PR.

**Comment by deviantintegral** [comment]
Since oh-my-zsh is opt-in, 👍 to automatically switching the shell from me.

**Comment by svpernova09** [comment]
I'm fine with it auto setting default.
