### ISSUE TITLE
 Vagrant up - SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by TerrePorter** [laravel/homestead#1106]
URL: ["https://vagrantcloud.com/laravel/homestead"]
Error: SSL certificate problem: self signed certificate in certificate chain

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
$ vagrant -v
Vagrant 2.2.4

  - Provider: Virtualbox, VMWare or Parallels and its version.
VirtualBox Graphical User Interface
Version 6.0.6 r130049 (Qt5.6.2)

  - Homestead: Run `homestead --version` to show the version.
8.3.1

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

Did all three.

## Host operating system
Windows 10

## Homestead. json 
```json
{
    "ip": "192.168.10.10",
    "memory": 4096,
    "cpus": 2,
    "provider": "virtualbox",
    "authorize": "C:\\local_devel\\.ssh\\id_rsa.pub",
	"hostname": "hs831c",
	"name": "hs831c",
    "keys": [
        "C:\\local_devel\\.ssh\\id_rsa"
    ],
	"aliases": [
		"phptesting.lan"
	],
    "folders": [
        {
            "map": "C:\\local_devel\\_MySQL_Backups",
            "to": "/home/vagrant/MySQL_Backups"			
        },
        {
            "map": "C:\\local_devel\\Code",
            "to": "/home/vagrant/Code",
			"type": "nfs",
			"mount_options": ["nolock,vers=3,udp,noatime,actimeo=1"]
        }
    ],
    "sites": [
		{
			"map": "phptesting.lan",
			"to": "/home/vagrant/Code/phptesting/public"
		}
    ],
    "databases": [
        "homestead"
    ]
}
```

## Vagrant destroy & up output
N/A 

## Expected behavior
I would expect it to download the virtual box file.

## Actual behavior
$ vagrant up
Bringing machine 'hs831c' up with 'virtualbox' provider...
==> hs831c: Box 'laravel/homestead' could not be found. Attempting to find and install...
    hs831c: Box Provider: virtualbox
    hs831c: Box Version: >= 7.2.1
The box 'laravel/homestead' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/laravel/homestead"]
Error: SSL certificate problem: self signed certificate in certificate chain

## Steps to reproduce
1. Download Homestead release from github
2. Configure Homestead.json
3. Vagrant up

## References
I could find not existing references in GitHub.

**Comment by TerrePorter** [comment]
Ok so I took some time this morning to investigate the issue i was having. After some debugging, it appears this is a anti-virus being a pain in the butt.

I have Kaspersky, and it has this nifty feature to scan SSL sites, it does this by injecting its own SSL cert (which happens to be self-signed).

Anyways, disabling the SSL scanning made everything work.

Reference, for anyone else who ended up here:
https://github.com/curl/curl/issues/3588
https://forum.kaspersky.com/index.php?/topic/408518-bash-shell-windows-10-httpsssl-not-working/

**Comment by AleksKost** [comment]
Thanks!

**Comment by ssbarnea** [comment]
Apparently that is caused by https://github.com/hashicorp/vagrant/issues/11120 https://github.com/hashicorp/vagrant/issues/10363

**Comment by fiver-watson** [comment]
Just saved me a big headache - thank you!

**Comment by suwidadi** [comment]
thanks @adeluna84 this works for me, using vagrant 2.2.7

**Comment by fadykuzman** [comment]
I also have Kaaspersky on my work laptop and not allowed to pause it or shut it down.
So thanks @adeluna84

**Comment by dkuhndba** [comment]
Ran into a similar issue. SSL error when running "vagrant up".  First tried putting this line in the Vagrantfile:
config.vm.box_download_insecure =true

Ran "vagrant up" again, and it threw a URL error. So I manually downloaded the json file from oracle.github.io, 7.json file, and put it in the same directory as the Vagrantfile. And ran "vagrant up", and it worked.

**Comment by l7rf1i82** [comment]
dkuhndba, thank you. save my time

**Comment by Hromz** [comment]
thx, you saved me!

**Comment by swissmant** [comment]
> Ran into a similar issue. SSL error when running "vagrant up". First tried putting this line in the Vagrantfile: config.vm.box_download_insecure =true
> 
> Ran "vagrant up" again, and it threw a URL error. So I manually downloaded the json file from oracle.github.io, 7.json file, and put it in the same directory as the Vagrantfile. And ran "vagrant up", and it worked.

Thanks dkuhndbba. Adding the box_download_insecure flag worked for me. For anyone trying this, I added it into this section:
`

    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.box_download_insecure = true
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end
`
