### ISSUE TITLE
Fix lvm volume group name for lmm

### ISSUE THREAD

**Issue by deviantintegral** [laravel/homestead#1112]
```
vagrant@REDACTED:~$ sudo lmm status
Active snapshot:

Database snapshots:
  master
  Volume group "vagrant-vg" not found
  Cannot process volume group vagrant-vg

% used by MySQL databases.
(standard_in) 1: syntax error
/opt/lmm/functions.sh: line 48: [: -eq: unary operator expected
```

When we fixed builds at https://github.com/laravel/homestead/issues/1071#issuecomment-485154215 to create a specific `homestead-vg` volume group, we didn't update `/opt/lmm/config.sh` with the new name. I need to fix this, or make it a proper environment variable that we can set.

**Comment by svpernova09** [comment]
I used homestead-vg for simplicity sake. Let’s stick with that?

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by m4olivei** [comment]
I also ran into this issue today taking Homestead for a spin with Drupal things.
