### ISSUE TITLE
A customization command failed. Command: ["modifyvm", "d4a54c54-86ae-4931-9362-770a2324661f", "--natdnshostresolver1", "true"]

### ISSUE THREAD

**Issue by BobbyBabes** [laravel/homestead#1113]
## Versions
  - Vagrant: ```Vagrant 2.2.4```
  - Provider: ```VirtualBox Graphical User Interface Version 6.0.6 r129722```
  - Homestead: ```homestead --version``` ```bash: homestead: command not found```. I did ```git checkout v8.3.2``` after cloning this repo.

## Host operating system
Arch Linux. ```uname --all``` output : ```Linux demobox 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64 GNU/Linux```

## Homestead.yaml
Too long.
[https://gist.github.com/BobbyBabes/f20798b1a203e46c944a3c5029424df3](https://gist.github.com/BobbyBabes/f20798b1a203e46c944a3c5029424df3)

## Vagrant destroy & up output
No destroy output. There is nothing to detroy. :) This is the first attempt at installing Homestead. And there are no other boxes. Vagrant and nfs-tools installed only yesterday.
Vagrant up output : [https://gist.github.com/BobbyBabes/e216780442f9ef1e60b28d8697e30247](https://gist.github.com/BobbyBabes/e216780442f9ef1e60b28d8697e30247)

## Expected behavior
No errors.

## Actual behavior
Error because I specified ```natdnshostresolver: on```?
Which was copy+pasted from here : [https://laravel.com/docs/5.8/homestead#provider-specific-settings](https://laravel.com/docs/5.8/homestead#provider-specific-settings)

## Steps to reproduce
1. Follow the instructions at [https://laravel.com/docs/5.8/homestead](https://laravel.com/docs/5.8/homestead)
2. Copy my ```.env``` and ```Homestead.yaml``` into the Homestead folder, right after running ```bash init.sh```.
3. Execute ```vagrant up```.

## References
None found in my search results.

**Comment by deviantintegral** [comment]
Does it work if you manually change https://github.com/laravel/homestead/blob/ffc11254f79586996acd84e3793c8b9ff0c013fc/scripts/homestead.rb#L44 to:

```
vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
```

**Comment by BobbyBabes** [comment]
Ruby is not on my brag list. So I hope that I translated correctly to the command line.
I ran the following command in the Homestead folder (VM UUID copied from error output), and received no error. The prompt re-appeared very quickly.  :
```Bash
vboxmanage modifyvm 'd4a54c54-86ae-4931-9362-770a2324661f' --natdnshostresolver1 on
```

**Comment by BobbyBabes** [comment]
I replaced Line 44 with the code you provided. And all ilooks to go well.
Although it's sitting for ever on ```Mounting NFS shared folders...``` now though :

```
 demouser  demobox  ~  dev  Homestead  ⚓ d24813d  1✎  1+  $  vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' version '7.2.1' is up to date...
==> homestead-7: Clearing any previously set forwarded ports...
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
    homestead-7: Adapter 3: bridged
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 4040 (guest) => 4040 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7: 
    homestead-7: Vagrant insecure key detected. Vagrant will automatically replace
    homestead-7: this with a newly generated keypair for better security.
    homestead-7: 
    homestead-7: Inserting generated public key within guest...
    homestead-7: Removing insecure key from the guest if it's present...
    homestead-7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead-7: Machine booted and ready!
==> homestead-7: Checking for guest additions in VM...
    homestead-7: The guest additions on this VM do not match the installed version of
    homestead-7: VirtualBox! In most cases this is fine, but in rare cases it can
    homestead-7: prevent things such as shared folders from working properly. If you see
    homestead-7: shared folder errors, please make sure the guest additions within the
    homestead-7: virtual machine match the version of VirtualBox you have installed on
    homestead-7: your host and reload your VM.
    homestead-7: 
    homestead-7: Guest Additions Version: 5.2.8_KernelUbuntu r120774
    homestead-7: VirtualBox Version: 6.0
==> homestead-7: Setting hostname...
==> homestead-7: Configuring and enabling network interfaces...
==> homestead-7: Exporting NFS shared folders...
==> homestead-7: Preparing to edit /etc/exports. Administrator privileges will be required...
[sudo] password for demouser:              
==> homestead-7: Mounting NFS shared folders...

```

**Comment by BobbyBabes** [comment]
Should the ``owner:group`` pair of NFS shared folders in the VM, be ``root``` ?

```Bash
vagrant@homestead:~$ ls -lah /home/vagrant/tomsen-brody/public
total 8.0K
drwxr-xr-x 2 root root 4.0K Apr 25 17:43 .
drwxr-xr-x 3 root root 4.0K Apr 25 17:43 ..
vagrant@homestead:~$ ls -lah /home/vagrant/craft/public
ls: cannot access '/home/vagrant/craft/public': No such file or directory
vagrant@homestead:~$ ls -lah
total 68K
drwxr-xr-x 10 vagrant vagrant 4.0K Apr 25 18:13 .
drwxr-xr-x  3 root    root    4.0K Apr 20 18:24 ..
-rw-r--r--  1 vagrant vagrant  220 Apr 20 18:24 .bash_logout
-rw-r--r--  1 vagrant vagrant 3.7K Apr 20 18:24 .bashrc
drwx------  3 vagrant vagrant 4.0K Apr 20 18:36 .cache
drwxrwxr-x  4 vagrant vagrant 4.0K Apr 20 18:37 .composer
drwxr-xr-x  5 vagrant vagrant 4.0K Apr 20 18:34 .config
drwx------  3 vagrant vagrant 4.0K Apr 20 18:24 .gnupg
-rw-------  1 vagrant vagrant   34 Apr 25 18:13 .lesshst
drwxr-xr-x  3 vagrant vagrant 4.0K Apr 20 18:36 .local
-rw-r--r--  1 vagrant vagrant   67 Apr 20 18:35 .my.cnf
drwxr-xr-x  4 vagrant vagrant 4.0K Apr 20 18:34 .npm
-rw-r--r--  1 vagrant vagrant  856 Apr 20 18:37 .profile
drwx------  2 vagrant vagrant 4.0K Apr 25 17:42 .ssh
-rw-r--r--  1 vagrant vagrant    0 Apr 20 18:25 .sudo_as_admin_successful
drwxr-xr-x  3 root    root    4.0K Apr 25 17:43 tomsen-brody
-rw-r--r--  1 vagrant vagrant    5 Apr 20 18:24 .vbox_version
-rw-r--r--  1 vagrant vagrant  254 Apr 20 18:36 .wget-hsts
vagrant@homestead:~$ 
```

**Comment by svpernova09** [comment]
@deviantintegral  looks like we're assuming true `settings['natdnshostresolver'] ||= 'on'` when we should be checking the value.

**Comment by deviantintegral** [comment]
I think we're actually getting hit by [YAML's boolean type](https://yaml.org/type/bool.html). If I force it to a string by setting `natdnshostresolver: 'on'`, it works without touching `Homestead.rb`.

Two options: we could treat this as a docs bug, and add quotes to the docs. The advantage of this is that if Virtualbox ever adds other supported settings, we don't have to change anything.

Or, we could limit ourselves to a boolean setting, and manually switch that to a string. If we do that, I still think we should change the docs to `true/false` instead of `on/off` just to avoid the confusion.

**Comment by svpernova09** [comment]
IMHO lets update the docs.

**Comment by svpernova09** [comment]
Closing this as the docs have now been updated.

**Comment by BobbyBabes** [comment]
Thanks guys.
