### ISSUE TITLE
[feature request] Add opt-in option to install docker-ce

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1114]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: 7.2.1

Add a opt-in feature to install docker-ce, like crystal, dotnetcore, golang, etc.

If this is useful, I'm happy to provide a PR, but I have a couple of questions:

When installing docker-ce, what method should be used ?
- deb
- repository (manual)
- script provided by docker

The vagrant user should be able to run docker without sudo ?
(this can have security issues, as quoted in  [https://docs.docker.com/install/linux/linux-postinstall/](https://docs.docker.com/install/linux/linux-postinstall/), `the docker group grants privileges equivalent to the root user. For details on how this impacts security in your system, see Docker Daemon Attack Surface`?

**Comment by svpernova09** [comment]
I'd be fine with this as an optional item. As for the installation method, I don't have a big preference. I would lean towards providing the most up to date version which would possibly be via the script from Docker.

As for security concerns, Vagrant by design is inherently insecure, the vagrant user may already be able to sudo without a password so I'd be fine allowing them to run Docker without sudo.

**Comment by deviantintegral** [comment]
I recently added docker-ce in `after.sh` for a project - this is copied from their docs, except for the group add.

```
# Install Docker
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

sudo usermod -a -G docker vagrant
```

**Comment by ricardoseriani** [comment]
Thanks for the script @deviantintegral.
I'm thinking in using the script provided by docker, because IMHO if anything else is needed in a future version, the script will/should be updated and responsible for take care of this.
