### ISSUE TITLE
Unable to connect to host 127.0.0.1 because access was denied.

### ISSUE THREAD

**Issue by steffiv** [laravel/homestead#1116]
## Versions
  - Vagrant: Vagrant 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: Vagrant 2.2.4

## Host operating system
Mac OS Sierra

## Homestead.yaml
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
neo4j: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/websites/project1
      to: /home/vagrant/websites/project1

    - map: ~/websites/project2
      to: /home/vagrant/websites/project2

sites:
    - map: project1.test
      to: /home/vagrant/websites/project1/public

    - map: project2.test
      to: /home/vagrant/websites/project2/public

databases:
    - homestead
    - dbproject2

## Vagrant destroy & up output
https://gist.github.com/steffiv/30f051e9adf3a7592eb328ed938961fe

## .env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=33060
DB_DATABASE=dbproject2
DB_USERNAME=dbproject2
DB_PASSWORD=secret

## Expected behavior
I want to connect my second database (dbproject2) in Sequel Pro. The first gave no problems.

## Actual behavior
I use Sequel pro but my second database gives the error:
<img width="422" alt="Schermafbeelding 2019-04-30 om 15 41 50" src="https://user-images.githubusercontent.com/37297769/56965958-855be200-6b5e-11e9-9757-0f6ec166210e.png">
Can someone tell me what I am doing wrong?

Thanks!

**Comment by ndberg** [comment]
Laravel 5.8? Did the standard password change from secret to password?

**Comment by steffiv** [comment]
I have not changed the password to what laravel had by default. It has been a long time since I used laravel so I don't know what it was in the earlier version

**Comment by ricardoseriani** [comment]
AFAIK, when using the "Sequel pro" or any host program, you should point to the IP of the virtual machine, or map the port in the Homestead.yaml.

**Comment by steffiv** [comment]
I thought so in the beginning (it seemed logical) but then the first database (in my first project) did not work and when I put it back to 127.0.0.1 it worked. 

Now if I change my second project:
.env: DB_HOST=192.168.10.10 
I get this: 
<img width="504" alt="Schermafbeelding 2019-04-30 om 19 33 24" src="https://user-images.githubusercontent.com/37297769/56981314-e0053600-6b7e-11e9-9b0b-1c7bc003e04e.png">

**Comment by svpernova09** [comment]
Since you're pointing Sequel Pro @ Port `33060`, you should use host `127.0.0.1`.

You can verify what localhost ports are mapped by looking at these lines during `vagrant up`:

```
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 4040 (guest) => 4040 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
```

The default username is `homestead` and the default password is `secret`.

**Comment by ricardoseriani** [comment]
In case you wanna use this specific user, you should check if the permission for remote connection is OK and check the port of connection.
But as @svpernova09 said, you can use the homestead user for this, since normally the vagrant/hometead it's used only for development.

**Comment by steffiv** [comment]
Hi, 

I cannot get the permission right (I've only just got my mac), I can indeed take the default value, but my previous project already has this and I regret that I will lose this.

But thank you all for your time and wisdom!
