### ISSUE TITLE
No docs for ~/Homestead/user-customizations.sh

### ISSUE THREAD

**Issue by BobbyBabes** [laravel/homestead#1126]
I can't ask this at the [Laravel Docs repo]() (issues not enabled), so I'm brave/tough and ask here.
The Homestead documentation explains ```~/Homestead/resources/after.sh``` for extra provisioning, but does not explain ```user-customizations.sh```. Which is mentioned briefly in ```after.sh```. : 
>#!/bin/sh
>
>\# If you would like to do some extra provisioning you may
>\# add any commands you wish to this file and they will
>\# be run after the Homestead machine is provisioned.
>\#
>\# If you have user-specific configurations you would like
>\# to apply, you may also create user-customizations.sh,
>\# which will be run after this script.

## Versions
  - Vagrant: ```Vagrant 2.2.4``` (vagrant -v)
  - Provider: ```Oracle VM VirtualBox VM Selector v6.0.6``` (virtualbox --help)
  - Homestead: ```homestead --version``` displays : ```bash: homestead: command not found```. I did ```git checkout v8.3.2``` after cloning this repo. Also ```vagrant box list``` displays : ```laravel/homestead (virtualbox, 7.2.1)```. Which suggests Homestead version ```7.2.1```?

## Host operating system
```Linux ladyluck 5.0.12-arch2-1-ARCH #1 SMP PREEMPT Sat May 4 21:09:16 UTC 2019 x86_64 GNU/Linux```

## Homestead.yaml
N/A. This is a question about documentation.

## Vagrant destroy & up output
N/A. This is a question about documentation.

## Expected behavior
A brief usage explanation for ```~/Homestead/user-customizations.sh```. What type of tasks are fit to be inserted.

## Actual behavior
```~/Homestead/user-customizations.sh``` is not documented.

What confuses me is:
> user-specific configurations

Does this mean specific to one or more user profiles created in the Homestead VM?
Or does it mean specific to the person who is going to use the Homestead VM locally?
Or an entirely different purpose?
What type of tasks should go in this file?

Also how does ```~/Homestead/user-customizations.sh``` relate to ```~/Homestead/after.sh```?
For example, I have ```autofs``` file sharing set up and working. Do I insert my Bash script into ```after.sh```, or into ```user-customizations.sh```. Some of the shares are for all. Some shares are VM-user **specific. But can't make the proper decision which file to use (or both?).

I did the autofs setup directly in a running Homestead VM. it won't survive a ```vagrant halt``` and ```vagrant up```. So for now I run a Bash script after ```vagrant halt``` and ```vagrant up``` to do the autofs setup. Or use ```vagrant suspend``` and ```vagrant resume```.

## Steps to reproduce
Search the Homestead docs for ```user-customizations.sh```.

## References
None that I'm aware of.

**Comment by svpernova09** [comment]
Anything the system needs to operate should be placed and run from `after.sh`. 

Anything a user (You, Your teammates, etc) want to change preference wise would go into `user-customizations.sh` If you want to use Emacs and your Coworkers are hardcore Vim users, this is how you can set your defaults to Emacs while your heathen teammates can set theirs to Vim. You shouldn't Version control this file, I believe it should be in the `.gitignore` file by default.

**Comment by svpernova09** [comment]
@stevegrunwell I believe this is what you implemented for us, is ^^ that an accurate representation?

**Comment by stevegrunwell** [comment]
The extent of my contributions on this has been #932, but [I did also write a blog post detailing how to use the feature](https://stevegrunwell.com/blog/laravel-homestead-user-customizations-sh/) that could absolutely be mined for some official documentation.

**Comment by BobbyBabes** [comment]
@svpernova09 Thanks for the clear explanation. And the crack at Vim. : )
@stevegrunwell Thanks for adding this to Homestead. I read your article and came away with some great usage tips. :1st_place_medal:

Understandable that ```user-customizations.sh``` is in the ```.gitignore``` file. But why is ```after.sh``` also in ```.gitignore``` if it could contain code that the system needs to operate?

**Comment by svpernova09** [comment]
>  And the crack at Vim. : )

Before I get railroaded, it should be known that I am a devout Vim user and only made that crack for comedic intent :D

**Comment by svpernova09** [comment]
> Understandable that user-customizations.sh is in the .gitignore file. But why is after.sh also in .gitignore if it could contain code that the system needs to operate?

This is a bit of the chicken & egg problem. Homestead shouldn't version control `after.sh` because you may not *want* to. The minute you add anything to `after.sh` you *should commit it to version control*

**Comment by BobbyBabes** [comment]
> This is a bit of the chicken & egg problem. Homestead shouldn't version control after.sh because you may not want to. The minute you add anything to after.sh you should commit it to version control

OK. Then that minute has arrived. Because it will be used. Glad I asked because otherwise I would have had all the others after me.

> Before I get railroaded, it should be known that I am a devout Vim user and only made that crack for comedic intent :D

Well, I started using NeoVim with Gonvim GUI on the desktop not too long ago. Still setting up with plugins though. So I'm hopping between it, and VScode. On the server side I use Vim because the man pages have similar navigation.
