### ISSUE TITLE
Enhancement to use node projects with pm2 with easy config

### ISSUE THREAD

**Issue by MerrySean** [laravel/homestead#1142]
## Versions
Vagrant 2.2.4
Virtualbox 6.0.4
homstead 8.3.1

## Host operating system
MAC OS MOVAJE (10.14.4)

## Problem to solve - Use of node project with watch enabled and hot-reloading specifically (vue) with webpack mix

1. First Step is to install pm2 on your machine
1.1 `vagrant up`
1.2 `vagrant ssh`
1.3 `npm install pm2 -g`
1.4 make sure pm2 is installed properly it should show the version of the install pm2
2. open homestead.rb file ( can be found on scripts folder ) 
2.1 paste the code below AFTER line 287
```
     # generate pm2 JSON config file
          if site['pm2']
            config.vm.provision "shell" do |s2|
              s2.name = 'Creating Site Ecosystem for pm2: ' + site['map']
              s2.path = script_dir + "/create-ecosystem.sh"
              s2.args = Array.new
              s2.args << site['pm2'][0]['name']
              s2.args << site['pm2'][0]['script'] ||= "npm"
              s2.args << site['pm2'][0]['args'] ||= "run serve"
              s2.args << site['pm2'][0]['cwd']
            end
          end
```

3. create a file on scripts folder named create-ecosystem.sh
3.1 Paste the code below 
```
#!/usr/bin/env bash

mkdir /home/vagrant/ecosystem 2>/dev/null

PATH_ECOSYSTEM="/home/vagrant/ecosystem"

rm -rf /home/vagrant/ecosystem/*

PATH_JSON="${PATH_ECOSYSTEM}/${1}.json"

# variables
# 1 = name
# 2 = script
# 3 = args
# 4 = path

BASE_ECO='{
  "name": "'$1'",
  "script": "'$2'",
  "args": "'$3'",
  "cwd": "'$4'"
}'

# Only generate an ecosystem if there isn't one already there.
if [ ! -f $PATH_JSON ]
then
    echo "$BASE_ECO" > $PATH_JSON
fi
```
3.1 **IMPORTANT**: as you could see above we are creating a file on `~/ecosystem` folder
4. Now on your homestead.yaml file, you can now use the kind of syntax seen below, as you can see you can find a pm2.
```
- map: projectName.box
      to: 8080
      pm2:
        - name: "passport"
          script: "npm"
          args: "run serve"
          cwd: "/home/vagrant/projects/vue/projectName"
      type: proxy
```
4.1 `cwd` is the path to your node project
4.2 as you can see i'm using `type: proxy` this is not documented in homestead documentation. but it just creates an NGINX virtual-site to your app.
4.3 `to: 8080` is because when I ran npm run serve on my node app the port it's going to listen in on `8080`

5. on you node app configure webpack's devServer with this
```
devServer: {
    host: "0.0.0.0",
    public: "192.168.10.10:8080",
    port: 8080,
    disableHostCheck: true,
  }
```
6. on you .zshrc / .bashrc / (shell config)
```
function homestead() {
    ( cd ~/Homestead && vagrant $* )
}

function hpm2() {
    ( cd ~/Homestead && vagrant ssh -c "pm2 start ecosystem/${1}.json" )
}
```
6.1 first function is for homestead 
6.2 second function is for homestead pm2
6.3 as you can see `vagrant ssh -c "pm2 start ecosystem/${1}.json` we are running pm2 start on ecosystem folder and finding the json. 
6.4 remember `${1}` is the name that you used on the homestead.yaml site - pm2 config.
6.5 reload vagrant `vagrant reload --provision`
6.6 you can now run your node project in your host machine using `hpm2 projectName` and it would be automatically hosted on your homestead depending on your map value.

now to fix a webpack issue on not reloading/recompiling assets on file-edit we need to use 
- https://github.com/mhallin/vagrant-notify-forwarder

this is a vagrant plugin that notifies the guest client that we changed a file on the host.
- https://blog.codecentric.de/en/2017/08/fix-webpack-watch-virtualbox/

after that, it would be easy to add more node app/projects to homestead.

NOTE: every time you reload vagrant the pm2 services is to be lost, you need to start it again

**Comment by MerrySean** [comment]
I would love to make a pull request but I'm not really confident enough knowing that all of the homestead users are using my code.

**Comment by svpernova09** [comment]
> I would love to make a pull request but I'm not really confident enough knowing that all of the homestead users are using my code.

Don't let that stop you, plenty of helpful people will give you feedback as needed.
