### ISSUE TITLE
Upgrade to Ubuntu 19.04

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#1144]

**Comment by svpernova09** [comment]
After double checking release schedules, I realized that 19.04 is not the LTS I expected it was. We still have until 4/2023 for 18.04 support, so we'll be sticking with 18.04 and take the next scheduled LTS version: 20.04

/cc @ricardoseriani, @browner12, @cbj4074

**Comment by ricardoseriani** [comment]
Just to let you know, the next ubuntu LTS should be the 20.04, expected to be released in April, 2020.

**Comment by svpernova09** [comment]
We should see an `8.0.0-alpha2` tonight
