### ISSUE TITLE
[proposal] Utilize collections to do the installs of "optional packages/features"

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1153]
What you guys think about using collections to do the installs of "optional packages/features".
This could be something like:

```yaml
features: 
  - ohmyzsh
  - ruby
```

Pros:
A new group could make things more organized.
Since AFAIK any of this "optional features" it's only a installation and not a setup, this could facilitate the `homestead.rb`, because if it's follows a pattern, the `homestead.rb` could iterate over the items and call the scripts without checking for each option explicitly.
Make the creation of additional "optional packages/features" more easy, as far as it follows the convention.

Cons:
It's a breaking change, but since homestead 9.0 will be a major version, this could be more "forgiving"
Needs development of a "pattern" to follow for easy integration.

**Comment by ricardoseriani** [comment]
I see that some features are being removed, so I don't know if this proposal is really useful or not...

**Comment by svpernova09** [comment]
I like the idea of making these optional things easier to add.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by ricardoseriani** [comment]
Good to know.

What about the "pattern" that we are gonna use ?
I'm thinking about creating  a subfolder in the scripts folder. If so, which name should I use (i was thinking about `features` ) ?
And when moving the `install` scripts to these folder, should I rename then to remove the `install-` suffix, or not ?

**Comment by ricardoseriani** [comment]
Oh, do you have any idea of which scripts will remain and which will be removed ?
So I can do the cleaning while moving to the new folder.

**Comment by svpernova09** [comment]
> I'm thinking about creating a subfolder in the scripts folder. If so, which name should I use (i was thinking about features ) ?

Sounds good. 

`scripts/features/` will contain `mongodb.sh` (as opposed to `install-mongo.sh`), `mariadb.sh` (Aas opposed to `install-maria.sh`)

> Oh, do you have any idea of which scripts will remain and which will be removed ?

There should be open issues for everything in the project: https://github.com/laravel/homestead/projects/1 I don't know if that is a complete list or not but I can say with high confidence the things listed there *will* be removed / not exist in v9.

**Comment by svpernova09** [comment]
btw we have `version_9` branch started so you can see what's already been removed. Any v9 PRs should be made against that branch.

**Comment by ricardoseriani** [comment]
Yeah, I already saw the new branch when I was looking in the issues/PR, but thanks anyway for pointing this.
I will start working on this and submit a PR when done.

**Comment by browner12** [comment]
how would we handle different versions of the same feature?

for example, in the past we used to be able to install different versions of ElasticSearch.

Can you do something like 

```yaml
features:
    - elasticsearch=5
```

or would we do something like 

```yaml
features:
    - elasticsearch4
    - elasticsearch5
```

**Comment by ricardoseriani** [comment]
Good point...
How it's handled today ? There already is any pattern ?
Because AFAIK, the `install-elasticsearch.sh` deals with different versions in the same script, but `install-mysql8` is specifically for mysql 8 install.

**Comment by browner12** [comment]
ok, so how about if it's in a separate script, we make them separate features, but if versioning is handled in 1 script, we'll pass an argument in. 

```yaml
features:
    - mysql
    - mysql8
    - elasticsearch: 5
```

I think this would allow you to still do your optimization of looping through features rather than calling them each explicitly.

**Comment by svpernova09** [comment]
Something to keep in mind: We're only able to support versions found in the PPA repos. (The Elastic search script actually handles versioning the best IMHO. But that is due to the need for specific versions).

We should possibly default MySQL to v8 in Homestead 9. And have a MySQL 5.x optional installer.

**Comment by ricardoseriani** [comment]
The problem that I'm current on is this:

When using the syntax:
```yaml
features:
    - mysql
    - mysql8
    - elasticsearch: 7
```

Due to the `:` in some options, some keys are `simple text` (like mysql or mysql8) , and some keys are `HashString` (like elasticsearch: 7).
Should I treat both types, using an if or something like that, or should we stick with just one of this  (or we could use the `=` syntax, like in `elasticsearch=7`) ?

**Comment by browner12** [comment]
is `elasticsearch=7` valid syntax for YAML? I just made that up, before looking at the spec.

would it help if we just made everything a `simple text`?

```yaml
features:
    - elasticsearch7
```

and then alias a string without a version number to the most current version?

**Comment by ricardoseriani** [comment]
> is `elasticsearch=7` valid syntax for YAML? I just made that up, before looking at the spec.

I think that in this case, it's treated as a `string`, so we could do a split in the `=` and pass everything else to the script as argument.

So, if the yaml is:
```yaml
features:
    - mysql8
    - elasticsearch=7
```

We could call the script `scripts/features/mysql8.sh` without any arguments, and the script `scripts/features/elasticsearch.sh` passing `7` as an argument.

**Comment by svpernova09** [comment]
Elasticsearch is a special case, because there are multiple versions and damn good reasons for needing them (AWS ES!) I'm ok with the `feature:version` paradigm. I'd also be ok if for consistency we wanted to do:

```
features:
    - mysql: 5 // installs Mysql 5.x
    - elasticsearch: 6 // installs ES 6.0.0
```

**Comment by ricardoseriani** [comment]
So, all of features will have a format of `<feature>:<version> ?
Because, the problem that I'm having is that, if some have, and some not, they needed to be treated distinctly.

**Comment by svpernova09** [comment]
> So, all of features will have a format of <feature>:<version> ?

I think so, do you see a problem with that? I think consistency here is key rather than handling them differently, if they DO need to be handled differently, lets handle that by passing args (versions) to a script and negotiating that in the script (like we do today with ES)

**Comment by ricardoseriani** [comment]
Not at all.
I'm just wondering about things that have "frequent" versions update, like the `install-golang.sh`.
In this case, it will be `golang: 1.12.5` (If this script it will be continued maintened at all ... ) ?

**Comment by svpernova09** [comment]
> I'm just wondering about things that have "frequent" versions update, like the install-golang.sh.
In this case, it will be golang: 1.12.5 (If this script it will be continued maintened at all ... ) ?

For things like Go, where we would always want the latest version I think we could `go: true` (string or boolean, whichever is easier)
