### ISSUE TITLE
PostgreSQL 11 in Homestead

### ISSUE THREAD

**Issue by cuoool** [laravel/homestead#1159]
My team is using PosgreSQL procedure that available only in version 11 but Homestead is running PostgreSQL 10. I'm running Homestead v7.1.2 with Vagrant 2.2.4. Is there a way to upgrade database version for PostgreSQL?

**Comment by svpernova09** [comment]
You can check official Postgres docs for instructions on upgrading. We're currently working on the next major version of Homestead which will be defaulting to Postgres 11.

**Comment by svpernova09** [comment]
I would start here: https://computingforgeeks.com/install-postgresql-11-on-ubuntu-18-04-ubuntu-16-04/

**Comment by cuoool** [comment]
Thanks @svpernova09

**Comment by dwhoban** [comment]
@svpernova09 Any update on this?  Noticed that Forge now installs 11.4 for new machines.  Is there a flag we can set?

**Comment by svpernova09** [comment]
@dwhoban 

Oops, I totally dropped the ball here. Looks like Homestead installs 10. I'll see about getting setting version 11 as the default and do a 8.1 basebox release and likely a 9.1 repo release. Would look to release the new base box ~early August.

**Comment by svpernova09** [comment]
This will be in base box 8.1.0 due early August.
