### ISSUE TITLE
PHP 7.2 + mcrypt?

### ISSUE THREAD

**Issue by octoxan** [laravel/homestead#1187]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.8
  - Homestead: 7.2.1

Trying to figure out how to enable mcrypt for php7.2 and am going crazy trying to get it to work. What would be the best option for getting mcrypt to work for a php7.2 project?

Sadly, there's some awful things like Magento 1.9.x out there that use php7.2 but also require mcrypt.

**Comment by svpernova09** [comment]
You would need to install mcrypt extension via PECL I believe, quick google search returns https://websiteforstudents.com/install-php-7-2-mcrypt-module-on-ubuntu-18-04-lts/
