### ISSUE TITLE
Do we need to remove mysql completely when switching to mariadb?

### ISSUE THREAD

**Issue by deviantintegral** [laravel/homestead#1188]
@m4olivei mentioned to me that `lmm` wasn't working for him after installing mariadb. It looks like the problem is that https://github.com/laravel/homestead/blob/master/scripts/install-maria.sh#L28-L30 removes the `/var/lib/mysql` symlink to the lvm mount, which then gets recreated on the root partition when mariadb is installed.

Is there a specific reason to remove the data directory? AFAIK it should be compatible with mariadb.

Aside, what about defaulting to mariadb over mysql? For myself, I tend to recommend mariadb because there's such a disconnect between Oracle's company values and the broader open source / free software communities. In the Drupal world, mariadb has become as common if not more common than MySQL. But if the vast majority of Laravel installs use MySQL, then I can see why it makes sense.

**Comment by svpernova09** [comment]
> Is there a specific reason to remove the data directory? AFAIK it should be compatible with mariadb.

AFAIK that's just an oversite and should be fixed.

> Aside, what about defaulting to mariadb over mysql?

I go back and forth on this and keep coming back to it would be confusing to people to switch and nearly everyone expects MySQL, not MariaDB. However, I think we could swap it and likely no one would ever be the wiser unless someone was paying attention.

**Comment by svpernova09** [comment]
Resolved via 46d8294
