### ISSUE TITLE
The box you attempted to add doesn't match the provider you specified

### ISSUE THREAD

**Issue by CraigPedley** [laravel/homestead#1201]
## Versions
  - Vagrant: 2.2.5
  - Provider: vagrant-vmware-fusion (5.0.4, global)

## Host operating system
macOS Mojave 10.14.5

## Actual behavior

Wrong box returned for vmware_desktop provider. 

craigs-mbp:Downloads cpedley$ **vagrant box add laravel/homestead**
==> box: Loading metadata for box 'laravel/homestead'
    box: URL: https://vagrantcloud.com/laravel/homestead
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) hyperv
2) parallels
3) virtualbox
4) vmware_desktop

Enter your choice: **4**
==> box: Adding box 'laravel/homestead' (v8.0.0-beta) for provider: vmware_desktop
    box: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/8.0.0-beta/providers/vmware_desktop.box
    box: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
**The box you attempted to add doesn't match the provider you specified.**

Provider expected: vmware_desktop
Provider of box: virtualbox

**Comment by svpernova09** [comment]
What happens when you skip the `vagrant box add laravel/homestead` and run `vagrant up` after configuring your `Homestead.yaml`?

**Comment by CraigPedley** [comment]
Hi Joe, that worked great thank you.
