### ISSUE TITLE
I am having the same problem. Everything was working well with vagrant 2.2.2 and homestead 7.2

### ISSUE THREAD

**Issue by ksorbo** [laravel/homestead#1224]
I am having the same problem. Everything was working well with vagrant 2.2.2 and homestead 7.2
My setup vagrant 2.2.5, homestead box 8.0.0 windows 10
This is what I did.
1. Delete Homestead3 folder. Deleted all homestead boxes (vagrant box remove laravel/homestead --all)
2. Followed the exact steps to install homestead on the laravel docs page. 
   - vagrant box add laravel/homestead  ==> laravel/homestead 8.0.0 box downloaded
  - git clone https://github.com/laravel/homestead.git ~/Homestead3
  - cd ~/Homestead3
  - git checkout release
 - composer update
  - init.bat
3. vagrant up  then vagrant ssh   then cd in code folder
4.  composer require symfony/finder   => composer.,json created correctly
5. composer update =>>> doesn't throw any errors, **BUT NO symfony folder in vendor** 

_**This has to be a permissions related error in homestead**_

In my other project, I created a simple test program with Symfony/Finder
`    
    require('../vendor/autoload.php');

    use Symfony\Component\Finder\Finder;

    $f = new Finder();
    $f->files()->in('../config');
    if($f->hasResults()) {
        echo "Has results\n";
    }else{
        die("didn't get anything");
    }
    foreach ($f as $file) {
        $absoluteFilePath = $file->getRealPath();
        $fileNameWithExtension = $file->getRelativePathname();
        echo "$absoluteFilePath => $fileNameWithExtension\n";
    }`

When I run this on my laptop, it returns the folder content as intended.
When I run it via virtual homestead (either web host or via ssh commandline,), it fails

It seems to be a permissions error in homestead. All file permissions look correct (
    drwxrwxrwx  1 vagrant vagrant    0 Jul  6 20:03 ./
    drwxr-xr-x 12 vagrant vagrant 4096 Jul  6 20:42 ../
    -rwxrwxrwx  1 vagrant vagrant   60 Jul  6 19:59 composer.json*
    -rwxrwxrwx  1 vagrant vagrant 2204 Jul  6 19:59 composer.lock*
    drwxrwxrwx  1 vagrant vagrant    0 Jul  6 20:01 public/
    drwxrwxrwx  1 vagrant vagrant    0 Jul  6 20:04 vendor/

Can't be a nginx problem because I get the Finder loading problem even from the CLI
(Vagrant destroy && vagrant up gist)
https://gist.github.com/ksorbo/c656ca3517d02cf4b123ed4a0939f0fa

Homestead.yml
---
ip: "10.0.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

_Originally posted by @ksorbo in https://github.com/laravel/homestead/issues/1178#issuecomment-508951159_

**Comment by svpernova09** [comment]
> https://gist.github.com/ksorbo/c656ca3517d02cf4b123ed4a0939f0fa#file-gistfile1-txt-L58

Please update to Virtualbox 6.x and make sure you also update the extensions for 6.x. Then show another gist of `vagrant destroy && vagrant up`

**Comment by ksorbo** [comment]
@svpernova09 THANKS.

Upgrading to Oracle Virtualbox 6.0.8 seems to have solved the issues. My new gist after the upgrade from Virtualbox 5.x to 6.0.8 is:
https://gist.github.com/ksorbo/b548813fb43fa8ea9bd28e51ddefb616
