### ISSUE TITLE
Composer on vboxsf mount

### ISSUE THREAD

**Issue by salika86** [laravel/homestead#1225]
Hi,

I was struggling with running composer on Homestead, some specific packages were not found. Same worked on my host system, problem appeared only when running "laravel new" inside Homestead.

```
Skipped installation of bin Resources/bin/var-dump-server for package symfony/var-dumper: file not found in package
Skipped installation of bin bin/php-parse for package nikic/php-parser: file not found in package
Skipped installation of bin bin/psysh for package psy/psysh: file not found in package
Skipped installation of bin phpunit for package phpunit/phpunit: file not found in package
```

Then:
                                                                                                                                                 
```
  [RuntimeException]                                                                                                                               
  Could not scan for classes inside "/vagrant/laravel/blog/vendor/phpunit/php-code-coverage/src/" which does not appear to be a file nor a folder
```

Googled it, could not pick up anything relevant, like others did not stuck with this. Tried on ubuntu/disco64 box with my config, then ran into the same at the point when configured the code folder vboxsf mount which finally led me to the the problem.

The root cause appears to be vboxsf, when I modify the mount type in Homestead.yaml to nfs, the problem is gone, works nice. Maybe it is due to Ubuntu's old virtualbox version.

I have struggled so much to make this work, so decided to share the results with you guys, which may make you to change the default code folder mount type to nfs instead of vboxsf, to avoid others to run into this.

```
olders:
    - map: ~/laravel/code
      to: /home/vagrant/code
      type: "nfs"
```

--------------------------------------------------------------------------------------------
Versions:
System: Ubuntu 18.04

Package: vagrant
Version: 1:2.2.5

Package: virtualbox
Version: 5.2.18-dfsg-2~ubuntu18.04.5

Homestead scripts: v9.0.2

--------------------------------------------------------------------------------------------

**Comment by svpernova09** [comment]
Try upgrading to Virtualbox 6 and see if the issue remains.
