### ISSUE TITLE
why did box version change to < 8.0.0-alpha1'

### ISSUE THREAD

**Issue by michaelwps** [laravel/homestead#1229]
why did < 8.0.0-alpha1 get added?
Tag: 8.5.5
Line 21:  config.vm.box_version = settings['version'] ||= '>= 7.2.1'

For Tags: 8.6.0 and 8.5.6
Line 21:  config.vm.box_version = settings['version'] ||= '>= 7.2.1, < 8.0.0-alpha1'

when i run vagrant box upgrade

output:  Box 'laravel/homestead' (v7.2.1) is running the latest version.

**Comment by svpernova09** [comment]
If you're trying to upgrade Homestead. run `vagrant destroy`. Then update to the latest release branch and run `vagrant up`, the updated base box will be downloaded for you.
