### ISSUE TITLE
unable to access 'https://github.com/laravel/homestead.git~/Homestead/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by Owuor23** [laravel/homestead#1235]
$ git clone https://github.com/laravel/homestead.git~/Homestead
Cloning into 'Homestead'...
fatal: unable to access 'https://github.com/laravel/homestead.git~/Homestead/': Could not resolve host: github.com

Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
  - Provider: Virtualbox, VMWare, Hyper-V, or Parallels and its version.
  - Homestead: You should be on the most recent `release` branch.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
What should have happened? Please include as much detail as possible.

## Actual behavior
What actually happened? Please include as much detail as possible.

## Steps to reproduce
1.
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by svpernova09** [comment]
You're missing a space between the repo URL and the destination folder. 

Run this: `git clone https://github.com/laravel/homestead.git ~/Homestead`

**Comment by rijithjayarajan** [comment]
I am also facing the same issue:

fatal: unable to access 'https://githuab.com/CSB-book/CSB.git/': Could not resolve host: githuab.com

None of the above mentioned solutions didn't work for me :)

Please help!!!

**Comment by rijithjayarajan** [comment]
I am also facing the same issue:

fatal: unable to access 'https://githuab.com/CSB-book/CSB.git/': Could not resolve host: githuab.com

None of the above mentioned solutions didn't work for me :)

Please help!!!

**Comment by svpernova09** [comment]
@rijithjayarajan You've misspelled `github.com`

**Comment by sherrif10** [comment]
git config --global --unset https.proxy, it saved me

**Comment by Electronicmaniac** [comment]
> 
> 
> git config --global --unset https.proxy, it saved me

Saved me too, thanks! Why does this work btw?
