### ISSUE TITLE
Permission denied under Code folder with newly installed macOS

### ISSUE THREAD

**Issue by libern** [laravel/homestead#1238]
VirtualBox 6.0.4
Vagrant 2.2.5
homestead 8.0.0
mac Mojave 10.14.5 (18F132)
MacBook Pro (15-inch, 2017)

----

With re-install of macOS, and everything.

Doing git clone under `~/code` folder is failed, but succeed in other folders.

Under `~/code`, I can manually make dir, touch file, git init, or anything inside VM, but git clone failed.

```
vagrant@homestead:~/code$ git clone https://git.abc.com/libern/apps
Cloning into 'apps'...
remote: Counting objects: 3787, done.
remote: Compressing objects: 100% (2946/2946), done.
fatal: Unable to create temporary file '/home/vagrant/code/apps/.git/objects/pack/tmp_pack_XXXXXX': Permission denied
fatal: index-pack failed
```

I have tried re-installed box or everything. Used default homestead config file.

**Comment by libern** [comment]
I have tried following, now working already.

```
cd ~/Homestead
git checkout v8.6.0
vagrant destroy && vagrant up

        Adding box 'laravel/homestead' (v7.2.1) for provider: virtualbox

```

**Comment by irineujunior** [comment]
Its something related to ~/.ssh/id_rsa.pub.
This file is not been copy from local machine to vm.

**Comment by libern** [comment]
It is disk write permission, it is not ssh key permission.

I have successfully git clone from another directory with same environment.

@irineujunior

**Comment by svpernova09** [comment]
Sounds like a disk permission or running vagrant as the wrong user. But I can't be sure. It's impossible to debug because you didn't fill out the issue template.

**Comment by ncla** [comment]
I had the same problem as you had, interestingly updating the vagrant box to v8.0.1 fixed this issue as well for (along with weird composer permission issues). https://github.com/laravel/homestead/issues/1240#issuecomment-515500927
