### ISSUE TITLE
No valid IDs were given to the NFS synced folder implementation to prune.

### ISSUE THREAD

**Issue by Amin01Kz** [laravel/homestead#1250]
Hi, I'm using Vagrant 2.2.5 with Hyper-v on Windows 10 Pro to run laravel/homestead and whenever I try to start the vagrant with _vagrant up_ it says: 

>  No valid IDs were given to the NFS synced folder implementation to
> prune. This is an internal bug with Vagrant and an issue should be
> filed.

cmd result:
![image](https://user-images.githubusercontent.com/20126084/61963719-7fe92900-afe1-11e9-9e00-f31cc9bc5502.png)

also tried with _vagrant reload --provision_ but get the same result.
and folders that are supposed to be synced, they aren't (this is the issue!). 
also I have access to the vagrant via ssh and it works fine

my Homestead.yaml file: 
![image](https://user-images.githubusercontent.com/20126084/61963610-40bad800-afe1-11e9-9832-0dae8c6be8a5.png)

Any idea how to fix it?
Thanks in advance.

**Comment by svpernova09** [comment]
I don’t believe you can use NFS with Hyper-V. Last I looked they Hyper-V provider doesn’t implement NFS which is why you see the vagrant bug warning. AFAIK this isn’t a Homestead issue, it’s a limitation of Hyper-V.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by Amin01Kz** [comment]
I see, you're right it's a limitation of Hyper-V. I installed VirtualBox and disabled Hyper-V, it works fine now.
Thank you.

**Comment by renanBritz** [comment]
I'm having this exact same issue. BUT

I am not trying to mount folders with NFS!

I CANNOT disable hyperv, because I need it for android emulator on a Ryzen CPU.
