### ISSUE TITLE
FYI: LVM activation skip defaults to "false", breaking mount during boot if you have lmm branches

### ISSUE THREAD

**Issue by deviantintegral** [laravel/homestead#1253]
Ubuntu 18.04 changed the default behaviour so that snapshots are not "activated" by default. That means if you create a branch with lmm and reboot, the boot will fail due to a missing device.

I've fixed this over at https://github.com/Lullabot/lmm/blob/ubuntu-18.04/functions.sh#L26, and this will automatically be pulled into the next Homestead release. In the mean time, adding `git -C /opt/lmm pull` in `after.sh` will fix this for existing boxes.

**Comment by svpernova09** [comment]
New base box which has been release which resolves this issue.
