### ISSUE TITLE
VMware workstation IP Address not respected

### ISSUE THREAD

**Issue by qerim** [laravel/homestead#1259]
This is more of a note similar to issue #375 

Fresh install of Windows 10, Vagrant and Homestead.

## Versions
  - Vagrant: 2.2.5
  - Provider: vmware_workstation
  - Homestead: 8.0.0

## Host operating system
Windows 10 x64 1903

I have left the default IP in `Homestead.yaml`:

    ip: "192.168.10.10"

And added `hosts` entries:

    192.168.10.10 qerim.test

However, when attempting to reach the site, nothing was showing up, `ping qerim.test` was returning nothing.

After `vagrant ssh` and checking the IP Address allocated by running `ifconfig`

        eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
                inet 192.168.16.128  netmask 255.255.255.0  broadcast 192.168.16.255
                inet6 fe80::20c:29ff:fe8f:3831  prefixlen 64  scopeid 0x20<link>
                ether 00:0c:29:8f:38:31  txqueuelen 1000  (Ethernet)
                RX packets 73193  bytes 94237107 (94.2 MB)
                RX errors 0  dropped 0  overruns 0  frame 0
                TX packets 27990  bytes 3296274 (3.2 MB)
                TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

        eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
                inet 192.168.10.10  netmask 255.255.255.0  broadcast 192.168.10.255
                inet6 fe80::20c:29ff:fe8f:383b  prefixlen 64  scopeid 0x20<link>
                ether 00:0c:29:8f:38:3b  txqueuelen 1000  (Ethernet)
                RX packets 39  bytes 11200 (11.2 KB)
                RX errors 0  dropped 0  overruns 0  frame 0
                TX packets 31  bytes 4059 (4.0 KB)
                TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

        lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
                inet 127.0.0.1  netmask 255.0.0.0
                inet6 ::1  prefixlen 128  scopeid 0x10<host>
                loop  txqueuelen 1000  (Local Loopback)
                RX packets 687  bytes 182567 (182.5 KB)
                RX errors 0  dropped 0  overruns 0  frame 0
                TX packets 687  bytes 182567 (182.5 KB)
                TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Changing my hosts file to the `192.168.16.128` address worked:

    192.168.16.128 qerim.test

Hope it helps someone.

**Comment by svpernova09** [comment]
Unfortunately for VMware the IP is merely a suggestion. There are several other factors which we can’t control when it comes to applying network settings on VMware
