### ISSUE TITLE
Should the default shell in Homestead be ZSH instead of BASH?

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#1263]
Thoughts on defaulting to oh-my-zsh as the default shell for the `vagrant` user?

**Comment by deviantintegral** [comment]
💯 from me. We'd want to make sure that git status checks are disabled out of the box, as those can be very slow on the mounted code directory.

**Comment by Lucky-Loek** [comment]
Not really sure what the added value is? It's not too hard to install yourself if you really need it. 

I like zsh and oh-my-zsh but recently I find that this project is becoming pretty bloated with all kinds of stuff that not a lot of people actually need. Does the average developer that spins up a vm to access his/her project *really* need to be able to install zsh plugins in said vm by default?

**Comment by sandervankasteel** [comment]
I agree with @Lucky-Loek. For my own shell I use zsh and oh-my-zsh and I absolutely love it. However, I believe that adding such functionality to a VM is counterproductive. 

I can only speak for myself, but the most commands I execute on a daily basis in this VM are `php artisan` and `composer` related commands, I really don't need zsh (and oh-my-zsh) for that. 

If you really need zsh (or oh-my-zsh) in a VM, you will obviously install it yourself, but my guess would be that most people really don't need oh-my-zsh in a VM.

**Comment by svpernova09** [comment]
Fair enough, thanks for the feedback.
