### ISSUE TITLE
serve-laravel

### ISSUE THREAD

**Issue by jerrydomm** [laravel/homestead#1270]
* Homestead v9.0.0 released
* Settler v8.0.0 released
*Vagrant 2.2.5

Hi, when i want to add a site like:

serve mysite.test /home/vagrant/code/mysite/public

I get the next error:

dos2unix: /vagrant/scripts/serve-laravel.sh: No such file or directory
dos2unix: Skipping /vagrant/scripts/serve-laravel.sh, not a regular file.
bash: /vagrant/scripts/serve-laravel.sh: No such file or directory

Which is the correct command to do this?

thanks in advance...

**Comment by svpernova09** [comment]
You should add sites to your `Homestead.yaml` and then run `vagrant destroy && vagrant up`
