### ISSUE TITLE
Enhancement - nginx forward http to https

### ISSUE THREAD

**Issue by michael-schaefer-eu** [laravel/homestead#1276]
## Why
> All sites should be protected with HTTPS. Once you've got HTTPS set up, you need to make sure that all unsecure HTTP traffic to your site is redirected to HTTPS. - google (1,2)

I think this is also true for development environments, to make sure that all sites are developed and tested with https by default.

## Homestead.yaml example
```yaml
folders:
    - map: ~/Projects/myproject
      to: /home/vagrant/myproject

sites:
    - map: myproject.test
      to: /home/vagrant/myproject/public
      php: "7.3"
```

## Expected behavior
When I open up *myproject.test* in a browser, the server should return a 301 forward to *https://myproject.test*

## Actual behavior
When I open up *myproject.test* in a browser, the server will return *http://myproject.test*

## Steps to reproduce
1. Setup new project and start the homestead vagrant box
2. Open the configured site in browser without https

## Proposed Solution
Each NGINX server configuration should contain by default the following redirection (3):

```
server {
    listen 80;
    server_name .myproject.test;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name .myproject.test;
    root "/home/vagrant/myproject/public";
    [...]
}
```

## References

1.  [google developers, http-redirects-to-https](https://developers.google.com/web/tools/lighthouse/audits/http-redirects-to-https) 
2.  [google support, 301](https://support.google.com/webmasters/answer/6073543?hl=en)
3. https://ssl-config.mozilla.org/

**Comment by juangiordana** [comment]
Hello,

I disagree with your proposal. Default settings have their purpose, if you need your app to work on HTTPS by default, then, that is a requirement for your app.

Homestead gives you the benefit of listening on both ports and you can choose the one that works for you the most.

Regards.

PS: you don't need two separate serve directives for listening on both ports in your nginx config. Have a look to the ones Homestead creates for your projects to see an example.

**Comment by svpernova09** [comment]
I agree that this should be a project-level decision. Currently, we have no method to easily pass these kinds of tweaks to the virtual host when we create them. Wouldn't be opposed to adding something, but it'd need to be pretty robust.

**Comment by michael-schaefer-eu** [comment]
So, maybe I don't understand which _purpose_ the default insecure settings have?

> Default settings have their purpose

Maybe you can clear things up, @juangiordana ?

Why is an `insecure by default` development environment better than a `secure by default` environment?

> Currently, we have no method to easily pass these kinds of tweaks to the virtual host when we create them.

Why tweak that when you can just change the site-type scripts with an additional redirect command, @svpernova09 ?

**Comment by svpernova09** [comment]
> Why is an insecure by default development environment better than a secure by default environment?

Vagrant is insecure by default, there's no value in attempting to secure it.

>Why tweak that when you can just change the site-type scripts with an additional redirect command, @svpernova09 ?

I don't want to change the default behavior of `serve-laravel.sh` to redirect http to https.

Homestead allows users to override virtual-host configuration via [site types](https://laravel.com/docs/6.x/homestead#site-types).

**Comment by michael-schaefer-eu** [comment]
So could that be a way to add site types with redirection?

That way homestead could keep the _default_ behavior and also have virtual-hosts with http to https redirection which you could use per project:

```
sites:
    - map: laravel.test
      to: /home/vagrant/laravel-project/public
      type: "laravel-redirect"
```

**Comment by svpernova09** [comment]
Yep, it could. I dunno if http -> https redirection is a good enough reason to introduce a new site type though.
