### ISSUE TITLE
serve: not found

### ISSUE THREAD

**Issue by juangiordana** [laravel/homestead#1277]
Trying to add `serve` commands in `after.sh` or `user-customizations.sh` do not work.

## after.sh / user-customizations.sh
```sh
serve www.homestead.test /home/vagrant/Projects/laravel/public 7.1
```

```console
==> homestead: Running provisioner: shell...
    homestead: Running: /tmp/vagrant-shell20190923-10391-u0ah38.sh
    homestead: /tmp/vagrant-shell: 3: /tmp/vagrant-shell: serve: not found
    homestead: /tmp/vagrant-shell: 4: /tmp/vagrant-shell: serve: not found
    homestead: /tmp/vagrant-shell: 5: /tmp/vagrant-shell: serve: not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by svpernova09** [comment]
`serve` is an alias, likely you'll want to use the full shell path name when calling it:

```
./vagrant/scripts/serve-{$type}.sh www.homestead.test /home/vagrant/Projects/laravel/public 7.1
```

Or you could just `vagrant destroy && vagrant reload` to rebuild and recreate.

**Comment by juangiordana** [comment]
`serve-*` commands are defined as functions in the `/vagrant/aliases` file, so they do not exist as scripts thus they cannot be called the way you provided.

I'm having trouble trying to `source /vagrant/aliases` from `user-customizations.sh` to run the `serve-laravel` function / `serve` aliase.

**Comment by svpernova09** [comment]
You don't want to source the aliases file. Just use the full command path.

**Comment by juangiordana** [comment]
`./vagrant/scripts/serve-laravel.sh` does not exist. 

`serve-laravel` is a shell function defined within the `aliases` file.

**Comment by svpernova09** [comment]
> ./vagrant/scripts/serve-laravel.sh does not exist.

The correct path is `./vagrant/scripts/site-types/serve-laravel.sh`

If that path doesn't exist, something is wrong with your `Homestead.yaml` But I can't see what because you didn't follow the instructions in the issue template.

> serve-laravel is a shell function defined within the aliases file.

Yes, you shouldn't rely on aliases when you're using `after.sh` or `user-customizations.sh`

**Comment by juangiordana** [comment]
I haven't provided my Homestead.yaml because it's simpler than the default.

The path you are pointing out is incorrect. I think the script you want me to run is `/vagrant/scripts/site-types/laravel.sh` (full path spec.), but that script receives different parameters than the `serve-laravel` function.

The whole point of what I'm trying to accomplish is to have several domains referencing the same site and the `serve-laravel` function was a simpler approach. I don't want to add much more scripting complexity than that, so I'll stick on running the command manually after SSHing into the machine.

**Comment by juangiordana** [comment]
Figured out the problem. I was using `#! /bin/sh` instead of `#! /bin/bash`, so `source` wasn't working.

This is the final `user-customizations.sh` script:

```sh
#! /bin/bash

source /vagrant/aliases

serve-laravel homested2.test /home/vagrant/Projects/laravel/public 7.1
```
