### ISSUE TITLE
host only adapter

### ISSUE THREAD

**Issue by obb12** [laravel/homestead#1280]
## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox 5.2.20
  - Homestead: 8.01

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Operation canceled by the user
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component VirtualBoxWrap, interface IVirtualBox
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp

**Comment by svpernova09** [comment]
It’s near impossible for anyone to help you because you have ignored our issue template. If you still need help please open a new issue and complete the issue template.

**Comment by obb12** [comment]
how do i need to format the last thing?
