### ISSUE TITLE
Question: User Input in after.sh

### ISSUE THREAD

**Issue by ndberg** [laravel/homestead#1284]
## Versions
  - Vagrant: Vagrant 2.2.5
  - Provider: Virtualbox
  - Homestead: 9.1.0

## Host operating system
macOS 10.14.6

---

Question, is there a possibility to ask for user input in after.sh?

I tried different methods from [https://stackoverflow.com/questions/226703/how-do-i-prompt-for-yes-no-cancel-input-in-a-linux-shell-script](url)
but none worked:
```
# First test
while true; do
    read -p "Do you wish to install this program?" yn
    case $yn in
        [Yy]* ) make install; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

# Second test
echo -n "Is this a good question (y/n)? "
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo Yes
else
    echo No
fi

# Third test
echo -n "Is this a good question (y/n)? "
old_stty_cfg=$(stty -g)
stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg # Careful playing with stty
if echo "$answer" | grep -iq "^y" ;then
    echo Yes
else
    echo No
fi
```

I don't have a lot experience with shell scripting, but it looks like I can't access STIN.

Thanks

**Comment by svpernova09** [comment]
No, provisioning is 100% non-interactive.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by ndberg** [comment]
ok thx. 

Is it possible to accomplish this with own variables in Homestead.yaml and access them in after.sh (or if not possible, access them in the Vagrantfile?)

**Comment by svpernova09** [comment]
> Is it possible to accomplish this with own variables in Homestead.yaml and access them in after.sh (or if not possible, access them in the Vagrantfile?)

Can you explain what you're trying to do? You can compile whatever you want in after.sh, you just need to be able to script the process in a non-interactive way.

**Comment by ndberg** [comment]
I try to do multiple stuff in after.sh which the developers should be able to easily active/deactivate. One example is to download the database from production and import it into homestead. 

Is it possible to do add something in Homestead.yaml like: 
````
options: 
    -   importdbfromprod: true
````
and then in after.sh
````
if [ options.importdbfromprod]; then
    # import the db
fi
````
or is there a better approach for this?

thx a lot

**Comment by svpernova09** [comment]
These options are parsed from YAML -> Ruby -> Passed into the Shell Scripts. So you can't just use them natively. Take a look at `scripts/features`, they all drop a file to note the feature has been installed: https://github.com/laravel/homestead/blob/master/scripts/features/golang.sh#L3-L7 You probably want something like this. Set a file somewhere and have your script check for its existence and then do a thing.

**Comment by ndberg** [comment]
ah ok, thx a lot for your help
