### ISSUE TITLE
Restoring the database from the vagrant destroy triggered backup mechanism

### ISSUE THREAD

**Issue by myyylk** [laravel/homestead#1285]
First of all I would like to thank you @svpernova09 and all the other contributors for maintaining Homestead.

I lately use the automatic backup feature when the box got destroyed.
But I didn't find a feature to restore the database from this backup.
Is there one I haven't found or would this be a a nice feature to have in Homestead?

Thanks in advance and many Greetings.

**Comment by svpernova09** [comment]
You should be able to run `dbimport` from the CLI from inside the VM. If you don't have this command, ensure your `aliases` file contains this function: https://github.com/laravel/homestead/blob/master/resources/aliases#L250-L264

**Comment by svpernova09** [comment]
> First of all I would like to thank you @svpernova09 and all the other contributors for maintaining Homestead.

Thanks for the kind words :D

**Comment by myyylk** [comment]
> Thanks for the kind words :D

You're welcome. :-)

> You should be able to run dbimport from the CLI from inside the VM. If you don't have this command, 
> ensure your aliases file contains this function:
> https://github.com/laravel/homestead/blob/master/resources/aliases#L250-L264

Yeah I know this one, but if I'm not wrong, then this doesn't work with the one which is created by vagrant destroy. `dbimport` expects a gzipped file, which you can create by `dbexport`. 
But the option `backup: true` in my Homestead.yaml results in a SQL file in `mysql_backup` or `postgres_backup`.

There is no alias to recover that one, or what I thought of is an automatic way doing this,
so I don't have to manually call `mysql -uhomestead -psecret *db* < mysql_backup/file.sql`.

Homestead would work a bit more like a docker Container with that option, what would be amazing. :)

**Comment by svpernova09** [comment]
Right, the importing from those backups is manual at this point. Not sure of a way to selectively do restore based on conditions that would be easy to understand and follow.

**Comment by myyylk** [comment]
Maybe something of the following:

Next to the created `mysql_backup/file.sql`, create a symbolic link `latest.sql` or `restore.sql` or so in in the backup folder which references the created backup file.

When starting the vm or when provisioning, then check if a `latest.sql` exists and when true, then check if database has no tables and afterwards try to restore that database from the file into the one from `Homestead.yaml`. The last step would be to delete that symbolic link `latest.sql`

**Comment by marshnmedia** [comment]
I had the same issue.  Instead of using the Homestead config `backup: true` I came up with another approach which backs up all databases on `vagrant destroy`, and imports all databases on `vagrant up`.  

You can create your own custom Vagrantfile to extend/customize the Vagrantfile that comes with Homestead.  You can place it in ~/.vagrant.d/Vagrantfile
https://developer.hashicorp.com/vagrant/docs/vagrantfile#load-order-and-merging

In that file I placed my own custom 'on destroy hook':

    Vagrant.configure("2") do |config|
    config.vm.define "homestead" do |homestead|
    homestead.trigger.before :destroy do |trigger|
    trigger.warn = "Backing up all mysql databases"
    trigger.run_remote = {inline: "mysqldump -uhomestead -psecret --all-databases --skip-lock-tables --routines 2>/dev/null | gzip > '/vagrant/mysqldump.sql.gz'"}
    end
    end
    end

I also added this to the Homestead after.sh:

    SENTINEL_FILE="/home/vagrant/.homestead-config-sentinel"
    if [ ! -f "$SENTINEL_FILE" ]; then
    echo "Importing All Databases"
    cat "/vagrant/mysqldump.sql.gz" | zcat | mysql -uhomestead -psecret 2>/dev/null
    sudo mysql -u root -e "FLUSH PRIVILEGES" #reloads grant table for user perms
    #load timezone tables
    sudo mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
    echo "Done Importing All Databases"
    touch "$SENTINEL_FILE"
    fi
