### ISSUE TITLE
Question/Bug: sudo phpdismod xdebug not working anymore

### ISSUE THREAD

**Issue by ndberg** [laravel/homestead#1288]
How to call:
`sudo phpdismod xdebug` in Homestead 9.2?

# Versions

- Vagrant: Vagrant 2.2.5
- Provider: Virtualbox
- Homestead: 9.2.0
# Host operating system

macOS 10.14.6

# Problem
Disabling xdebug module as in [documentation](https://laravel.com/docs/5.8/homestead#debugging-web-requests) is not working anymore
`sudo phpdismod xdebug`

# Expected behavior

disabling xdebug module

# Actual behavior
```
➜  sudo phpdismod xdebug
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.4/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.4/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.4/mods-available
```

# Steps to reproduce

CLI: sudo phpdismod xdebug

**Comment by svpernova09** [comment]
Xdebug doesn't exist for 7.4 yet.

If you need Xdebug switch to a lower version of PHP

**Comment by ndberg** [comment]
ok thx

**Comment by ndberg** [comment]
Just for anyone stumbling across this. Since Version 9(?) you have to specify the version in the command:
`sudo phpdismod -v php7.3 xdebug`
and then reload the service:
`sudo service php7.3-fpm restart`

**Comment by ndberg** [comment]
Note, disabling works:
```
sudo phpenmod -v php7.3 xdebug; sudo service php7.3-fpm restart;
```

but enabling not:
```
sudo phpenmod -v php7.3 xdebug; sudo service php7.3-fpm restart;
```

There's no error, but it's just not enabled again. Don't know why. Anyone know?

**Comment by deviantintegral** [comment]
Is the symlink showing up in `/etc/php/7.3/mods-enabled/` (from memory, exact path may be different)?

I tend to use `-v ALL` just because if I'm switching PHP versions it's good to know these sorts of configs are kept in sync.

**Comment by ndberg** [comment]
hmm there is no mods-enabled folder anywhere, just a `/etc/php/7.3/mods-available/` folder.

Just ran some tests:
```
# sudo phpenmod -v ALL xdebug; sudo service php7.3-fpm restart;
```
-> While the command echo's look okay (just the irritating warnings for php7.4), debugging is still possible, and in `phpinfo()` xdebug is still loaded:

```
This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
    with blackfire v1.27.1~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

Another test run on two different machines: `sudo phpdismod -v php7.3 xdebug; sudo service php7.3-fpm restart;`
- on one machine (homestead 9.2.2) it really disabled it, xdebug does not show up on `phpinfo()` and can't be enabled with `phpenmod` anymore.
- while on the other machine (homestead 9.2.2 as well) it has no effect.

I'm a little bit confused..

**Comment by deviantintegral** [comment]
The path is per SAPI, so it's actually `/etc/php/7.3/fpm/conf.d/`.

For specific versions, it's `-v 7.3`, not `-v php7.3`. The versions correspond to the version folders in `/etc/php`.

**Comment by ndberg** [comment]
well, thanks @deviantintegral. Actually that drove my confusion.

For alle future readers, this actually works well with Homestead 9.2:

Disable / Enable xdebug for all php-versions:
```
sudo phpenmod xdebug; sudo service php7.3-fpm restart;
sudo phpdismod xdebug; sudo service php7.3-fpm restart;
// or with -v ALL, actually gives me the same result
sudo phpenmod -v ALL xdebug; sudo service php7.3-fpm restart;
sudo phpdismod -v ALL xdebug; sudo service php7.3-fpm restart;
```

Or Disable / Enable xdebug for all a specifiv php-version:
```
sudo phpenmod -v 7.3 xdebug; sudo service php7.3-fpm restart;
sudo phpdismod - 7.3 xdebug; sudo service php7.3-fpm restart;
```

Only enable / disable for cli:
```
sudo phpdismod -s cli xdebug
sudo phpenmod -s cli xdebug
```

I added / changed some aliases for this:
```
alias xoncli='sudo phpenmod -v ALL -s cli xdebug'
alias xoffcli='sudo phpdismod -v ALL -s cli xdebug'
alias xon='sudo phpenmod -v ALL xdebug; sudo service php7.3-fpm restart;'
alias xoff='sudo phpdismod -v ALL xdebug; sudo service php7.3-fpm restart;'
```
