### ISSUE TITLE
Box 'laravel/homestead' could not be found. Attempting to find and install...

### ISSUE THREAD

**Issue by Boussarhane** [laravel/homestead#1292]
## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox 6.0
  - Homestead: 9.2.

## Host operating system
Windows 10 Pro.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
Vagrant destroy 
```
D:\Labs\laravel6>vagrant destroy
==> laravel6: VM not created. Moving on...
```
Vagrant up
```
D:\Labs\laravel6>Vagrant up
Bringing machine 'laravel6' up with 'virtualbox' provider...
==> laravel6: Box 'laravel/homestead' could not be found. Attempting to find and install...
    laravel6: Box Provider: virtualbox
    laravel6: Box Version: >= 8.2.0
==> laravel6: Loading metadata for box 'laravel/homestead'
    laravel6: URL: https://vagrantcloud.com/laravel/homestead
==> laravel6: Adding box 'laravel/homestead' (v8.2.1) for provider: virtualbox
    laravel6: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/8.2.1/providers/virtualbox.box
==> laravel6: Box download is resuming from prior download progress
    laravel6: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    laravel6: Progress: 0% (Rate: 32976/s, Estimated time remaining: 10:06:16)
```

## Expected behavior
After running vigrant up command, a guest machine should be created and configured according to my Vagrantfile.

## Actual behavior
Box 'laravel/homestead' could not be found. Attempting to find and install...

## Steps to reproduce
1. `vegrant box add laravel/homestead --box-version 8.1.0` (box: successfully added box 'laravel/homestead' (v8.1.0) for 'virtualbox')
2. `D:\Labs>composer create-project --prefer-dist laravel/laravel laravel6` (Project created successfully)
3. `D:\Labs\laravel6>composer require laravel/homestead --dev` (successfully executed)
4. `D:\Labs\laravel6>Dvendor\\bin\\homestead make` (Homestead installed!)
5. `D:\Labs\laravel6>vagrant up` (Box 'laravel/homestead' could not be found. Attempting to find and install...)

**Comment by svpernova09** [comment]
Did you let the box finish downloading? You didn’t post the full log

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by Boussarhane** [comment]
I have a screenshot of the `vegrant box add laravel/homestead --box-version 8.1.0`  have a look please.
![log vagrant homestead](https://user-images.githubusercontent.com/4639306/66273306-9f66c280-e86a-11e9-9ca4-db258ad21d02.png)

**Comment by svpernova09** [comment]
Still have no idea what the issue is.

From the Homestead folder run this: `vagrant destroy` then `vagrant up`, please post a gist.github.com of the full output of both commands.

**Comment by Boussarhane** [comment]
Already done. have a look at my very first message

**Comment by svpernova09** [comment]
> 
> 
> Already done. have a look at my very first message

From your first post...

```
D:\Labs\laravel6>Vagrant up
Bringing machine 'laravel6' up with 'virtualbox' provider...
==> laravel6: Box 'laravel/homestead' could not be found. Attempting to find and install...
    laravel6: Box Provider: virtualbox
    laravel6: Box Version: >= 8.2.0
==> laravel6: Loading metadata for box 'laravel/homestead'
    laravel6: URL: https://vagrantcloud.com/laravel/homestead
==> laravel6: Adding box 'laravel/homestead' (v8.2.1) for provider: virtualbox
    laravel6: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/8.2.1/providers/virtualbox.box
==> laravel6: Box download is resuming from prior download progress
    laravel6: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    laravel6: Progress: 0% (Rate: 32976/s, Estimated time remaining: 10:06:16)
```

This is incomplete. The download should either error or finish. Please show me a complete log where something goes wrong.

**Comment by Boussarhane** [comment]
The download is already done in the first command `vegrant box add laravel/homestead --box-version 8.1.0`? Correct me if I"m wrong?

**Comment by svpernova09** [comment]
For me to help you, I need you to post a fresh log of `vagrant destroy` then `vagrant up`, Without those logs, it's impossible for anyone to attempt to help you.

**Comment by Boussarhane** [comment]
Here you can find my two gists: https://gist.github.com/Boussarhane

**Comment by svpernova09** [comment]
> Here you can find my two gists: https://gist.github.com/Boussarhane

[Again I'm asking you](https://github.com/laravel/homestead/issues/1292#issuecomment-538768675): What happens *after* this? Does the download just stall out and never finish?

Best I can tell this is a problem between you and S3. If the box is missing, Vagrant will try to download it again. If you're having issues downloading Vagrant boxes there's nothing Homestead can do.

**Comment by svpernova09** [comment]
Glad you got it working.

**Comment by Boussarhane** [comment]
Thanks. Now im checking .`vagrant.d\boxes\laravel-VAGRANTSLASH-homestead`, I found two boxes 8.1.0 and 8.2.1 and after checking my index file under `.vagrant.d\data\machine-index` I found out :
```
"box":{ 
               "name":"laravel/homestead",
               "provider":"virtualbox",
               "version":"8.2.1"
}
```
Which means I'm using the new downloaded version (8.2.1) How can use 8.1.0 version instead of the newly installed?
