### ISSUE TITLE
Running queue workers on UP

### ISSUE THREAD

**Issue by vpratfr** [laravel/homestead#1297]
I could see in the documentation how we could periodically run the Laravel scheduler.

However, I could not find a way to run the queue workers required on the project.

For example, in our project, we use:

- `art queue:work --queue=notifications`
- `art queue:work --queue=generate_documents`
- `art websockets:serve`

Each of those are supposed to run in the background and should be running when starting the VM.

Would there be a way to script this so that everyone in the team gets a VM running all the background workers by default?

Thanks

**Comment by svpernova09** [comment]
Homestead has always assumed you the dev would run these ad hoc for development. If you want to run them on boot, you could add a cron job for @restart php path/to/artisan queue:work

**Comment by vpratfr** [comment]
Hi, 

Thanks for the idea. 

Here is the CRON task I have added. 

`(crontab -u vagrant -l ; echo "*/5 * * * * @restart php /home/vagrant/code/artisan queue:work --queue=notifications") | crontab -u vagrant -`

However the command does not work : `@restart` is not a command which seems to work in homestead. Am I missing something?

 `@restart: command not found`

**Comment by svpernova09** [comment]
`@restart` is a cron command you use instead of the time syntax. You'll want something along these lines:

`@restart php /home/vagrant/code/artisan queue:work --queue=notifications`

**Comment by vpratfr** [comment]
For anyone coming back here : it seems that `@reboot` is the right command, not `@restart`

I have put the commands in my `after.sh` script. Will test that and see if that works. 

Thanks a lot for the ideas.

**Comment by svpernova09** [comment]
Oops sorry for telling you the wrong command >.<

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org
