### ISSUE TITLE
Minor issue: ssh shell greeter tells you "Homestead v9.0.0 released", even on Homestead v9.2.2 

### ISSUE THREAD

**Issue by HenkPoley** [laravel/homestead#1302]
.. which can be interpreted as "There is a new release, check your composer.json now".

**Comment by svpernova09** [comment]
Thanks for the reminder! Just updated it. Ubuntu doesn't always update this as expected so you may not immediately see it, but you can view the current live page here: https://homestead.joeferguson.me/
