### ISSUE TITLE
´Could not resolve host: vagrantcloud-files-production.s3.amazonaws.com´ when trying to install it with vagrant

### ISSUE THREAD

**Issue by Gr3gorywolf** [laravel/homestead#1305]
## Versions
  - Vagrant:Vagrant 2.2.6.
  - Provider: Virtualbox.
  - Homestead: 8.2.1.

## Host operating system
Windows 10

## Expected behavior
The installation should be completed 

## Actual behavior
The installation fails due host error

## Steps to reproduce
1.Execute vagrant box add laravel/homestead on terminal

**Comment by svpernova09** [comment]
This was part of a global AWS outage, nothing we could do. It should be resolved by now.
