### ISSUE TITLE
Installing ImageMagick 

### ISSUE THREAD

**Issue by tonyclemmey** [laravel/homestead#1312]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.6
  - Provider: Virtualbox 6.0.14r133895
  - Homestead: v9.3.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
MacOS Mojave 14.16

## Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/homestead-sites/site1
      to: /home/vagrant/code/site1

sites:
    - map: site1.test
      to: /home/vagrant/code/site1
      php: "7.1"

databases:
    - site1

features:
    - mariadb: true
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
I would like to install ImageMagick and have any site in my homestead directory or site 1 using php7.1 to be able to use (https://github.com/m-emelchenkov/pdfthumb)

```
vagrant@homestead:~$ sudo apt-get update && sudo apt-get install -y imagemagick php-imagick && sudo service php7.3-fpm restart && sudo service nginx restart
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:3 https://deb.nodesource.com/node_12.x bionic InRelease
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [613 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [795 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,025 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [402 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [572 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [619 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [990 kB]
Get:13 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [596 kB]
Hit:14 http://ppa.launchpad.net/nginx/development/ubuntu bionic InRelease
Hit:15 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:16 https://cli-assets.heroku.com/apt ./ InRelease
Hit:17 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
Hit:18 http://ftp.osuosl.org/pub/mariadb/repo/10.4/ubuntu bionic InRelease
Fetched 5,863 kB in 6s (1,044 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  php-imagick
The following packages will be upgraded:
  imagemagick
1 upgraded, 1 newly installed, 0 to remove and 245 not upgraded.
Need to get 14.2 kB/295 kB of archives.
After this operation, 2,682 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 imagemagick amd64 8:6.9.7.4+dfsg-16ubuntu6.8 [14.2 kB]
Fetched 14.2 kB in 0s (344 kB/s)
Selecting previously unselected package php-imagick.
(Reading database ... 174186 files and directories currently installed.)
Preparing to unpack .../php-imagick_3.4.4-1+ubuntu18.04.1+deb.sury.org+11_amd64.deb ...
Unpacking php-imagick (3.4.4-1+ubuntu18.04.1+deb.sury.org+11) ...
Preparing to unpack .../imagemagick_8%3a6.9.7.4+dfsg-16ubuntu6.8_amd64.deb ...
Unpacking imagemagick (8:6.9.7.4+dfsg-16ubuntu6.8) over (8:6.9.7.4+dfsg-16ubuntu6.7) ...
Setting up php-imagick (3.4.4-1+ubuntu18.04.1+deb.sury.org+11) ...
Setting up imagemagick (8:6.9.7.4+dfsg-16ubuntu6.8) ...
vagrant@homestead:~$ php -v
PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
vagrant@homestead:~$ convert -version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
vagrant@homestead:~$ php -m | grep imagick
imagick
```

## Actual behavior
It does not seem to work even though installed.

**Comment by svpernova09** [comment]
The CLI PHP version is unaffected by the site setting of PHP version, you should use one of the built in aliases to change php versions such as `php71` to switch the CLI to 7.1

**Comment by tonyclemmey** [comment]
Ok, thanks for the PHP CLI switch tip. So I have `$ vagrant/homestead ssh` into the box then `$ php71` and run `$ sudo apt-get update && sudo apt-get install -y imagemagick php-imagick && sudo service php7.1-fpm restart && sudo service nginx restart` and then `$php -m` to see if the imagick is loaded, which it shows in list but still the Craft site plugin I'm trying to use does not work. I have also run `$ homestead reload --provision` the site plugin seems to work on a site which I assume is apache server and the only difference with my local version is my Homestead setup. 

Any guidance on getting the PHP ImageMagick library successfully installed would be very appreciated, everywhere I look online shows different methods for trying to get it installed in homestead.

**Comment by tonyclemmey** [comment]
After trying to add `extension=imagick.so` to the bottom of both `php.ini` files in `/etc/php/7.1/cli` and `/etc/php/7.1/fpm` suggested by other answers online I'm still unable to get it working and not sure where I am going wrong? or if this is an issue with the PHP version?

```
root@homestead:/etc/php/7.1/fpm# php -i | grep 'php.ini'
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Configuration File (php.ini) Path => /etc/php/7.1/cli
Loaded Configuration File => /etc/php/7.1/cli/php.ini
```

```
root@homestead:/etc/php/7.1/fpm# php --ini
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Configuration File (php.ini) Path: /etc/php/7.1/cli
Loaded Configuration File:         /etc/php/7.1/cli/php.ini
Scan for additional .ini files in: /etc/php/7.1/cli/conf.d
Additional .ini files parsed:      /etc/php/7.1/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.1/cli/conf.d/10-opcache.ini,
/etc/php/7.1/cli/conf.d/10-pdo.ini,
/etc/php/7.1/cli/conf.d/15-xml.ini,
/etc/php/7.1/cli/conf.d/20-bcmath.ini,
/etc/php/7.1/cli/conf.d/20-calendar.ini,
/etc/php/7.1/cli/conf.d/20-ctype.ini,
/etc/php/7.1/cli/conf.d/20-curl.ini,
/etc/php/7.1/cli/conf.d/20-dom.ini,
/etc/php/7.1/cli/conf.d/20-exif.ini,
/etc/php/7.1/cli/conf.d/20-fileinfo.ini,
/etc/php/7.1/cli/conf.d/20-ftp.ini,
/etc/php/7.1/cli/conf.d/20-gd.ini,
/etc/php/7.1/cli/conf.d/20-gettext.ini,
/etc/php/7.1/cli/conf.d/20-iconv.ini,
/etc/php/7.1/cli/conf.d/20-igbinary.ini,
/etc/php/7.1/cli/conf.d/20-imagick.ini,
...........
```

**Comment by svpernova09** [comment]
Add this to `after.sh` 
```
sudo apt-get update
sudo apt-get install -y php-imagick
```

Then run `vagrant destroy && vagrant up`, when the VM comes back up you should be able to check `phpinfo()` for the Imagick section:

<img width="996" alt="Screen Shot 2019-11-15 at 09 34 09" src="https://user-images.githubusercontent.com/967362/68955292-4fddb580-078b-11ea-801a-291e68d85eb2.png">

**Comment by tonyclemmey** [comment]
Hey @svpernova09 

Revisiting this in regards to installing on the latest Homestead Box. (performing vagrant destroy && vagrant up) but seem to have issues with Imagick not showing.

- Vagrant: 2.2.15
- VirtualBox: 6.1.20r143896
- Homestead: 11.1.0

Inside `after.sh` file
```
$ sudo apt-get update
$ sudo apt-get install -y imagemagick
$ sudo apt-get install -y php-imagick
```

Homestead SSH, and run commands manually to check imagick installed (below output)
```
imagemagick is already the newest version (8:6.9.10.23+dfsg-2.1ubuntu11.2).
php-imagick is already the newest version (3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1).
```

Add `extension=imagick` to PHP version used (php74) to `php.ini` files
```
$ sudo nano /etc/php/7.4/cli/php.ini
$ sudo nano /etc/php/7.4/fpm/php.ini
$ sudo service php7.4-fpm restart
```

Create and check a phpinfo() page but no Imagick is shown same for CLI `php -m | grep imagick` using php74.

Check extensions directory and `imagick.so` does not exist 
```
$ php-config --extension-dir
$ ll /usr/lib/php/20190902
```

PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: /usr/lib/php/20190902/imagick (/usr/lib/php/20190902/imagick: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/imagick.so (/usr/lib/php/20190902/imagick.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Any ideas? or to what might need to be done differently now.

**Comment by tonyclemmey** [comment]
Ok it seems the below will work

```
$ sudo apt-get install -y php7.4-imagick
```

**Comment by janeannpaul366** [comment]
@tonyclemmey Thankyou so much..

sudo apt-get install -y php7.4-imagick

this worked for me..was stuck with the imagick issue for a while..

**Comment by rashadmirza** [comment]
Add this line to your **after.sh** file:

`sudo apt-get install -y php7.4-imagick`

Then

`$ vagrant reload --provision`
