### ISSUE TITLE
PHP7.4 Memcached

### ISSUE THREAD

**Issue by repat** [laravel/homestead#1314]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox
  - Homestead: release

## Host operating system
MacOS

## Expected behavior
PHP7.4 has the `memcached` extension installed

## Actual behavior
> vagrant@homestead:~/$ php7.4 -m
> [PHP Modules]
> bcmath
> calendar
> Core
> ctype
> curl
> date
> dom
> exif
> FFI
> fileinfo
> filter
> ftp
> gd
> gettext
> hash
> iconv
> imagick
> imap
> intl
> json
> ldap
> libxml
> mbstring
> mysqli
> mysqlnd
> odbc
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> PDO_ODBC
> pdo_pgsql
> pdo_sqlite
> pgsql
> Phar
> posix
> pspell
> readline
> Reflection
> session
> shmop
> SimpleXML
> soap
> sockets
> sodium
> SPL
> sqlite3
> standard
> sysvmsg
> sysvsem
> sysvshm
> tokenizer
> xdebug
> xml
> xmlreader
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib
> 
> [Zend Modules]
> Xdebug
> Zend OPcache

## Steps to reproduce
1. Switch to PHP7.4
2. Try to use anything that uses the memcached extension

**Comment by svpernova09** [comment]
Is the extension in the repo yet? This isn’t a bug, just a 7.4 isn’t GA yet so the implementation should be considered RC quality at best.

Thanks for the report I’ll check into memcached on 7.4

**Comment by repat** [comment]
I couldn't find it but I also don't know how you guys do this magic ;-) Just wanted to try out PHP7.4 to be prepared but couldn't use memcached ootb. Figured it's not a bug, just fyi

**Comment by themaric** [comment]
@svpernova09 Can you please re-check this out?

My development environment:

- Vagrant: 2.2.6
- Provider: Virtualbox 6.0.14
- Homestead: 10.0.1
- Box: 9.0.1
- Host operating system: Arch Linux

This is what I got:

```lang=bash
$ php7.4 -m
[PHP Modules]
bcmath
bz2
calendar
componere
Core
ctype
curl
date
dba
dom
enchant
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mongodb
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

Thanks in advance!

**Comment by svpernova09** [comment]
Yeah, memcached is one of the packages I dropped. Building a test box now with fixes, once I verify it I'll build new boxes.

**Comment by themaric** [comment]
Ta la!
