### ISSUE TITLE
Is not to run php script. Is to download.

### ISSUE THREAD

**Issue by allowing** [laravel/homestead#1319]
## Versions
Homestead v9.4

![Download the script](https://user-images.githubusercontent.com/20262949/69603062-708ff000-1054-11ea-9369-6ce793cf0efd.jpg)

**Comment by svpernova09** [comment]
Looks like the web server Is broken, run vagrant destroy && vagrant up

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by staudenmeir** [comment]
Are you using Homestead with a non-Laravel site?

I'm having the same issue. I'm using Homestead for WordPress sites, but have never specified a custom site type in `Homestead.yaml`. With #1316, this no longer works.

I can specify the (undocumented) type `wordpress`, but that redirects everything into the `wp` directory.

@svpernova09 Is there a (simple) way to prevent that or a 'neutral" site type?

**Comment by svpernova09** [comment]
@browner12 😎 What about that new site type? 

@staudenmeir, yeah sorry about that. Unintended consquences.

@browner12: Should we revert this change to the `laravel` site type and put the more strict version into `strict` type? Open to ideas.

**Comment by allowing** [comment]
I redo so many times. when fullback v9.3.1 It’s worked fine. So totally sure the issue is 9.4

**Comment by svpernova09** [comment]
@allowing I've just tagged https://github.com/laravel/homestead/releases/tag/v9.4.1 Please update and `vagrant destroy && vagrant up` and let me know if you still have the issue.

**Comment by staudenmeir** [comment]
Great, thanks!

**Comment by allowing** [comment]
![image](https://user-images.githubusercontent.com/20262949/69700542-aa7cf700-1125-11ea-8640-51ca4e3517ae.png)
@svpernova09 There is a new tips :(

**Comment by svpernova09** [comment]
@allowing This is the same issue as before, there's either something wrong with your YAML or your files aren't accessible by the user you're running `vagrant` as.

**Comment by browner12** [comment]
sorry for the slow reply guys. been losing all my money on vacation in Vegas....

I'm still of the mindset that the *default* should be to force everything through `index.php`, and if needed, make a new site type for the people who want the old behavior. I understand this can break some existing applications, but with documentation and the appropriate Twitter alerts, people can adjust as needed.  We want to cover the 99% use case, which I believe is to run everything through the Front Controller.  People who need to be able to execute PHP files directly should be required to make the minor tweaks to their Homestead configuration.

Being a project of the size and importance that Homestead is, I believe we also have a responsibility to encourage current best practices, and I would say that best practice is to run everything through the FC.

If someone has a use case for directly executing a PHP file versus sending it through `index.php`, I would love if you could share.

**Comment by svpernova09** [comment]
> I'm still of the mindset that the default should be to force everything through index.php, and if needed, make a new site type for the people who want the old behavior. I understand this can break some existing applications, but with documentation and the appropriate Twitter alerts, people can adjust as needed. We want to cover the 99% use case, which I believe is to run everything through the Front Controller. People who need to be able to execute PHP files directly should be required to make the minor tweaks to their Homestead configuration.

Agreed. We should keep defaults normalized and we should add site types to support old behavior if people are having issues (Such as in this case)

> Being a project of the size and importance that Homestead is, I believe we also have a responsibility to encourage current best practices, and I would say that best practice is to run everything through the FC.

Certainly, I rolled back this change and moved it to a site type because I felt like this was a breaking change we didn't properly note and people having boxes break on them like this in a minor release isn't what we want. Happy to discuss the best path forward.
