### ISSUE TITLE
vagrant box add laravel/homestead fails.

### ISSUE THREAD

**Issue by paulgeneres** [laravel/homestead#1324]
## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox
  - Homestead: release

## Host operating system
Windows 10

## vagrant box add laravel/homestead output
https://gist.github.com/paulgeneres/3db839eaab974935a704b95174eced0b

I don't know if it's HashiCorp, Homestead, or me, but `vagrant box add laravel/homestead` is failing. Anybody else have this issue?

**Comment by svpernova09** [comment]
Interesting, I was able to download it without issue. I’d try again in a bit, might be an S3/AWS issue.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by paulgeneres** [comment]
Okay. Thanks. I'll try again in the morning.

**Comment by svpernova09** [comment]
If this is an existing system you've used Homestead on, try doing `vagrant box update` from the Homestead folder.

**Comment by cregx** [comment]
Same issue on Mac OS X 10.15.1 (Catalina) when updating: vagrant box update

**Comment by sandervankasteel** [comment]
It appears to be a bug on the side of vagrant, https://github.com/hashicorp/vagrant/issues/11179

**Comment by jeroenboumans** [comment]
As a temporarily work around I've installed vagrant from source (which includes the latest patch that fixes this issue) using these instructions: https://www.vagrantup.com/docs/installation/source.html

From within that directory run your homestadd add box command:
`bundle exec vagrant box add laravel/homestead`

Or run in debug mode:
`bundle exec vagrant box add laravel/homestead --debug`

**Comment by kadoyau** [comment]
Same issue. I try @jeroenboumans steps and issue is solved.

**Comment by samwrigley** [comment]
These steps worked for me and avoids having to build Vagrant from source: https://github.com/hashicorp/vagrant/issues/11226#issuecomment-559979637

**Comment by paulgeneres** [comment]
Another work-around:

1. Download the box from `https://vagrantcloud.com/laravel/boxes/homestead/versions/9.0.0/providers/virtualbox.box` to your homestead folder.
2. Create a file named metadata.json in your homestead folder and paste in this gist: `https://gist.github.com/paulgeneres/9319888048e01865d2259c1c2a6c89e1`
3. run vagrant box add laravel/homestead metadata.json
