### ISSUE TITLE
POSTGIS Support

### ISSUE THREAD

**Issue by bryanrscott** [laravel/homestead#1327]
I might be wrong but in v10.0.0 POSTGIS support 
a) should the file "scripts/postgis.sh" be in "scripts/features/postgis.sh"

b) I think the script needs to be looked at (to include versions), for example the final line
sudo apt-get -y install postgresql-11-postgis-2.5 postgresql-11-postgis-2.5-scripts

c) Any chance of considering moving to postgis 3?
sudo apt-get -y install postgresql-11-postgis-3 postgresql-11-postgis-3-scripts

**Comment by svpernova09** [comment]
> I might be wrong but in v10.0.0 POSTGIS support
> a) should the file "scripts/postgis.sh" be in "scripts/features/postgis.sh"

Yep!

> b) I think the script needs to be looked at (to include versions), for example the final line
> sudo apt-get -y install postgresql-11-postgis-2.5 postgresql-11-postgis-2.5-scripts
> 
> c) Any chance of considering moving to postgis 3?
> sudo apt-get -y install postgresql-11-postgis-3 postgresql-11-postgis-3-scripts

Updated the feature to use version 3, also added them to the base box since it's just 2 packages.  Starting with https://github.com/laravel/homestead/releases/tag/v10.0.1 you can use `postgis: true` to install these packages.
