### ISSUE TITLE
getmxrr not working

### ISSUE THREAD

**Issue by rabol** [laravel/homestead#1330]
I'm using latest version of vagrant, virtualbox and Homestead

getmxrr, nslookup etc. does not work from the terminal in homestead

**Comment by svpernova09** [comment]
Not sure what to tell you. I don't know what `getmxrr` is. I know what `nslookup` is but Vagrant should pass along any DNS queries to your host machine. So it may be something regarding  your networking? Was this working in a previous version? There's a reason we have the issue template. It's near impossible to debug when you completely ignore it.
