### ISSUE TITLE
why newest release remove client_max_body_size 100m; line

### ISSUE THREAD

**Issue by indraakkk** [laravel/homestead#1331]
## Host operating system
Ubuntu 18.04

## Expected behavior
nano /etc/nginx/sites-available/marketplace.local
```
server {
.
.
client_max_body_size 100m;
.
.
}
```

## Actual behavior
nano /etc/nginx/sites-available/marketplace.local
```client_max_body_size 100m;``` is removed

**Comment by svpernova09** [comment]
Check out the commit message here: https://github.com/laravel/homestead/commit/bcec472e2896fe880b89f690bfff5f48a6ddd1e9#diff-00f030f92ac0db045d3055bcdbe39d70
