### ISSUE TITLE
Updating Homestead deletes all existing databases without warning

### ISSUE THREAD

**Issue by mariopro** [laravel/homestead#1332]
Please note this is not a true bug report, rather an important suggestion that should be considered to be implemented for Homestead updates.

## Versions
v9.1.0 +

## Host operating system
macOS Catalina
Virtualbox 6.0.14

## Homestead.yaml
Not applicable

## Vagrant destroy & up output
**This is where users might encounter the problem**
It happened to myself the first time I upgraded Homestead because I was unaware (although I should) that destroying Vagrant will **delete all databases**. Fortunately, I had backups, although not the daily backup for two projects. In summary, has to rebuild/import all the databases back to the machine.

## Expected behavior
The suggestions go towards the system warning the user of the consequences of the `vagrant destroy` command and advise to backup databases prior to perform the update.

I'm not sure if other settings will be reset also, and if so, warnings should appear in the terminal.

## Actual behavior
The current behavior lets the user perform the `vagrant destroy` to update the new Homestead release and all databases (and possibly other custom settings) are deleted from the machine.

## Steps to reproduce
1. Under the Homestead, directory perform the `composer update`;
2. The system will update as expected.
3. If no `vagrant destroy` command is done, the next time the user runs `vagrant up` the terminal shows the message that the new release/version is available but not implemented. "Run vagrant destroy to apply the update of the latest Homestead available".
4. After this, with `vagrant up` the machine is then rebuilt but all databases are lost.

## References
None

**Comment by browner12** [comment]
https://laravel.com/docs/6.x/homestead#database-backups

**Comment by mariopro** [comment]
Thanks @browner12  for the clarification and note. Never noticed or paid attention to that in the docs but probably, as a suggestion for less experienced users, this could come as "true" by default.
Thanks!

**Comment by mohammad6006** [comment]
I missed my databases 
is there any way to restore?

**Comment by mariopro** [comment]
> I missed my databases
> is there any way to restore?

If you did not have dumps and neither the option set in your .yaml file to `backup: true`, they're lost.

In case you had the option in your Homestead.yaml file set to `backup: true` when you provision the machine, the backups will be restored.

In case you did not have it in the Homestead.yaml file but had the DB dumps, just create import the dumps to each respective database.

As suggested above by @browner12  more details in the Laravel docs at 
[https://laravel.com/docs/6.x/homestead#database-backups](https://laravel.com/docs/6.x/homestead#database-backups)
