### ISSUE TITLE
Documentation Request: Document all the default aliases.

### ISSUE THREAD

**Issue by thinsoldier** [laravel/homestead#1344]
I looked in the alias file for the first time ever and noticed `dbexport` and `dbimport`. These aren't mentioned in the documentation on laravel.com. I also recently noticed `flip` in the documentation. Was that documented back in 2017? I don't think it was. Would have saved me a boat load of headache back in the day if it was.

**Comment by svpernova09** [comment]
Feel free to open an PR against the docs repo. Note: the docs repo uses branches for versioning so ensure you're PRing against the current (Laravel) version of the docs.
