### ISSUE TITLE
Setup subdomains

### ISSUE THREAD

**Issue by IsmetGlumcevic** [laravel/homestead#1348]
- Vagrant: Vagrant 2.2.6
  - Provider: Virtualbox
  - macOS Catalina

## Homestead.yaml

    ip: "192.168.10.10"
    memory: 2048
    cpus: 2
    provider: virtualbox
    authorize: ~/.ssh/id_rsa.pub

    keys:
    - ~/.ssh/id_rsa

    folders:

       - map: ~/Projects/Laravel5/site
          to: /home/vagrant/code/site

    sites:

    - map: site.test
       to: /home/vagrant/code/site/public
       php: "7.1"

    - map: subdomain1.site.test
       to: /home/vagrant/code/site/public
       php: "7.1"

    - map: subdomain2.site.test
       to: /home/vagrant/code/site/public
       php: "7.1"

    - map: subdomain3.site.test
       to: /home/vagrant/code/site/public
       php: "7.1"

     databases:
    - homestead

     features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

I have domain like site.test and 3 subdomains like subdomain1.site.test.
This is hosts:

    192.168.10.10   site.test
    192.168.10.10   subdomain1.site.test
    192.168.10.10   subdomain2.site.test
    192.168.10.10   subdomain3.site.test

It always open site.test. Subdomain subdomain1.site.test automatic redirect to site.test

**Comment by svpernova09** [comment]
Not sure what to tell you. There are so many factors unrelated to Homestead which could be causing this. Redirects in your application?

**Comment by svpernova09** [comment]
If you're trying to use multiple variable / known subdomains in your laravel application I think you *don't* want to specify them as sites to have hosts created for them. I think you want to remove those, rebuild and let your application handle the requests and routing instead of having virtual hosts for each subdomain. Just a wild guess.

**Comment by IsmetGlumcevic** [comment]
It work without homestead. I need homestead because has multiple versions php...
This is my route

      $subdomainRoutes = function() {
          Route::get('/', 'Front\IndexController@subdomainIndex');
      };
      Route::group(array('domain' => 'subdomain1.site.test'), $subdomainRoutes);
      Route::group(array('domain' => 'subdomain2.site.test), $subdomainRoutes);
      Route::group(array('domain' => 'subdomain3.site.test), $subdomainRoutes);
      Route::get('/', 'Front\IndexController@index');

**Comment by svpernova09** [comment]
Does it look like your routing is just overwriting the `domain` array key? 

Based on https://laravel.com/docs/6.x/routing#route-group-subdomain-routing I would expect your code to look like this:

```
Route::domain('{sub}.site.test')->group(function () {
    Route::get('/', function ($sub, $id) {
        //
    });
});
```

Not sure how to help you. This is outside of the scope of Homestead as far as I can tell.
