### ISSUE TITLE
Package Request: Git LFS

### ISSUE THREAD

**Issue by bandgeekndb** [laravel/homestead#1353]
Simple package request, could the git-lfs package be included out of the box? It's a relatively small package and for those of us who use LFS in their repos, it would be nice to not have to install it separately. Thanks!

**Comment by bandgeekndb** [comment]
@svpernova09 Sorry to tag directly, but I'm now realizing I could easily submit a PR to Settler for adding this. Is this something you'd be amenable to before I go ahead and submit the PR? Thanks!

**Comment by svpernova09** [comment]
Hey! Sorry for the long delay. Totally ok to ping me for this. Yeah go for it. I should have replied sooner that this would be fine PR for settler.

**Comment by bandgeekndb** [comment]
Closed by [laravel/settler #216](https://github.com/laravel/settler/pull/216).
