### ISSUE TITLE
Loading of SQLite extension "Spatialite"

### ISSUE THREAD

**Issue by vpratfr** [laravel/homestead#1360]
I develop an application which requires MySQL geometry columns (Point, Polygon, etc.)

I have some unit tests which are failing because SQLite does not natively support those types.

Support for such types is provided via the SQLite extension "[Spatialite](https://www.gaia-gis.it/fossil/libspatialite/index)"

That package can be installed easily via `sudo apt-get install -y spatialite-bin`

I cannot figure out however how to enable that extension in PHP and have Laravel use it.

Seems Spatialite is installed but not loaded by Laravel / PHP.

Any idea what I would need to do to get my tests to pass?

**Comment by vpratfr** [comment]
Here is some information I could find for integration with PHP5. Don't know how I could enable it with the latest Homestead.

http://www.gaia-gis.it/spatialite-2.4.0-4/splite-php.html

**Comment by browner12** [comment]
I had been trying to figure out how to enable Sqlite Extensions as well for their JSON extension, and was never able to find the solution.

**Comment by svpernova09** [comment]
> I develop an application which requires MySQL geometry columns (Point, Polygon, etc.)

Test against MySQL then. Or use SQLite in production. Practice how you play IMHO.

**Comment by svpernova09** [comment]
It would appear none of the `Spatialite` packages actually create or contain the `*.so` file to be loaded. You could try compiling the extension yourself and see if it works from there. Should be straightforward just adjust the php.ini paths to the FPM paths and tweak Nginx instead of Apache.

Unless we can find a package to produce this `.so` extension to be loaded I think we're out of luck.

**Comment by browner12** [comment]
I was able to generate the `.so`s easy enough, but that's where I got stuck.

I'm also in the boat where I test against MySQL now.

**Comment by svpernova09** [comment]
> I was able to generate the .sos easy enough, but that's where I got stuck.

From here, it looks like once you have the SO you just have to put in an accessible folder and drop a config extension into PHP, the bigger thing I'd be worried about is if this was last known good on 5.3, I doubt it's going to play well w/ 7.

**Comment by vpratfr** [comment]
> Test against MySQL then. Or use SQLite in production. Practice how you play IMHO.

That is what I have reverted to currently. However there is a huge speed difference, I figured I would ask here if that issue had already been solved for any kind of SQLite extension.
