### ISSUE TITLE
Docs incomplete? Homestead by default forwards ports to the host machine - no private network setting

### ISSUE THREAD

**Issue by marcinwasilewski** [laravel/homestead#1376]
I am familiar with vagrant. Normally the way I would set it up is:
- set up a private network IP in Vagrantfile,
- on the host machine, add this IP to the /etc/hosts along with the desired domain name,
- add a new site in nginx/apache with that domain name,
- access the site from the host machine by going to http://hostname .

I thought I would try homestead to speed up the process and avoid potential server config pitfalls. The same way I was configuring vagrant seems to be encouraged in the official Laravel docs, except most of the work is supposed to be done automatically by homestead. One just needs to specify the IP in homestead.yaml.

It turns out however that by default, homestead forwards port 80 from guest to 8000 of host machine, and the webserver is inaccessible directly as these ports are closed from outside. So the only way to access the app is via localhost on the host machine through a forwarded port: http://localhost:8000. The /etc/hosts entries should point to 127.0.0.1 then... 

Are the docs outdated or am I missing something? The docs should require one additional step (adding a private network to homestead config file):

    networks:
        - type: "private_network"
          ip: "192.168.10.20"

Which way is the recommended way - or what are the pros and cons of doing it either way?

**Comment by deviantintegral** [comment]
Homestead also supports mDNS which lets you use `*.local` domains without hacking `/etc/hosts`: https://laravel.com/docs/6.x/homestead#configuring-homestead

**Comment by svpernova09** [comment]
https://laravel.com/docs/6.x/homestead#network-interfaces
