### ISSUE TITLE
Cannot connect workbench or navicat

### ISSUE THREAD

**Issue by laravelcoder** [laravel/homestead#1377]
Everything worked fine until up updated homestead. now when i try to connect my gui to the db i get this error.

```
2007- protocol mismatch; server version = 11; client version = 10;
```
I cannot find a fix and im hoping you might have one. 

I have the normal setup. 
host: 127.0.0.1
user: homestead
pass: secret

Like i said normally this worked everytime but now i get that error. 

Thanks in advance.

**Comment by svpernova09** [comment]
Please fill out the entire issue template. It's the only way anyone has a chance of helping you.
