### ISSUE TITLE
nginx config for Prestashop

### ISSUE THREAD

**Issue by LucaF87** [laravel/homestead#1386]
Hi,
I created the configuration to be able to use Prestashop,

[serve-prestashop.zip](https://github.com/laravel/homestead/files/4361966/serve-prestashop.zip)
if someone needs it I attach it to you.

How To install:
Copy the file serve-prestashop.sh into scripts folder in your homestead main folder.
Open Homestead.yaml and add "type: prestashop" on your sites configurations.
ES:
- map: mysitename.local
      to: /var/www/mysitename
      type: prestashop

Enjoy :)

**Comment by powolnymarcel** [comment]
Thanks, helped us ;)
