### ISSUE TITLE
Sort DB backups into folders

### ISSUE THREAD

**Issue by ethanclevenger91** [laravel/homestead#1392]
## Versions
  - Vagrant: 2.2.7
  - Provider: VBox 6.0.18
  - Homestead: release

It'd be great if DB backups were not just timestamped on the file name, but grouped into timestamped folders. That way it'd be easy to re-import an entire directory of files.

Couldn't find this script in the repo, but could work on a PR if I knew where to look

**Comment by svpernova09** [comment]
The functionality is located in the Homestead Ruby class: https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L572-L585

As these are inline command scripts I don't know if I'd be in favor of any added complexity.
