### ISSUE TITLE
connection refused or bad gateway

### ISSUE THREAD

**Issue by ojabi** [laravel/homestead#1400]
I'm using the latest Vagrant and latest VirtualBox, Homestead version 9.5.0-alpha1 as of a week ago. I've always had issues with getting connection refused to 503 bad gateway errors and have to reboot Homestead VM. I'm wondering what is going on with this? I have this issue whether I'm using Ubuntu Linux or Windows 10 as a VM host.

**Comment by svpernova09** [comment]
You forgot to fill out the issue template.
