### ISSUE TITLE
v10.8 default Postgresql version

### ISSUE THREAD

**Issue by bryanrscott** [laravel/homestead#1412]
## Versions
  - Vagrant: 2.2.6
  - Provider: VMWare
  - Homestead:  10.8

## Host operating system
MacOs

## Expected behavior
postgresql 12 should be on port 5432
as per homestead 10.8 release notes.

## Actual behavior
postgresql 9.6 is on port 5432, postgresql 12 is port 5435
root@homestead:~# pg_lsclusters
Ver Cluster Port Status Owner    Data directory               Log file
9.6 main    5432 down   postgres /var/lib/postgresql/9.6/main /var/log/postgresql/postgresql-9.6-main.log
10  main    5433 down   postgres /var/lib/postgresql/10/main  /var/log/postgresql/postgresql-10-main.log
11  main    5434 down   postgres /var/lib/postgresql/11/main  /var/log/postgresql/postgresql-11-main.log
12  main    5435 online postgres /var/lib/postgresql/12/main  /var/log/postgresql/postgresql-12-main.log

## Steps to reproduce
vagrant destroy
vagrant up

**Comment by svpernova09** [comment]
I was afraid of this :/

Thanks for reporting, I'll dig into it

**Comment by bryanrscott** [comment]
cheers, if it helps.   I am looking into adding the following to after.sh (it is not as good as specified db's etc are not created)

sudo systemctl stop postgresql
sudo sed -i 's/^port.*/port = 5435/' /etc/postgresql/9.6/main/postgresql.conf
sudo sed -i 's/^port.*/port = 5432/' /etc/postgresql/12/main/postgresql.conf
sudo service postgresql@12-main restart
sudo -u postgres psql -c "CREATE ROLE homestead LOGIN PASSWORD 'secret' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;"
sudo -u postgres /usr/bin/createdb --echo --owner=homestead homestead

**Comment by svpernova09** [comment]
I'm testing out a fix that will require a base box update. But yeah, this will work for now ^

**Comment by svpernova09** [comment]
Tagged https://github.com/laravel/settler/releases/tag/v9.5.1
Uploaded https://app.vagrantup.com/laravel/boxes/homestead/versions/9.5.1
