### ISSUE TITLE
Homestead Settings File Not Found.

### ISSUE THREAD

**Issue by Jennp1987** [laravel/homestead#1416]
I am using Gitbash to set up Homestead, Virtual Box, Vagrant and Vagrant Box. I am getting the message that the Homestead Settings file is not found. I did copy the entire folder of Homestead of this branch into the new C drive folder under Users that I created, and it does have the Homestead.yaml.example file but I keep getting this error message. How can I fix it?

**Comment by svpernova09** [comment]
What is the output of `init.bat`?

**Comment by Jennp1987** [comment]
command not found

**Comment by svpernova09** [comment]
So let's step back and review. So far you should have done the following:

* Cloned this repo to your local system (let's say to C:\users\code\homestead)
* open a terminal (cmd.exe or powershell.exe) run `cd C:\users\code\homestead`
* run `init.bat`

What's the output from that?


Note: I just don't know enough about git bash. Powershell is *awesome* and I highly recommend WIndows users embrace it. (The new terminal app is 10/10 too)

**Comment by Jennp1987** [comment]
Well, this is what I'm getting when I use Powershell when trying to cd into the Homestead folder. 
 Set-Location : A positional parameter cannot be found that accepts argument 'Bot\Homestead'.
At line:1 char:1
+ cd C:\Users\J Bot\Homestead
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by svpernova09** [comment]
Since you have a space in your username you should quote it on the command line (And many other places).

```
cd "C:\Users\J Bot\Homestead"
init.bat
```

**Comment by Jennp1987** [comment]
I got it up and running! Thanks for the response!
