### ISSUE TITLE
The Nginx server has established its own CA, server, client certificate, Chrome prompts https is not secure

### ISSUE THREAD

**Issue by huyifanstar** [laravel/homestead#1425]
Certificate creation process：
![image](https://user-images.githubusercontent.com/15685376/82398671-0053ab80-9a86-11ea-8344-4c828ab9d8e2.png)

chrom version:   81.0.4044.138
nginx version： nginx/1.16.1

Firefox prompt is ok

![image](https://user-images.githubusercontent.com/15685376/82409340-11a9b180-9aa0-11ea-8b9f-7e21c3751777.png)
What should I do now？

**Comment by browner12** [comment]
I'm not sure I exactly understand your question, but I'm guessing you need to add the root certificate to your trusted list.

Start by copying the root cert in Homestead to your shared folder.

`cp /etc/nginx/ssl/ca.homestead.homestead.crt ~/code`

Then on your host open this file.  On a Mac it will bring up keychain. Double click the cert, and then under "Trust" select "Always Trust".

**Comment by huyifanstar** [comment]
chrom Has joined, and nginx is also configured  (crt/key)
