### ISSUE TITLE
Renew SSL certificate

### ISSUE THREAD

**Issue by m-lotze** [laravel/homestead#1431]
The homestead ssl certificate on my box was generated in march 2019 and now is no longer accepted by chrome, because it is only valid for a year. Is there a simple way to renew the certificate without updating the box or a download link for a current version of the certificate? i made quite a lot of customizations after installing homestead and would want to avoid doing it all over.

**Comment by svpernova09** [comment]
You are supposed to use after.sh to implement your own customizations. Vagrant boxes aren’t built to be long running. You’re also on a really old base box and homestead version. It’s just not practical for me to support anything but the latest version.

Take this time to learn the lesson that virtual machines should be treated as cattle, not pets.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by adriandmitroca** [comment]
I don't think it's 100% related but also refers to SSL issue, specifically to some root cert that expired on 30 of May.

I have downloaded fresh Settler & Homestead versions and configured everything from scratch and there you go, PHP's `file_get_contents()` and up with `file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in` error.

References:
[1] https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration
[2] https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020
