### ISSUE TITLE
`php74` command not found

### ISSUE THREAD

**Issue by nathanpurcell** [laravel/homestead#1433]
## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox
  - Homestead: 9.5.1

## Host operating system
macOS High Sierra (10.13.6)

## Homestead.yaml
n/a

## Vagrant destroy & up output
n/a

## Expected behavior
Homestead's CLI PHP version should have been changed to 7.4

## Actual behavior
The command `php74` cannot be found:  
`-bash: php74: command not found`

## Steps to reproduce
In Homestead: 
1. Run `php73` (or any of the other available options as per docs) - CLI PHP version is now 7.3.x (or equivalent)
2. Run `php74`  - command not found. 

## References
No other GitHub issues I could find.  
[Corresponding Laravel docs](https://laravel.com/docs/7.x/homestead#multiple-php-versions) for commands. 

I think this may just be a small oversight as I believe 7.4 is the default version when installing Homestead - I just can't get back to it! 

Thanks!

**Comment by svpernova09** [comment]
Update your aliases file. If you have made changes to this file you can delete it and run the init script again to create a fresh copy.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by nathanpurcell** [comment]
That was it, thank you. 
Would you like me to make a PR to the Laravel docs repo to add this as an instruction under "Updating Homestead"?

**Comment by svpernova09** [comment]
Go for it! feel free to ping me in the PR.

Glad it was an easy fix

**Comment by nathanpurcell** [comment]
https://github.com/laravel/docs/pull/6097
Thanks!
