### ISSUE TITLE
Hyper-V maxmemory and mac address

### ISSUE THREAD

**Issue by DaWolfey** [laravel/homestead#1445]
Vagrant supports two settings for Hyper-V boxes that would be really useful for Homestead to incorporate.

These are:
maxmemory - which defines the maximum amount of memory a hyper-v guest can use (this enables the hyper-v dynamic memory feature, and the current memory setting becomes startup memory)

mac - which sets the guests nic's mac address - this is really useful when provisioning because you can't set the ip directly through the settings and so if you use dhcp, it ensures the box always gets the same address.

**Comment by svpernova09** [comment]
Thanks for the heads up! I'll have a look at supporting these in the Homestead config.

**Comment by svpernova09** [comment]
Give 611c1f89a05f88e5f5a29864d22927caac07fdd8 (master branch as of this post) a spin.

## Usage Notes (Hyper-V Specific)

https://www.vagrantup.com/docs/providers/hyperv/configuration


### `hyperv_mac`

> `mac` (string) - MAC address for the guest network interface


### `hyperv_maxmemory`

>`maxmemory` (integer) - Maximum number of megabytes allowed to be allocated for the VM. When set Dynamic Memory Allocation will be enabled.


### `hyperv_enable_virtualization_extensions`

> `enable_virtualization_extensions` (boolean) - Enable virtualization extensions for the virtual CPUs. Default: false

**Comment by svpernova09** [comment]
These options are now supported as of https://github.com/laravel/homestead/releases/tag/v10.11.0
