### ISSUE TITLE
xdebug.ini in CLI of PHP

### ISSUE THREAD

**Issue by longestdrive** [laravel/homestead#1446]
Hi

Currently using v9.5.1

Out of the box Xdebug is installed and working on the php-fpm version but not in the CLI version

I am able to get this to work by copying the `20-xdebug.ini` file from the `php\7.4\fpm\conf.d` folder to the `php\7.4\cli\conf.d` folder.

Would it be possible to update the base configuration that this config file is already set up for cli version?

Thanks

**Comment by svpernova09** [comment]
We intentionally ship Xdebug disabled on the CLI. We provide an alias https://github.com/laravel/homestead/blob/master/resources/aliases#L266-L285 to toggle this.
