### ISSUE TITLE
Proposal: Change "master" branch to "main"

### ISSUE THREAD

**Issue by mendelB** [laravel/homestead#1450]
Hey, Homestead friends!

First of all, as a grateful Homestead user -- I wanted to offer my sincere thanks for this Open Source delight! I'm thankful for all the work that goes into maintaining, improving, and keeping this project free and accessible. 🙌 

As you're probably well aware, there's been much chatter (and action!) within the tech community regarding renaming the dubiously titled `master` branch default to a more racially friendly and less problematic name like `main` in respective projects.

- [Github's](https://thenextweb.com/dd/2020/06/15/github-plans-to-replace-racially-insensitive-terms-like-master-and-whitelist/) working to replace the default
- [Some quick](http://www.kapwing.com/blog/how-to-rename-your-master-branch-to-main-in-git/) context on the movement for the switch, along with a howto guide
- An article about [Engineers at Twitter](https://www.cnet.com/news/twitter-engineers-replace-racially-loaded-tech-terms-like-master-slave/) purging racially insensitive terms from their codebase
- A well written [Twitter thread](https://twitter.com/mislav/status/1270388510684598272) with some succinct points on the issue

I could very well be naive as to the more far-reaching complex consequences of such a venture within the Homestead project. But I happened to be considering the implications of changing the branch name on personal/work-related projects using Homestead, and I figured it would be prudent also to raise this - what I would consider "enhancement" - for consideration on Homestead itself! (And of course, all the better if this could extend to other projects in the Laravel ecosystem!)

**Is this something that could be considered?**

I'm happy to offer my time to help with this in any way that I can, as I certainly understand that this could be putting work on other folks' plates.

Thanks so so much in advance for your consideration and thoughts!!!

---

_I also just want to recognize that in the scheme of the holistic movement for racial equity, this admittedly doesn't have much apparent tangible effect ([this](https://twitter.com/bryanl/status/1278343673672011776) poignant Tweet puts it well). But I do firmly believe, that this certainly helps demonstrate and hopefully effect a more inclusive attitude from us as a Tech community, and helps alleviate any future pain and exclusion caused by these loaded terms, as words do matter!_

**Comment by browner12** [comment]
while I am all for BLM and other social justice issues, I personally feel like the term 'master' has no racial context in this scenario, and we should not treat it as such.

This is not a hill I'm going to die on, so if someone wants to do the work to change it, so be it, but my opinion is it's unnecessary.

**Comment by mendelB** [comment]
> while I am all for BLM and other social justice issues, I personally feel like the term 'master' has no racial context in this scenario, and we should not treat it as such.
> 
> This is not a hill I'm going to die on, so if someone wants to do the work to change it, so be it, but my opinion is it's unnecessary.

@browner12 Thanks for responding. Respectfully, I think it's important to recognize that while intuitively the term has no racial context, in the scheme of [it being rooted](https://twitter.com/tobie/status/1270290278029631489?s=20) within the "master/slave" metaphor -- I think we have to consider this being inherently intertwined with a painful racial history that's all too prevalent today. (Of course, even, understanding that America is not the center of the Universe, this is all too, unfortunately, universal).

I'd encourage you to read through the [Twitter thread](https://twitter.com/mislav/status/1270388510684598272) I linked to in the description for what I feel like is a very compelling case for this switch, regardless of the technical nuances of the term itself.

Thanks for listening!

**Comment by svpernova09** [comment]
@taylorotwell @driesvints has this come up for the Laravel org yet?

**Comment by browner12** [comment]
Thanks for linking all those references, I did read through the Twitter threads. I always love to see different perspectives to challenge my views.

I definitely agree more with the second Twitter thread, but good to see both opinions.

Symbolic gestures definitely can have importance, but to me this one feels more like an empty gesture.

**Comment by mendelB** [comment]
@browner12 Thanks for taking the time to read through those threads! 

I certainly hear your point. I feel like empty symbolic gestures and virtue signaling can sometimes be more dangerous than simple inaction. It can make us feel good about "Improving the status quo" even in the face of glaring practical positive change.

But to me, in the face of the current mass consciousness, the larger conversation, and most importantly, hearing from BIPOC friends & colleagues that this _does_ makes a difference, I have a much stronger appreciation for even seemingly small gestures like this.

It admittedly can be difficult to intuitively, viscerally feel this as a white person (speaking for myself here), but even if there's a small minority of folks who are emotionally affected, who might feel less included or just a quick sting, or an all too familiar disappointment, wouldn't a small gesture quickly turn into something so essential and useful, and assume importance? I feel more strongly about this since, as a Tech community, we have so much work to do to make our environment more inclusive, so even the smaller things bear weight!

And finally, per the second thread -- I don't feel like "symbolic" gestures, and broader concrete action should be mutually exclusive. If they are, it's a sign that we need to _really_ introspect!

Again, I sincerely appreciate the conversation!!

**Comment by driesvints** [comment]
@svpernova09 no

**Comment by svpernova09** [comment]
Thanks Dries!

I spoke to @taylorotwell briefly this morning and this is the first time for the Laravel organization this has come up. We both agree that Homestead is a good test run of this change since we're mostly isolated from the rest of the Laravel project repositories.

To move forward with this change:

I need Taylor to give me more access over this repo and laravel/settler to so I have permission to rename the `master ` branches. Otherwise, he can perform the change himself and we can expect the current default branch `master` to be changed to `main` on both repositories.

**Comment by mendelB** [comment]
Thanks so much for this update and for taking this on @svpernova09!! 🙌 

This _sounds_ simple enough, but if there's any which way I can help, please do give me a shout!

**Comment by salaback** [comment]
@taylorotwell @svpernova09 Not to be a rain cloud, and I understand @mendelB's point that words matter, but if you do make this change, any chance you can take a second look at business practices and maybe find a way to create more opportunities for disadvantaged folks in tech? I don't know how many roles there are in the Laravel organisation, and I know open source is generally a meritocracy, but maybe there is also a chance to create a trainee role targeting towards African Americans. Just thinking about how good intentions can be targeting towards more lasting impacts.

**Comment by svpernova09** [comment]
@salaback

I have zero influence on Laravel's business practices. I'm not employed by Laravel.

**Comment by Fossil01** [comment]
This is the dumbest issue on Github I have ever seen.

**Comment by driesvints** [comment]
@Fossil01 if you don't have anything productive to bring to this issue then please refrain from posting.

**Comment by Fossil01** [comment]
That was the first thing I said out loud when I read this. I did some Googling and apparently this really is a "thing" now?

Let's just keep identity politics out of the Laravel / tech-space. There is literally zero racial connotation about the words master or slave in this context.

If you give in to this then there's no stopping any of the inevitable next ridiculous demands.

**Comment by salaback** [comment]
@Fossil01 I’ll agree with you that the issue feels a bit superfluous, hence my own comment encouraging some sort of action be taken rather than spending the type to refactor branches.  

Though to say there is ‘zero racial connotation’ is also hardly accurate. While in Git we don’t talk about them as Master and Slave branches that is the connotation, and of course in DB design and other parts of tech we do actually use this terminology. I’m a white guy sitting in a posh office so I don’t feel a lot of sting to see the references, but it doesn’t take a lot of emotional intelligence to see how such nomenclature can be very painful those with other backgrounds. And no matter how large the tech community is, we all have an individual responsibility for continuing or discontinuing the use of offensive terms and analogies.

**Comment by kybash** [comment]
The noun master can be used in at least 5 different ways (1. Controller, 2. Skilled Person, 3. Teacher, 4. Title, 5. Copy). [https://dictionary.cambridge.org/dictionary/english/master](https://dictionary.cambridge.org/dictionary/english/master)

Here within the context of describing a software release version it would arguably fall under the 5th category, like the master copy of a film or audio recording.

The "master version" of this software is used as a basis for further derivative works.

**Comment by svpernova09** [comment]
I've locked conversation here because there's nothing to be gained by the recent influx of sillyness. Decisions have been made. This issue is only still open because I don't have access to make this change. I'm literally waiting for @taylorotwell to recover / catch up after Laracon before bugging him about this. Or I'll just tag him and bug him now :D

**Comment by taylorotwell** [comment]
Done.
