### ISSUE TITLE
[QUESTION] Recommended way to have MySQL 5.7 on version 11

### ISSUE THREAD

**Issue by maxacarvalho** [laravel/homestead#1460]
Hello,

Hopefully this is a quick one.  
What's the recommended way to have the MySQL version 5.7 instead 8 installed, since the Homestead version 11 bring MySQL 8 by default.

Thanks!

**Comment by svpernova09** [comment]
Currently, you'd have to do this manually.

I'll see what I can do.

**Comment by maxacarvalho** [comment]
thanks a mil @svpernova09!

**Comment by browner12** [comment]
are you running into actual backwards compatibility issues? or are you just trying to keep your local in sync with your production?

**Comment by maxacarvalho** [comment]
I have a legacy project alongside with a new Laravel application.  
The new Laravel application will replace the legacy and it will be a API-first solution. But of course, that will take a long time, until then we will have to keep both applications running, pointing to the same database, which needs to be (for now) 5.7.

**Comment by svpernova09** [comment]
There's nothing I can do, [MySQL 5.7 isn't available for 20.04/focal](http://repo.mysql.com/apt/ubuntu/dists/focal/). :(

![image](https://user-images.githubusercontent.com/967362/88206602-23c8dd00-cc14-11ea-85ab-4aacdc573e52.png)

**Comment by maxacarvalho** [comment]
Got it, no worries then, thanks again!

**Comment by browner12** [comment]
My understanding is that MySQL 8 is also mostly backwards compatible with 5.x so I'd be curious to hear if you can run your legacy application on 8. 

I know personally I upgraded an application to v8 with zero issues.

**Comment by Morinohtar** [comment]
> 
> 
> There's nothing I can do, [MySQL 5.7 isn't available for 20.04/focal](http://repo.mysql.com/apt/ubuntu/dists/focal/). :(
> 
> If you need 5.7 you should stick with Homestead 10.x
> 
> ![image](https://user-images.githubusercontent.com/967362/88206602-23c8dd00-cc14-11ea-85ab-4aacdc573e52.png)


I'm using Homestead 10 but i'm not being able to turn off mysql 8 and put 5.7.

### My specs
  - Vagrant: 2.2.14
  - Provider: Virtualbox
  - Homestead: 20.04 branch
  - Homestead Box: 10.1.1

I destroyed the machine, updated Homestead.yaml and set there mysql8 to false, boot up the machine again and the mysql 8 keeps popping up.

**Comment by svpernova09** [comment]
> 
> 
> > There's nothing I can do, [MySQL 5.7 isn't available for 20.04/focal](http://repo.mysql.com/apt/ubuntu/dists/focal/). :(
> > If you need 5.7 you should stick with Homestead 10.x
> 
> 
> I'm using Homestead 10 but i'm not being able to turn off mysql 8 and put 5.7.
> ### My specs
> 
>     * Vagrant: 2.2.14
> 
>     * Provider: Virtualbox
> 
>     * Homestead: 20.04 branch
> 
>     * Homestead Box: 10.1.1
> 
> 
> I destroyed the machine, updated Homestead.yaml and set there mysql8 to false, boot up the machine again and the mysql 8 keeps popping up.


You are confusing Homestead (repo) version 10 with Homestead Vagrant Box (base box) version 10. You want Homestead (repo) version 10 which uses Vagrant box (base box) version 9.
