### ISSUE TITLE
Folder /etc/ssl/certificates doesn't exist in v11.x

### ISSUE THREAD

**Issue by Stoux** [laravel/homestead#1467]
## Versions
  - Vagrant: 2.2.6
  - Provider: VirtualBox v6.0.31
  - Homestead: v11.0.1

## Host operating system
macOS Catalina 10.15.6

## Expected behavior
Folder `/etc/ssl/certificates` to exist.

## Actual behavior
Folder doesn't exist, however `/etc/ssl/certs` does exist.

## References
https://github.com/laravel/homestead/releases/tag/v11.0.0

> SSL certificates are now installed at /etc/ssl/certificates instead of /etc/nginx/ssl

Is this an error in the release notes and can we modify our scripts to work with `/etc/ssl/certs` or will this be modified to `/etc/ssl/certificates` in future releases?

**Comment by svpernova09** [comment]
This is a typo in the release notes yes. Thanks for pointing it out, I'll update them.

I verified in Homestead and Settler we're operating under the assumption SSL certs will reside in `/etc/ssl/certs`. *not* `/etc/ssl/certificates`
