### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by bartek1234321** [laravel/homestead#1471]
Hi, I've got some symfony 4 app, Vagrant 2.2.9 and virtualbox 6.1 and laravel/homestead (9.5.1 and 10.0.0) Homestead.yaml the same for both, the same page: login page for homestead 10.0.0 loads in 300ms and for 9.5.1 about 4500ms why?

**Comment by svpernova09** [comment]
I have no idea and you haven't offered anything here to help me even begin to narrow down what it could be.
