### ISSUE TITLE
Proposal: Support WSL2/docker

### ISSUE THREAD

**Issue by pacharrin** [laravel/homestead#1479]
Since the release of WSL2 [docker now can be run in windows 10](https://docs.docker.com/docker-for-windows/wsl/) without a pro license.

It will greatly reduce the pain for windows developers if docker is added as a supported provider

The current pain we are facing is we have laravel projects running with homestead and other (non laravel) projects running in docker. and activating hyper-v heavily affect the performance of the laravel projects

I have not much experience with this codebase but if someone is willing to guide me, I will gladly help to make this happen

**Comment by svpernova09** [comment]
So Homestead *on* docker isn't a thing I'm interested in exploring. It's just a Bad Idea(tm) IMHO.

I've been working on "What does Homestead on WSL look like?" but I'm not ready to announce/discuss widely just yet.

**Comment by svpernova09** [comment]
https://twitter.com/JoePFerguson/status/1301327211530723328

If this looks interesting take a look at https://joeferguson.me/exporting-and-importing-wsl-linux-distributions-on-windows-10/

https://github.com/laravel/homestead/blob/20.04/scripts/wsl.sh

`sudo scripts/wsl.sh`

`./scripts/site-types/laravel.sh "/PATH/TO/PROJECT/public" "DOMAIN" 80 443 "7.4"`
