### ISSUE TITLE
Homestead & WSL 2 - Windows 10

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#1484]
# Provision/Configure Ubuntu 20.04

You must be on the Homestead branch `20.04`. Create a new/blank Ubuntu 20.04 WSL Distribution. Run the new distribution and change directories to where you have Homestead cloned. For me this is `/mnt/c/Users/halo/Code/homestead`. Run the initial provisioning script to install the base Homestead system. The script will ask you for your WSL username and user group. You should use your username for your user group unless you have specific plans or requirements outside of the scope of Homestead.

    $ cd Code/homestead
    $ sudo ./bin/wsl-init
    [sudo] password for halo:
    What is your WSL user name?
    halo
    What is your WSL user group? (Same as username if you're unsure)
    halo
    Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
    ...

# Create Sites from Homestead Configuration

Add a new top level configuration item in your `Homestead.yaml` configuration such as:

```
wsl_sites:
    -   map: vcdt.test
        to: /mnt/c/Users/halo/Code/vcdt/public
```

    $ ./bin/homestead wsl:create-sites

The sites from `wsl_sites` will be created.

# Create Databases from Homestead Configuration

WSL will read from the normal `databases` configuration in `Homestead.yaml`

```
databases:
    - homestead
    - vcdt
    - laminas
```

    $ ./bin/homestead wsl:create-databases
    mysql: [Warning] Using a password on the command line interface can be insecure.
    mysql: [Warning] Using a password on the command line interface can be insecure.
    mysql: [Warning] Using a password on the command line interface can be insecure.
    mysql: [Warning] Using a password on the command line interface can be insecure.
    mysql: [Warning] Using a password on the command line interface can be insecure.
    mysql: [Warning] Using a password on the command line interface can be insecure.
    WSL Databases have been created!

The databases from `databases` will be created.

# Installing Optional Features

WSL will read from the normal `features` configuration in `Homestead.yaml`
```
features:
    - timescaledb: true
```

    $ ./bin/homestead wsl:apply-features
    Using postgresql.conf at this path:
    /etc/postgresql/12/main/postgresql.conf

    Writing backup to:
    /tmp/timescaledb_tune.backup202010041216

    Recommendations based on 50.17 GB of available memory and 8 CPUs for PostgreSQL 12
    Saving changes to: /etc/postgresql/12/main/postgresql.conf
    Command output can be found via: sudo cat ~/.homestead-features/timescaledb.log
    WSL features have been configured!

**Comment by litan1106** [comment]
@svpernova09 I got NULL error when I ran ./bin/homestead wsl:wsl:create-site
it created the site but error out before the cert.

![image](https://user-images.githubusercontent.com/1310539/92972809-c09b4000-f437-11ea-9043-6be3c8a10116.png)

`PHP Fatal error:  Uncaught Error: Call to undefined function Laravel\Homestead\isNull() in /mnt/c/WSL2Homestead/src/WslCreateSiteCommand.php:82
Stack trace:
#0 /mnt/c/WSL2Homestead/vendor/symfony/console/Command/Command.php(258): Laravel\Homestead\WslCreateSiteCommand->execute()
#1 /mnt/c/WSL2Homestead/vendor/symfony/console/Application.php(916): Symfony\Component\Console\Command\Command->run()
#2 /mnt/c/WSL2Homestead/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#3 /mnt/c/WSL2Homestead/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#4 /mnt/c/WSL2Homestead/bin/homestead(16): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /mnt/c/WSL2Homestead/src/WslCreateSiteCommand.php on line 82`

**Comment by svpernova09** [comment]
> @svpernova09 I got NULL error when I ran ./bin/homestead wsl:wsl:create-site
> it created the site but error out before the cert.

Whoops! I have some local changes I haven't pushed.

**Comment by svpernova09** [comment]
Should be fixed as of da5eed767e34495f64aa5d2ab4d458179acf38e3

**Comment by litan1106** [comment]
@svpernova09 I tried provision script again with a fresh ubuntu 20.04 with wsl2. It required php and composer as prerequisite.

`./bin/homestead wsl:init`

# bin/homestead content
`#!/usr/bin/env php
<?php

if(is_file( __DIR__.'../../vendor/autoload.php')) {
    require  __DIR__.'../../vendor/autoload.php';
} else {
    require __DIR__.'../../vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Laravel Homestead', '11.2.0');

$app->add(new Laravel\Homestead\MakeCommand);
$app->add(new Laravel\Homestead\WslCreateSiteCommand);
$app->add(new Laravel\Homestead\WslInitializeCommand());

$app->run();
`

**Comment by litan1106** [comment]
@svpernova09 I got an error with `./bin/homestead wsl:create-site` because the nginx conf still referred to vagrant user.

nginx confg
```cat /etc/nginx/nginx.conf
user vagrant;
worker_processes auto;
pid /run/nginx.pid;```

wsl:create-site error
```/mnt/c/Homestead/src/WslCreateSiteCommand.php:91:
string(125) "Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
"
/mnt/c/Homestead/src/WslCreateSiteCommand.php:97:
string(38) " * Restarting nginx nginx
   ...fail!
"
PHP Fatal error:  Uncaught Error: Call to a member function writeln() on string in /mnt/c/Homestead/src/WslCreateSiteCommand.php:100
Stack trace:
#0 /mnt/c/Homestead/vendor/symfony/console/Command/Command.php(258): Laravel\Homestead\WslCreateSiteCommand->execute()
#1 /mnt/c/Homestead/vendor/symfony/console/Application.php(916): Symfony\Component\Console\Command\Command->run()
#2 /mnt/c/Homestead/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#3 /mnt/c/Homestead/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#4 /mnt/c/Homestead/bin/homestead(16): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /mnt/c/Homestead/src/WslCreateSiteCommand.php on line 100```

**Comment by svpernova09** [comment]
> @svpernova09 I tried provision script again with a fresh ubuntu 20.04 with wsl2. It required php and composer as prerequisite.
> 
> `php ./bin/homestead wsl:init`

I assumed PHP was already there. Will investigate.

**Comment by svpernova09** [comment]
>  I got an error with ./bin/homestead wsl:create-site because the nginx conf still referred to vagrant user.
> ./bin/homestead wsl:create-site

I get 

```
/mnt/c/Users/halo/Code/homestead/src/WslCreateSiteCommand.php:97:
string(38) " * Restarting nginx nginx
   ...done.
"
/mnt/c/Users/halo/Code/homestead/src/WslCreateSiteCommand.php:97:
string(38) " * Restarting nginx nginx
   ...done.
"
/mnt/c/Users/halo/Code/homestead/src/WslCreateSiteCommand.php:97:
string(38) " * Restarting nginx nginx
   ...done.
"
PHP Fatal error:  Uncaught Error: Call to a member function writeln() on string in /mnt/c/Users/halo/Code/homestead/src/WslCreateSiteCommand.php:100
Stack trace:
#0 /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Command/Command.php(258): Laravel\Homestead\WslCreateSiteCommand->execute()
#1 /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Application.php(916): Symfony\Component\Console\Command\Command->run()
#2 /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#3 /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#4 /mnt/c/Users/halo/Code/homestead/bin/homestead(17): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /mnt/c/Users/halo/Code/homestead/src/WslCreateSiteCommand.php on line 100

Fatal error: Uncaught Error: Call to a member function writeln() on string in /mnt/c/Users/halo/Code/homestead/src/WslCreateSiteCommand.php on line 100

Error: Call to a member function writeln() on string in /mnt/c/Users/halo/Code/homestead/src/WslCreateSiteCommand.php on line 100

Call Stack:
    0.0016     394680   1. {main}() /mnt/c/Users/halo/Code/homestead/bin/homestead:0
    0.2639    1822992   2. Symfony\Component\Console\Application->run() /mnt/c/Users/halo/Code/homestead/bin/homestead:17
    0.3940    2060696   3. Symfony\Component\Console\Application->doRun() /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Application.php:140
    0.3941    2064112   4. Symfony\Component\Console\Application->doRunCommand() /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Application.php:264
    0.3941    2064112   5. Laravel\Homestead\WslCreateSiteCommand->run() /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Application.php:916
    0.3942    2065944   6. Laravel\Homestead\WslCreateSiteCommand->execute() /mnt/c/Users/halo/Code/homestead/vendor/symfony/console/Command/Command.php:258
```

But no nginx errors, I'll fix the `writeln()` error shortly

**Comment by litan1106** [comment]
> > @svpernova09 I tried provision script again with a fresh ubuntu 20.04 with wsl2. It required php and composer as prerequisite.
> > `php ./bin/homestead wsl:init`
> 
> I assumed PHP was already there. Will investigate.
php not installed by default on ubuntu wsl
![image](https://user-images.githubusercontent.com/1310539/93113763-7c45b500-f66e-11ea-9fb5-3ebf7585a691.png)

**Comment by svpernova09** [comment]
We should remove the PHP init command, move the `wsl.sh` script to `bin/wsl-init`.

Create new WSL distro, Navigate to homestead folder, run `bin/wsl-init` which bootstraps everything and from there you configure`Homestead.yaml` and start running wsl:create-sites` commands

**Comment by svpernova09** [comment]
Using a57003f60e970e551712d0fb8f5eb3314216b667:

https://gist.github.com/svpernova09/849337cb89812b97925002042e6c6dbc

**Comment by litan1106** [comment]
The new wsl-init script works great in WSL2. I noticed the php7.4-fpm service failed.

`ERROR: unable to bind listening socket for address '/run/php/php7.4-fpm.sock': No such file or directory (2)
ERROR: FPM initialization failed`

**Comment by svpernova09** [comment]
> 
> 
> @svpernova09 The new wsl-init script works great in WSL2. I noticed the php7.4-fpm service failed.
> 
> `ERROR: unable to bind listening socket for address '/run/php/php7.4-fpm.sock': No such file or directory (2) ERROR: FPM initialization failed`

Haven't been able to replicate, but I have fixed a few other issues with 7f57b782e3e0314fad16fde90600bdf98b8b0d21

**Comment by svpernova09** [comment]
New tweaks: 6aad11cad0efb4b7b1ea0ee0ac85ec5ad549d87b

Usage:
```
halo@Rage:/mnt/c/Users/halo$ cd Code/homestead
halo@Rage:/mnt/c/Users/halo/Code/homestead$ export WSL_USERNAME=halo
halo@Rage:/mnt/c/Users/halo/Code/homestead$ export WSL_USER_GROUP=halo
halo@Rage:/mnt/c/Users/halo/Code/homestead$ sudo -E ./bin/wsl-init
```

Log: https://gist.github.com/svpernova09/d2f39d6b14d745c70a30855f5740fb32

**Comment by litan1106** [comment]
@svpernova09 I used the above code to wsl-init but I still got an error with mysql. (I reinstalled ubuntu wsl for every wsl init test.)

https://gist.github.com/litan1106/9625765774dc5a701476953e1e55ffd1#file-new-wsl-init-log-L5754

**Comment by svpernova09** [comment]
> @svpernova09 I used the above code to wsl-init but I still got an error with mysql. (I reinstalled ubuntu wsl for every wsl init test.)
> 
> https://gist.github.com/litan1106/9625765774dc5a701476953e1e55ffd1#file-new-wsl-init-log-L5754

This seems to be common on 20.04, I've seen this in my other systems, I believe it's because the user we're switching to doesn't have access to the filesystem and thus presents this weird error, but the mysql command appears to complete without error.

**Comment by litan1106** [comment]
@svpernova09 I ran `./bin/homestead wsl:create-site` after `sudo -E ./bin/wsl-init` but I still ran into php7.4-fpm failed issue.

how do we enable features or services with this wsl2 init approach?

![image](https://user-images.githubusercontent.com/1310539/93271471-340abd80-f768-11ea-8c50-9b0fedbdd57f.png)

` sudo service php7.4-fpm restart`
 `* Restarting PHP 7.4 FastCGI Process Manager php-fpm7.4                                                                                                                                                        [fail]`

sudo cat /var/log/php7.4-fpm.log
```[15-Sep-2020 14:45:59] ERROR: unable to bind listening socket for address '/run/php/php7.4-fpm.sock': No such file or directory (2)```

**Comment by svpernova09** [comment]
> how do we enable features or services with this wsl2 init approach?

You can't at the moment. My plan is to continue building PHP wrappers around the bash scripts similar to how Ruby is the wrapper for them when running in Vagrant. So I'm anticipating more commands such as "Create databases", "Install features", etc. I'm going to be writing about this process for phparch.com so at least those two features should be expected sometime this week.

**Comment by litan1106** [comment]
> > how do we enable features or services with this wsl2 init approach?
> 
> You can't at the moment. My plan is to continue building PHP wrappers around the bash scripts similar to how Ruby is the wrapper for them when running in Vagrant. So I'm anticipating more commands such as "Create databases", "Install features", etc. I'm going to be writing about this process for phparch.com so at least those two features should be expected sometime this week.

Nice. I am thinking something like [this](https://gist.github.com/litan1106/2bfa0bb17da8cfccb5e33415050512ac) too.

**Comment by svpernova09** [comment]
> 
> Nice. I am thinking something like [this](https://gist.github.com/litan1106/2bfa0bb17da8cfccb5e33415050512ac) too.

Yes exactly. feel free to PR this. 

We also need to account for some features having [variables parsed to the ENV](https://github.com/laravel/homestead/blob/20.04/scripts/homestead.rb#L270). We're duplicating [feature parsing and running](https://github.com/laravel/homestead/blob/20.04/scripts/homestead.rb#L244-L273) and we also need to [create the path(s)](https://github.com/laravel/homestead/blob/20.04/scripts/homestead.rb#L225-L227) in [wsl init](https://github.com/laravel/homestead/blob/20.04/bin/wsl-init#L656)

**Comment by litan1106** [comment]
> @svpernova09 I ran `./bin/homestead wsl:create-site` after `sudo -E ./bin/wsl-init` but I still ran into php7.4-fpm failed issue.
> 
> ` sudo service php7.4-fpm restart`
> `* Restarting PHP 7.4 FastCGI Process Manager php-fpm7.4 [fail]`
> 
> sudo cat /var/log/php7.4-fpm.log
> `[15-Sep-2020 14:45:59] ERROR: unable to bind listening socket for address '/run/php/php7.4-fpm.sock': No such file or directory (2)`

I added the following to fixed the php fpm issue.

`mkdir -p /run/php`
`touch /run/php/php7.4-fpm.sock`
`touch /run/php/php7.3-fpm.sock`

**Comment by litan1106** [comment]
@svpernova09 I am using this WSL 2 [SystemD solution](https://github.com/DamionGans/ubuntu-wsl2-systemd-script) to start the services automatically so I don't have to start the services after system reboot.

**Comment by svpernova09** [comment]
> 
> 
> > > how do we enable features or services with this wsl2 init approach?
> > 
> > 
> > You can't at the moment. My plan is to continue building PHP wrappers around the bash scripts similar to how Ruby is the wrapper for them when running in Vagrant. So I'm anticipating more commands such as "Create databases", "Install features", etc. I'm going to be writing about this process for phparch.com so at least those two features should be expected sometime this week.
> 
> Nice. I am thinking something like [this](https://gist.github.com/litan1106/2bfa0bb17da8cfccb5e33415050512ac) too.

Currently hacking on this ^

**Comment by litan1106** [comment]
@svpernova09 I have been using the wsl2 homestead workflow for 2 weeks. it's perfect and super fast. so light weight, perfect integration with docker desktop with wsl2 distro

- I ran into slow terminal issue with ohmyzsh.
- I ran into xdebug issue with phpstorm because the wsl2 ip changes every reboot. (my work around for the phpstorm xdebug is to set the xdebug.remote_host every reboot. lol)

wsl2 host ip cat `/etc/resolv.conf`

![image](https://user-images.githubusercontent.com/1310539/94055379-b65f3700-fd91-11ea-86bf-0a3571bb36b7.png)

thanks

**Comment by litan1106** [comment]
@svpernova09 I did a test with `wsl:apply-feature`, it worked like a charm with the vagrant user. lol (with the vagrant user, we can get the feature scripts to work without a single change.)

Steps to reproduce:
1. Create a new/blank Ubuntu 20.04 WSL Distribution with vagrant as username
2. Clone laravel/homestead 20.04 branch
3. Change to the homestead directory
4. Run commands
`sudo -E ./bin/wsl-init`
5. Restart the ubuntu-20.04 shell/session
6. Cd to the homestead directory again to run create-site and apply-feature
`./bin/homestead wsl:create-sites`
`./bin/homestead wsl:apply-feature`
7. Enjoy the blazing faster and light weight wsl2 development

**Comment by pacharrin** [comment]
I'll gladly help to test this,

tried @litan1106  steps, and everything ran without errors.

i only have one question do i need to start nginx and mysql servers manually or are there any extra steps i need to do?

**Comment by litan1106** [comment]
> I'll gladly help to test this,
> 
> tried @litan1106 steps, and everything ran without errors.
> 
> i only have one question do i need to start nginx and mysql servers manually or are there any extra steps i need to do?

You won't need to start it manually with this pr. (you can check `sudo systemctl status nginx` after you launch the wsl2 terminal`)

https://github.com/laravel/homestead/pull/1503/files#diff-06d003347c8900c844035a53e017e545R30

**Comment by svpernova09** [comment]
Sorry I've been AFK/Silent. I've been waiting on #Hactoberfest :D and also trying to work through some issues in regards to Features and WSL, since the feature scripts all assume they're running as the `vagrant` user instead of the WSL user. So far in the one feature we've enabled for WSL it adds a bit of boilerplate bloat to the feature scripts and I'm just not sure what the right tradeoff to take is. PR reviews + more work coming. I also need to push a `20.04-dev` branch so we can stop cowboy coding this onto the `20.04` branch.

**Comment by litan1106** [comment]
> Sorry I've been AFK/Silent. I've been waiting on #Hacktoberfest :D and also trying to work through some issues in regards to Features and WSL, since the feature scripts all assume they're running as the `vagrant` user instead of the WSL user. So far in the one feature we've enabled for WSL it adds a bit of boilerplate bloat to the feature scripts and I'm just not sure what the right tradeoff to take is. PR reviews + more work coming. I also need to push a `20.04-dev` branch so we can stop cowboy coding this onto the `20.04` branch.

I think it's fine to use vagrant as user in wsl2 provision because any feature script created for homestead will work in wsl2 too. Unless you guys prefer to define a user in the Homestead.yaml, then get the user from Homestead.yaml settings.

**Comment by svpernova09** [comment]
> I think it's fine to use vagrant as user in wsl2 provision because any feature script created for homestead will work in wsl2 too. Unless you guys prefer to define a user in the Homestead.yaml, then get the user from Homestead.yaml settings.

Yeah, I'm *probably* just going to add the boilerplate unless I can easily figure out a way around it. we'll see! Thanks for all your feedback & help!

**Comment by svpernova09** [comment]
A few updates:
* Added Docs for Databases, Features, general updates
* Added WSL support for all features

**Comment by litan1106** [comment]
> A few updates:
> 
> * Added Docs for Databases, Features, general updates
> * Added WSL support for all features
> * PRs should be made against `20.04-dev` branch

Love the WSL2 Support. Thanks for the hard work again.

**Comment by Houbsi** [comment]
Hi I just redid tthe whole setup several times, to figure out a problem on my end.

But i found out that the Databases are not created. Is there any other command I have to run, so that the Databases are created?

Nginx, php-fpm & mysql autostart is not yet configured during the setup process? If not I could take a look at it, if needed.

Thanks for the hard work! :)

**Comment by litan1106** [comment]
> Hi I just redid tthe whole setup several times, to figure out a problem on my end.
> 
> ~But i found out that the Databases are not created. Is there any other command I have to run, so that the Databases are created?~
> **EDIT:** Just found the wsl:create-databases Function.
> 
> Nginx, php-fpm & mysql autostart is not yet configured during the setup process? If not I could take a look at it, if needed.
> 
> Thanks for the hard work! :)

There is a pr #1517 for setup systemd on wsl2.

**Comment by litan1106** [comment]
I ran into issue when I tried to use mariadb instead of mysql in the `./bin/homestead wsl:apply-features` 

mariadb log
https://gist.github.com/litan1106/add837263254d88434ea012253d7ee0e

**Comment by svpernova09** [comment]
> 
> 
> @svpernova09
> I ran into issue when I tried to use mariadb instead of mysql in the `./bin/homestead wsl:apply-features`
> 
> mariadb log
> https://gist.github.com/litan1106/add837263254d88434ea012253d7ee0e

Confirmed. Seeing the following on a freshly configured 20.04:

```
halo@Rage:/mnt/c/Users/halo/Code/homestead$ ./bin/homestead wsl:apply-features
[sudo] password for halo:
Failed to retrieve unit state: Connection reset by peer
Warning! D-Bus connection terminated.
Failed to stop apparmor.service: Connection reset by peer
See system logs and 'systemctl status apparmor.service' for details.
Failed to retrieve unit state: Connection reset by peer
Failed to reload daemon: Connection reset by peer
Failed to reload daemon: Connection reset by peer
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: Sub-process /usr/bin/dpkg returned an error code (1)
[info] Repository file successfully written to /etc/apt/sources.list.d/mariadb.list
[info] Adding trusted package signing keys...
[info] Running apt-get update...
[info] Done adding trusted package signing keys
touch: cannot touch '/etc/mysql/debian.cnf': No such file or directory
E: Sub-process /usr/bin/dpkg returned an error code (1)
sed: can't read /etc/mysql/mariadb.conf.d/50-server.cnf: No such file or directory
/mnt/c/Users/halo/Code/homestead/scripts/features/mariadb.sh: line 50: /etc/mysql/mariadb.conf.d/50-server.cnf: No such file or directory
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Failed to retrieve unit state: Connection reset by peer
Warning! D-Bus connection terminated.
Failed to restart mysql.service: Connection reset by peer
See system logs and 'systemctl status mysql.service' for details.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Failed to retrieve unit state: Connection reset by peer
Warning! D-Bus connection terminated.
Failed to restart mysql.service: Connection reset by peer
See system logs and 'systemctl status mysql.service' for details.
Failed to retrieve unit state: Connection reset by peer
Warning! D-Bus connection terminated.
Failed to restart mysql.service: Connection reset by peer
See system logs and 'systemctl status mysql.service' for details.
Command output can be found via: sudo cat ~/.homestead-features/mariadb.log
WSL features have been configured!
halo@Rage:/mnt/c/Users/halo/Code/homestead$```

**Comment by Simoneu01** [comment]
Hi! First of all thank you !! I finally found what I needed.

Here are some bugs that I found:
I have enabled ohmyzsh as a feature and saw that it creates a / home / vagrant folder and attempted to use the vagrant user
https://gist.github.com/Simoneu01/4c3297b9dbc83f2ea41c28e464ff8e7e

**Comment by svpernova09** [comment]
WSL Support is now in `master`

**Comment by litan1106** [comment]
Awesome. Thanks

**Comment by litan1106** [comment]
I shared my ubuntu wsl2 systemd gist if anyone interested.

https://gist.github.com/litan1106/b7752acaa371f89660c7b83f27f71577

**Comment by juliomotol** [comment]
I'm having trouble on running `sudo bin/wsl-init`. It get stuck on `Starting redis-server: redis-server`. When I try to manually start the service - `sudo service redis-server start` - it works just fine.

![image](https://user-images.githubusercontent.com/21353103/104808515-be9c2000-5821-11eb-9c08-255a184d8655.png)

**Comment by karmendra** [comment]
When I try to install mysql by ./bin/homestead wsl:apply-features
I get error that mysql.sh script is not found, not sure why homestead/scripts/features is not having mysql.sh, it does have maraidb.sh

**Comment by karmendra** [comment]
Thanks, and sorry about my limited knowledge about it. are you suggesting we can use shelter instead of homestead for wsl?

**Comment by karmendra** [comment]
Ah ok, I get it.

Looking at the script amd64.sh, I feel like I can start a fresh wsl 2 Ubuntu 20.04 and then run this script to provision everything that I need for my laravel development environment, and then I can just install the Homestead repo and run commands ./bin/homestead wsl:create-sites and ./bin/homestead wsl:create-databases after setting up the Homestead.yml file. (I will not run ./bin/wsl-init and ./bin/homestead wsl:apply-features and ignore those for time being). You think it will work? I will give it a shot anyways.

Thanks.

**Comment by karmendra** [comment]
Hi @svpernova09, 
Can I submit a PR for the script update that I did?

Thanks,
Karmendra

**Comment by svpernova09** [comment]
> Hi @svpernova09, Can I submit a PR for the script update that I did? And is there a way to test this, I mean is there any test suite? I have tested for my use case, and it is working good.
> 
> Before running the wsl-init, in WSL I had to enable systemd and also update the resolve.conf to allow for WSL Distro to be able to resolve domain names using google DNS.
> 
> Thanks, Karmendra

Sure! I'm happy to review any PRs

**Comment by karmendra** [comment]
@svpernova09 I have been studying this fore many days now. and here is my proposal.

1. in wsl-init I add mysql as default DB, instead of mariadb, as that is the default homestead.yaml configuration. and to install mariadb can always enable the feature and install it (script is already present).

2. As per the new amd64.sh will install Mailhog as well in wsl-init

3. I also see current wsl-init is not having the proper feature tracking enabled i.e. # Configure feature tracking path mkdir -p /home/vagrant/.homestead-features

Apart from this wherever I can I will update the scripts to the latest as per amd64.sh (e.g. maraidb.sh installation, php older versions etc)

Let me know if this sounds good, I have already did the changes, running manual tests as of now.

Thanks,
Karmendra

**Comment by MichaelBelgium** [comment]
So, recently installed windows 11 and need a new dev environment, for windows 10 i had homestead, vagrant and virtualbox.

I wanna use WSL2 now, so i don't need vagrant/virtualbox.

Using the main branch and installed ubuntu 20.04:, wsl-init script works. the `wsl:create-sites` appear to be failing.

The first time it was because i had `type: "apache"` but i assume thats not supported (same for seperate php versions per site)

```
wsl_sites:
  - map: xxxxx
    to: /mnt/xxxxxxx/public
    type: "apache"
```

I commented the type and then i get this:


```
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
WSL sites have been created!
```

It cant restart nginx it seems, so like on this line?

https://github.com/laravel/homestead/blob/9d4fee9291baf4a031ebe9ee261b04c4c2364ff9/src/WslCreateSiteCommand.php#L122

But if i do restart nginx manually, using the exact same command, it works nonetheless.

Next thing: executing ` ./bin/homestead wsl:create-databases` works nicely
And then ` wsl:apply-features` i get

```
sh: 1: cannot create /home/michael/.homestead-features/mariadb.log: Directory nonexistent
Command output can be found via: sudo cat ~/.homestead-features/mariadb.log
WSL features have been configured!
```

There is no `.homestead-features` folder in `/home/michael` so command output doesn't exit too.

One thing I'm wondering, the mappings need to be added manually? In the hosts file from windows, pointing to wsl?
