### ISSUE TITLE
Proposal: Add RVM as supported feature

### ISSUE THREAD

**Issue by martianatwork** [laravel/homestead#1489]
I know that RVM can be installed easily but it will be easier to maintain it using homestead.
I can create a PR if approved.

Reference:
https://rvm.io/rvm/install

**Comment by svpernova09** [comment]
I would welcome a PR that implemented RVM in similiar fashion to other features.

**Comment by martianatwork** [comment]
@svpernova09 should we support stable ruby and bundler out of the box?

**Comment by svpernova09** [comment]
Yes, that seems reasonable.
