### ISSUE TITLE
oh-my-zsh error

### ISSUE THREAD

**Issue by yazeed** [laravel/homestead#1497]
Why do I see this as soon as I ssh into a newly created vagrant box based off v11.2.2? Something seems off with the oh-my-zsh setup there.

`/home/vagrant/.zprofile:source:2: no such file or directory: /home/vagrant/.bash_aliases`

I'm using this vagrant box.

==> homestead: Checking for updates to 'laravel/homestead'
    homestead: Latest installed version: 10.1.0
    homestead: Version constraints: ~> 10.0

I have vagrant up to date, and virtualbox up to date.

**Comment by svpernova09** [comment]
Show me the `aliases` file from the root of Homestead. According to your `.zprofile` it doesn't exist/didn't get copied to `/home/vagrant/.bash_aliases` as it should have.

**Comment by yazeed** [comment]
You're correct. There is no .bash_aliases file.

**Comment by svpernova09** [comment]
> Show me the aliases file from the root of Homestead

:D

**Comment by yazeed** [comment]
![Screen Shot 2020-09-15 at 3 07 14 AM](https://user-images.githubusercontent.com/191483/93153045-9039f700-f700-11ea-9ab5-d2c181d0f7ac.png)

Yeah, none there too.

**Comment by svpernova09** [comment]
Run the `init.sh`/ `init.bat` script again and it will recreate the aliases file for you.

**Comment by yazeed** [comment]
That worked, thanks a lot.
