### ISSUE TITLE
Connection to the database is denied everytime restart computer.

### ISSUE THREAD

**Issue by hieuhtse05008** [laravel/homestead#1498]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant 2.2.6
  - Provider: Virtualbox 6.0.

## Host operating system
Ubuntu 20.04

## Homestead.yaml
---
ip: "192.168.10.10"
memory: 4048
cpus: 6
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /home/nang/code/keetool-client-server
      to: /home/vagrant/keetool-client-server
    - map: /home/nang/code/eduto-client-server
      to: /home/vagrant/eduto-client-server            

sites:
    - map: keetool.com
      to: /home/vagrant/keetool-client-server/public
      php: "7.1"
    - map: edutoclient.test
      to: /home/vagrant/eduto-client-server/public      
      php: "7.4"

databases:
    - eduto
    - colorme
    - senn
    - colorme_elearning 	
features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

## Vagrant destroy & up output
https://gist.github.com/hieuhtse05008/b0853b33e43c7be897a288b553df9f03

## Expected behavior
Connection to mysql database must be normally.

## Actual behavior
There is an error happend everytime I try to connect database
After vagrant ssh, "mysql -u root -p" command not working with the same error below.
**Illuminate\Database\QueryException
SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost'**

**Comment by mikepage** [comment]
Windows has broken wsl/virtualbox yesterday with an update, reverting this update has solved my issue.

**Comment by svpernova09** [comment]
> 
> 
> Windows has broken wsl/virtualbox yesterday with an update, reverting this update has solved my issue.

WSL has nothing to do with Vagrant. If you're having an issue w/ WSL tooling please comment in that issue. If you're having another problem, feel free to open a new issue.

**Comment by svpernova09** [comment]
@hieuhtse05008 

I'm not sure I understand the issue. Your `vagrant up` looks good. When you reboot the computer while vagrant is running you may need to run `vagrant reload` or even `vagrant up`. The services *should* automatically start.  If they don't check the https://laravel.com/docs/8.x/homestead for "Enable / Disable Services"

**Comment by hieuhtse05008** [comment]
> Windows has broken wsl/virtualbox yesterday with an update, reverting this update has solved my issue.

I'm currently  using Ubuntu 20.04, I had this issue from Ubuntu 18.04 ultil now.

**Comment by hieuhtse05008** [comment]
> @hieuhtse05008
> 
> I'm not sure I understand the issue. Your `vagrant up` looks good. When you reboot the computer while vagrant is running you may need to run `vagrant reload` or even `vagrant up`. The services _should_ automatically start. If they don't check the https://laravel.com/docs/8.x/homestead for "Enable / Disable Services"

At first, I think it was a problem about vagrant or laravel/homestead box but it still fail after I reinstall vagrant or my ubuntu.
