### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by successdavis** [laravel/homestead#1502]
I can't access my site, all I get is a 502 Bad Gateway.

I meticulously followed the procedure provided here https://laravel.com/docs/8.x/homestead,

Here is how I have configured my host file 
192.168.10.10	homestead.test

Here is my Homestead.Yaml file configuration
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\Users\STECHMAX\Homestead\code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

**Comment by svpernova09** [comment]
There's not really enough for us to help you out here.
