### ISSUE TITLE
Is there any way to add custom nginx sites config?

### ISSUE THREAD

**Issue by utopictown** [laravel/homestead#1510]
wondering is it possible to add custom nginx sites-available file in Homestead config somewhere because self created sites-available would disappear after the machine has been provisioned. i need it because i want to serve a nodejs app. i know its mainly for laravel but its doable and this is the only missing part i think

**Comment by svpernova09** [comment]
This is a prime candidate to add a new site type. Take a look at the `site-types` folder. Create a new script that creates the virtualhost you need for NodeJS.
