### ISSUE TITLE
Latest release tries to download a box with v9

### ISSUE THREAD

**Issue by pOmelchenko** [laravel/homestead#1515]
Why latest release tries to download an older homestead box?

I see it is related with that rows but I don't see instructions for setting latest box version https://github.com/laravel/homestead/blob/e20bb5c6edcec632b4776665647a3f6805bb8657/scripts/homestead.rb#L21-L23
I think it can be confusing new users

## Versions
  - Vagrant: Vagrant 2.2.10
  - Provider: Virtualbox 6.1.14r140239
  - Homestead: latest from `release` branch

## Host operating system
macOS 10.15.7 (19H2)

## Homestead.yaml
I tried with default `Homestead.yaml` file and my own custom file where I add only `sites` and `databases` for used projects

## Vagrant destroy & up output
```bash
➜  Homestead git:(release) vagrant box list
laravel/homestead (virtualbox, 10.1.1)
➜  Homestead git:(release) vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Box 'laravel/homestead' could not be found. Attempting to find and install...
    homestead: Box Provider: virtualbox
    homestead: Box Version: ~> 9
==> homestead: Loading metadata for box 'laravel/homestead'
    homestead: URL: https://vagrantcloud.com/laravel/homestead
==> homestead: Adding box 'laravel/homestead' (v9.6.1) for provider: virtualbox
    homestead: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/9.6.1/providers/virtualbox.box
==> homestead: Box download is resuming from prior download progress
Progress: 100% (Rate: 453/s, Estimated time remaining: --:--:--)^C
```

## Expected behaviour
I wait for `homestead` with box v10.1.1

## Actual behaviour
Vagrant tried to download an older box with v9.6.1

## Steps to reproduce
1. `git clone` homestead or `fetch` and `pull` the latest release branch
2. `sh init.sh`
3. `vagrant up` or `vagrant destroy` and `vagrant up`

**Comment by svpernova09** [comment]
You're using the `release` branch which uses base box version 9.x You have the 10.1.1 box installed.

If you want to use Ubuntu `20.04` use the 20.04 branch. If you want Ubuntu 18.04 Use the `release` branch. The Homestead (repo) version will do it's best to make sure you're using the right version.
