### ISSUE TITLE
Fatal error: Unknown: Failed opening required '/opt/xhgui/external/header.php' (include_path='.:/usr/share/php') in Unknown on line 0

### ISSUE THREAD

**Issue by paolooo** [laravel/homestead#1516]
xhgui has now deprecated external/header.php in the master branch but it's still available on v0.13

https://github.com/perftools/xhgui/commit/de772f15ffb6c7daab6b4e09fe1e7e7216e5ac26

**Comment by paolooo** [comment]
Hi @svpernova09, I'm sorry to ask but why did you close this? I think we should remove the following line in the future?

https://github.com/laravel/homestead/blob/7310972b118cf1e78166ec01f75542c7e5fdfff9/scripts/install-xhgui.sh#L150

Thoughts?

**Comment by svpernova09** [comment]
Sorry, I misunderstood. Yes, we should remove this.

**Comment by paolooo** [comment]
No worries. Sorry, I didn't explain it well :) I'll create a PR for this.
