### ISSUE TITLE
use timescaleDB Community version instead of  OSS version

### ISSUE THREAD

**Issue by xoco70** [laravel/homestead#1523]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

Versions
Vagrant: Vagrant 2.2.10
Provider: Virtualbox 6.1
Homestead: 10.14.0

in this [https://github.com/laravel/homestead/blob/master/scripts/features/timescaledb.sh](https://github.com/laravel/homestead/blob/master/scripts/features/timescaledb.sh): 

we can see 

```
sudo apt-get -y install timescaledb-oss-postgresql-9.6
sudo apt-get -y install timescaledb-oss-postgresql-10
sudo apt-get -y install timescaledb-oss-postgresql-11
sudo apt-get -y install timescaledb-oss-postgresql-12

```

timescale version is OSS, which is a subset of timescaledb community version.

From [https://www.timescale.com/legal/licenses ](https://www.timescale.com/legal/licenses)

> As of December 2018, we began categorizing features as Apache-2 or Community. Roughly speaking, as long as you are not offering TimescaleDB as a hosted Database-as-a-Service, you can use all Community features for free. For any questions, please contact licensing@timescale.com.

I think Homestead could just use the community version.

For my use, I get: 

```
Feature not supported: 7 ERROR: function "time_bucket_gapfill" is not supported under the current license "ApacheOnly"

HINT: Upgrade to a Timescale-licensed binary to access this free community feature 
```

Not Cool !

**Comment by svpernova09** [comment]
Resolved for Homestead 10.x https://github.com/laravel/homestead/releases/tag/v10.15.0

**Comment by svpernova09** [comment]
Resolved for Homestead 11.x https://github.com/laravel/homestead/releases/tag/v11.3.0
