### ISSUE TITLE
Trying to install laravel/homestead vagrant box

### ISSUE THREAD

**Issue by Frankie-C** [laravel/homestead#1524]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.10
  - Provider: VMWare
  - Homestead: -

## Host operating system
macOS Catalina 10.15.7

## Expected behavior
option for vmware_desktop is disabled/removed and unable to install vagrant box for v10.1.1

## Actual behavior
install via option vmware_desktop

## Steps to reproduce
![image](https://user-images.githubusercontent.com/48665103/97009134-51585600-1576-11eb-8fbe-ab06610412c0.png)

**Comment by svpernova09** [comment]
Whoops! It's been fixed https://app.vagrantup.com/laravel/boxes/homestead/versions/10.1.1 but apparently it's taking a few minutes to update across S3. Should be fixed soon.

**Comment by Frankie-C** [comment]
> Whoops! It's been fixed https://app.vagrantup.com/laravel/boxes/homestead/versions/10.1.1 but apparently it's taking a few minutes to update across S3. Should be fixed soon.

Great !

**Comment by svpernova09** [comment]
Just following up this should be resolved now. I was able to download the new box.

> ==> homestead: Successfully added box 'laravel/homestead' (v10.1.1) for 'vmware_desktop'!
