### ISSUE TITLE
Mysql Database are no provisioned unless features: - mysql: true is added to Homestead.yaml

### ISSUE THREAD

**Issue by xyztextbooks** [laravel/homestead#1531]
Your recent code changes prevent skip provisioning of databases unless mysql is enabled in the features directive. No mention of this is made in your docs or Homestead.yaml.example

This works:

  databases:
     - mytest
  features:
      - mysql: true

Prior to this commit, the features code was not needed:

  commit 7ef844020750deb012d3596b9b0a9aa97b896977
  Author: Joe Ferguson <joe@joeferguson.me>
  Date:   Tue Oct 20 16:55:00 2020 -0500
  Only create databases when enabled

**Comment by svpernova09** [comment]
Resolved via https://github.com/laravel/homestead/releases/tag/v10.15.1

**Comment by buismaarten** [comment]
Problem still exists for version 11.

**Comment by svpernova09** [comment]
@buismaarten please open a new issue and fill out the template if you're still having issues on the latest `20.04` branch. Note: part of this fix was to add `mysql: true` to the `features:` list in `Homestead.yaml`. Ensure you've done that.
