### ISSUE TITLE
Update composer to version 2.

### ISSUE THREAD

**Issue by iAxel** [laravel/homestead#1534]
Hello, everyone!

I'm use homestead release branch.

So after release composer v2, I wanted to change composer version in the homestead. But after a successful command `composer self-update`, the path to composer changes from` ~ / .composer` to `~ / .config / composer`
Is it possible to fix this somehow?

**Comment by svpernova09** [comment]
You can do this by editing `PATH="/home/vagrant/.composer/vendor/bin:$PATH"` in `/home/vagrant/.profile`

**Comment by iAxel** [comment]
After editing can I delete the `/.composer` folder?

**Comment by svpernova09** [comment]
I haven't done this yet, You should consult: https://getcomposer.org/upgrade/UPGRADE-2.0.md
