### ISSUE TITLE
Feature Request: Add Postgres v13

### ISSUE THREAD

**Issue by litan1106** [laravel/homestead#1535]
https://www.postgresql.org/about/news/postgresql-13-released-2077/

**Comment by svpernova09** [comment]
Will do! Also waiting for TimescaleDB 2.0

**Comment by svpernova09** [comment]
Next base box version 9.x: https://github.com/laravel/settler/commit/bcd7fed5a8d93aef1b3ab404d4b688a657e825ec

**Comment by svpernova09** [comment]
As of https://github.com/laravel/homestead/commit/5574ce62d9f9f07060e1abe1de835e5dea4723ff WSL supports & Defaults to PostgreSQL 13. Base boxes will get built during the next round of updates (ETA ~30 days or so)
