### ISSUE TITLE
Latest release for PHP <= v7.3 defaults to Homestead box v9 instead of v10

### ISSUE THREAD

**Issue by BenceSzalai** [laravel/homestead#1539]
## Versions
  - Vagrant: v2.2.9
  - Provider: vagrant-parallels v2.0.1
  - Homestead: v11.2.4 + see below

## Host operating system
MacOS v10.14.6 (irrelevant)

## Expected behavior
`v11.2.4` should use `v10` as the default Homestead box, as `v11.1.x` versions did.

## Actual behavior
`v11.2.4` uses `v9` as the default Homestead box.

## Why it is a problem?
`v11.1.2` has been already using `v10` as the default Homestead box.

If someone has PHP `v7.1 - v7.3` and has `laravel/homestead` package configured in composer with the version constraint `^11` or similar they may end up in a situation that after a `composer update` `laravel/homestead` turns from `v11.1.2` to `v11.2.4`, which in turn means their vagrant will start to look for `v9` box instead of the `v10` they have been using before. From `v11.3` up, the default box version is set to `v10` again, but `v11.3+` is only available for those already updated their PHP to `v7.4`.

The point is, if `v10` box was fine in `v11.1.2` on PHP `v7.1`, the default box probably should not downgrade to `v9` in `v11.2.4`, especially that anyone between PHP `v7.1` and `v7.3` will stuck at `v11.2.4` as the latest available version.

If there is no meaningful reason for `v11.2.4` to default to a box version lower than `v11.1.2` was, please release `v11.2.5` with the default box version bumped back to `v10`, as it was in `v11.1.2`, so those who not yet updated to PHP `v7.4` could avoid surprise when vagrant suddenly decides to download `v9` box instead of using `v10` after a composer update.

**Comment by BenceSzalai** [comment]
Actually the box version constraint has been changed from `>= 9.5.0` (allowing v10 box in `v11.2.3`) to `~> 9.5.0` (excluding v10 box in `v11.2.4`) in 71075118fa392929eec810ce38af4bfde259f417 .

**Comment by svpernova09** [comment]
> 
> 
> Actually the box version constraint has been changed from `~> 10.1.1` (in `v11.2.3`) to `~> 9` (in `v11.2.4`).

This is possibly me confusing myself when limiting which branch gets limited to which base box. Base boxes are currently 1 major version behind the repo branches.

**Comment by svpernova09** [comment]
So I believe this is currently working as intended. The version you mentioned is pointed at the wrong branch. https://github.com/laravel/homestead/commit/e20bb5c6edcec632b4776665647a3f6805bb8657 This is 100% my fault and has been correct in subsequent versions. Thanks for the heads up on this. Upgrading to the latest 11.x should resolve this issue. 

The root cause here is I've been ~not so~ secretly maintaining support on *both* Ubuntu LTS versions and this is one case where I was trying to move to fast and got my branches crossed. Eventually I'm going to stop supporting 18.04 and focus primarily on 20.04.

For reference:

Homestead v11 is based on the `20.04` branch, which correlates to the 10.x releases of https://github.com/laravel/settler/tree/20.04 

Homestead v10 is based on the `release` branch, which correlates to the 9x releases of https://github.com/laravel/settler

Settler is also following with `master` = 9.x and `20.04` = 10.x versions.

**Comment by BenceSzalai** [comment]
Thanks for the explanation!

My point is that the latest `v11.x` version is only available for those using PHP `v7.4`. That's why I've suggested to make a `v11.2.5` release with the default box version bumped back to `v10`, but everything else kept the same as in `v11.2.4`, so anyone between PHP `v7.1` and `v7.3` would receive the fix, as for them the "latest" `v11.x` version is `v11.2.4`, not `v11.3.x` or newer.

**Comment by svpernova09** [comment]
> 
> 
> Thanks for the explanation!
> 
> My point is that the latest v11.x version is only available for those using PHP v7.4.

PHP version of the Homestead repo is based on `composer.json` Homestead v11.x should be using 20.04, v10.x using master. I'll take a look and make sure these `composer.json` files are correct. They should allow at least PHP7.3 or higher.

**Comment by svpernova09** [comment]
# Verified Homestead 10 Should force base box 9.x

```
PS C:\Users\halo\Code\homestead> vagrant box update
==> homestead: Checking for updates to 'laravel/homestead'
    homestead: Latest installed version: 9.6.0
    homestead: Version constraints: ~> 9
    homestead: Provider: vmware_desktop
==> homestead: Box 'laravel/homestead' (v9.6.0) is running the latest version.
PS C:\Users\halo\Code\homestead>
```

# Verified Homestead 11 Should force base box 10.x

```
PS C:\Users\halo\Code\homestead> vagrant box update
==> homestead: Checking for updates to 'laravel/homestead'
    homestead: Latest installed version: 10.1.1
    homestead: Version constraints: ~> 10
    homestead: Provider: vmware_desktop
==> homestead: Box 'laravel/homestead' (v10.1.1) is running the latest version.
PS C:\Users\halo\Code\homestead>
```

If you want Homestead 10 you can use PHP 7.1+ (But not 8.0). If you want Homestead 11 you need PHP 7.4+ or 8. I normally try to support whatever php.net supports but in this case, there are some PHPUnit 8/9 issues around 7.2/7.3  that it's easier to keep our tried and true test suite where it is.

I don't think 11 will support lower than 7.4 and I doubt 10 will support 8.

**Comment by BenceSzalai** [comment]
Sorry for being a pain, but I think this was a separate issue.

The problem is that the default base box was v10 in Homestead `v11` up to `v11.2.3` but has been reduced to `v9` in `v11.2.4`. But since the minimum PHP version from Homestead `v11.3` up has been bumped to 7.4, anyone using PHP v7.1-7.3 together with Homestead v11 will remain with a v9 default box.

So right now anyone installing Homestead v11 on PHP 7.1-7.3 will default to base box v9. Changes made to the `20.04` branch won't help this, because `composer.json` prevents PHP v7.3 or lower users to benefit from the latest changes.

The solution would be to
* check out [`v11.2.4`](https://github.com/laravel/homestead/releases/tag/v11.2.4) (the latest version that supports PHP v7.3 or lower),
* change base box version to `~> 10` [here in homestead.rb](https://github.com/laravel/homestead/blob/e20bb5c6edcec632b4776665647a3f6805bb8657/scripts/homestead.rb#L22),
* commit and tag as `v11.2.5`.

This way the last version for people below PHP v7.4 would not default to v9 base box, as it does now incorrectly, considering that the default base box was v10 up to `v11.2.3` and is v10 again from `v11.3.0`. `v11.2.4` is the only exception and causes issues for anyone not yet upgraded to PHP v7.4 or newer, because composer will use `v11.2.4` for them.

**Comment by svpernova09** [comment]
> This way the last version for people below PHP v7.4 would not default to v9 base box, as it does now incorrectly, considering that the default base box was v10 up to v11.2.3 and is v10 again from v11.3.0. v11.2.4 is the only exception and causes issues for anyone not yet upgraded to PHP v7.4 or newer, because composer will use v11.2.4 for them.

For this situation instead of backdating a version, I'd rather tell users to upgrade, whether that's upgrading PHP or to the newest Homestead release. Sorry for any inconvinience.
