### ISSUE TITLE
Getting Homestead up an running on MacOS Big Sur with VM Ware Fusion 12

### ISSUE THREAD

**Issue by tobiasvielmetter** [laravel/homestead#1547]
## Versions
Vagrant 2.2.13
VM Ware Fusion Professional Version 12.0.0 (16880131) with most recent vagrant plugin
'laravel/homestead' version '9.6.0'

## Host operating system
macOS Big Sur 11.0.1

## Vagrant destroy & up output
homestead up                
Bringing machine 'homestead' up with 'vmware_fusion' provider...
==> homestead: Checking if box 'laravel/homestead' version '9.6.0' is up to date...
==> homestead: Verifying vmnet devices are healthy...
==> homestead: Preparing network adapters...
==> homestead: Starting the VMware VM...
==> homestead: Waiting for the VM to receive an address...
==> homestead: Forwarding ports...
    homestead: -- 22 => 2222
==> homestead: Waiting for machine to boot. This may take a few minutes...
    homestead: SSH address: 127.0.0.1:2222
    homestead: SSH username: vagrant
    homestead: SSH auth method: private key
    homestead: Warning: Connection refused. Retrying...

## Expected behavior
homestead should be starting correctly

## Actual behavior
does not start and cannot connect via SSH to virtual machine as the port forwarding does not work anymore, probably because of the new way vmware fusion interacts with big sur (now api based and not with kext).

## References
Relevant vagrant issue https://github.com/hashicorp/vagrant/issues/12045
Adding 
```
v.ssh_info_public = true
v.whitelist_verified = true
```
to the homestead.rb does not entirely solve this. I can then ssh into the machine and its pvisioned but then the virtual machine does not resolve any external hosts. At that point I gave up, as it clearly is not working with current macOS and vmware fusion, or am I missing something?

**Comment by svpernova09** [comment]
I'm afraid there's nothing Homestead can do for you here. The issue is either with the provider or Vagrant itself.

**Comment by tobiasvielmetter** [comment]
> I'm afraid there's nothing Homestead can do for you here. The issue is either with the provider or Vagrant itself.

Thanks. That might be the case. I was under the impression there might be a way to work around the issues from the ruby scripts from homestead that configure vagrant as it was discussed in https://github.com/hashicorp/vagrant/issues/12045 — I am not very fluent in configuring vagrant or ruby scripting (thats why I am using homestead), so I have overview where exactly the problem is. Are you saying homestead cannot do anything about compatibility with vmware/vagrant?

**Comment by svpernova09** [comment]
> 
> 
> > I'm afraid there's nothing Homestead can do for you here. The issue is either with the provider or Vagrant itself.
> 
> Thanks. That might be the case. I was under the impression there might be a way to work around the issues from the ruby scripts from homestead that configure vagrant as it was discussed in [hashicorp/vagrant#12045](https://github.com/hashicorp/vagrant/issues/12045) — I am not very fluent in configuring vagrant or ruby scripting (thats why I am using homestead), so I have overview where exactly the problem is. Are you saying homestead cannot do anything about compatibility with vmware/vagrant?

Correct: As I've learned over the years it's better to let the OS teams and Provider teams work out their issues with Vagrant whenever a new major OS release comes along. It's just easier on me, and the users who are trying to debug.

**Comment by tobiasvielmetter** [comment]
@svpernova09  Understood. Thank you for explaining.

**Comment by tobiasvielmetter** [comment]
For anyone having the same issue, with the recent update of vagrant (2.2.14) and vmware fusion (12.1.0) and changing  https://github.com/laravel/homestead/blob/b228c64778ee2f7567b436a0cb6da92f8745b385/scripts/homestead.rb#L58 to ```
    # Configure A Few VMware Settings
    ['vmware_fusion', 'vmware_workstation'].each do |vmware|
      config.vm.provider vmware do |v|
        v.vmx['displayName'] = settings['name'] ||= 'homestead'
        v.vmx['memsize'] = settings['memory'] ||= 2048
        v.vmx['numvcpus'] = settings['cpus'] ||= 1
        v.vmx['guestOS'] = 'ubuntu-64'
        if settings.has_key?('gui') && settings['gui']
          v.gui = true
        end
        #according to https://github.com/hashicorp/vagrant/issues/12045
        v.ssh_info_public = true
      end
    end
```
it does fully seem to work for me again.

**Comment by svpernova09** [comment]
Anyone still having issues after reviewing https://github.com/hashicorp/vagrant/issues/12045#issuecomment-729294393 ? Looks like there are still some issues pending a Fusion update.
