### ISSUE TITLE
PHP8 Support for 20.04 branch

### ISSUE THREAD

**Issue by gdarko** [laravel/homestead#1567]
Hello,

I installed the 20.04 branch but i don't think you added PHP8 support. Can you provide more information on whether PHP8 is implemented in Homestead or not?

Thanks.

**Comment by svpernova09** [comment]
Branch `20.04` has PHP 8. The current release still has PHP 7.4 as the default. See [Multiple PHP versions](https://laravel.com/docs/8.x/homestead#multiple-php-versions)
