### ISSUE TITLE
homestead motd

### ISSUE THREAD

**Issue by yazeed** [laravel/homestead#1571]
Sorry, this is just a curious question, why does it show two different versions for settler in my homestead's MOTD?

```
 _                               _                 _
| |                             | |               | |
| |__   ___  _ __ ___   ___  ___| |_ ___  __ _  __| |
| '_ \ / _ \| '_ ` _ \ / _ \/ __| __/ _ \/ _` |/ _` |
| | | | (_) | | | | | |  __/\__ \ ||  __/ (_| | (_| |
|_| |_|\___/|_| |_| |_|\___||___/\__\___|\__,_|\__,_|

* Homestead v10.17.0, v11.4.0
* Settler v9.7.2 (Ubuntu 18.04)
* Settler v10.1.1 (Ubuntu 20.04)
```

Think it should just say *Settler v10.1.1 (Ubuntu 20.04)* since that's what I'm on.

**Comment by svpernova09** [comment]
This data is sourced (and heavily cached in the VM) from https://homestead.joeferguson.me/

I'm currently supporting 2 Ubuntu LTS versions of Homestead:

* Ubuntu 18.04 via Homestead v10.x.x Vagrant box / Settler v9.x.x.
* Ubuntu 20.04 via Homestead v11.x.x Vagrant box / Settler v10.x.x.

My current plan is to stop supporting Ubuntu 18.04 this month. I believe we've seen the last releases for 10.x and 11.x.

Here are my next steps:

* Merge the `20-04-dev` into `20.04`  and then into `master`
* Test and Ensure PHP 8. MySQL 8, etc defaults.
* Test & verify WSL feature: Ensure PHP 8. MySQL 8, etc defaults.
* Release Homestead v12, Vagrant box / Settler v11.
