### ISSUE TITLE
Homestead.test says "No input file specified" and when I vagrant provision I get the following:

### ISSUE THREAD

**Issue by benpoarch** [laravel/homestead#1584]
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Checking if box 'laravel/homestead' version '9.7.2' is up to date...
==> homestead: Running provisioner: file...
    homestead: /Users/benpoarch/LaravelStuff/Homestead/aliases => /tmp/bash_aliases
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Unable to mount one of your folders. Please check your folders in Homestead.yaml
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Ignoring feature: mysql because it is set to false
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Ignoring feature: mariadb because it is set to false
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Ignoring feature: ohmyzsh because it is set to false
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
    homestead: Ignoring feature: webdriver because it is set to false
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/xj/vfzltd1s4jbf1w8r7_8n6b_h0000gn/T/vagrant-shell20210102-10417-1qoqqjs.sh
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/xj/vfzltd1s4jbf1w8r7_8n6b_h0000gn/T/vagrant-shell20210102-10417-1ykt8te.sh
==> homestead: Running provisioner: Creating Certificate: homestead.test (shell)...
    homestead: Running: script: Creating Certificate: homestead.test
==> homestead: Running provisioner: Creating Site: homestead.test (shell)...
    homestead: Running: script: Creating Site: homestead.test
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/xj/vfzltd1s4jbf1w8r7_8n6b_h0000gn/T/vagrant-shell20210102-10417-dh5zkp.sh
==> homestead: Running provisioner: Checking for old Schedule (shell)...
    homestead: Running: script: Checking for old Schedule
==> homestead: Running provisioner: Creating Certificate: homestead2.test (shell)...
    homestead: Running: script: Creating Certificate: homestead2.test
==> homestead: Running provisioner: Creating Site: homestead2.test (shell)...
    homestead: Running: script: Creating Site: homestead2.test
==> homestead: Running provisioner: shell...
    homestead: Running: inline script
==> homestead: Running provisioner: shell...
    homestead: Running: /var/folders/xj/vfzltd1s4jbf1w8r7_8n6b_h0000gn/T/vagrant-shell20210102-10417-725eap.sh
==> homestead: Running provisioner: Checking for old Schedule (shell)...
    homestead: Running: script: Checking for old Schedule
==> homestead: Running provisioner: Clear Variables (shell)...
    homestead: Running: script: Clear Variables
==> homestead: Running provisioner: Restarting Cron (shell)...
    homestead: Running: script: Restarting Cron
==> homestead: Running provisioner: Restart Webserver (shell)...
    homestead: Running: script: Restart Webserver
==> homestead: Running provisioner: Update Composer (shell)...
    homestead: Running: script: Update Composer
    homestead: You are already using composer version 2.0.8 (stable channel).
    homestead: chown: cannot access '/home/vagrant/.composer/': No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by svpernova09** [comment]
![image](https://user-images.githubusercontent.com/967362/103449547-45bc9600-4c6f-11eb-8588-c5d8a17a0298.png)

> homestead: Unable to mount one of your folders. Please check your folders in Homestead.yaml
