### ISSUE TITLE
Upgrade TimescaleDB to 2.0

### ISSUE THREAD

**Issue by yazeed** [laravel/homestead#1590]
Hi,

I'd like to submit a PR to upgrade the default Timescale shipped with Homestead from v1.7.4 to v2.0 as it's nearing a final release, RCv4, but thought I'd ask here first to see if this would be a welcome change.

There are some great new enhancements and features bundled with v2.0 and it would be nice to have it by default on the box.

The way to install it, below, won't be changing with the upcoming full release.

```
# Add our PPA
sudo add-apt-repository ppa:timescale/timescaledb-ppa
sudo apt-get update

# Now install appropriate package for PG version
sudo apt install timescaledb-2-postgresql-12
```

Reference: https://docs.timescale.com/latest/getting-started/installation/ubuntu/installation-apt-ubuntu

**Comment by svpernova09** [comment]
This *would* be a welcome change. I know 2.0 just went GA recently. As long as it's in the repos and available.

**Comment by JonoB** [comment]
Note: Timescale only works on Postgres 11 or 12, and Homestead's default Postgres version is 13 at the moment.

**Comment by yazeed** [comment]
> Note: Timescale only works on Postgres 11 or 12, and Homestead's default Postgres version is 13 at the moment.

Well, yes, it will be supported in [Feb 2021](https://github.com/timescale/timescaledb/issues/2779#issuecomment-769783709).
