### ISSUE TITLE
Update Composer On Every Provision Failure

### ISSUE THREAD

**Issue by jasonjpeters** [laravel/homestead#1593]
## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox / 6.1.16 r140961
  - Homestead: 11.2

## Host operating system
```
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster
```

## Expected behavior
Vagrant/Homestead to bring box up and run all provisioning.

## Actual behavior
Vagrant /Homestead fails during provisioning while updating and changing directory ownership. This has the added effect of not running the after.sh script.

## Error
```
==> glohaven-ch: Running provisioner: Update Composer (shell)...
    glohaven-ch: Running: script: Update Composer
    glohaven-ch: Upgrading to version 2.0.8 (stable channel).
    glohaven-ch:    
    glohaven-ch: Use composer self-update --rollback to return to version 2.0.7
    glohaven-ch: chown: 
    glohaven-ch: cannot access '/home/vagrant/.composer/'
    glohaven-ch: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to reproduce
1. install homestead using the per-project installation method https://laravel.com/docs/8.x/homestead#per-project-installation
2. vagrant up

## Temp Resolution
Updated line 590 of ```vendor/laravel/homestead/scripts/homestead.rb``` to 
```ruby
...
      s.inline = 'sudo chown -R vagrant:vagrant /usr/local/bin && sudo -u vagrant /usr/local/bin/composer self-update --no-progress' # && sudo chown -R vagrant:vagrant /home/vagrant/.composer/'
...
```

**Comment by svpernova09** [comment]
I'm ok for the temp resolution at the moment. This is a side effect of Composer 2 going final on a base box that wasn't prepared for it. I don't anticipate another 11.x/10.x base box release. This should be resolved in the next major Homested release which will be Composer 2.0 by default (and thus have the path created as expected).

**Comment by mscarchilli** [comment]
@svpernova09 Why will this not be fixed for 11.x/10.x base box releases? If it's literally only one line of code to comment something out, there's no reason not to. There are still a lot of developer using those base boxes, and this would safe a lot of headaches and hours of wasted time. There's no reason anybody should have to alter the vendor file every time a box is going to be built.

Please do the right thing and just update those releases instead of relying on people having to use a "temp resolution" which in fact would be an "acceptable annoyance to developers" by the Laravel/Homestead team.

**Comment by svpernova09** [comment]
I've come back to look into this and confirmed on the `20.04` branch this change has no effect. I expect it's a problem with the older than `10.1.1` base box I'm using.

Without this PR: https://gist.github.com/svpernova09/2c859ac2a1c086af0516631650802e11

With This PR: https://gist.github.com/svpernova09/97e4d6a3ed9e145640cd790bdf03e304

**Comment by ogierzien** [comment]
I just wanted to add the following to the temp solution to be safe through down- and upgrades:
Add this command to your post-autoload-dump script
```
# one can change the '10.7.0'-part to fit their needs. For when you need to support a broader version 
test $(php vendor/bin/homestead --version | awk '{print $3}') == '10.7.0' && perl -i -pe's/--no-progress /--no-progress\\x27#/g' vendor/laravel/homestead/scripts/homestead.rb
```
It will implicitly check for existence of homestead (the test command will return false on error).
It will make sure 

snippet of how entire post-autoload-dump script will look in `composer.json`:
```
"post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover --ansi",
      "test $(php vendor/bin/homestead --version | awk '{print $3}') == '10.7.0' && perl -i -pe's/--no-progress /--no-progress\\x27#/g' vendor/laravel/homestead/scripts/homestead.rb"
    ],
```

**Comment by senguttuvang** [comment]
For some reason, pearl one-liner didn't work for me. I had to tweak it a bit. Here, how it looks

  `"scripts": {
    "post-autoload-dump": [
      "# patch the homestead bug https://github.com/laravel/homestead/issues/1593#issuecomment-893448811",
      "test $(php vendor/bin/homestead --version | awk '{print $3}' | cut -d . -f 1) -lt 12 && perl -i -pe\"s/--no-progress /--no-progress'#/g\" vendor/laravel/homestead/scripts/homestead.rb"
    ]
  }`
