### ISSUE TITLE
PHP 8.0 rc1 instead of PHP 8.0 version on Homestead v11

### ISSUE THREAD

**Issue by buismaarten** [laravel/homestead#1595]
Hello everyone,

Since a couple of months I noticed that Homestead v11 (per project installation) installs PHP 8.0 rc1 instead of the normal PHP 8.0 version.

I think it has something to do with the latest v10 release of Settler, which is released on October 10th (https://github.com/laravel/settler/releases/tag/v10.1.1).

My questions:
1. Could the normal version of PHP 8.0 be enabled on Homestead v11 (20.04 branch)?
2. Isn't it somewhat confusing that the Homestead repository Readme says the Ubuntu 18.04 branch is unsupported while it is the only branch that gives the normal version of PHP 8.0?

It looks that the 18.04 is more up-to-date and marked as unsupported at the same time.
Sorry if it's just me, but could you make it clear?

**Comment by nfhh** [comment]
It will down after ten minutes, but the virtualbox display is running

![image](https://user-images.githubusercontent.com/30310521/105366394-3f03bc00-5c3a-11eb-942d-2c108f4f89e6.png)
![image](https://user-images.githubusercontent.com/30310521/105366434-4d51d800-5c3a-11eb-8f53-69507019668e.png)

**Comment by svpernova09** [comment]
If you need the latest PHP 8.x Homestead has you'll want the `release` branch. (Which is currently Ubuntu 18.04)

**Comment by buismaarten** [comment]
That doesn't work because the PHP requirement is ^7.1 according to composer.json (https://github.com/laravel/homestead/blob/release/composer.json#L5), this will not work with PHP 8.0 that is installed on my MacBook.
