### ISSUE TITLE
Hey why close this issue? Please fix it dont be lazy

### ISSUE THREAD

**Issue by JoseAburt** [laravel/homestead#1597]
This f** s** project is giving me this error:

delaravel: SSH address: 127.0.0.1:2222
delaravel: SSH username: vagrant
delaravel: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by svpernova09** [comment]
> This f** s** project is giving me this error:

If it's so bad you can figure this out yourself.

Also, you've completely ignored the issue template we have *twice*.  So fix it? No, it's not *my* issue. it's *yours*.

**Comment by MrJmpl3** [comment]
The creator of this issue does not deserve a solution, but for future reference.

Posible solution:
https://stackoverflow.com/questions/54251855/virtualbox-enable-nested-vtx-amd-v-greyed-out/65849976#65849976
https://github.com/laravel/homestead/issues/1607#issuecomment-773355624

**Comment by cjsio** [comment]
> The creator of this issue does not deserve a solution, but for future reference.
> 
> Posible solution: https://stackoverflow.com/questions/54251855/virtualbox-enable-nested-vtx-amd-v-greyed-out/65849976#65849976 [#1607 (comment)](https://github.com/laravel/homestead/issues/1607#issuecomment-773355624)

Unfortunately this solution did not work for me. It did not fix the vagrant bootup issue but it did break my Linux env running inside Windows (which makes sense because that requires HyperV).

This still appears finnicky but I've had better luck with destroying and recreating the vagrant box. If you're encountering this ssh key timeout issue, definitely try `vagrant destroy` and then `vagrant up` for a fresh box.
