### ISSUE TITLE
Help with Per Project Installation, mysql 5.7, ubuntu 18.04

### ISSUE THREAD

**Issue by nathangross** [laravel/homestead#1598]
Vagrant 2.2.14
macOS 11.1

Hi, I'm curious about how the `make` command works. Will that generate the necessary config based on whichever homestead branch I currently have checked out? Preferred set up: https://laravel.com/docs/8.x/homestead#per-project-installation

**Context**: I'm pretty new with Homestead/Vagrant. I typically just use Valet. However, I'm working on a legacy project and need to use php 5.6 and mysql 5.7. Due to the mysql 5.7 need, I believe I need to use the Ubuntu 18 version.

Any guidance here would be much appreciated. Thanks!

**Comment by svpernova09** [comment]
You'll want to require a specific version of Homestead. I would try `composer require --dev laravel/homestead:v10.17.0` or just update your `composer.json` to use `v10.17.0`. This will be Ubuntu 18.04, MySQL 5.7. If you edited `composer.json` run `composer update` and you should see "Installing laravel/homestead (v10.17.0)"

From here. you can delete/rename/move the following files:

```
Homestead.yaml
Vagrantfile
after.sh
aliases
```

You should add these to your project's version control (except `Homestead.yaml`, which is unique to your machine).  Over time Homestead may update these files but we normally note in the release notes when you need to. To refresh any of these files delete them and run `homestead make` again. None of these files will ever be overwritten by the command.

**Comment by nathangross** [comment]
Ok, wow. I totally forgot homestead was brought into this repo locally via composer and to control it there 🤦🏻‍♂️ For some reason I thought it was creating config based on my original install at ~/Homestead 

This makes sense—I am up and running. Thanks!

**Comment by svpernova09** [comment]
Homestead per project users. "There are *dozens* of us!" :D
