### ISSUE TITLE
No longer providing Hyper-V or VMware base boxes

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#1606]
I think I'm going to stop providing Homestead base box builds on Hyper-V and VMware.

Would this negatively affect you?

Tell me about it via email: First at First Last dot Me 
Subject "Homestead Providers"

**Comment by svpernova09** [comment]
For clarity's sake, you can comment here. Or email me if you'd prefer not to post publicly.

**Comment by Gorkyman** [comment]
@svpernova09 Please, please continue to provide vmware. It will affect our work as we all have vmware virtualizations for homestead.

**Comment by svpernova09** [comment]
> 
> 
> @svpernova09 Please, please continue to provide vmware. It will affect our work as we all have vmware virtualizations for homestead.

Thanks for the feedback: note despite the docs currently having removed mentions of VMware and Hyper-V I *am* planning on supporting VMware w/ Homestead base box 11.0.0, I'm just having an issue building the box currently which is why it's not currently available.

**Comment by browner12** [comment]
Joe and I discussed this in Slack a bit, but adding here for completeness.

I think it's important to maintain at least one virtualization software that will support Apple M1.  Virtualbox is mostly mum on the issue right now, but doesn't appear to be very interested in it.  Parallels has said they **will** support it.

**Comment by Sn0wCrack** [comment]
This will affect some of our developer's workflows, as some of our developers run Windows and have a Homestead setup for our larger Laravel apps as well as Docker for a few smaller apps, meaning they are forced to use Hyper-V rather than VirtualBox (like we're all honestly prefer)

**Comment by Braunson** [comment]
@Sn0wCrack I've managed to figure a workaround. I have Hyper-V enabled and am using Docker as well as VirtualBox at the same time.

Key to getting VirtualBox working is when running `vagrant up` to have the `Oracle VirtualBox` window open and click on the site your starting up so it's focused on the right side. The issue where Vagrant can't connect via SSH disappears and the box starts right now.

Not ideal but a workaround to get things working immediately.

**Comment by svpernova09** [comment]
As a follow up, I'm commited to publishing a VMware base box for the new version of Settler. There will be a VMware base box for v11.0.0 whenever I can get past the [current blockers of building the image on VMware](https://github.com/chef/bento/issues/1285#issuecomment-772999877).

**Comment by svpernova09** [comment]
Closing this issue. I'm going to stop providing Hyper-V builds. There will be at least one more VMware release whenever I can get past the [current blockers of building the image on VMware](https://github.com/chef/bento/issues/1285#issuecomment-772999877).

**Comment by Gorkyman** [comment]
@svpernova09 it seems like all blockers are resolved... is it possible to build VMware again? Would really appreciate it ;)

**Comment by vaites** [comment]
Is there any instructions to create by ourselves an Hyper-V (or any other provider) build? Thanks!

**Comment by Gorkyman** [comment]
Can we please have an update on this? I checked and all open issues were resolved, so maybe we can have VMware support back?
