### ISSUE TITLE
Session dont persist session.

### ISSUE THREAD

**Issue by juangonzaq** [laravel/homestead#1610]
Hi, upgrade version of homestead and now all laravel projects don't persist session.

Could you give me some clue, I tried all the session drivers and none of them work.

Thank you !

Vagrant 2.2.14
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Webprojects
      to: /home/vagrant/code/Webprojects

sites:
    - map: instamarcas.local
      to: /home/vagrant/code/Webprojects/pattern/instamarcas/public
      php: "7.3"

    - map: multimarca.local
      to: /home/vagrant/code/Webprojects/pattern/multimarca/public
      php: "7.4"
    
    - map: mass-api.local
      to: /home/vagrant/code/Webprojects/pattern/mass/mass-api/public
      php: "7.3"

    - map: catusita-api.local
      to: /home/vagrant/code/Webprojects/seek/catusita/catusita_api/public
      php: "7.4"

    - map: tecsup.local
      to: /home/vagrant/code/Webprojects/seek/tecsup
      php: "7.2"

databases:
    - homestead

features:
    - mysql: false
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

**Comment by svpernova09** [comment]
I have no idea. You haven't really given us much to go on here.

**Comment by svpernova09** [comment]
## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

**Comment by juangonzaq** [comment]
sorry. here ! 

https://gist.github.com/juangonzaq/5630f855b917c6f690bc92bcac3679e8

Thanks you!

**Comment by svpernova09** [comment]
> 
> 
> sorry. here !
> 
> https://gist.github.com/juangonzaq/5630f855b917c6f690bc92bcac3679e8
> 
> Thanks you!

Thanks, this looks fine. Make sure you're using Virtualbox 6.1.x? You may also want to try mapping individual folders instead of your `Webprojects` folder. I don't think that would cause your session drivers to break.  Make sure your Windows user owns the `Webprojects` folder?

**Comment by juangonzaq** [comment]
yes, i using Virtualbox 6.1.x, the problem is only with laravel, I have other projects in php and the session works fine, I have tried with the other session drivers in laravel and the problem persists, even using redis..
