### ISSUE TITLE
Add information about Nginx client_max_body_size to Homestead documentation

### ISSUE THREAD

**Issue by Hembi** [laravel/homestead#1615]
I have facing some issue with a fresh install of the latest Homestead image.
I got cors error on a large file upload on Angular frontend with Laravel backend, costs a lot of time, to find out, that Laravel API response 413 error code, if the sent file is too large.
This is because Nginx default client_max_body_size setting is 1M.
(http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)

A fixed 100M setting has been removed from Homestead in https://github.com/laravel/homestead/commit/bcec472e2896fe880b89f690bfff5f48a6ddd1e9#diff-00f030f92ac0db045d3055bcdbe39d70

Please add some initial setup proposal to Nginx part in Homestead documentation, to make work easier with Homestead.

**Comment by DieterHolvoet** [comment]
In #1600 this option was added back, but only for the `symfony4` site type. Seems better to me to be consistent.

**Comment by svpernova09** [comment]
I would accept a PR that added this to each site type of the same value. say 16MB? 

I would also LOVE a PR that added this as a configurable option. Happy to help talk through that via Laravel Discord, #homestead channel.

**Comment by DieterHolvoet** [comment]
> I would accept a PR that added this to each site type of the same value. say 16MB?

Why not a much bigger value? I wonder, do people actually use that limit as a means of validation? I know I don't, so IMO that option should have a size that will never be reached in normal situations, like 500MB or 1GB. Or we could set it to 0 to disable the check altogether.

**Comment by svpernova09** [comment]
I've standardized on 100M default vaule for `client_max_body_size`, which is what Sail uses as well.  https://github.com/laravel/homestead/commit/e004869cefc507df6e87ebaa122f8f5db1ab4e01
