### ISSUE TITLE
Readme for release appears to be out of date

### ISSUE THREAD

**Issue by LewisCraik** [laravel/homestead#1619]
The [readme.md](https://github.com/laravel/homestead/blob/release/readme.md) for release branch shows Ubuntu 18.4 and Homestead 10.x.
![Screen Shot 2021-02-20 at 20 16 43](https://user-images.githubusercontent.com/24432037/108607621-5a88f080-73b9-11eb-843e-24b2c3d32e63.png)

However the [readme.md](https://github.com/laravel/homestead/blob/main/readme.md) for main branch shows release branch as being on Ubuntu 20.4 and Homestead 12.x.
![Screen Shot 2021-02-20 at 20 17 07](https://user-images.githubusercontent.com/24432037/108607703-d8e59280-73b9-11eb-918b-de3e150ac6e9.png)

Checking the box it seems to be Ubuntu 20.4, as per Main branch.
![Screen Shot 2021-02-20 at 20 37 38](https://user-images.githubusercontent.com/24432037/108607968-9ae96e00-73bb-11eb-9d36-4024c1107f3d.png)

**Comment by LewisCraik** [comment]
#1620 Submitted PR for this.

**Comment by svpernova09** [comment]
I caught this in `main` after I did the last release. This will be fixed automatically in the next release.
