### ISSUE TITLE
The xphp() alias command doesn't trigger Xdebug 3 because it uses Xdebug 2 settings

### ISSUE THREAD

**Issue by jonagoldman** [laravel/homestead#1655]
## Versions
  - Vagrant 2.2.16
  - Virtualbox 6.1.20
  - Homestead 12.2.0 
  - Settler 11.3.0 (Ubuntu 20.04 / PHP 8.0.5 / Xdebug 3.0.3)

## Expected behavior
Running the `xphp` command in the terminal should run `php` with `xdebug` enabled.

## Actual behavior
The command doesn't trigger xdebug:

```shell
Xdebug: [Config] The setting 'xdebug.remote_autostart' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_host' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_host (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
```

## Steps to reproduce
Run `xphp -v` or `xphp artisan` in the terminal.

## Proposed fix
Update the current alias:
https://github.com/laravel/homestead/blob/120b71524e961aa0b6738de158b1dfb36e5c0995/resources/aliases#L290-L293

To use the correct settings:
```bash
    php \
        -dxdebug.mode=debug \
        -dxdebug.start_with_request=yes \
        -dxdebug.client_host=${HOST_IP} \
        "$@"
```

**Comment by svpernova09** [comment]
Resolved via https://github.com/laravel/homestead/releases/tag/v12.3.0 You'll need to remove your existing `aliases` file and run `bash init.sh` or `init.ps1` to regenerate the `aliases` file with the fixes.
