### ISSUE TITLE
Change php version 

### ISSUE THREAD

**Issue by YaroslavFedan** [laravel/homestead#1664]
Operating system Big Sur 11.4
Homestead v12.3.0 

Tried to specify the current version of php in Homestead.yaml settings 

folders:
    - map: /path_to_project/project
      to: /home/vagrant/code/project
      php: "7.4"

- did not give any result

In vagrant container php -v show me current version php8.0
I tried to change version in different ways
- php74
- sudo update-alternatives --config php

Global command php -v show me really new version - 7.4
but inside application command phpinfo() show me still php version 8.0

Internet searches did not give a solution. How to fix it

**Comment by svpernova09** [comment]
Not sure, you didn't include any logs so I can't see what's happening.
