### ISSUE TITLE
homestead 11.3 missed redis extension under php 8.0

### ISSUE THREAD

**Issue by chan15** [laravel/homestead#1670]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox
  - Homestead: laravel/homestead (virtualbox, 11.3.0) branch is release
  - Laravel: 8.26.1
  - PHP: 7.3

I upgrade homestead to 11.3.0 today, and I got the error message:

```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught LogicException: Please make sure the PHP Redis extension is installed and enabled. in /home/vagrant/code/novax-kumay-core-api/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:77
Stack trace:
```

I made a test file

```php
var_dump(extension_loaded('redis'));
```

```bash
php8.0 redis.php // true
php7.3 redis.php // false
```

and I do ` grep -iR redis /etc/php/` and got:

```
/etc/php/8.0/cli/conf.d/20-redis.ini:extension=redis.so
/etc/php/8.0/cgi/conf.d/20-redis.ini:extension=redis.so
/etc/php/8.0/fpm/conf.d/20-redis.ini:extension=redis.so
/etc/php/8.0/mods-available/redis.ini:extension=redis.so
/etc/php/8.0/phpdbg/conf.d/20-redis.ini:extension=redis.so
```

why only `php8.0` has `redis.so` in this version? the project works perfectly on homestead 9.x.

**Comment by chan15** [comment]
and I check from v9.7.2 to v11.3.0, it happened after v11.0.0

**Comment by svpernova09** [comment]
This is odd. We're installing the only `php-redis` package already. https://launchpad.net/%7Eondrej/+archive/ubuntu/php/+index?field.series_filter=focal&batch=75&memo=75&start=75 via https://github.com/laravel/settler/blob/master/scripts/provision.sh#L54

I'll check this for the next box release.

**Comment by svpernova09** [comment]
I've fixed this here in the `main`branch, Add `php7.3: true` to the list of features and it should reinstall/upgrade the packages (including `php7.3-redis`)
