### ISSUE TITLE
VMWare Workstation provider is now open source

### ISSUE THREAD

**Issue by gdarko** [laravel/homestead#1692]
It looks like the Vagrant VMWare Workstaiton / Fusion drivers are now open source. Do you think they will be supported?

I know Homestead used to support it in the early version, but in the current documentation i don't see support for VMWare providers.

https://www.vagrantup.com/docs/providers/vmware

**Comment by svpernova09** [comment]
We've had a long history of supporting VMware, however, I'm not currently able to get the Ubuntu template to correctly boot and complete a provision.

**Comment by MrReeds** [comment]
vmware support should be a must, seems like from vagrant box version 11 there is no support

**Comment by Gorkyman** [comment]
@svpernova09 could you maybe check this again? It seems like all blockers were resolved...

**Comment by mnightingale** [comment]
@Gorkyman fyi I've successfully made my own v12.2.0 build, I needed to make some fixes to the linking script for settler https://github.com/laravel/settler/pull/243 what you can do is manually build it and import the box into vagrant.

**Comment by Gorkyman** [comment]
@mnightingale if only would I know how :)
