### ISSUE TITLE
command not found: vagrant

### ISSUE THREAD

**Issue by reinisk22** [laravel/homestead#1693]
Trying to set up homestead on a new mac (Big Sur 11.3.1) but getting `command not found: vagrant` when trying to start it. Is it possible my macs version is not supported?

What I did:

1. Installed VirtualBox (Version: 6.1.26)
2. Installed homestead like so: 
    * git clone https://github.com/laravel/homestead.git ~/src/homestead
    * cd  ~/src/homestead
    * composer install
    * bash init.sh
    * configured my `Homestead.yaml` file
    * Tried to run any vagrant command but getting the mentioned error.

Expected outcome:
Vagrant box is created

Actual outcome:
`command not found: vagrant`

**Comment by svpernova09** [comment]
Did you install Vagrant?

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by reinisk22** [comment]
> Did you install Vagrant?
> […](#)
> -- - Joe Ferguson JoeFerguson.me osmihelp.org
> On Sep 4, 2021, 09:43 -0500, Reinis ***@***.***>, wrote: Trying to set up homestead on a new mac (Big Sur 11.3.1) but getting command not found: vagrant when trying to start it. Is it possible my macs version is not supported? What I did: 1. Installed VirtualBox (Version: 6.1.26) 2. Installed homestead like so: • git clone https://github.com/laravel/homestead.git ~/src/homestead • cd ~/src/homestead • composer install • bash init.sh • configured my Homestead.yaml file • Tried to run any vagrant command but getting the mentioned error. Expected outcome: Vagrant box is created Actual outcome: command not found: vagrant — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Had an issue with my setup, sorry for the spam post.
