### ISSUE TITLE
wsl docs

### ISSUE THREAD

**Issue by Simoneu01** [laravel/homestead#1696]
where can I find the complete documentation for WSL?

**Comment by svpernova09** [comment]
There is no official documentation. You can find some direction from https://github.com/laravel/homestead/issues/1484

I'm not sure the WSL support belongs in Homestead. I think it may be time to rip it out into its own project. I've been working on a handful of ideas but nothing to announce at the moment.

**Comment by Simoneu01** [comment]
wow thanks for your work!
