### ISSUE TITLE
Install script setting installed-flag so early that it is a likely source for trouble

### ISSUE THREAD

**Issue by LMCom** [laravel/homestead#1697]
The following pattern is something I've seen in every install script I checked. The problem is (and it might have gotten me once) that the installed-flag is set so early (Line 19). In this case, about 40 lines of installation script are following. If anything goes wrong there, the installed-flag is already set and all following runs will terminate early with a message like "`<feature> already installed`".

I propose setting the flag as late as possible in every script.

https://github.com/laravel/homestead/blob/8db0f821b6222263a1562d759e343032ed38f8a4/scripts/features/elasticsearch.sh#L3-L19

**Comment by svpernova09** [comment]
The goal of these files is so that the runtime (Vagrant or WSL/php code) knows what's installed VS not installed. *most* often we don't want to run installers again so we set this early.
