### ISSUE TITLE
vagrant up errors out with apt failures

### ISSUE THREAD

**Issue by schu** [laravel/homestead#1701]
## Versions

  - Vagrant: `2.2.18`
  - Provider: Virtualbox `6.1.26,145957`
  - Homestead: `910ed887dcbd5815e10c3637195eae4b5a8a4db4`

## Host operating system

macOS 11.6

## Vagrant destroy & up output

https://gist.github.com/schu/5e77f14488a8eb28fd6c444bbc50f368

## Expected behavior

`vagrant up` succeeds, Homstead VM is fully set up.

## Actual behavior

Setup errors out early due to apt failures.

The public key for the Heroku apt repo seems to be missing + some `dl.bintray.com` endpoints seem to be inaccessible.

Am I missing something? Thanks.

**Comment by rlangenf** [comment]
Same problem.

pulled repo, checkout release -> vagrant up --provision 

and getting the same public key for the Heroku apt errors.

**Comment by schu** [comment]
According to https://blog.rabbitmq.com/posts/2021/03/migrate-off-of-bintray/ `dl.bintray.com` is probably obsolete.

**Comment by carstenlehmann** [comment]
Same here.... there was an opend issue... [#1688](https://github.com/laravel/homestead/issues/1688)
quietly closed by @svpernova09 
Are we doing something wrong?

Error happens if you follow the Laravel homestead installation instructions....

**Comment by schu** [comment]
@carstenlehmann thanks for pointing to the previous issue, somehow I missed it.

My box image was outdated, after updating it with `vagrant box update` the setup works.

**Comment by svpernova09** [comment]
Upgrading to the latest base box will resolve this.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org
