### ISSUE TITLE
Where are the current docs?

### ISSUE THREAD

**Issue by tremby** [laravel/homestead#1713]
The Github page links to https://laravel.com/docs/homestead, but that page only lists versions up to 8.x, and the latest release is 12.x.

I can't find anything on the page at all about how to configure databases, other than one example (how to disable Mysql and enable Postgres) which doesn't help me.

I'm currently using the source code itself as documentation, and it's an uphill battle.

Example: everything points to it having mysql installed by default. I confirmed that it is. It has made a "homestead" database. But that's not what I want. I have an old configuration file which has a "databases" key, and in the mysql install script I see that it'll loop through these and make a mysql database for each. But it's not doing that! After reading more source code I found that I need to add `mysql: true` in the features key first. To me it's bizarre.

Similarly with php7.4, which I needed -- I specified this version against a site, and it definitely got installed, but the php7.4-fpm service wasn't enabled. I found I needed to add `php7.4: true` in the features key too.

**Comment by svpernova09** [comment]
> > options vary per feature.
> 
> Hopefully this is on the list of things to document?

I 100% support any effort to improve the Homestead documentation. I've even tried to spin it out into its own [more detailed format](https://github.com/svpernova09/homestead-docs) but it's never gained a lot of traction. The time I devote to Homestead is largely focused on "Can the box be used on our supported providers" and sometimes that's a challenge when things like #1707 also come up.
