### ISSUE TITLE
VirtualBox 6.1.28 no longer auto assigns HostOnly IPs

### ISSUE THREAD

**Issue by wsamoht** [laravel/homestead#1717]
## Summary
Starting in VirtualBox 6.1.28 (released October 19, 2021), it no longer auto assigns HostOnly IPs. This means the default homstead IP of `192.168.10.10` cannot be used to connect to the VM by default or out-of-the-box. I am not sure if this can be "fixed" in homestead or the fix within VirtualBox just needs to be documented. This issue is more of a FYI and a possible discussion as the root issue is not with homestead itself.

I discovered this problem after upgrading to VirtualBox 6.1.28 and trying to connect to the VM with Tinkerwell and trying to view the ngrok dashboard. Both are configured to connect using the IP address `192.168.10.10`.

## Detailed issue
When `vagrant up` is ran, the `vboxnet0` network adapter no longer gets enabled and the subnet `192.168.10.1/24` assigned.

Here you can see it remains down by running `ip address list`:

![image](https://user-images.githubusercontent.com/5725966/138734713-18e6bdc5-cc8d-44e3-bcb3-4da7c84519a2.png)

## Manual/temporary fix
On the host, run the following commands:
```
sudo ip link set dev vboxnet0 up
sudo ip address add 192.168.10.1/24 dev vboxnet0
```

Running `ip address list` now shows the following:

![image](https://user-images.githubusercontent.com/5725966/138735193-2beccabe-6f07-4333-99c7-f01a813fd442.png)

## Permanent fix
The VirtualBox [documentation](https://www.virtualbox.org/manual/UserManual.html#network_hostonly) says it now only auto assigns IP addresses in the `192.68.56.0/21` range. To auto assign the `192.168.10.10/24` range, a `networks.conf` file needs to be created.

Create `/etc/vbox/networks.conf` on the host with the following contents:
```
* 192.168.10.0/24
```
Now when you run `vagrant up`, the `vboxnet0` adapter will be enabled and have its IP address assigned.

## Resources
- [VirtualBox forum post with solution](https://forums.virtualbox.org/viewtopic.php?f=7&t=104218#p507770)
  - [Another related post](https://forums.virtualbox.org/viewtopic.php?f=7&t=104198)
  - [And another one](https://forums.virtualbox.org/viewtopic.php?f=7&t=104219)
- [VirtualBox change log 6.1.28](https://www.virtualbox.org/wiki/Changelog)
  - States "Network: More administrative control over network ranges, see user manual"
- [VirtualBox 6.7. Host-Only Networking documentation](https://www.virtualbox.org/manual/UserManual.html#network_hostonly)

## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox
  - Homestead: 12.7.1

## Host operating system
Linux Mint 20.2

**Comment by shmdesign** [comment]
> > @svpernova09 you need to create `networks.conf`. It is not there by default. From looking at the VirtualBox changelog and documentation, it seems like it was meant to be. Kinda odd though to make a change like this on a minor version.
> > Anything in the `192.68.56.0/21` range will work out-of-the-box without any custom configuration per VirtualBox's [documentation](https://www.virtualbox.org/manual/UserManual.html#network_hostonly).
> 
> I see what you're saying but it's not at all what I'm seeing on my end. If you're being affected by this I would change your IP in `Homestead.yaml` to something like `192.68.56.10`.

This is correct except the ip address in your Homestead.yaml file should be ip: "192.168.56.10" instead of "192.68.56.10" as mentioned in @svpernova09 's answer

Thanks guys for this. I 'only' lost an hour thank to this thread 👌🏼

**Comment by LucaRed** [comment]
Shouldn't we change the default IP address in Homestead.yaml from `192.168.10.10` to something supported such as `192.168.56.10`?

The Laravel docs should be updated too, since they mention `192.168.10.10` in their examples.

**Comment by Ardakilic** [comment]
What is the correct value without adding a custom file? 192.68.56.10 or 192.168.56.10 ?

**Comment by LucaRed** [comment]
The [VirtualBox documentation](https://www.virtualbox.org/manual/ch06.html#network_hostonly) says `192.68.56.0/21`, but it looks like [it's a typo](https://github.com/hashicorp/vagrant/issues/12553#issuecomment-951207028) and so it should be `192.168.56.10`.

I really don't know.  I cannot make it work with any of these IPs on macOS Monterey and VirtualBox 6.1.28.

**Comment by Ardakilic** [comment]
I can't make it work with neither combinations with macOS Monterey and VirtualBox. I event installed the 6.1.29 test build with security disabled. It powers up, but I cannot access to the network.

**Comment by Ardakilic** [comment]
OK, Just made it work on Monteret.

* Get the latest test build from here: https://www.virtualbox.org/wiki/Testbuilds
* Disable SIP security if on mac, until the new version appears.
* Update the homestead yaml ip to `ip: "192.168.56.10"`
* Update the hosts file ip accordingly

No need to add /etc/vbox/networks.conf file.

**Comment by LucaRed** [comment]
It worked, thank you @Ardakilic ! Homestead v12.7.1 works fine for me.

**Important note**:  once the next VirtualBox stable version is released, be sure to [re-enable System Integrity Protection](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection) in order to secure your system.

**Comment by Erulezz** [comment]
Why mess around with VirtualBox test builds and SIP when only changing the IP to `192.168.56.4` (as suggested above)  also just works?

**Comment by ryantxr** [comment]
I would like to add my experience in case someone else has to deal with this. 

This is on macOS

I upgraded to macOS Monterey. Virtualbox would not start so I upgraded it to 6.1.30 r14843. As described above, ip address 192.168.10.10 no longer worked. I also upgraded to Homestead `12.0.0`.

Some suggested just changing the IP address in Homestead.yaml to 192.168.56.4. This did not work for me.

I created `/etc/vbox/networks.conf`. I tried adding `* 192.168.10.0/24`. I rebooted the mac. Homestead.yaml had 191.168.10.10 as the ip address. On the host(mac), the address was 192.168.10.1. I tried various settings in /etc/vbox/networks.conf and I was not able to get it to assign the same ip on the host side(mac) and the guest side(homestead)

I ended up doing the following:

Set `/etc/vbox/networks.conf` to :

```
# This is the default. So technically, I could just delete this file.
* 192.168.56.0/21
```
In Homestead.yaml I set the ip address to 192.168.56.4. Reboot mac.

Brought up the vm `homestead up` (vagrant up)

ping 192.168.56.4 failed.

The adapter was assigned the ip address 192.168.56.1. I could use it this way. However, I wanted the ip address in homestead.yaml to match the ip address on the host so as not to cause confusion. So I went into VirtualBox and changed the assigned ip address of the adapter.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/12485311/147840037-4a4f0cf2-2d9b-41ca-9165-0657ce94fb3d.png">

Ping on 192.168.56.4 now works.
