### ISSUE TITLE
Mailhog & Golang are still x86_64 on the Homestead ARM Build

### ISSUE THREAD

**Issue by Fossil01** [laravel/homestead#1722]
Just installed Homestead for M1 ARM and it's working beautifullly. I just noticed that Mailhog is still x86 instead of ARM64 :-)

`$ file /usr/local/bin/mailhog /usr/local/bin/mailhog: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=5bd20561544187a6b7e9f36d96e025f323b45628, with debug_info, not stripped`

[EDIT]
Oh the same with Golang apparently: 

`/usr/local/go/bin/go: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked`

**Comment by Fossil01** [comment]
Ok so there is no ARM64 release of Mailhog but you can just do `go get github.com/mailhog/MailHog` after installing Go and then the ARM64 binary is found in `go/bin`. Seems to work fine on my install.

**Comment by svpernova09** [comment]
thanks for reporting this stuff!

**Comment by svpernova09** [comment]
Mailhog will require a new base box build. Go has been updated in `main` branch here in Homestead.

**Comment by Fossil01** [comment]
Just a note: I tried that ARM release from the Mailhog Github releases page but it wouldn't run in Ubuntu ARM. That's why I compiled it from the source. Maybe I did something wrong, don't know but writing this comment just to be sure :-)

**Comment by svpernova09** [comment]
I've fixed the golang to use the correct binary. I'm also seeing what you're reporting with Ubuntu ARM Mailhog not working. I guess an alternative would be to include go and use `go get` might be a good option. Going to give that a spin in settler.

**Comment by svpernova09** [comment]
🤔ARM binaries not running in a virtualized ARM OS from an ARM host sounds like a provider bug. Are there any known Parallels issues?

I would hate to have to pull source code and compile these dependencies because **go lang was supposed to fix this**!

**Comment by Fossil01** [comment]
Might be because it's probably armv7 and not arm64/armv8. When I did `go get github.com/mailhog/MailHog` i got a working binary.

Now I have another issue where curl segfaults, but only on one URL (so far) and only over https... `curl https://webservice.fanart.tv` beats me. wget does it too. Looks like there's a bug maybe in the arm64 version of openssl.

**Comment by Fossil01** [comment]
@svpernova09 ngrok also is  x86-64 still :-)

**Comment by svpernova09** [comment]
> 
> 
> @svpernova09 ngrok also is x86-64 still :-)

Thanks! Sorry about the issues I'm going to try to get some time this weekend on a new ARM box.

**Comment by Fossil01** [comment]
No worries, I've been happily using Homestead on my M1 since release and have fixed the small issues without much time.

**Comment by svpernova09** [comment]
Is using `go get` still stable for you? I may have to change more stuff in Settler or I may just create an ARM provision script. I don't like bash if's.

**Comment by Fossil01** [comment]
Yeah it worked to get mailhog just fine.

I'm trying to upgrade OpenSSL to the latest version instead of 20.04's 1.1.1f because that seems to have a bug, at least on the ARM version: https://github.com/curl/curl/issues/7932

I failed to make it work however :-)

**Comment by juanparati** [comment]
Because all those problems with OpenSSL 1.1.1f I decided to use my homestead compatible box:
https://app.vagrantup.com/Juanparati/boxes/homestead-debian-arm

It uses OpenSSL 1.1.1d and Curl PHP extension works without problems.

**Comment by svpernova09** [comment]
[homestead-arm](https://app.vagrantup.com/laravel/boxes/homestead-arm/versions/11.5.1) v11.5.1 has been released to resolve Golang, Mailhog, and ngrok issues.
