### ISSUE TITLE
Homestead docs update

### ISSUE THREAD

**Issue by tomaszstrojny** [laravel/homestead#1726]
Hi,

Not sure if this is the right place to do it but I just wanted to let you know that from VirtualBox version 6.1.28 MacOS and Linux machines have IPs restricted to subnet `192.168.56.0/21` for host-only networks. Just wanted to ask you to update docs so that no new users have to troubleshoot it using the Homestead documentation which uses `192.168.10.10` as an example IP. 

More info in this answer:

https://stackoverflow.com/a/69768235

Just close this issue if you think it's not worth it.

Thanks!

**Comment by svpernova09** [comment]
The Homestead docs currently live in this repo: https://github.com/laravel/docs
