### ISSUE TITLE
Running homestead I got error The private key to connect to the machine via SSH must be owned

### ISSUE THREAD

**Issue by PetroGromovo** [laravel/homestead#1728]
Running homestead(^12.7) in laravel ^8.65 app(kubuntu 20) I got error 

    The private key to connect to the machine via SSH must be owned

Searching in next for decision I found that I need to use chmod. I tried and failed.
I do:

    hoster@hoster-laptop:/project_path$ vagrant up --provision
    Bringing machine 'homes-ex1' up with 'virtualbox' provider...
    ==> homes-ex1: Importing base box 'laravel/homestead'...
    ==> homes-ex1: Matching MAC address for NAT networking...
    ==> homes-ex1: Checking if box 'laravel/homestead' version '11.5.0' is up to date...
    ==> homes-ex1: Setting the name of the VM: homes-ex1
    ==> homes-ex1: Clearing any previously set network interfaces...
    ==> homes-ex1: Preparing network interfaces based on configuration...
        homes-ex1: Adapter 1: nat
        homes-ex1: Adapter 2: hostonly
    ==> homes-ex1: Forwarding ports...
        homes-ex1: 80 (guest) => 8000 (host) (adapter 1)
        homes-ex1: 443 (guest) => 44300 (host) (adapter 1)
        homes-ex1: 22 (guest) => 2222 (host) (adapter 1)
    ==> homes-ex1: Running 'pre-boot' VM customizations...
    ==> homes-ex1: Booting VM...
    ==> homes-ex1: Waiting for machine to boot. This may take a few minutes...
        homes-ex1: SSH address: 127.0.0.1:2222
        homes-ex1: SSH username: vagrant
        homes-ex1: SSH auth method: private key
        homes-ex1: 
        homes-ex1: Vagrant insecure key detected. Vagrant will automatically replace
        homes-ex1: this with a newly generated keypair for better security.
        homes-ex1: 
        homes-ex1: Inserting generated public key within guest...
        homes-ex1: Removing insecure key from the guest if it's present...
        homes-ex1: Key inserted! Disconnecting and reconnecting using new SSH key...
    The private key to connect to the machine via SSH must be owned
    by the user running Vagrant. This is a strict requirement from
    SSH itself. Please fix the following key to be owned by the user
    running Vagrant:
    
    /project_path/.vagrant/machines/homes-ex1/virtualbox/private_key
    hoster@hoster-laptop:/project_path$  who
    hoster   tty1         2021-10-31 05:48 (:0)
    hoster@hoster-laptop:/project_path$ cd ~/.ssh/
    hoster@hoster-laptop:~/.ssh$ ls -la
    total 20
    drwxrwxrwx  3 hoster hoster 4096 oct 30 17:44 .
    drwxr-xr-x 29 hoster hoster 4096 oct 31 05:48 ..
    -rw-------  1 hoster hoster 2610 oct 18:06 id_rsa
    -rw-r--r--  1 hoster hoster  574 oct 29 18:06 id_rsa.pub

I found a hint to run next command :

    sudo chown `whoami` /project_path/.vagrant/machines/homes-ex1/virtualbox/private_key

But I still got error :

    hoster@hoster-laptop:~/.ssh$ cd /project_path
    hoster@hoster-laptop:/project_path$ vagrant up --provision
    Bringing machine 'homes-ex1' up with 'virtualbox' provider...
                                                                    ==> homes-ex1: Checking if box 'laravel/homestead' version '11.5.0' is up to date...
    ==> homes-ex1: Running provisioner: setting authorize key (shell)...
    The private key to connect to the machine via SSH must be owned
    by the user running Vagrant. This is a strict requirement from
    SSH itself. Please fix the following key to be owned by the user
    running Vagrant:
    
    hoster@hoster-laptop:/project_path$ ls -l /project_path/.vagrant/machines/homes-ex1/virtualbox/private_key
    -rwxrwxrwx 1 root root 1679 oct 31 10:24 /project_path/.vagrant/machines/homes-ex1/virtualbox/private_key

Looking at coommand above looks like command sudo chown above did not work. 
Why so and how to fix it ?

in my kubuntu 20, Linux hoster-laptop 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Vagrant 2.2.6

virtualbox : 6.1

Thanks in advance!

**Comment by svpernova09** [comment]
I have no idea. Never seen this before. Are the paths to your keys in `Homestead.yaml` correct?
