### ISSUE TITLE
Forwarded ports and IP issues Parallels/homestead-arm

### ISSUE THREAD

**Issue by jwcobb** [laravel/homestead#1729]
I recently switched from VirtualBox to Parallels so I could use the homestead-arm box. I assumed everything would be the same as it was on VirtualBox using the same `Homestead.yaml` file (with the addition of `box: laravel/homestead-arm`) but I noticed a couple differences.

1. Not all of the same ports were forwarded by default. My `Homestead.yaml` didn't need to list all the "standard" ports for forwarding under VirtualBox, but it seems by default only the HTTP(S) ports are forwarded with Parallels/homestead-arm.
2. The `ip` entry in `Homestead.yaml` seems to be ignored by Parallels/homestead-arm.

I'm happy to submit a PR with an updated `Homestead.yaml` with more ports forwarded by default, but I'm not sure if that is really what is needed or if the issue is with the homestead-arm box or (in the case of IP) it is just a Parallels thing.

**Comment by mstralka** [comment]
I am having the same problem with `homestead-arm` on Apple Silicon.

I was able to get port forwarding to work like this:
~~~yaml
ports:
  - send: 2222
    to: 22
~~~

But the `ip` entry still isn't working.

**Comment by jwcobb** [comment]
@mstralka Have you been able to reliably get the box to launch and work? I haven't. The Parallels DHCP seems to always assign it 10.211.55.3 but it can never SSH to the box.

**Comment by svpernova09** [comment]
> Not all of the same ports were forwarded by default. My Homestead.yaml didn't need to list all the "standard" ports for forwarding under VirtualBox, but it seems by default only the HTTP(S) ports are forwarded with Parallels/homestead-arm.

@jwcobb Sounds like a couple of issues going on, notably, making sure the Homestead repo version is up to date w/ the release branch. We changed port forwarding to reduce the number of default ports in an attempt to help with networking issues. 

> The ip entry in Homestead.yaml seems to be ignored by Parallels/homestead-arm.

The IP in `Homestead.yaml` is merely a suggestion to the provider. If the Provider isn't respecting this value there's not much Homestead can do.

Note: I'm unable to confirm the IP behavior:

```
vagrant@homestead:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1c:42:ae:0b:77 brd ff:ff:ff:ff:ff:ff
    inet 10.211.55.20/24 brd 10.211.55.255 scope global dynamic eth0
       valid_lft 1406sec preferred_lft 1406sec
    inet6 fdb2:2c26:f4e4:0:21c:42ff:feae:b77/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 2591928sec preferred_lft 604728sec
    inet6 fe80::21c:42ff:feae:b77/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1c:42:5b:4b:2f brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.10/24 brd 192.168.10.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fdb2:2c26:f4e4:2:21c:42ff:fe5b:4b2f/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 2591928sec preferred_lft 604728sec
    inet6 fe80::21c:42ff:fe5b:4b2f/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:42:57:e5:b4 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
vagrant@homestead:~$ ip addr | grep 192.168.10.10
    inet 192.168.10.10/24 brd 192.168.10.255 scope global eth1
vagrant@homestead:~$
```
