### ISSUE TITLE
Maybe need add boot_time to wait mathine start.

### ISSUE THREAD

**Issue by mouyong** [laravel/homestead#1765]
https://github.com/laravel/homestead/blob/35620748af486b9ae387df0da94e3677934f62ef/resources/localized/Vagrantfile#L21

Maybe need add boot_time to wait mathine start.

![image](https://user-images.githubusercontent.com/10336437/155733267-497bd72a-8293-4628-84b4-dad1eb4f7b76.png)

```
    # set boot timeout to 1800 seconds.
    config.vm.boot_timeout = 1800
```

![image](https://user-images.githubusercontent.com/10336437/155733002-dc4a0bc8-19c4-42e5-8c39-f2164db1166a.png)

**Comment by svpernova09** [comment]
This is usually an issue with the virtualization provider. On modern hardware `vagrant up` should take less than 2 minutes under basic conditions.
