### ISSUE TITLE
Provider specific settings not possible (libvirt provider + virtiofs file sharing)

### ISSUE THREAD

**Issue by misog** [laravel/homestead#1774]
Hi, when using libvirt provider with bidirectional virtiofs file sharing then this libvirt specific setting must be provided in Vagrantfile:
```
config.vm.provider :libvirt do |libvirt|
  libvirt.memorybacking :access, :mode => "shared"
end
```
If it is not set then this error occurs during `vagrant up`:
```
could not attach device because: Call to virDomainAttachDeviceFlags failed: unsupported configuration: virtiofs requires shared memory
Error while attaching new device to domain. Call to virDomainAttachDeviceFlags failed: unsupported configuration: virtiofs requires shared memory
```
Is it possible to set arbitrary provider specific settings in Homestead.yaml? Or add just this provider specific setting to Homestead like the `natdnshostresolver` for Virtualbox?

PS. `vagrant destroy` should be run if the error still occurs after reloading.

**Comment by svpernova09** [comment]
Homestead doesn't support libvirt.
