### ISSUE TITLE
Proposal: mysql - add disable_log_bin to /etc/mysql/mysql.conf.d/mysql.cnf

### ISSUE THREAD

**Issue by ndberg** [laravel/homestead#1775]
## Versions
  - Homestead: 13.2.1

## Actual behavior 
mysql log_bin is enabled by default (since mysql 8 - before it was disabled by default)

## Proposal
I don't think that a lot of users need log_bins in dev environments. 
We could set
`disable_log_bin`
in 
`/etc/mysql/mysql.conf.d/mysql.cnf`
by default?

I just stumbled upon it while importing a lot of files into the db and then the vm ran out of space.

**Comment by svpernova09** [comment]
This will be in the next base box release https://github.com/laravel/settler/commit/15193085bca2600e4b7336234debcf0a5f5e5683

**Comment by svpernova09** [comment]
This will be in the next base box release https://github.com/laravel/settler/commit/15193085bca2600e4b7336234debcf0a5f5e5683
