### ISSUE TITLE
Per-project Homestead without composer and PHP

### ISSUE THREAD

**Issue by misog** [laravel/homestead#1778]
Hi, Homestead can be installed globally with `git` and `bash init.sh` and also it can be installed per-project with `composer` which requires PHP.

However one of the reasons to use Homestead is to not depend on PHP and composer on the host OS.

Could be Homestead installed per-project just with `git` and `bash`? It could also unpack/set up composer files as alternative init method (other local development host OS could have composer installed).

Thank you

**Comment by svpernova09** [comment]
PHP is a hard requirement for Per Project.

**Comment by misog** [comment]
Perhaps PH7 interpreter could be shipped with laravel/homestead to run PHP code? It is ~500 KB compiled.

**Comment by misog** [comment]
@TerrePorter Thanks, but that is essentially the global install. However I tried to install the global Homestead directly into the project and it seems to be working essentially as per-project with no php/composer requirement. Here is how it looks like: 
```
/home/user/testproject/homestead
/home/user/testproject/code
```

The homestead folder contains Homestead.yaml in which a correct folder path needs to be specified:
```
folders:
    - map: ../code
      to: /home/vagrant/code
```
