### ISSUE TITLE
FYI Do not Upgrade to Virtualbox 7 Until Vagrant updates

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#1807]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/967362/194970142-dc3e00a6-ff87-4979-bc61-79b31388a6f2.png">

**Comment by Sn0wCrack** [comment]
Looks like they released Vagrant 2.3.2 today with now supports VirtualBox 7.

**Comment by browner12** [comment]
I'm not even getting any output at this point, Vagrant just seems to hang. 

Think I'm gonna downgrade to v6 for a bit.

**Comment by browner12** [comment]
Strangely enough it works on my laptop, but not my desktop. No fix yet.

Will probably wait for Vagrant to release a new version.

**Comment by DeanWronowski** [comment]
@bradsi  Not as of yet, I got a bit further. I followed an article where you trick Vagrant into thinking it has compatibility. But then got other issues.

**Comment by svpernova09** [comment]
Typical Warning: I wouldn't upgrade to macOS Ventura or Virtualbox 7 for a bit until we hear how Vagrant-related tools are working on those systems.

I have no immediate plans to support Virtualbox on Apple Silicon. It may happen in the future but if you want Homestead on Apple Silicon I continue to stand by Parallels being the best option.

**Comment by browner12** [comment]
Do you have an example of a feature that would break?  Is it something we can fix, or is it something upstream we don't have control of?

**Comment by svpernova09** [comment]
> Do you have an example of a feature that would break? Is it something we can fix, or is it something upstream we don't have control of?

These might be outdated, but from my last test here's what I was seeing:

* [meilisearch seems unsupported](https://github.com/laravel/homestead/pull/1804/files#diff-c11afc25d987947a4142a4d35260edae6009cbabb7685cc0e7be8fa5fbc3dadcR2)
* [mongodb is unsupported](https://github.com/laravel/homestead/pull/1804/files#diff-5b6c9fe7f7f77e434882a546a1c97c25cd586f91650d13c2efa48c61d1e1c798R2)

Unsupported on arm64 (lesser of issues)

* CouchDB
* Crystal

**Comment by svpernova09** [comment]
macOS 13.0 (22A380)
Parallels Version 18.0.3 (53079)
Vagrant 2.3.2

Homestead appears to be working.

**Comment by svpernova09** [comment]
Version 7.0.2 r154219 (Qt5.15.2)

Confirming 

```Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Importing base box 'laravel/homestead'...
==> homestead: Matching MAC address for NAT networking...
==> homestead: Checking if box 'laravel/homestead' version '12.2.0' is up to date...
==> homestead: Setting the name of the VM: homestead
==> homestead: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp

vagrant up: 00:55```

**Comment by svpernova09** [comment]
Looks like both Virtualbox 7.x and 6.1.x are broken on macOS Ventura

```
==> homestead: Destroying VM and associated drives...
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Importing base box 'laravel/homestead'...
==> homestead: Matching MAC address for NAT networking...
==> homestead: Checking if box 'laravel/homestead' version '12.2.0' is up to date...
==> homestead: Setting the name of the VM: homestead
==> homestead: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp

vagrant destroy -f; vagrant up: 01:00
```

**Comment by svpernova09** [comment]
Homestead appears to be running fine with Parallels Version 18.0.3 (53079) on macOS Ventura 13.0 (22A380) on my M1 Apple Silicon system.

**Comment by bradsi** [comment]
@svpernova09 IIRC Virtualbox 7.x supports MacOS Ventura. However, the `host-only adapter` has been deprecated. It seems this is definitely a Virtualbox issue instead of anything Homestead related, just wanted to add this info.

**Comment by middaparka** [comment]
> Looks like both Virtualbox 7.x and 6.1.x are broken on macOS Ventura

Can very much confirm - full un-installs/re-installs, etc. don't appear to make any difference. 😬

**Comment by sanderdewijs** [comment]
I've been following this thread on the [Vagrant discuss channel](https://discuss.hashicorp.com/t/vagrant-up-fails-on-macos-13-x-ventura-with-latest-2-3-2-vagrant-release/46043/13) . Looks like someone found a solution by adding the [virtualbox__intnet](https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/networking#virtualbox-internal-network) flag to the Vagrant file.

**Comment by almostkareem** [comment]
I only fixed it on macOS Ventura by replacing Virtualbox with Parallels.

**Comment by pascalbaljet** [comment]
https://github.com/hashicorp/vagrant/pull/12983

**Comment by svpernova09** [comment]
Just added https://github.com/laravel/homestead/commit/4b258ed7aeaed89f151b15b3cdcef92ca14725db which should add support. Going to wait for some feedback before tagging a release.

**Comment by Tosh79** [comment]
Hey @svpernova09 , 
I just applied the changes under https://github.com/laravel/homestead/commit/4b258ed7aeaed89f151b15b3cdcef92ca14725db to my own setup, running virtualbox7 / vagrant 2.3.2 on Ventura 13.0.

Good news first: homestead is up and running again! I even got to `vagrant ssh` to my machine and stuff.
Bad news: Aside from `vagrant ssh` the running machine seems to be invisible to the rest of my system. I am not able to reach the site under the configured site-urls. Even trying to ping `192.168.56.56` fails.

Hopefully, you'll get this up and running again. Best wishes!

**Comment by mikeziri** [comment]
> Hey @svpernova09 , I just applied the changes under [4b258ed](https://github.com/laravel/homestead/commit/4b258ed7aeaed89f151b15b3cdcef92ca14725db) to my own setup, running virtualbox7 / vagrant 2.3.2 on Ventura 13.0.
> 
> Good news first: homestead is up and running again! I even got to `vagrant ssh` to my machine and stuff. Bad news: Aside from `vagrant ssh` the running machine seems to be invisible to the rest of my system. I am not able to reach the site under the configured site-urls. Even trying to ping `192.168.56.56` fails.
> 
> Hopefully, you'll get this up and running again. Best wishes!

I'm at the same point also.
Trying to understand why the private ip 192.168.56.56 isn't being mapped from the VM to macos.
I'm using dnsmasq and everything is well mapped.
Though pinging directly does not work.

**Comment by mikeziri** [comment]
With a little persistence I got it running.

Digging in the hashicorp issue, we must create the missing **Host-only Network**.
Either via Virtual Box Manager GUI or issuing on the console something like:

`VBoxManage hostonlynet add --name=HostOnly --netmask=255.255.255.0 --lower-ip=192.168.56.1 --upper-ip=192.168.56.100 --enable`

Important bits are the Name **HostOnly** and the lower and upper bounds contain 192.168.56.56 (as .1 and .100 do).

Then, we have to go to VirtualBox Manager GUI and you should see under `File/Tools/Network Manager` then Host-only Networks, your **HostOnly** network created (after creating the network via CLI and having VBoxManager GUI open, it doesn't refresh the created network. You must restart the App)

![Screenshot 2022-11-11 at 22 28 18](https://user-images.githubusercontent.com/551167/201439851-4779e78b-ea77-411c-a378-69028dd60401.JPG)

Finally, we must attach the newly created network to the Adapter 2 on Homestead VM:
Go to Homestead/Settings/Network/Adapter 2 and change the **Attached to** to **Host-only Network** and below, select the **HostOnly** network created:
![Screenshot 2022-11-11 at 22 27 28](https://user-images.githubusercontent.com/551167/201440016-320f8b21-3a03-4fa7-a0b4-fb38252bb7a7.JPG)

![Screenshot 2022-11-11 at 22 27 51](https://user-images.githubusercontent.com/551167/201440031-77f2558e-2e06-412c-986d-3c1c573f66c8.JPG)

You should now be able to ping 192.168.56.56 and the vhosts respond on the browser.

**Comment by Tosh79** [comment]
Hey @mikeziri , I got it running this second. Although I already had set up the Host-only Network (I forgot to mention), it didn't work for me. Reason: my dnsmasq-service didn't start up because of a broken valet installation (I had tried earlier this evening).

So! Everyhing is up and running again! Thanks all!

**Comment by svpernova09** [comment]
Hello everyone. I've spent a good chunk of time debugging Virtualbox 6.1.x and 7.0.x on macOS Ventura (currently 13.0.1 (22A400))

The hostonly tweak currently in `main` but not `release` creates an un-routable situation as mentioned in previous comments. 

If you're stuck and have no other options, here's a workaround

> CAUTION: This puts your Homestead VM on your PUBLIC NETWORK! This is UNSAFE as you're exposing a VULNERABLE LINUX VM to your network! Please be aware of what this means.

Update your `Homestead.yaml` to add a public network device and bind it to your actual network interface. On my 15-inch, 2017 Macbook Pro this is `en0: Wi-Fi (AirPort)` and my home network IP is `192.168.1.x` so my configuration below is:

```
networks:
    - type: "public_network"
      ip: "192.168.1.199"
      bridge: "en0: Wi-Fi (AirPort)"
```

Here's the log: https://gist.github.com/svpernova09/0cb023ed7ea5cd8a2d64c82868e5e769

Update your hostnames (such as `fresh.test` to the new public IP:

```
cat /etc/hosts | grep fresh.test                                                                                                                                                                                  
192.168.1.199 fresh.test
```

And the URL should now work again:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/967362/201555314-52e8f113-5bd9-4b90-9c54-f413b1f84889.png">

**Comment by Zaister** [comment]
Hey @mikeziri., I've tried your method of switching the Network, but as soon as I boot up the VM, it switches back to intnet. I'm currently on homestead main branch, vagrant 2.3.3, VirtualBox 7.0.2. Am I missing something?

**Comment by mikeziri** [comment]
> Hey @mikeziri., I've tried your method of switching the Network, but as soon as I boot up the VM, it switches back to intnet. I'm currently on homestead main branch, vagrant 2.3.3, VirtualBox 7.0.2. Am I missing something?

I'm having that behavior as well.
Tried to make some changes on the homestead.rb to always select the new network but hadn't any luck.
I usually leave the VM running so not a big problem for me until this gets resolved properly from upstream.

**Comment by bradsi** [comment]
I've reverted `homestead.rb` back to the default, upgraded to Vagrant 2.3.3, and ran `vagrant reload --provision`. Everything is working fine for me now.

Vagrant: 2.3.3
Virtualbox: 7.0.2r154219
OS: MacOS Ventura 13.0.1

**Comment by Sn0wCrack** [comment]
I can also confirm it looks like Vagrant 2.3.3 works fine with VirtualBox 7.0.2 using Homestead 13.3.2, so the homestead.rb changes to add virtualbox__intnet doesn't look to be required to resolve this issue.

**Comment by mikeziri** [comment]
Can also confirm.
On homestead @release branch with Vagrant 2.3.3 and VirtualBox 7 on MacOs Ventura, now working.
Thank you all.

**Comment by DeanWronowski** [comment]
Works for me as well,

**Comment by jfkr** [comment]
I'm unable to find a vagrant box with Homestead 13.x, the only one available under https://app.vagrantup.com/laravel/boxes/homestead is the 12.x version. Can someone point me to the right place? Thank you.

**Comment by svpernova09** [comment]
https://github.com/laravel/homestead/issues/1815#issuecomment-1384723555
