### ISSUE TITLE
Update the MongoDB version from 4.4 to 6.X

### ISSUE THREAD

**Issue by skeeith** [laravel/homestead#1810]
Would it be possible if you guys could bump up the MongoDB Version or add support for specifying what MongoDB to install if its v4 to v6.

**Comment by skeeith** [comment]
@svpernova09 is there a guide line to contributing here? I'm planning to update the `scripts/mongo.sh` file to upgrade from 4.4 to 6.0

**Comment by skeeith** [comment]
@svpernova09 I already have a running version of the updated scripts here, I also updated the NodeJS from v14 to v18 LTS too.

**Comment by svpernova09** [comment]
Thanks!
