### ISSUE TITLE
Remove the older php installation from the settler in favor of the "Feature scripts for old PHP versions

### ISSUE THREAD

**Issue by litan1106** [laravel/homestead#1814]
We should remove the older php installations from the settler in favor of the "Feature scripts for old PHP versions". (most of these PHP versions are EOL) It could speed up the homestead `vagrant provision`. For these people still want older PHP versions, they can use the feature script #1684 

https://github.com/laravel/settler/blob/master/scripts/amd64.sh#L76

**Comment by stebogit** [comment]
This has never been documented, has it? Is it like this?
```yaml
features:
    - php80: true
    - php74: true
```
I'll push a PR with few updates on the official docs

**Comment by svpernova09** [comment]
Hold off on documenting these "features". There needs to be some clean up done before people start trying to use them.

**Comment by svpernova09** [comment]
The php*.sh feature scripts are meant to duplicated settler scripts in case we ever need to run them at runtime. I'd rather not have them documented as they shouldn't be normally used for end users. At one point in time I was going to make PHP versions other than the "default" as installed on demand, but ultimately the smaller Vagrant image size wasn't realized just missing PHP versions so I binned the idea.

**Comment by stebogit** [comment]
So all available PHP versions are installed by default, right?

If I understand correctly you can run multiple PHP versions specifying them in each `sites` directive in the yaml file, but still the VM has the default (8.1 currently) PHP version ("engine"?) running. In other words, if you don't specify a version for a site that gets the default version.
Instead, to modify the version for the CLI you can run a command (like `php74`) or set the `php` directive.
Is that correct?

Is there a way to set both the global - i.e. for all sites - and the CLI version of PHP (different than the default value of course) at once?

**Comment by svpernova09** [comment]
> So all available PHP versions are installed by default, but only the default is enabled, right?

Correct, users can expect a Homestead base box to contain all available supported PHP versions. We're incredibly fortunate to have [Ondřej Surý](https://launchpad.net/~ondrej)  in the PHP community who maintains the best archive of PHP packages this side of `deb` flavored Linux.

> If I understand correctly you can run multiple PHP versions specifying them in each `sites` directive in the yaml file, but still the VM has the default (8.1 currently) PHP version ("engine"?) running. In other words, if you don't specify a version for a site that gets the default version. Instead, to modify the version for the CLI you can run a command (like `php74`) or set the `php` directive. Is that correct?
> 

The CLI PHP version by default is the currently supported PHP version (8.1 today) and can be overridden w/ `php: 7.4` at the top level of `Homestead.yaml`. Site PHP configurations have no impact on the CLI PHP version.

> Is there a way to set both the global - i.e. for all sites - and the CLI version of PHP (different than the default value of course) at once?

 No, there is no way to override what Homestead considers the "default" PHP version. If everything uses 7.4, you can set those sites to use that version and then set `php:` at the top level of your configuration.
