### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by olssonm** [laravel/homestead#1826]
Just checking in to see if adding PHP 8.2 is on the roadmap since 8.2 was released in the beginning of december 2022. 

Noticed that there was a commit last year to add 8.2 as an alias (https://github.com/laravel/homestead/commit/f8a63da075bf9a8bcdb313829686d9760079c48a) – but no install scripts as there is for 8.1 etc.

I myself run homestead-arm via Parallels and would love to see 8.2 get added. Would probably be able to write a PR myself, but figured that the people with the real know-how should do it 😅 And run a manual install myself in the mean time.

**Comment by csaba215** [comment]
Check out my PR: #1827
I am still testing it. It is based on php8 script so it should probably work fine.

**Comment by svpernova09** [comment]
[This comment](https://github.com/laravel/homestead/issues/1807#issuecomment-1290786202) is still the latest regarding 8.2.

The next major Homestead and Settler versions are coming this month 8.2 default, Ubuntu 20.04). I've been waiting to see how the Virtualbox issues would shake out.
