### ISSUE TITLE
MySQL Databases on 

### ISSUE THREAD

**Issue by browner12** [laravel/homestead#1840]
## Versions

  - Vagrant: 2.3.4
  - Provider: Parallels 18
  - Homestead: `release`

## Host operating system

MacOS 12.6.2

### Description

Thanks Joe for your continued work on Homestead. I just upgraded to the new base box yesterday, and everything's gone pretty smoothly.  One little gotcha I ran into was my databases weren't getting installed unless I had `mysql: true` in my features.   I see that this field is shown in both the `Homestead.json` and `Homestead.yaml` file, but not the `Homestead.yaml.example` file.  I also noticed we don't have `mysql` listed as a "feature" option in the [docs](https://laravel.com/docs/9.x/homestead#installing-optional-features). 

Before I send any PRs, I just wanted to check in to make sure this was the intended/expected behavior, that we require the `mysql: true` feature option, even though MySQL is our default database.

Thanks!

**Comment by svpernova09** [comment]
> Before I send any PRs, I just wanted to check in to make sure this was the intended/expected behavior, that we require the mysql: true feature option, even though MySQL is our default database.

PR away, I have a feeling the docs are behind and `Homestead.yaml.example` needs to be updated to match the default `Homestead.yaml`. Thanks!

**Comment by svpernova09** [comment]
`Homestead.yaml.example` has been updated in https://github.com/laravel/homestead/commit/dc2e490abb6d81fc05d241bab42747ff9a480648

Ping me on your docs PRs and I'll 👍 them if needed. Thanks!
