### ISSUE TITLE
Slow Vagrant box v13.0.0 for libvirt provider

### ISSUE THREAD

**Issue by misog** [laravel/homestead#1855]
Hi, the laravel/homestead vagrant box v13.0.0 for libvirt provider runs very slow. Provisioning is slow, ssh command are slow, like 5-times slower than it should be.

**Workaround**
I downloaded laravel/homestead v13.0.0 for virtualboax and converted it to libvirt version with https://github.com/sciurus/vagrant-mutate

The converted libvirt version runs fast.

Linux, Debian
Vagrant 2.2.19

**Comment by csaba215** [comment]
What version of  laravel/homestead are you using?
Can you post your vm's xml? (Do you have <domain type="kvm"> in it ? )
I suspect you are not using kvm(Hardware Acceleration), and instead using qemu.

**Comment by misog** [comment]
Laravel Homestead 14.1.1

Where can I find vm's xml? I have no `<domain` string in files in the homestead folder.

**Comment by csaba215** [comment]
Try with version 14.2.0. (You also need to run vagrant destroy(backup your data first, if needed) and vagrant up)
