### ISSUE TITLE
Fatal Error: Unable to access 

### ISSUE THREAD

**Issue by JamesD17011** [laravel/homestead#1857]
Getting following error in Vagrant 2.3.4 running latest version of Homestead 

vagrant@vagrant:~$ vagrant@vagrant:~$ git clone https://github.com/laravel/homestead.git ~/Homestead
Cloning into '/home/vagrant/Homestead'...
fatal: unable to access 'https://github.com/laravel/homestead.git/': Could not resolve host: github.com

**Comment by Sn0wCrack** [comment]
If this is an error you're getting inside of the Homestead Virtual Machine try adding the `natdnsresolver` option to your Homestead.yaml as outlined in the [Homestead documentation](https://laravel.com/docs/9.x/homestead#natdnshostresolver) and performing a reprovision of your Virtual Machine (make sure to back up any data such as databases before doing so).

Also it would be useful if you still have issues after making this change to post your host operating system, the Vagrant provider you're using (VirtualBox, Hyper-V, etc.) and your Homestead.yaml file.

**Comment by JamesD17011** [comment]
Good morning
Will get to this and update the case

**Comment by JamesD17011** [comment]
![Homestead#1857_Terminal2](https://user-images.githubusercontent.com/12768502/219079932-4e52dceb-d08b-4014-b293-3e045e0607ff.jpg)
![Homestead#1857_CMD](https://user-images.githubusercontent.com/12768502/219079934-7fcafabd-87ec-47a2-b1c8-26432cea3ed8.jpg)
![Homestead#1857_Terminal](https://user-images.githubusercontent.com/12768502/219079936-d4d4cc66-f9ba-4ecc-a5c6-471e344ca6c0.jpg)

Please see the following attached files 
As for the requested specifications: 
Host OS: Windows 10 Home version 22H2 
Vagrant Provider: VirtualBox 7.0 (Version 7.0.6 r155176

**Comment by Sn0wCrack** [comment]
Did you add in the line mentioned in the Laravel documentation I linked previously regarding setting `natdnsresolver` to `off`?

If you did, you will need to run `vagrant destroy` and then `vagrant up` running provision will not be enough to get that setting to take affect, as it changes  things related to your Virtual Machine's virtual network adapter.
As previously mentioned make sure to back up any data such as databases in your Virtual Machine if you have any first.

If the above still does not resolve the issue, please provide your Homestead.yaml file.
And for additional debugging you can try running the following commands and providing the output:
 - `dig github.com`
 - `curl -vvv https://github.com`
