### ISSUE TITLE
Feature Request: Add Mailpit integration

### ISSUE THREAD

**Issue by litan1106** [laravel/homestead#1860]
Mailpit is the new replacement for Mailhug but much faster.

The laravel  v10 env now uses mailpit https://github.com/laravel/laravel/blob/10.x/.env.example#L32

https://github.com/axllent/mailpit

**Comment by svpernova09** [comment]
I'd take a PR accepting this but have no immediate plans to do this.

**Comment by Sn0wCrack** [comment]
I'd be happy to take a crack at this potentially.

A couple ways I could see this going is:

- Install mailpit and a systemd unit in Settler and then use the "services" section in the Homestead configuration file to enable an disable the systemd unit for mailhog and mailpit.
- Similar to the the MariaDB feature script, add a mailpit feature script that uninstalls mailhog and replaces it with mailpit.

If there's a preference either way I'm happy to accommodate and go that route.
