### ISSUE TITLE
Is it time to jump to 22.04?

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#1910]
PHP 8.3 will be released at then end of the month so I've been working on updates in preparation. 

Do users want Ubuntu 22.04?

**Comment by ducconit** [comment]
+1

**Comment by LlamaDuckGoose** [comment]
+1

20.04 LTS ends in April 2025 so would be a good idea to try upgrading before then

**Comment by Sn0wCrack** [comment]
+1

(either that or jump to Debian lol)

**Comment by d-damien** [comment]
I'm off topic there but just letting you know that Vagrant (and all Hashicorp products) went to a "non-free opensource" license specifying you can't use it in production. Now being OSS for dev technically won't change anything for Homestead since it is the very purpose, but it is sending a wrong signal. I would suggest to have an abstraction layer to be able to add other providers.

**Comment by svpernova09** [comment]
> I'm off topic there but just letting you know that Vagrant (and all Hashicorp products) went to a "non-free opensource" license specifying you can't use it in production. Now being OSS for dev technically won't change anything for Homestead since it is the very purpose, but it is sending a wrong signal. I would suggest to have an abstraction layer to be able to add other providers.

I hear you but it's likely out of scope for Homestead since Vagrant is the foundation of the project.

**Comment by csaba215** [comment]
+1

I also started working on it but it's still far from ready.
laravel/settler#248

**Comment by skeeith** [comment]
@svpernova09 I guess, it's better to move upgrade to 22.04, since you're upgrading to vagrant 2.4.0, while at it, why don't we add support for Virtual Box v7 as well? cause Virtual Box v6.X ends next month...

**Comment by ALameLlama** [comment]
@skeeith it would be Vagrant that would need to support this rather then Homestead but also Vagrant does support this as of [2.3.2](https://github.com/hashicorp/vagrant/blob/main/CHANGELOG.md#232-october-18-2022). I am running homestead while using Vagrant 2.4.0 and Virtualbox 7.0.10. and haven't run into any issues.

**Comment by svpernova09** [comment]
My current plan is the next version of Settler will be based on 22.04 and support VirtualBox 7.0.x The next version of Homestead will be a major version bump to support this and the new default of PHP 8.3

**Comment by lloricode** [comment]
+1 for php8.3

**Comment by lloricode** [comment]
> @skeeith it would be Vagrant that would need to support this rather then Homestead but also Vagrant does support this as of [2.3.2](https://github.com/hashicorp/vagrant/blob/main/CHANGELOG.md#232-october-18-2022). I am running homestead while using Vagrant 2.4.0 and Virtualbox 7.0.10. and haven't run into any issues.

same as mine, I am using vagrant 2.4 and virtualbox 7. all working as well

**Comment by Xety** [comment]
> > @skeeith it would be Vagrant that would need to support this rather then Homestead but also Vagrant does support this as of [2.3.2](https://github.com/hashicorp/vagrant/blob/main/CHANGELOG.md#232-october-18-2022). I am running homestead while using Vagrant 2.4.0 and Virtualbox 7.0.10. and haven't run into any issues.
> 
> same as mine, I am using vagrant 2.4 and virtualbox 7. all working as well

I have vagrant 2.4, VB 7 and `laravel/homestead` v14.5.0 but I have some version issue :
![image](https://github.com/laravel/homestead/assets/8210023/ad2340aa-a178-4901-be60-754b40cb05b2)

**Comment by svpernova09** [comment]
Update: I have the amd64 box building and in testing. The ARM box fails to build due to an issue with Mailhog that I need to look into.

MongoDB seemed fine on 22.04 (It was one of the reasons we delayed upgrading for so long).

The Drupal and Drush launchers don't play nice with PHP 8.3 (And Drush is archived) so they have been removed.

**Comment by ALameLlama** [comment]
I don't think mailhog has been updated I'm years? Does mailpit have the same issue?

**Comment by svpernova09** [comment]
> I don't think mailhog has been updated In years, Does mailpit have the same issue?

Thanks! Replaced Mailhog w/ Mailpit

**Comment by skeeith** [comment]
@lloricode @ALameLlama there's some couple issues we've found on Vagrant 2.4.0 and Virtual Box v7.X that we've discuss on the other thread. I won't be specifying them here but you could read them here https://github.com/laravel/homestead/issues/1907

**Comment by jvitasek** [comment]
> `Vagrant.require_version '>= 2.4'`

@svpernova09 Hey, isn't there going to be a problem with https://github.com/hashicorp/vagrant/issues/13263? It seems Node doesn't work on shared directories in newer Vagrant versions, if I'm reading it correctly.

I'm currently trying it and getting errors: 
> npm ERR! ENOTSUP: operation not supported on socket, write

**Comment by svpernova09** [comment]
> > `Vagrant.require_version '>= 2.4'`
> 
> @svpernova09 Hey, isn't there going to be a problem with [hashicorp/vagrant#13263](https://github.com/hashicorp/vagrant/issues/13263)? It seems Node doesn't work on shared directories in newer Vagrant versions, if I'm reading it correctly.
> 
> I'm currently trying it and getting errors:
> 
> > npm ERR! ENOTSUP: operation not supported on socket, write

We have to require this version of Vagrant to be able to specify multiple architectures in providers: IE the ARCH box for Apple Silicon is also named `laravel/homestead`. 

This looks like yet another reason not to use Virtualbox. With Broadcom's purchase and upheaval of VMware's programs, I'd be hesitant to recommend that route. Now that we have a new release out the door, I can get back to testing libvirt more, possibly the new default.

**Comment by svpernova09** [comment]
It's done. Homestead v15.0.0 has been tagged and requires a base box version of 14.0.2. Thanks to @browner12 for a ton of hands-on testing and PRs over the past 2 days.
