### ISSUE TITLE
There is no InfluxDB v2.x

### ISSUE THREAD

**Issue by PerikiyoXD** [laravel/homestead#1912]
Why is Is InfluxDB v2.x not already added?

Is there any inconvenience on having that specific package?

I work with that and I'd find it useful if we got it too.

**Comment by svpernova09** [comment]
I'd accept a PR updated our InfluxDB install to install V2

**Comment by PerikiyoXD** [comment]
@svpernova09 there you go

**Comment by svpernova09** [comment]
Thanks for the PR!
