### ISSUE TITLE
Cannot install new Homestead box on windows 11 Pro

### ISSUE THREAD

**Issue by Serringer** [laravel/homestead#1918]
## Versions
Vagrant: 2.4.0
Virtual Box: 7.0
Provider: virtual box
Homestead: upto date
Host: windows, newest updates

I have done a total fresh install, I am trying to install laravel/homestead 13.0.0 box, but Vagrant always installs 12.2.0 which is out of range for the requirements for the box, here is the message:

Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Box 'laravel/homestead' could not be found. Attempting to find and install...
    homestead: Box Provider: virtualbox
    homestead: Box Version: >= 13.0.0, < 14.0.0
==> homestead: Loading metadata for box 'laravel/homestead'
    homestead: URL: https://vagrantcloud.com/api/v2/vagrant/laravel/homestead
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: laravel/homestead
Address: https://vagrantcloud.com/api/v2/vagrant/laravel/homestead
Constraints: >= 13.0.0, < 14.0.0
Available versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.3.0, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 1.0.0, 1.0.1, 1.1.0, 2.0.0, 2.1.0, 2.2.0, 3.0.0, 3.1.0, 4.0.0, 5.0.1, 5.1.0, 5.2.0, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 7.0.0, 7.1.0, 7.2.1, 8.0.0.pre.alpha1, 8.0.0.pre.alpha2, 8.0.0.pre.alpha3, 8.0.0.pre.alpha4, 8.0.0.pre.beta, 8.0.0, 8.0.1, 8.1.0, 8.2.0, 8.2.1, 9.0.0, 9.0.1, 9.1.0, 9.1.1, 9.2.0, 9.3.0, 9.4.0, 9.5.0, 9.5.1, 9.6.0, 9.6.1, 9.7.2, 10.0.0, 10.1.0, 10.1.1, 11.0.0, 11.1.0, 11.3.0, 11.4.0, 11.5.0, 12.0.0, 12.1.0, 12.2.0, 13.0.0

But as you can see the last version should fulfill that version demands, any suggestions?

**Comment by ALameLlama** [comment]
Can you try and run this?
```
vagrant box add laravel/homestead https://app.vagrantup.com/laravel/boxes/homestead
```

Might be similar to this:
https://github.com/laravel/homestead/issues/1907

**Comment by Serringer** [comment]
That worked thank you
