### ISSUE TITLE
Problem installing using composer due to symfony/yaml dependency

### ISSUE THREAD

**Issue by josueprocomp** [laravel/homestead#1943]
When installing Laravel 10 locally it installs symfony/yaml 7, because laravel/sail has a symfony/yaml dependency: "^6.0|^7.0".

But when installing after Homestead using composer as vendor (per project installation), and having Homestead a symfony/yaml dependency: "^5.0 || ^6.0" a conflict occurs, since the local Laravel project already has symfony/yaml locked to version 7 in composer.lock.

## Expected behavior

Homestead should install without problems (conflicts) on a fresh Laravel installation, when running:

`composer require laravel/homestead --dev`

## Actual behavior

$ composer require laravel/homestead --dev

./composer.json has been updated
Running composer update laravel/homestead
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/homestead[v2.0.0, ..., v2.2.1] require symfony/console ~2.0 -> found symfony/console[2.0.4, ..., v2.8.52] but the package is fixed to v6.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/homestead v2.2.2 requires symfony/console ~2.0 || ~3.0 -> found symfony/console[2.0.4, ..., v2.8.52, v3.0.0, ..., v3.4.47] but the package is fixed to v6.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/homestead[v3.0.0, ..., v3.1.0, v4.0.0, ..., v4.0.5] require symfony/console ~2.3|~3.0 -> found symfony/console[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but the package is fixed to v6.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/homestead[v5.0.0, ..., v5.4.0, v6.0.0, ..., v6.6.0, v7.0.0, ..., v7.20.0] require php ^5.6 || ^7.0 -> your php version (8.3.2) does not satisfy that requirement.
    - laravel/homestead[8.0.0, ..., v8.6.0, v9.0.0, ..., v9.4.1, v10.0.0, ..., v10.17.0, v11.0.0, ..., v11.2.4] require php ^7.1 -> your php version (8.3.2) does not satisfy that requirement.
    - laravel/homestead[v11.2.0, ..., v11.3.3] require php ^7.4 -> your php version (8.3.2) does not satisfy that requirement.
    - laravel/homestead[v11.4.0, v12.0.0, ..., v12.8.0, v13.0.0, ..., v13.1.1] require symfony/console ~5.1 -> found symfony/console[v5.1.0, ..., v5.4.34] but the package is fixed to v6.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/homestead v13.2.0 requires symfony/yaml ^6.0 -> found symfony/yaml[v6.0.0, ..., v6.4.0] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/homestead[v13.2.1, ..., v13.3.2, v14.0.0, ..., v14.5.0, v15.0.0, ..., v15.0.1] require symfony/yaml ^5.0 || ^6.0 -> found symfony/yaml[v5.0.0, ..., v5.4.31, v6.0.0, ..., v6.4.0] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel/homestead * -> satisfiable by laravel/homestead[v2.0.0, ..., v2.2.2, v3.0.0, v3.0.1, v3.0.2, v3.1.0, v4.0.0, ..., v4.0.5, v5.0.0, ..., v5.4.0, v6.0.0, ..., v6.6.0, v7.0.0, ..., v7.20.0, 8.0.0, ..., v8.6.0, v9.0.0, ..., v9.4.1, v10.0.0, ..., v10.17.0, v11.0.0, ..., v11.4.0, v12.0.0, ..., v12.8.0, v13.0.0, ..., v13.3.2, v14.0.0, ..., v14.5.0, v15.0.0, v15.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/homestead:*" to figure out if any version is installable, or "composer require laravel/homestead:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

## Steps to reproduce

$ composer create-project laravel/laravel example-app
$ cd example-app
$ composer require laravel/homestead --dev

## Solution

If Homestead supports symfony/yaml 7, update the dependency in composer.json to:

"symfony/yaml": "^5.0 || ^6.0 || ^7.0"

## Workaround

$ composer require laravel/homestead --dev --with-all-dependencies
./composer.json has been updated
Running composer update laravel/homestead --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 1 update, 0 removals
  - Locking laravel/homestead (v15.0.1)
  - Downgrading symfony/yaml (v7.0.0 => v6.4.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Downgrading symfony/yaml (v7.0.0 => v6.4.0): Extracting archive
  - Installing laravel/homestead (v15.0.1): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  laravel/sail ................................................................................................................................ DONE
  laravel/sanctum ............................................................................................................................. DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE

83 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets].  

No security vulnerability advisories found.
Using version ^15.0 for laravel/homestead

**Comment by ALameLlama** [comment]
https://github.com/laravel/homestead/pull/1944

**Comment by svpernova09** [comment]
Released https://github.com/laravel/homestead/releases/tag/v15.0.2 which should resolve this.
