### ISSUE TITLE
I got this bug while executing MAKE command:

### ISSUE THREAD

**Issue by netaccount-tarik** [laravel/homestead#1953]
I got this bug in new 15 version (tried all 15 versions as well) while executing MAKE command below if i trying to set homestead per project in outside of laravel folder for example, when i try revert with 14.5 version of homestead in require step before than it works. Please solve this to be fixed in 15 and --dev versions... p.s. I am using vagrant+virtualbox.

php vendor/bin/homestead make

PHP Fatal error:  Declaration of Laravel\Homestead\MakeCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /home/tarik/GitHub/uhu/vendor/laravel/homestead/src/MakeCommand.php on line 68

![2024-02-12_18-05](https://github.com/laravel/homestead/assets/81200991/be788ead-43f0-4dd0-8534-da30f487f6ea)

**Comment by ilvalerione** [comment]
I get the same error message with Laravel 11 and Homestead 15
