### ISSUE TITLE
VMware Desktop Support

### ISSUE THREAD

**Issue by Sn0wCrack** [laravel/homestead#1961]
Wondering if there's any current plans to revive VMware Desktop (Fusion) as a provider for Homestead?

At the minute I'm currently evaluating Apple Silicon Macs for a future standard environment for my team and noticed the only currently supported provider is Parallels, however I remembered VMware being supported in the past.

While Parallels works great, the licensing system for non-personal licenses is a bit of mess and so I'm looking at other solutions for my team to use to see if anything else works and we could evaluate what's the best to use from our management teams perspective. 

Locally I've managed to build the Settler vagrant box on my M1 Macbook using a VMware Fusion free license and added it as a different box and it all seems to run fairly well without much changes to Homestead itself. 

The only change I needed to make for VMware to work was to remove the following bit of code in the scripts/homestead.rb file:
```ruby
v.vmx['guestOS'] = 'ubuntu-64'
```

Otherwise VMware seems to just think the VM image you're trying to run is for x86 and not ARM.

--------

I am aware that at the moment the builds for the vagrant boxes are handled manually so I had a couple thoughts on that:

- What is the feasibility of automating the creation of the vagrant boxes via GitHub Actions. I am aware Chef builds their Bento boxes using GitHub actions (just used for testing I believe, but the theory is solid on it)
    - GitHub currently doesn't support ARM64 natively, but it is something they have in beta the moment. Alternatively there may be a provider willing to provide servers for this project.
- How much of what is customized in the Settler box build process that couldn't be moved into the Homestead provisioning scripts and potentially shift the base box to just be the chef/bento-ubuntu-22.04 and save the need to build a box entirely.
    - There are things I know that could just removed from Settler, such as the PHP installs, as provisioning already updates/installs all used PHP versions as part of provisioning.

I'm totally willing to help with either of the above projects if needed as well, I internally manage quite a few GitHub Runner servers and would be happy to assist in providing advice, scripts or managing these servers if need be.

And more than happy to investigate further on shifting parts of Settler into the provisioning script as well.

**Comment by svpernova09** [comment]
I have no plans to revive any VMware support since Broadcom's acquisition of VMware.
