### ISSUE TITLE
amd64 libvirt box missing after settler v13

### ISSUE THREAD

**Issue by ALameLlama** [laravel/homestead#1975]
It looks like with settler v13 we stopped building the libvirt box
https://app.vagrantup.com/laravel/boxes/homestead

## Versions

- Vagrant: 2.4.1
- Provider: Libvirt
- Homestead: v15

## Host operating system
Pop!_OS 22.04

**Comment by svpernova09** [comment]
https://github.com/svpernova09/homestead/issues/1

**Comment by ALameLlama** [comment]
Closing this since the project is now dead
