### ISSUE TITLE
PHP 8.4 Support

### ISSUE THREAD

**Issue by SachinAgarwal1337** [laravel/homestead#1988]
Will Homestead be supporting PHP 8.4 anytime soon?

**Comment by browner12** [comment]
this project is basically abandoned, and will not be receiving updates

check out Joe Ferguson's fork, which has 8.4 support

**Comment by browner12** [comment]
or also complain that you want Homestead supported by Laravel again! 😆

**Comment by crynobone** [comment]
No, we not introducing PHP 8.4 supports as this package is no longer maintained

**Comment by fish3046** [comment]
There was significant work done less than a year ago.  Was there a post about this being truly abandoned?  @svpernova09 ?

**Comment by browner12** [comment]
@svpernova09 has his own fork of this repo with 8.4 support.

**Comment by fish3046** [comment]
Neat, guess I missed [this issue](https://github.com/laravel/homestead/issues/1977).  [Here's the aforementioned fork](https://github.com/svpernova09/homestead) as well.

Thanks!
