### ISSUE TITLE
eth0 IP Address?

### ISSUE THREAD

**Issue by scottwakefield** [laravel/homestead#24]
I seem to be having network issues with Homestead, which causes the box to suffer from severe lag. It appears that the box is getting assigned an that's conflicting with my router. 

Comparing the Homestead eth0 address (with ifconfig) with the same on a working vagrant box reveals the following:

**Working Box**
inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0

**Homestead Box**
inet addr:192.168.0.15  Bcast:192.168.255.255  Mask:255.255.0.0

If I turn off my WiFi connection the lag is gone instantly, so I'm sure it's a networking/conflict issue. 

I'm just wondering why/how Homestead is assigned that particular IP and if there's a way of changing it. I've never had this issue with any other Vagrant box.

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
