### ISSUE TITLE
[Proposal] Include MailHog in Homestead

### ISSUE THREAD

**Issue by lioannou** [laravel/homestead#376]
As requested from https://github.com/laravel/internals/issues/257

I've recently switched away from MailCatcher (due to multiple issues with Ruby + Gems) - and found MailHog - https://github.com/mailhog/MailHog

Mailhog is an alternative for Mailcatcher or Mailtrap.io that doesnt require any special dependencies like Ruby, so installation dead simple. Here is a quick article I found on it: http://iankent.uk/2014/04/20/introducing-go-mailhog/

Here is an example of bash installation script that would cover everything needed to include in Homestead: https://gist.github.com/varghesejacob/68caf7aeee53305a1ffa#file-mailhog-bash-script

MailHog includes hooks (like Mailcatcher) to use in PHPUnit Tests so you can 'test' your emails are been sent etc etc: https://gist.github.com/varghesejacob/6113ac971a00611015c5#file-mailhog-test-helper.

And MailHog has a web viewer - so you can "see" your emails (just like Mailtrap.io etc)

Obviously people could install this themselves - but it would seem to be a natural synergy with Homestead - providing everything 'out of the box'. Taylor has previously tweeted that perhaps MailCatcher should be in Homestead by default: https://twitter.com/taylorotwell/status/536923096213516288 - and it was highly "+1" from many replied tweets (including @JeffreyWay) - so this would potentially be a better 'drop in' replacement.

Obviously there is also MailTraip.io - but Mailhog is a local service - so is much faster/reliable etc etc.

**Comment by svpernova09** [comment]
Thanks, I'll take this for a spin and if it's not too heavy I'll get it added.

**Comment by lioannou** [comment]
@svpernova09 - thanks.

I've been using it for over 2 years now and it's been bulletproof for me.

Let me know if you notice any issues.

**Comment by svpernova09** [comment]
Implemented in Settler https://github.com/laravel/settler/pull/88/files

**Comment by lioannou** [comment]
Awesome work. I just installed a new fresh 7.1 homestead and then manually ran the commands above - and it looks like it is working perfectly.

Thanks so much.

We should probably do a PR for this for the docs + features section?

**Comment by svpernova09** [comment]
I just had to release a fix today for the box, so I'd like to see at minimum a week of stable usage before we push out a new box download. Once this is merged I expect ~2 weeks before the next release (unless some urgent bug is discovered). Once it's merged I'll PR the docs.
