### ISSUE TITLE
Homestead Box Mcrypt

### ISSUE THREAD

**Issue by djekl** [laravel/homestead#387]
## Versions
  - Vagrant: Vagrant 1.9.0
  - Provider: Virtualbox 5.1.10 r112026 (Qt5.6.2)
  - Homestead: 1.9.0

The latest Homestead Box doesn't have Mcrypt installed by default, and also now no longer works with Laravel 4.2 legacy projects once I install Mcrypt `sudo apt-get install -y php7.1-mcrypt`

`Function mcrypt_get_iv_size() is deprecated` inside `/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php` line 305

![Function mcrypt_get_iv_size() is deprecated](https://d3dr1ze7164817.cloudfront.net/items/3s3E1k1i2Z192g21031M/Image%202016-12-07%20at%2012.10.21%20pm.png?X-CloudApp-Visitor-Id=1061807)

**Comment by djekl** [comment]
Mcrypt deprication is here - https://github.com/laravel/framework/issues/16329

**Comment by svpernova09** [comment]
Laravel v4.2.20 was released to bring PHP 7.0 compatibility to the 4.2.x version. Homestead 4.x will be the version that supports PHP 7.1. To continue using Homestead with PHP 7.0 please use version   3.1 of Homestead.

If you want to continue using PHP 7.1 you'll have to adjust your code base to catch or suppress deprecated warnings.

**Comment by djekl** [comment]
I am using `Laravel Framework version 4.2.22`

This latest box doesn't have Mcrypt, this is one limiting factor, and the other is that deprication WITHIN the laravel framework itself. Its not something I have control over!

**Comment by svpernova09** [comment]
The framework didn't depreciate mcrypt, the PHP Language did. 

At this time you should use Homestead 3.1, which supports PHP 7.0

**Comment by mul14** [comment]
That's just "deprecated warning". You can turn it off.

**Comment by benjaminkohl** [comment]
Does anyone know the correct error_reporting flags to use to hide this error? I excluded E_DEPRECATED and E_USER_DEPRECATED but I still see this message.
