### ISSUE TITLE
VMWare_Desktop

### ISSUE THREAD

**Issue by lioannou** [laravel/homestead#389]
Hi,

Small thing - is there any reason we still call the Homestead Box option "vmware_workstation" box as "vmware_desktop"?

See attached picture.

![desktop](https://cloud.githubusercontent.com/assets/1210658/20978014/34305340-bc9f-11e6-916b-8bb80647e359.png)

It is slightly confusing - especially when all the Homestead docs everywhere only ever references one option as "vmware_workstation".

Would be nice to standardize and switch it to be known as "vmware_workstation" in the future if possible? Not sure how that might break box upgrades looking for 'new' versions though?

**Comment by svpernova09** [comment]
That's not us, Atlas forces us to use that name.

**Comment by lioannou** [comment]
I think I just realised - what does vmware_fusion use? The same box?

**Comment by svpernova09** [comment]
`vmware_desktop` and `vmware_fusion` are essentially aliases for`vmware_workstation`.
