### ISSUE TITLE
[Proposal] cd into site folder when running 'vagrant ssh' 

### ISSUE THREAD

**Issue by dragosmocrii** [laravel/homestead#390]
Currently when you run **vagrant ssh** it will set the current directory to /home/vagrant. It would help a little if it could drop me right into my project's vagrant directory, which usually is a directory deeper, for example /home/vagrant/project.

Unfortunately I don't know bash very well, so I can't contribute this change myself. Hopefully something who can, decides to add this change.

Thanks!

**Comment by svpernova09** [comment]
Since Homestead supports multiple projects it's not something we'd add, but if you want give this a spin:

http://serverfault.com/a/482968

![screen shot 2016-12-07 at 12 59 16 pm](https://cloud.githubusercontent.com/assets/967362/20982176/02375be4-bc7d-11e6-9789-4a686a881611.png)

**Comment by dragosmocrii** [comment]
Hi Joe,

Sure Homestead supports multiple projects on a single machine, but when you vagrant up from a project's folder, doesn't vagrant use the Homestead.yaml config file to set up the VM? This config file has the **folders->to** settings which could be used to provision the VM, I guess.

I still think this could be useful :)

**Comment by svpernova09** [comment]
If you're using Vagrant per project, where you'll only ever have 1 project in vagrant, you could add the 1 liner to `after.sh` and it would accomplish what you're wanting.
