### ISSUE TITLE
PHP version of host machine matters? WHY?

### ISSUE THREAD

**Issue by matthebs** [laravel/homestead#394]
If the whole purpose of having a virtual machine why doesn't it matter what my host machine version of PHP is?
I want to run homestead as a per project but Its making me create the laravel project first then homestead. How ever my host machine version of php is 5.3 and I need version 5.6 or >.
Why don't I install it on my machine. because I want all my code to be isolated.

Is there a way todo this?
I tried installing laravel in the laravel virtual machine but the config never seems to work.
Even when the nginx settings look to be point in the correct spot.

Thanks 

Matt

**Comment by andrewhood125** [comment]
Homestead just like any other piece of software ( stop relating it to virtual machines for a moment ) has certain dependencies to run. 
  - Sass requires ruby `>=1.8.7` https://rubygems.org/gems/sass. 
  - Deluge Client requires any of these versions of Python 2.6, 2.7, 3.3, 3.4 https://pypi.python.org/pypi/deluge-client/1.0.2. 

It's not a problem specific to php, or packagist. Such is the nature of software that isn't prepackaged in an `installer.exe`

Homestead just happens to be a tool to build virtual machines for various php projects. It's a piece of software and requires `"php": ">=5.5.9"` https://github.com/laravel/homestead/blob/master/composer.json#L5 Why does it require that version? Idk. A good place to start looking would be the backwards incompatible changes between `5.5.9` and `5.3`. 

I would suggest installing the required version of php. If you tell us a little bit about your setup, we might be able to help. I don't understand the latter part of your question, but I can say it does sound like yak shaving.

**Comment by svpernova09** [comment]
The oldest supported version of the Laravel Framework is the LTS version 5.1 That version supports PHP 5.5.x. So IMHO it's not too much to expect users to be running that version for Homestead. 

If your host OS is running 5.3 you may be several versions behind.

Using Homestead per project requires composer, which requires PHP. Even if you do nothing else with PHP on your host OS it's still needed to run composer.

If you're on Windows, a good alternative may be the BASH system so you can install and run PHP there without having to install it in Windows.

**Comment by matthebs** [comment]
Thanks.
I got it working by moving stuff around, getting new files and updating with composer on the VB

**Comment by lioannou** [comment]
@matthebs - you dont need PHP or Git on your local machine at all.

Just download homestead from Github.com - and then run `vagrant up` in that folder. It works perfectly, although you wont be able to auto-update Homestead - you have to do it manually.
