### ISSUE TITLE
Vagrant Share no longer working after updating to 1.0.1

### ISSUE THREAD

**Issue by elasticsteve** [laravel/homestead#395]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox 5.1.10
  - Homestead: 1.0.1

## Host operating system
Win 10

## Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: G:/Dropbox/PhpStorm Projects/elasticstage
      to: /home/vagrant/elasticstage
    - map: G:/Dropbox/PhpStorm Projects/phpMyAdmin
      to: /home/vagrant/phpMyAdmin

sites:
    - map: elastic.app
      to: /home/vagrant/elasticstage/public
    - map: phpmyadmin.app
      to: /home/vagrant/phpMyAdmin

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant up output
Provide a link to a GitHub Gist containing the complete output.
[LINK](https://gist.github.com/elasticsteve/f391eb07ba7baa67858739fe0356e835)

## Expected behavior
`vagrant share` shared homestead with no problems before updating vagrant/virtualbox/homestead
although after updating vagrant (still with the old homestead version), all of a sudden I had to use: `vagrant up --http 80` - I found posts from other users having the same problem.

## Actual behavior
Since updating Homestead to 1.0.1 2 days ago, vagrant share doesn't work.

This is the vagrant output (looks fine):
```
C:\Users\Steve Rhodes\Homestead>vagrant share --http 80
==> homestead-7: Detecting network information for machine...
    homestead-7: Local machine address: 127.0.0.1
    homestead-7:
    homestead-7: Note: With the local address (127.0.0.1), Vagrant Share can only
    homestead-7: share any ports you have forwarded. Assign an IP or address to your
    homestead-7: machine to expose all TCP ports. Consult the documentation
    homestead-7: for your provider ('virtualbox') for more information.
    homestead-7:
    homestead-7: Local HTTP port: 80
    homestead-7: Local HTTPS port: disabled
    homestead-7: Port: 2222
    homestead-7: Port: 33060
    homestead-7: Port: 44300
    homestead-7: Port: 54320
    homestead-7: Port: 8000
==> homestead-7: Checking authentication and authorization...
==> homestead-7: Creating Vagrant Share session...
    homestead-7: Share will be at: easy-reindeer-5455
==> homestead-7: Your Vagrant Share is running! Name: easy-reindeer-5455
==> homestead-7: URL: http://easy-reindeer-5455.vagrantshare.com
==> homestead-7:
==> homestead-7: You're sharing your Vagrant machine in "restricted" mode. This
==> homestead-7: means that only the ports listed above will be accessible by
==> homestead-7: other users (either via the web URL or using `vagrant connect`).
```

This is what happens when I try to access the url:

![1](https://cloud.githubusercontent.com/assets/10718044/21141115/5b440d44-c133-11e6-8d6d-cd8b7b4125e2.jpg)

## Steps to reproduce
1. cd into homestead dir
2. vagrant share --http 80
3. open link in browser

**Comment by svpernova09** [comment]
Thanks for the report, I'll have a look at this later today.

**Comment by svpernova09** [comment]
@elasticsteve 

Instead of `vagrant share --http 80` please try `vagrant share --http 8000`

**Comment by elasticsteve** [comment]
Yes, that works.

Any explanation why and why it worked with 80 before?

**Comment by svpernova09** [comment]
I'm not certain, I've not used this feature in a long time. It could have been a fix / update in Virtualbox but I'd expect it was most likely a change made in Vagrant (unless you had this working in 1.9.x with pre 1.0.1 box)

**Comment by elasticsteve** [comment]
What would really help is if I could somehow make the default "vagrant share" work again. (It's built into PHPstorm and I don't have to ssh into the user directory first). I just can't figure it out.

Also, if you have a few folders (projects) in your Homestead.yaml (I deleted them for now), how does Vagrant know which folder to share? I couldn't find any info on this.

**Comment by elasticsteve** [comment]
@svpernova09 Yes, I had it working with 1.9.x pre 1.0.1. Also, please read what I said in the post before about more than one project/server.

**Comment by svpernova09** [comment]
RE: Working previously on port 80

No idea why it would have broken in the new boxes. Nothing around nginx or it's config changed.

Multiple projects/folders:

I believe it would default to the first nginx host that is in the config. There is an old thread https://laracasts.com/discuss/channels/general-discussion/vagrant-share?page=1 that has some possible workarounds, one of the first links is dead though.

**Comment by elasticsteve** [comment]
Yeah, I saw that, but it's more about assigning different ports to different projects. Strange that one can't find official info on such an important thing. I looked at the Vagrant doc and nothing.

Guess I have to give it a try and see if the first one in the config is used or not.

Thanks anyway!

**Comment by elasticsteve** [comment]
@svpernova09 Just as a follow up... Went back to 1.8.6 and `vagrant share --http 80` worked again.

Then I went back to 1.8.5 and I could even use plain `vagrant share` (which is built into PHPstorm and my preferred way).

The rest of my setup is VirtualBox 5.1 on Win 10.

I don't know if this is something that can be fixed on your end or not, but I thought I let you know...

**Comment by svpernova09** [comment]
If going back to 1.8.5 fixed it, there's nothing I can think of on our end to fix it. You may want to open a bug report on the vagrant repo: https://github.com/mitchellh/vagrant
