### ISSUE TITLE
Homestead 7 install

### ISSUE THREAD

**Issue by tjnine** [laravel/homestead#400]
## Installing Homestead 7 on OS X 10.12

  It seems there is a problem with the ssh keys, I have tried uninstalling and reinstalling Homestead 7 three times and each time I get the same errors and behavior as the last. I watched my terminal and it seems as soon as the provisioning starts and it gets to SSH auth method: private key the installation dies. I checked my ssh keys and id_rsa and id_rsa.pub are there. What am I doing wrong?

**Comment by svpernova09** [comment]
Please open a new issue filling out the issue template so we can see what versions of the different software you're using.
