### ISSUE TITLE
You made big mistake changing PHP version in new Homestead box

### ISSUE THREAD

**Issue by daryn-k** [laravel/homestead#402]
It's very stupid changing PHP version in new Homestead without asking my permission! Now I can't download previous Homestead with PHP 7.0, because it's need 8-10 hours for downloading! I hate you all!

**Comment by jonnywilliamson** [comment]
I'm sure that comment was made in jest.

I for one am very thankful for the speedy work you do with homestead. Great job Joe.

**Comment by svpernova09** [comment]
Thanks @jonnywilliamson 

I can see the frustration if you're having to download a new box over a slow connection. Especially since we've pushed 3-4 new boxes pretty close together. Trying to slow that down a bit. Next box version release is likely mid-January unless someone finds a bug that requires a quicker fix.

**Comment by lioannou** [comment]
@daryn-k  - I think you need to read this: https://laravel.com/docs/5.3/homestead#old-versions

@svpernova09 - since people can pick their box version - does it really matter if you push lots of updates?

**Comment by andrewhood125** [comment]
If that's really an issue maybe we can add some documentation surrounding building your over box from settler. All you really at that point is the base box.

**Comment by svpernova09** [comment]
@andrewhood125 Those with enough initiative can go figure it out, certainly. I don't want to support them building Settler. They shouldn't have to. I've taken steps to ensure they don't need to (by going back to 5.5.x and getting a working base box and branch of settler). 

Honestly, I just need to sit down, double check my versions and blog about it.
