### ISSUE TITLE
Don't set environment variables by default

### ISSUE THREAD

**Issue by barryvanveen** [laravel/homestead#411]
This issue is not concerned with any specific version of Vagrant or provider, it is about the default configuration values in Homestead.yaml.

## Homestead.yaml
```yaml
variables:
    - key: APP_ENV
      value: local
```

The default configuration sets an environment variable of APP_ENV=local. I believe this causes some headaches when you try to work with different environment variables. In my case I work with .env.local and .env.production.

Everything seems to work fine when using for example `php artisan migrate --env=production`. The problem is that all variables are taken from the configuration file _except_ for APP_ENV which is overridden by the nginx environment variable.

Since the APP_ENV configuration is present in the default Laravel environment file (and has been for some time), why would we set it in the Homestead configuration as well? My opinion is that this leads to unexpected and confusing behavior. Maybe it could be in comments, just like the Blackfire section.

## References
I've just had a discussion about this on https://ramy.nl/2016/03/15/load-a-different-environment-file-with-laravel-5-artisan/. Also, I believe (but cannot confirm), that some of the issues for laravel/framework would be solved by this.

**Comment by svpernova09** [comment]
You should be able to remove the `APP_ENV` variable (or the entire variables section) from your `Homestead.yaml` without any issues. Your `Homestead.yaml` must be from before fcf797b5506aa6549a4bde88c8084e5caf9425fd (Dec 2015). 

This should solve your problem. Let us know if the problem persists.

**Comment by barryvanveen** [comment]
You're right @svpernova09, sorry for overlooking that!

**Comment by svpernova09** [comment]
No worries! Glad you were able to sort it out.
