### ISSUE TITLE
Push feature

### ISSUE THREAD

**Issue by giolf** [laravel/homestead#415]
Would be not bad to add the "push" key in the `Homestead.yaml` file in the order to map different deployment stages.

**Comment by svpernova09** [comment]
Not familiar with what you're referring to as `push`, describe your use case?

**Comment by giolf** [comment]
[Vagrant - push](https://www.vagrantup.com/docs/push/)

**Comment by svpernova09** [comment]
@giolf You can easily add this to your `Vagrantfile`. Not sure it's something Homestead needs since I wouldn't want to show people how to expose plaintext passwords for this.
