### ISSUE TITLE
Update to MySQL 5.6.x

### ISSUE THREAD

**Issue by thinksaydo** [laravel/homestead#42]
I think Homestead (and Forge) could benefit from updating to the latest release of MySQL instead of the older version currently installed by default. Yes, we could update this ourselves, but the beauty of Homestead (and Forge) is the ease of local development without custom configuration.

Why MySQL 5.6? Speed: http://www.mysql.com/why-mysql/benchmarks/

What it takes to use the official Oracle Debian package instead of the outdated apt-get version: http://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/

I just attended an Oracle MySQL talk where the speaker encouraged everyone to be using 5.6 release now because of the dramatic performance improvements especially in InnoDB, with 5.7 on the horizon in March of 2015 with even faster performance.

Let me know if I can help with this in some way too.

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
