### ISSUE TITLE
bindfs causes new permissions problems and doesn't solve my nfs woes

### ISSUE THREAD

**Issue by vesper8** [laravel/homestead#429]
using:
VirtualBox-5.1.12-112440-OSX
Sierra 10.12.2
Vagrant 1.9.1
Homestead v4.0.3
Homestead box 1.0.1

I have been struggling with permission problems for months and it's driving me up the walls!

My yarn and composer commands work on the first run but any subsequent runs will cause permission denied errors.

I share all my folders with homestead using NFS

Looking for a solution I found out about bindfs, and then saw that you had recently implemented a bindfs solution (that was different from those I had read about, but also simpler)

I had found a description of a solution here http://martinpeverelli.github.io/magento/php/2016/03/19/homestead-for-magento/

But your implementation is even simpler:

```
        # bindfs support to fix shared folder (when nfs enabled) permission issue on mac osx
        if Vagrant.has_plugin?("vagrant-bindfs")
          config.bindfs.bind_folder folder["to"], folder["to"]
        end
```

I figure in order to use this (and make all my permission problems magically go away) all I have to do is run 'vagrant plugin install vagrant-bindfs' and restart my box?

I did that and it said the bindfs was now enabled. All my nfs files are now owned by vagrant:vagrant as opposed to 501:dialout

But not only did that not solve my composer/yarn permission problems. It is now causing a new permission problem with mysql

See, I also share my mysql data folder via NFS, and then I use apparmor to map the folders so that homestead's mysql is able to use the shared nfs folder. I do this because I have a ton of DBs in that folder and I want to persist them when I destroy/recreate the homestead box. This has always worked perfectly well before but since enabling bindfs it gives me these errors:

```
2017-01-16T14:14:37.013089Z 0 [Warning] Can't create test file /home/vagrant/MYSQLDATA/mysql/homestead.lower-test
2017-01-16T14:14:37.013437Z 0 [Warning] Can't create test file /home/vagrant/MYSQLDATA/mysql/homestead.lower-test
2017-01-16T14:14:37.033081Z 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
2017-01-16T14:14:37.033110Z 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
```

The odd thing is, I can create test files and write to the above files no problem logging in as the vagrant user.

After trying a lot of things, I stopped the box, uninstalled the vagrant-bindfs plugin, restarted the box.. and can confirm my little apparmor trick with the nfs mysql/data share is now working again as it did before.

Would really appreciate some help in finally solving my extremely annoying permission problem!!

**Comment by vesper8** [comment]
I just noticed that someone replied my thread with a suggestion

http://laravel.io/forum/06-07-2014-homestead-ideas-on-persisting-databases-upon-vagrant-destroy

```
bindfs --force-user='mysql' --force-group='mysql' /home/vagrant/mysqldata /home/vagrant/mysqldata
```

Haven't tried this yet. But I think he's on to something.

Would still love some help understanding why using vagrant-bindfs hasn't helped my problem with yarn and composer. And why it's causing the problem with mysql and apparmor

**Comment by svpernova09** [comment]
This is a bit outside my expertise (I've never needed to do anything but enable NFS). Mapping MySQL data folders into the VM but very much outside the scope/use case of Vagrant, and Homestead. 

You may consider not running Composer or Yarn from inside vagrant; run them on your host OS. That will likely resolve the need to fight with permissions there.

**Comment by vesper8** [comment]
the above bindfs command used to force the user:group to be mysql fixed my problem as far as mysql goes.

And you make a good point when you suggest I should just run composer/yarn from the main filesystem.
