### ISSUE TITLE
Vagrant up not starting box - Windows 10 - Virtualbox

### ISSUE THREAD

**Issue by sbramlett** [laravel/homestead#438]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 1.9.1
  - Provider: Virtualbox 5.1.14
  - Homestead: Run `homestead --version` to show the version.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.1`. You *will* show as up-to-date from the `~5.0` branch when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10

## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```

## Vagrant up output
https://gist.github.com/sbramlett/783887c93fab73b0d42649001ca3888a

## Vagrant box list output
C:\WINDOWS\system32>vagrant box list
laravel/homestead (virtualbox, 1.0.1)
ubuntu/trusty64   (virtualbox, 20170130.0.0)

## Expected behavior
Start my box

## Actual behavior
It tells me the box could not be found or accessed

## Steps to reproduce
1. Install Vagrant
2. Add laravel/homestead box
3. Run vagrant up

**Comment by sbramlett** [comment]
I deleted my Vagrantfile and all boxes to start over.  It seems to have worked without any issues after I did that. Not sure what went wrong during the first try. I'm running my laravel/homestead box now. Thanks!

**Comment by svpernova09** [comment]
I was going to suggest that, glad you got it working
