### ISSUE TITLE
Using Psy Sh to debug

### ISSUE THREAD

**Issue by andrewhood125** [laravel/homestead#440]
I'm looking for a way to use `eval(\Psy\sh());` to debug while using Homestead. Being that the server is daemonized it makes things tricky. 

What I've tried so far is:

`sudo service nginx stop`

and start nginx with daemon off. 

`sudo nginx -g 'daemon off;'`

I can't get any output from anything that way. The server works from the host machine but nothing else..

I killed nginx again and then started `./artisan server --host=0.0.0.0`

From the host machine I tack on `:8000` and that works but there's got to be a better way right?

**Comment by svpernova09** [comment]
Stop being a heathen and use Xdebug.


In all seriousness: I've never heard of PsySH, What is it giving you that xdebug isn't?

**Comment by andrewhood125** [comment]
PsySh is like dropping in `binding.pry` into your rails app. It gives you a full repl. TBH I haven't given a Xdebug a lot of use. I'll explore that. 

Still would be curious how anyone is using PsySh in Homestead if they are.

**Comment by svpernova09** [comment]
Xdebug will give you a full console at any point in the debugging process as well. Going to close for now, but I'll tweet and see if we can drive some traffic to this.
