### ISSUE TITLE
It's possible to have a Homestead version based on a 32bit OS?

### ISSUE THREAD

**Issue by sveggiani** [laravel/homestead#45]
Old CPU's not supporting Vt-x technology are unable to run homestead because its based on a 64bit VM.

More info and discussion: http://laravel.io/forum/05-18-2014-trouble-getting-homestead-to-start-in-windows

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
