### ISSUE TITLE
sqlite3 i/o error

### ISSUE THREAD

**Issue by Geczy** [laravel/homestead#454]
## Versions
  - Vagrant: Run `vagrant -v` to show the version.
1.9.1

  - Provider: Virtualbox, VMWare or Parallels and it's version.
virtualbox 5.1.14

  - Homestead: Run `homestead --version` to show the version.
4.0

## Host operating system
windows 10 15025

when i try to do a sqlite3 query i get the following error in laravel:
```
ErrorException in ReportController.php line 205:
SQLite3::query(): Unable to prepare statement: 10, disk I/O error
```

## Steps to reproduce
1. read a sqlite database file in laravel
2. attempt to query extending sqlite3

this works in a normal mamp environment

**Comment by Geczy** [comment]
Finding more about this, seems to be a virtualization iissue

Same issue here
https://www.virtualbox.org/ticket/16432

**Comment by Geczy** [comment]
http://sqlite.1065341.n5.nabble.com/sqlite3-OperationalError-disk-I-O-error-td18568.html

**Comment by svpernova09** [comment]
Where is your sqlite database? The problem is likely due to where you're storing it. Try putting it in the `database` folder and use `database_path()` helper to point to it. 

Remember that the user needs write permissions on the folder that contains the sqlite database as well as the sqlite file itself for it to work.

**Comment by Geczy** [comment]
My database is in the `storage/app/*` folder. I have chmod 777 on it and the file. I'm using `storage_path()`

I tried moving it to `database` and using the `database_path()` helper but the error is the same.

I think any folder inside the shared sync folder is not going to work because it's syncing from a windows host. I'd have to move it outside the share like in /tmp/ or something for it to work.

**Comment by lioannou** [comment]
Have you tried switching to the SMB file type for your sync'd folders? I had some IO issues with the new Homestead, VMWare and Windows 10 which were resolved by switch to smb. The performance is roughly the same.

```
folders:
    - map: c:/www
      to: /home/vagrant/www
      type: smb
```

**Comment by Geczy** [comment]
That worked! Thank you. I tried `rsync` type but not `smb`

**Comment by Geczy** [comment]
Type required to be in quotes as of 2019 `type: "smb"`
