### ISSUE TITLE
homestead1.1.0 error: Mcrypt PHP extension required.

### ISSUE THREAD

**Issue by reatang** [laravel/homestead#456]
Mcrypt PHP extension not install

![mcrypt_not_install](https://cloud.githubusercontent.com/assets/8022923/22852813/76313110-f07f-11e6-849f-d00fe68c21c4.png)

## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox 5.1.14
  - Homestead: 1.1.0
  - PHP VERSION: 7.1

## all config is default

**Comment by svpernova09** [comment]
What version of Laravel are you using? Mcrypt hasn't been required since 5.1 I believe.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by svpernova09** [comment]
FYI: http://php.net/manual/en/migration71.deprecated.php

**Comment by reatang** [comment]
Thank you for reminding, I will read php71 features。:-)
