### ISSUE TITLE
fresh installation fails

### ISSUE THREAD

**Issue by ultimateBusiness** [laravel/homestead#457]
I am working for years with homestead at a box-version of around v0.4.
Now I would like to upgrade to the actual box, so I destroy my working vagrant-box, make all updates to homestead, vagrant and the lastest version of the box (v1.1.0) and try to run, but get the following error:
```
Vagrant found a port collision for the specified port and virtual machine.
While this port was marked to be auto-corrected, the ports in the
auto-correction range are all also used.

VM: homestead-7
Forwarded port: 80 => 8000
```

Next, I remove all installations around homestead (.vagrant.d, .homestead and Homestead) - and yes, I have restarted my Mac ;-)

After all was cleared - I take the installation guide for Homestead an do all necessary steps to install Homestead, but the end result stays the same - please take a look at the Gist for the detailed output from the first start.

I have no local apache, nginx or other server installed and before the upgrade all runs perfect.
 
## Versions
  - Vagrant: 1.9.1
  - Provider: vmware_fusion 4.0.15
  - Homestead: latest version from GitHub

## Host operating system
MacOS 10.12.3

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: vmware_fusion
```

## Vagrant up output
https://gist.github.com/ultimateBusiness/8f4f1198107071b7b23e5b2431c0883a

**Comment by svpernova09** [comment]
Don't use `homestead up` We removed all but the `make` command. Use native vagrant commands instead. (this doesn't have anything to do with your issue)

The problem is VMware fusion *thinks* you don't have any available ports to be used. I've seen this happen when you have Virtualbox AND VMware installed on the same machine. I recommend you use one or the other, not both.

**Comment by ultimateBusiness** [comment]
I have made homestead as an alias, so my "homestead up" was a native "vagrant up" within the Homestead-directory.

I have deinstalled my Virtualbox-installation with the own uninstaller - restarted the system and still get the same error ;-(

```
$ vagrant up
Bringing machine 'homestead-7' up with 'vmware_fusion' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Verifying vmnet devices are healthy...
==> homestead-7: Preparing network adapters...
Vagrant found a port collision for the specified port and virtual machine.
While this port was marked to be auto-corrected, the ports in the
auto-correction range are all also used.

VM: homestead-7
Forwarded port: 80 => 8000
```

**Comment by ultimateBusiness** [comment]
my VMware Fusion version is: Professional Version 8.5.3 (4696910)

**Comment by svpernova09** [comment]
You may need to reinstall fusion as well. I ended up keeping Virtualbox on my main machine and removing fusion. and installing fusion onto a separate OS
