### ISSUE TITLE
vagrant up error - No live threads left. Deadlock? (fatal)

### ISSUE THREAD

**Issue by miloshdiklich** [laravel/homestead#459]
## Versions
  - Vagrant: 1.9.0
  - Provider: Virtualbox 5.1.14
  - Homestead: 1.1.0

## Host operating system
macOS Sierra 10.12.3

## Homestead.yaml
   ---
   ip: "192.168.10.10"
   memory: 2048
   cpus: 1
   provider: virtualbox
  
   authorize: ~/.ssh/id_rsa.pub
  
   keys:
     - ~/.ssh/id_rsa

 folders:
     - map: ~/www
       to: /home/vagrant/Code

 sites:
     - map: homestead.app
       to: /home/vagrant/Code/Laravel/public

 databases:
     - homestead

 blackfire:
     - id: foo
       token: bar
       client-id: foo
       client-token: bar

 ports:
     - send: 50000
       to: 5000
     - send: 7777
       to: 777
      protocol: udp
```

## Vagrant up output
https://gist.github.com/miloshdiklich/2f1c9180266086dca165785fc9c51fe0

**Comment by svpernova09** [comment]
Since you are failing so early in the process and Vi a Ruby error, my guess would be to reinstall the newest version of vagrant. If the error persists then reinstall virtualbox.

If the error persists after both of those steps post a gist of the output of $ vagrant up --debug &> vagrant.log

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by miloshdiklich** [comment]
I fixed it by completely removing both vagrant and virtualbox (not upgrading from current versions), but complete uninstall and then clean install the newest versions (Vagrant: 1.9.1 and VirtualBox: 5.1.14). 
Things to remove before installing the newest versions:

- rm -rf /opt/vagrant

- rm -f /usr/local/bin/vagrant

- rm -rf ~/.vagrant.d

- Uninstall VirtuaBox

- Remove VirtualBox VM's folder

Thanks @svpernova09
