### ISSUE TITLE
Include time syncing

### ISSUE THREAD

**Issue by alexdover** [laravel/homestead#463]
I've had it happen a couple of times where the virtual machine has gotten 5-15 minutes behind time and as a result things like OAuth fails because it checks token times.

To get around it I have installed ntp and run

    sudo ntpdate time.nist.gov

That seems to solve it. If the homestead box by default had ntp installed and synced the time that would help.

Thanks.

**Comment by svpernova09** [comment]
Thanks, I'll get this added to https://github.com/laravel/settler

**Comment by svpernova09** [comment]
Looks like

```
apt-get install -y ntpd
ntpd time.nist.gov
```

Should work?

**Comment by alexdover** [comment]
Awesome!

**Comment by ryancwalsh** [comment]
https://stackoverflow.com/a/48059114/470749 and https://askubuntu.com/a/256004/48214 were helpful for me.
