### ISSUE TITLE
Disable natdnshostresolver by default

### ISSUE THREAD

**Issue by rodymol123** [laravel/homestead#466]
Currently when using dns functions in PHP, you get a 
```[ErrorException] dns_get_record(): A temporary server error occurred.``` and the connection fails.

This has already been reported, referenced and tried to fix:
- https://github.com/laravel/framework/issues/14846
- https://github.com/laravel/homestead/pull/412
- https://github.com/laravel/homestead/issues/409

When manually editing the DNS server in ```/etc/resolv.conf``` to 8.8.8.8 the functions work, but as I learned reading the above pages I discovered the ```natdnshostresolver``` configuration.
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
natdnshostresolver: "off"
```

This also fixes the DNS issue, but isn't documented as far as I know. I suggest turning natdnshostresolver off by default or referencing it in the official documentation.

## Versions
  - Vagrant: Vagrant 1.8.7
  - Provider: Virtualbox 5.1.9 r111957

## Host operating system
Windows 10 Pro
```

**Comment by svpernova09** [comment]
Ah yes, I remember now. We wanted this on by default because we want Homestead to use the host's DNS by default (so you can easily map the fake domains via Host's hosts file).
