### ISSUE TITLE
Discussion: Why not set root as default credentials for ssh and mysql?

### ISSUE THREAD

**Issue by JesusLeon** [laravel/homestead#47]
Why not rely in using the _root_ user for the ssh and the _root:root_ for mysql? In a development environment this does not necessary represent a security threat, am I wrong?

Also, if this is intended to be "the default" development environment for Laravel-based (and perhaps other technologies) web applications, using the most common default values is more "default", precisely.

As an example, I had to commit a change on the DB config files for each of my existing projects in order to work on Homestead out-of-the-box. Otherwise, some more steps are required.

Thanks.

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
