### ISSUE TITLE
libvirt for Homestead?

### ISSUE THREAD

**Issue by obiwanakin** [laravel/homestead#478]
This isn't an issue, but I was wondering if it would be possible to include a `libvirt` provider for Homestead. I know there are `vmware_desktop`, `virtualbox`, and `parallels` providers, and a libvirt edition would be very nice.

**Comment by svpernova09** [comment]
is `libvert` a supported provider? Can you provide some links/docs on creating `libvirt` vagrant boxes? I've never used it, but happy to investigate if we can easily support it.

**Comment by obiwanakin** [comment]
@svpernova09 Cursory Google search shows [this](https://github.com/vagrant-libvirt/vagrant-libvirt) to be promising. You'll need a linux machine to build them.

**Comment by svpernova09** [comment]
I think we should hold off until there is more demand, or the provider matures a good bit. The QA matrix is a little troubling. (even though Ubuntu 16.04 is currently passing the release)

**Comment by j3j5** [comment]
I would love a `libvirt` edition as well, just to add my support for it! 😛

**Comment by mserralta** [comment]
Same here! We would like libvirt for laravel/homestead!!

**Comment by svpernova09** [comment]
Currently holding off until the provider matures. The QA matrix shows everything failing for Vagrant 1.9.1, and there hasn't been a commit in a little over a month.

**Comment by benddailey** [comment]
I would love to see this added as well. In the interim I was able to use [vagrant-mutate](https://github.com/sciurus/vagrant-mutate) to accomplish this. This assumes you have a hypervisor (probably kvm), libvirt and [vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) installed already.
~$ vagrant box add --provider virtualbox laravel/homestead
~$ vagrant plugin install vagrant-mutate
~$ vagrant mutate laravel/homestead libvirt
Then just set the provider to libvirt in you Homestead.yaml file then continue with the [homestead instructions](https://laravel.com/docs/5.5/homestead).

**Comment by jonasjuni** [comment]
thanks I'm using libvirt now!

**Comment by j3j5** [comment]
Thank you very much @benddailey , I am now using libvirt as well!!

**Comment by jafar690** [comment]
@benddailey you solution works, but am having syncing issues, might you know a fix?

**Comment by benddailey** [comment]
@jafar690 I am not sure what your issue with syncing is. I have moved away from using homestead and instead just run a virtual machine, with KVM and libvirt that matches my production linux installation and use SSH in VSCode. https://code.visualstudio.com/docs/remote/ssh. Hope that helps.

**Comment by pathros** [comment]
How do you install libvirt and start laravel homestead on Mac Apple Silicon M1?

**Comment by pathros** [comment]
How do you install libvirt and start laravel homestead on Mac Apple Silicon M1?

**Comment by tiffany-taylor** [comment]
I'm on Pop!_OS, if I `sudo apt install vagrant` it uninstalls Virtualbox, and if I `sudo apt install virtualbox`, it uninstalls Vagrant. Would love to see support for this.
