### ISSUE TITLE
[question] Custom php.ini or php settings on provision

### ISSUE THREAD

**Issue by rxstriker** [laravel/homestead#481]
Will it be added a feature in the near future that will allow us to use our own php.ini files or set our own php settings on provision, without creating a new custom box based on homestead?

**Comment by svpernova09** [comment]
You should be able to easily do this via `after.sh`. Is there something you're doing that wouldn't work there?

**Comment by rxstriker** [comment]
You are absolutely right, I didn't notice that after.sh was excluded from git.
Thank you very much for the fast response and help :D
