### ISSUE TITLE
JSON options for init and make commands

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#486]
* Add `json` flag to make command to use the JSON config stub instead of Yaml.
* Add `json` argument to `init.sh` and `init.bat` to use JSON config stub

**Comment by andrewhood125** [comment]
WDYT about dropping the json stub and running `Homestead.yaml` through yaml2json and using that? I'm happy to take this.

**Comment by svpernova09** [comment]
Since we're going to be doing this from PHP and from BASH / Batch I think it'd be easier to stick with stubs.

**Comment by svpernova09** [comment]
The `make` command is going to take some refactoring to support a JSON flag, mainly because we hardcoded the `.yaml` *everywhere*. (because who would ever use JSON  😇 )

Time to saddle up and pay down some tech debt on that I imagine.

**Comment by DojoGeekRA** [comment]
@svpernova09 i agree with you. I'm drafting a little bit on how we can tackle this in an elegant way and if no one comes with an idea before me i will push something very soon.

**Comment by svpernova09** [comment]
Sounds good.

Side note: Unless you find something broken that I haven't with the box I shared with you, I'm planning to release Homestead 5 and Settler 2 no earlier than March 1st.

**Comment by DojoGeekRA** [comment]
@svpernova09 great to know, thank you very much! I will keep you updated.

**Comment by svpernova09** [comment]
Resolved via #489
