### ISSUE TITLE
Can't "vagrant up" on a fresh instalation

### ISSUE THREAD

**Issue by TheoSl93** [laravel/homestead#497]
I have tried to install this box with vagrant, but it give me an error when trying to up the box, is seems that is a version issue. Vagrant and VirtualBox work fine. 

I installed first Vagrant, then I created the box, I downloaded the Homestead from the repository and I execute init.sh to generate the Homestead.yaml file. I got the error on the last step.

## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox 5.1.14 r112924 (Qt5.5.1)
  - Homestead: Last version downloaded from repository 1.10

## Host operating system
Linux 4.4.0-47 x64 | Ubuntu 16.04.2
## Homestead.yaml
```yaml: 
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
```

## Vagrant box list output
```
$ vagrant box list
laravel/homestead (virtualbox, 1.1.0)
```

## Vagrant up output
https://gist.github.com/TheoSl93/48454ba77915dda0023185f7edaad722

**Comment by svpernova09** [comment]
In the folder that you cloned Homestead to, then run `git checkout v4.0.5`. Then run `sh init.sh` again. Your config files will be in `~/.homestead`
