### ISSUE TITLE
connect to database

### ISSUE THREAD

**Issue by johannesfosseus** [laravel/homestead#5]
Hi

I cant connect to the databas from my app (works fine from sequel pro). See my app config, and error message. Guess I do miss something?

SQLSTATE[28000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)

'mysql' => array(
            'driver' => 'mysql',
            'host' => 'localhost',
            'database' => 'homestead',
            'username' => 'homestead',
            'password' => 'secret',
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
        ),

**Comment by mmfekri** [comment]
Migrate command (php artisan migrate) doesn't work when switch to localhost but app work well!

> Aha. Just tried changing 127.0.0.1 to localhost and it works. Is that a bug or did I read the docs wrong?
