### ISSUE TITLE
cURL, can't resolve CloudSearch endpoint

### ISSUE THREAD

**Issue by michaelaccenture** [laravel/homestead#50]
I use Guzzle\Http\Client to hit:

http://doc-{domain_name}-{domain_id}.us-east-1.cloudsearch.amazonaws.com/{api_version}/documents/batch

(6) could not resolve host, but if I hit the same url using Postman it succeeds.

I then tried basic curl request via command line:

curl {url}

I can hit almost any url, but not my CloudSearch endpoint.

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
