### ISSUE TITLE
Unable to mount shared folders on new installation

### ISSUE THREAD

**Issue by barryvanveen** [laravel/homestead#510]
## Versions
  - Vagrant 1.9.2
  - Virtualbox 5.1.16 r113841
  - Homestead 5.0.1

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: C:/Users/barry/.ssh/id_rsa.pub

keys:
    - C:/Users/barry/.ssh/id_rsa

folders:
    - map: C:/Users/barry/Documents/projects
      to: /home/vagrant/Code

sites:
    - map: barryvanveen.app
      to: /home/vagrant/Code/barryvanveen/public_html

databases:
    - barryvanveen
    - barryvanveen_testing

#variables:
#    - key: APP_ENV
#      value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

ports:
    - send: 80
      to: 80
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant up output
[https://gist.github.com/barryvanveen/24737ee26699af43fd4581e794394e95](https://gist.github.com/barryvanveen/24737ee26699af43fd4581e794394e95)

## Expected behavior
The VM should be provisioned but instead it produces an error because the shared folders can not be mounted.

## Actual behavior
Shared folders could not be mounted. Looking at the Virtualbox settings this makes sense because it lists these 2 paths:

1. \\?\C:\Users\barry\Documents\projects (named "home_vagrant_Code")
2. \\?\C:\Users\barry\Documents\Homestead (named "vagrant")

## Steps to reproduce
I'm running a clean installation, just downloaded and installed Vagrant, Virtualbox and laravel/homestead yesterday.

I've installed "vagrant plugin add vagrant-vbguest" (0.13.0) but this doesn't solve the error.

Also, I've tried fixing the paths to the shared folders and run "vagrant up --provision" again. This only seems to sort of postpone the problem. This time the provisioning also hits my after.sh script and processes that. At the end it tries to call a file on the VM, which isn't their because the mounting hasn't worked. 

The contents of after.sh and the output of "vagrant up --provision" are included in the gist linked above.

## References
I've looked around for similar problems but mostly there are old posts (2014, 2015) that try to solve the "vboxsf" problem. I guess that is fixed by manually renaming the shared folders since I don't get that error message again.

The problem is I don't a clue why the folders aren't mounted. I've logged into the VM using the Virtualbox interface. There is no /home/vagrant or /home/vagrant/Code folder that I can find.

Any help is very much appreciated! :)

Cheers,

Barry

**Comment by shanecash** [comment]
@barryvanveen Great write-up.

I'm experiencing the same issue with the same setup.

Unfortunately, other than confirming you're not the only one I don't have anything to add. To this point nothing I've tried has worked.

**Comment by svpernova09** [comment]
@barryvanveen 

I can confirm the behavior. I did a fresh install of Homestead & Virtualbox & Vagrant on Windows 10 and saw the same error.

I've just updated Virtualbox to the newest version (5.1.16 r113841) + Updated the extension. I'm about to build a new Virtualbox and I'll update here when it's ready for you to test.

**Comment by svpernova09** [comment]
I've confirmed it's not to do with the newest version of Virtualbox, I get the same error on a fresh built box.

**Comment by svpernova09** [comment]
@barryvanveen 

Looks like Virtualbox 5.1.16 is the culprit. Try downgrading to 5.1.14 (You can find the downloads here: https://www.virtualbox.org/wiki/Download_Old_Builds_5_1) and make sure you get that version of the extensions as well.

Tested on Windows 10 and that seems to be the issue.

**Comment by barryvanveen** [comment]
Thanks @svpernova09 for the quick replies! Unfortunately this doesn't solve my problems.

## What I did:
* uninstall Virtualbox 5.1.16
* install Virtualbox 5.1.14
* vagrant destroy && vagrant up

## What's the problem:
First problem is that the paths of the shared folders are still messed op. Virtualbox shows the as "\\\?\C:\Users\barry\Documents\Homestead". I manually fixed this in Virtualbox but the settings are off when you destroy and recreate the VM. 

After fixing these paths I run "vagrant up --provision" again but the folders are not mounted. There is a directory /home/vagrant/Code in the VM but it is mounted with errors. First it had no properties (ls -la listed all properties as ???). After changing the folder-type to "nfs" that is fixed but the folder is empty, which shouldn't be the case.

Also, there is no sign of the Homestead-folder that should also be shared to /home/vagrant. Looks like that shared folder is "empty" as well but because it is mounted on /home/vagrant it exists nevertheless.

## Questions
* Any idea why the Shared folders paths are messed up and do you think this is related to the folders not being mounted?
* Is there a way to get more debugging information about the mount errors? Since there is no clear error I find it hard to think of ways to solve this problem...

Thanks for any help!

**Comment by svpernova09** [comment]
The only other thing I can suggest is try changing your paths from `C:/Users/barry/Documents/projects` to `"C:\Users\barry\Documents\projects"`

Also map individual projects VS mapping an entire projects folder. so if you want to work on a project called "app" then map it's folder like this: `"C:\Users\barry\Documents\projects\app"`

**Comment by barryvanveen** [comment]
Thanks for your time @svpernova09!

I've got it working by downgrading to Virtualbox 5.1.10 and laravel/homestead 4.0.1. If it helps anyoneI can test some stuff out but otherwise I'm happy that I'm up and running again and can get to work.

**Comment by svpernova09** [comment]
Glad you got it working.

**Comment by nestormata** [comment]
I can confirm I had the same problem when upgrading to VirtualBox-5.1.16-113841-Win and worked just fine when I downgraded back to  VirtualBox-5.1.14-112924-Win.

Nestor

**Comment by jonnywilliamson** [comment]
Just wanted to add another confirmation that downgrading to Virtual box 5.1.14 from 5.1.16 fixes this issue, when using windows 10 as the host. The exact version I'm running now without issues is: 
Version 5.1.14 r112924 (Qt5.6.2)

Quick link to "older versions" of virtual box:
https://www.virtualbox.org/wiki/Download_Old_Builds_5_1 

Does anyone have a link etc to a bug report for virtual box before I try and create one?

**Comment by piotr-cz** [comment]
Same for me, nothing but downgrade of VirtualBox from v5.1.16 to v5.1.14 resolved issue. If anyone is interested in more information, see
- [Vagrant Issue](https://github.com/mitchellh/vagrant/issues/8352)
- [VirtualBox topic](https://forums.virtualbox.org/viewtopic.php?f=6&t=82165)
- [VirtualBox ticket](https://www.virtualbox.org/ticket/14651)

**Comment by Sbaughan** [comment]
I upgrade to VirtualBox 5.1.16 and the Homestead Environ stopped working. The file sharing via VirtualBox guest editions is failing in some way. 

I resolved this by downgrading to 5.1.14. Just install over the top of 5.1.16. :)

**Comment by amieiro** [comment]
This is a problem with the VirtualBox 5.1.16. I have updated the Virtual box to the latest release (5.1.18) and it mounts the shared folders. 

In my work machine (Windows 10 Professional) I have uninstalled VirtualBox, Vagrant and I have removed the Homestead folder (with a previous backup of the Homestead.yaml file) and the virtual machine files (available at C:\Users\my_user\VirtualBox VMs\).
I have reboot the machine.
Then I have installed the latest versions (VirtualBox 5.1.18, Vagrant 1.9.2), I have downloaded the box and I have cloned the latest Homestead repository (https://laravel.com/docs/5.4/homestead#first-steps). Then I have replaced the Homestead.yaml with the backup.

When I have executed "vagrant up", Vagrant have mounted the shared folders.

**Comment by BigSoftgr** [comment]
I was getting this "unable to mount" problem with the vagrant Homestead script (with newer VirtualBox version 5.1.22, Vagrant 1.9.5 but on Ubuntu 14.04). What I ended up doing and finally fixed was I opened up VirtualBox and defined the Shared Folders directly on there (right click on machine -> Shared Folders -> <define what you need> make permanent). Then restarted the machine normally by vagrant up and everything mounted fine this time.

**Comment by dlynch29** [comment]
I've got this issue on Windows 10 using WSL vagrant version 1.9.7 and Windows virtualbox 5.1.26

`ip: "192.168.10.10"
memory: 4096
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: c:\Users\Daniel Lynch\Documents\Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/wiki/public

databases:
    - homestead
`

In virtualbox this is the only shared folder listed:
`\\?\c:\Users\Daniel Lynch\Homestead`

Am I experiencing this same issue?

**Comment by svpernova09** [comment]
@dlynch29 

Make sure the first line in your Homestead.yaml is:
```
ip: "192.168.10.10"
```
Your paste has it on 2 lines, this won't be valid YAML. (likely not your issue)

This may be because you're trying to map a folder with a space in it. I've seen a lot of issues with it and I don't have a solution for it atm. Seems to be more of a Vagrant & Windows issue.

**Comment by dlynch29** [comment]
Yeah sorry, I think I might have messed up the pasted in content when trying to format the markdown. My first line is correct. 

I tried mapping it to `c:/Code` and `c:\Code` and I get the same result.

**Comment by svpernova09** [comment]
Try posting a new issue with all the requested info and such, I'll see if I can reproduce.

**Comment by sx0rp** [comment]
I think its Windows Defender. Try disabling it. Or use a firewall program that monitors more precisely like little snitch for mac does.

**Comment by jbreencp** [comment]
Encounter the same error every time I created a new project, but just resolved it. VM couldn't mount the new folders when I was running 'vagrant up --provision' from inside a shared folder.

Ran from homestead root and everything worked fine.

**Comment by svpernova09** [comment]
You should always run vagrant commands from the Homeastead root folder or project folder if you're using per project.

**Comment by bgarrison25** [comment]
I am running vagrant commands from the Homestead root folder and am still having this same issue. Tried all the above EXCEPT for downgrading.

**Comment by bgarrison25** [comment]
I am using version 5.2.12 btw

**Comment by amieiro** [comment]
Do you have the latest version of Virtualbox and Vagrant? Try disabling the firewall and other security suites

**Comment by ozanmuyes** [comment]
Hi everyone,

I'm on **Windows 7** and double quoting the map path and putting double backslashes instead of one solved the issue for me without downgrading. Here are the versions installed on my system;

* Vagrant 2.2.3
* Homestead 7.1.0
* VirtualBox 5.2.26

and here is my (shared) folder entry in `Homestead.yaml`;

```yml
---
ip: "192.168.10.10"
provider: virtualbox
# nothing important so far - just to emphasize beginning of a regular Homestead.yaml file
# snip

folders:
    - map: "D:\\Code"
      to: /home/vagrant/Code

# sites, databases etc.
```

Hope this helps to anyone has a problem.

PS: My firewall and other security suites (DEP etc.) is intact, I don't have any antivirus application installed.
