### ISSUE TITLE
[Proposal] Add possibility to install locales on first vagrant up

### ISSUE THREAD

**Issue by Amegatron** [laravel/homestead#52]
Hi!

I'm using Russian locale in PHP, and after any vagrant destroy / up I have to manually add russian locales to ubuntu. Still its a rare situation though, when I need to destroy the box.

Is it possible to have a feature in future to somehow automate this process e.g. by means of Homestead.yaml ?

As a workaround, theoretically, I can add a bash-script to do this for me by issuing a single command, but I'm not good at scripting yet.

```
sudo locale-gen ru_RU
sudo locale-gen ru_RU.UTF-8
```

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
