### ISSUE TITLE
Homestead will not install for either VirtualBox or VMWare on Windows 10

### ISSUE THREAD

**Issue by iviam** [laravel/homestead#543]
Hi

I have been trying to install Laravel Homestead for a week or 2 now and it still fails for me.

I have read several other issues (in the issues list here), and other peoples bug posts to try to address the problem and none of the suggested fixes have solved it for me. I have tried many different version combinations  of the tools involved as recommended in other threads but none of them will work for me.

## Versions
Laravel Homestead Git Branch: v5.2.1
Laravel Homstead: 2.1.0
Vagrant: 1.9.2
vagrant plugin list:
vagrant-share (1.1.7)
  - Version Constraint: > 0
vagrant-vbguest (0.13.0)
vagrant-vmware-workstation (4.0.18)
VirtualBox: Version 5.1.18 r114002 (Qt5.6.2)
VMware® Workstation 12 Pro: 12.5.5 build-5234757

## Host operating system
Windows 10 Home
	Version 1607
	OS Build 14393.1066

I have tried installing Homestead for both VMWare and also for VirtualBox, with not luck.

Regarding trying to install it for VMWare:

## Steps to reproduce
1.I have followed the guide here exactly but with 2 small changes: https://laravel.com/docs/5.4/homestead
2. The provider in the yaml file I changed to: vmware_workstation (as per instructions in the guide).
3. I changed the ip to: 192.168.11.10, if I do not change this value I get this error:
vagrant up
Bringing machine 'homestead-7' up with 'vmware_workstation' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Verifying vmnet devices are healthy...
The host only network with the IP '192.168.10.10' would collide with
another device 'VirtualBox Host-Only Network #4'. This means that VMware cannot create
a proper networking device to route to your VM. Please choose

In the end the Homstead.yaml looks like:
## Homestead.yaml
---
ip: "192.168.11.10"
memory: 2048
cpus: 1
provider: vmware_workstation

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

When I run “vagrant up” I get this output:
## Vagrant up output
vagrant up
Bringing machine 'homestead-7' up with 'vmware_workstation' provider...
==> homestead-7: Cloning VMware VM: 'laravel/homestead'. This can take some time        ...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Verifying vmnet devices are healthy...
==> homestead-7: Preparing network adapters...
WARNING: The VMX file for this box contains a setting that is automatically over        written by Vagrant
WARNING: when started. Vagrant will stop overwriting this setting in an upcoming         release which may
WARNING: prevent proper networking setup. Below is the detected VMX setting:
WARNING:
WARNING:   ethernet0.pcislotnumber = "32"
WARNING:
WARNING: If networking fails to properly configure, it may require this VMX sett        ing. It can be manually
WARNING: applied via the Vagrantfile:
WARNING:
WARNING:   Vagrant.configure(2) do |config|
WARNING:     config.vm.provider :vmare_workstation do |vmware|
WARNING:       vmware.vmx["ethernet0.pcislotnumber"] = "32"
WARNING:     end
WARNING:   end
==> homestead-7: Starting the VMware VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 192.168.80.129:22
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7:
    homestead-7: Vagrant insecure key detected. Vagrant will automatically repla        ce
    homestead-7: this with a newly generated keypair for better security.
    homestead-7:
    homestead-7: Inserting generated public key within guest...
    homestead-7: Removing insecure key from the guest if it's present...
    homestead-7: Key inserted! Disconnecting and reconnecting using new SSH key.        ..
==> homestead-7: Machine booted and ready!
==> homestead-7: Forwarding ports...
    homestead-7: -- 80 => 8000
    homestead-7: -- 443 => 44300
    homestead-7: -- 3306 => 33060
    homestead-7: -- 5432 => 54320
    homestead-7: -- 8025 => 8025
    homestead-7: -- 27017 => 27017
    homestead-7: -- 22 => 2222
==> homestead-7: Setting hostname...
==> homestead-7: Configuring network adapters within the VM...
==> homestead-7: Waiting for HGFS to become available...
==> homestead-7: Enabling and configuring shared folders...
    homestead-7: -- C:/cygwin64/home/Will/Homestead: /vagrant
==> homestead-7: Running provisioner: file...
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7:
==> homestead-7: ssh-rsa redacted
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Unable to mount one of your folders. Please check your folders         in Homestead.yaml
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: C:/cygwin64/tmp/vagrant-shell20170415-17528-ioa0j4.sh
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Certificate: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Site: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Restarting Nginx
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating MySQL Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Postgres Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Clear Variables
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Update Composer
==> homestead-7: You are already using composer version 1.4.1 (stable channel).
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: C:/cygwin64/tmp/vagrant-shell20170415-17528-15ozqvy.sh

The noteworthy line appears to be: Unable to mount one of your folders. Please check your folders         in Homestead.yaml

Those these lines may also be of interest:

WARNING: The VMX file for this box contains a setting that is automatically over        written by Vagrant
WARNING: when started. Vagrant will stop overwriting this setting in an upcoming         release which may
WARNING: prevent proper networking setup. Below is the detected VMX setting:
WARNING:
WARNING:   ethernet0.pcislotnumber = "32"
WARNING:
WARNING: If networking fails to properly configure, it may require this VMX sett        ing. It can be manually
WARNING: applied via the Vagrantfile:
WARNING:
WARNING:   Vagrant.configure(2) do |config|
WARNING:     config.vm.provider :vmare_workstation do |vmware|
WARNING:       vmware.vmx["ethernet0.pcislotnumber"] = "32"
WARNING:     end
WARNING:   end

## Expected behavior
There would be a shared Code folder in the host and the guest and going to homestead.app in a browser would display some content.

## Actual behavior
After the command finishes, there is no “Code” folder in either the guest or the host and the url of “homestead.app” returns: “No input file specified.”

Regarding trying to install it for VirtualBox:

## Steps to reproduce
1. Installing it for VirtualBox requires no deviation from the guide at all. I simply run through the steps here exactly: https://laravel.com/docs/5.4/homestead

In the end the Homstead.yaml looks like:
## Homestead.yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

When I run “vagrant up” I get the following output (note I fixed this output already -- see below):
## Vagrant up output
vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Importing base box 'laravel/homestead'...
Progress: 40%There was an error while executing `VBoxManage`, a CLI used by Vagr                                                               ant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "C:\\Users\\Will\\.vagrant.d\\boxes\\laravel-VAGRANTSLASH-ho                                                               mestead\\2.1.0\\virtualbox\\box.ovf", "--vsys", "0", "--vmname", "settler_defaul                                                               t_1491506934769_45171_1492216807654_76596", "--vsys", "0", "--unit", "9", "--dis                                                               k", "C:\\Users\\Will\\VirtualBox VMs\\settler_default_1491506934769_45171_149221                                                               6807654_76596\\box-disk001.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting C:\Users\Will\.vagrant.d\boxes\laravel-VAGRANTSLASH-homestead\2.1.0                                                               \virtualbox\box.ovf...
OK.
0%...10%...20%...30%...40%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the imported medium 'C:\Users\Will\Virtu                                                               alBox VMs\settler_default_1491506934769_45171_1492216807654_76596\box-disk001.vm                                                               dk'.
VBoxManage.exe: error: VMDK: cannot write allocated data block in 'C:\Users\Will                                                               \VirtualBox VMs\settler_default_1491506934769_45171_1492216807654_76596\box-disk                                                               001.vmdk' (VERR_DISK_FULL)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component A                                                               pplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(s                                                               truct HandlerArg *)" at line 886 of file VBoxManageAppliance.cpp

This output was new after switching to trying to use VMWare. So I removed the boxes from Vagrant, reinstalled them (vagrant box add laravel/homestead) and then ran “vagrant up” again. This time the output is:

## Vagrant up output
vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Importing base box 'laravel/homestead'...
==> homestead-7: Matching MAC address for NAT networking...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Setting the name of the VM: homestead-7
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7:
    homestead-7: Vagrant insecure key detected. Vagrant will automatically replace
    homestead-7: this with a newly generated keypair for better security.
    homestead-7:
    homestead-7: Inserting generated public key within guest...
    homestead-7: Removing insecure key from the guest if it's present...
    homestead-7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead-7: Machine booted and ready!
[homestead-7] GuestAdditions 5.1.18 running --- OK.
==> homestead-7: Checking for guest additions in VM...
==> homestead-7: Setting hostname...
==> homestead-7: Configuring and enabling network interfaces...
==> homestead-7: Mounting shared folders...
    homestead-7: /vagrant => C:/cygwin64/home/Will/Homestead
==> homestead-7: Running provisioner: file...
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7:
==> homestead-7: ssh-rsa redacted
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Unable to mount one of your folders. Please check your folders in Homestead.yaml
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: C:/cygwin64/tmp/vagrant-shell20170415-9468-1uc6dxf.sh
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Certificate: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Site: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Restarting Nginx
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating MySQL Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Postgres Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Clear Variables
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Update Composer
==> homestead-7: You are already using composer version 1.4.1 (stable channel).
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: C:/cygwin64/tmp/vagrant-shell20170415-9468-1wjn4dn.sh

The noteworthy part appears to be: Unable to mount one of your folders. Please check your folders in Homestead.yaml

## Expected behavior
There would be a shared Code folder in the host and the guest and going to homestead.app in a browser would display some content.

## Actual behavior
There is still no code folder, and going to homstead.app still says: “No input file specified.”

I am at my wits end here trying to figure out how to get this to install.

Any advice would be very appreciated. 

All the best

Will Ferrer

**Comment by iviam** [comment]
This is solved. I had assumed the problem had to do with versions of the software used, and not the guide (since other posts I found all complained that different versions of the software involved was the culprit).

I decided to stop following the guide exactly to see if I could resolve the issue on my own.

When I started trying to solve myself the problem myself it turned out to be very simple -- the guide does not tell you to create the Code directory on your host machine. I had assumed that meant it would be created for you if the Vagrant command was working properly.

I recommend adding a step to the guide so it's clear that Vagrant isn't going to make the host director for you.

All the best

Will

**Comment by svpernova09** [comment]
Glad you got it sorted out!

**Comment by Nadeemdeema** [comment]
$ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Checking if box 'laravel/homestead' version '9.5.1' is up to date...
==> homestead: Clearing any previously set forwarded ports...
==> homestead: Clearing any previously set network interfaces...
==> homestead: Preparing network interfaces based on configuration...
    homestead: Adapter 1: nat
    homestead: Adapter 2: hostonly
==> homestead: Forwarding ports...
    homestead: 80 (guest) => 8000 (host) (adapter 1)
    homestead: 443 (guest) => 44300 (host) (adapter 1)
    homestead: 3306 (guest) => 33060 (host) (adapter 1)
    homestead: 4040 (guest) => 4040 (host) (adapter 1)
    homestead: 5432 (guest) => 54320 (host) (adapter 1)
    homestead: 8025 (guest) => 8025 (host) (adapter 1)
    homestead: 9600 (guest) => 9600 (host) (adapter 1)
    homestead: 27017 (guest) => 27017 (host) (adapter 1)
    homestead: 22 (guest) => 2222 (host) (adapter 1)
==> homestead: Running 'pre-boot' VM customizations...
==> homestead: Booting VM...
==> homestead: Waiting for machine to boot. This may take a few minutes...
    homestead: SSH address: 127.0.0.1:2222
    homestead: SSH username: vagrant
    homestead: SSH auth method: private key
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'paused' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
