### ISSUE TITLE
xdebug cli alias

### ISSUE THREAD

**Issue by tomcastleman** [laravel/homestead#544]
Hi there,

Would users find value in having a standard alias for running php with xdebug configured and enabled from the cli which works with PHPStorm out the box?:

```bash
function xdebug() {
    (php -m | grep -q xdebug)
    if [[ $? -eq 0 ]]
    then
        XDEBUG_ENABLED=true
    else
        XDEBUG_ENABLED=false
    fi

    if ! $XDEBUG_ENABLED; then xon; fi

    php \
        -dxdebug.remote_enable=1 \
        -dxdebug.remote_host=10.0.2.2 \
        -dxdebug.remote_autostart=1 \
        "$@"

    if ! $XDEBUG_ENABLED; then xoff; fi
}
```
I have included only the xdebug settings we need to override from default.

This could be used as follows:

`$ xdebug artisan foo`

This works with PHPStorm with zero configuration.

**Comment by svpernova09** [comment]
Curious what others think, I don't have a preference. Is this solving the problem where people just aren't aware of the existing aliases to toggle xdebug on the command line? If so we just make mention in the docs to raise awareness rather than adding another alias.

**Comment by tomcastleman** [comment]
Followed up with #545
