### ISSUE TITLE
SSL Intermediate Certificate

### ISSUE THREAD

**Issue by pablopaul** [laravel/homestead#558]
I am in a situation where streaming MP3 in Homestead over SSL does not work in mobile Safari(without SSL it works) and on the live server (Lets Encrypt Cert) it is also working.

Does the SSL Certificate which comes with Homestead includes an intermediate certificate?

**Comment by svpernova09** [comment]
No, it's just a generic self signed cert. Because there is no trusted root verifying the cert there is no intermediate.

**Comment by pablopaul** [comment]
@svpernova09 can you give me a quick heads how you would get a cert with intermediate into a Homestead box? 

Is that for interest for the whole project (as I pointed out, very nasty mobile Safari security feature) and something you would integrate or not?

**Comment by svpernova09** [comment]
I'm not entirely sure. This *may* be relevant: http://stackoverflow.com/questions/26759550/how-to-create-own-self-signed-root-certificate-and-intermediate-ca-to-be-importe

I don't *think* this is something we'd want for Homestead but I'm happy to be proven wrong if we can find an unobtrusive implementation.
