### ISSUE TITLE
Aliases should *always* be copied over

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#559]
In the per project installation default method the user does *not* get the `aliases` file copied over. This can be confusing when reading the documentation about some of the shortcut commands that have been added.

TODO:
* The Homestead `make` command should always copy `aliases` and `after.sh` if it doesn't exist. It should never overwrite
* The Homestead `make` option for `aliases` should be changed to `--no-aliases` and not copy the file `aliases` if used
* The Homestead `make` option for `after` should be changed to `--no-after` and not copy the file `after.sh` if used
* Update/Add tests to verify new functionality

**Comment by svpernova09** [comment]
We should probably think about making `after.sh` always copy over as well.

**Comment by sergeyklay** [comment]
Yeah, good catch. We did this already https://github.com/phalcon/box/blob/master/src/aliases.rb

**Comment by ConnorVG** [comment]
The regression from this would probably piss me off, honestly.

**Comment by svpernova09** [comment]
@ConnorVG What regression? If you have an existing `aliases` file in the project root, the `make` command would not overwrite it. If the `make` command is overwriting any files (except in some cases `Homestead.yaml`) that's probably a bug.

**Comment by ConnorVG** [comment]
The regression is changed behaviour that alters the environment of the VM. What do you mean "What regression?" – we're literally asking here to implement a _change to behaviour_ that _mutates the vm environment_.

Regression is integral to this 'issue'.

**Comment by svpernova09** [comment]
This change will only affect users who are using the per project installation method. The implementation should not overwrite existing files so the is no way to break a user's current working version on upgrade or subsequent runs of the `make` command.

I don't understand what part will "piss" you off, can you help me understand?

**Comment by ConnorVG** [comment]
Per-project installation is very common (especially in the work places I have been in).

This is a regression issue as every new installation from this change on-wards would add a new `aliases` set to my box – which will add / change functionality based on what I'm used to.

>This **change** will only **affect** users 

See: "Regression".

**Comment by svpernova09** [comment]
So you have a problem that every new install would have these files that the previous versions wouldn't. I can see that being annoying.

The way around that would be to `composer update laravel/homestead` on each of those projects and re-run the `make` command to generate the missing files (if desired). Alternatively you could just delete the files after the make command ran if you didn't want them.

Probably a better scenario would be to reverse the current flags: `--aliases --after` to `--no-aliases --no-after` where the default behavior would be to create the files, but give the user an easy override to not even generate them.

Thanks for the feedback.

**Comment by svpernova09** [comment]
Updated OP with new requirements.

**Comment by DojoGeekRA** [comment]
@svpernova09 i'm kind of busy right now, but if no one takes the shoot, i will happily implement this on the weekend.

**Comment by svpernova09** [comment]
Resolved via #564

**Comment by svpernova09** [comment]
This has now been tagged https://github.com/laravel/homestead/releases/tag/v5.3.0

Note the default behavior is the `after.sh` and `aliases` will be copied over via the make command.

To prevent this behavior use the `no-after` and/or `no-aliases` flags.
