### ISSUE TITLE
[Proposal] Define multiple databases in Homestead.yaml

### ISSUE THREAD

**Issue by codeguy** [laravel/homestead#57]
Let me define multiple databases (users, passwords, database names) in Homestead.yaml. On `vagrant up`, you can use an inline provisioner to execute a custom bash script (much like you do with `serve.sh` now). This script will check to see if each database exists, and if not, create it and the specified user/password.

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
