### ISSUE TITLE
Serve aliases broken on per project installs

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#574]
the `serve`* aliases from the `aliases` files point to `scripts/...` files that don't exist in that path on per project installs, they would exist at `vendor/laravel/homestead/scripts/...`.

Maybe the `make` command should do some find & replace on the aliases file that fixes this, or just like we have with a `resources/LocalizedVagrantfile` we localize the aliases file with the static paths already set.

/cc @DojoGeekRA, @thecrypticace

**Comment by DojoGeekRA** [comment]
The file duplication definitely will be a pain to maintain and we have already forgot to update the `LocalizedVagrantfile` a couple of times, that's something that could happen to the `LocalizedAliases` and to `LocalizedXFiles`.

I agree that the `make` command should prepare the files to `per-project` installations and if it is done correctly, we can get rid of the `LocalizedVagrantfile`.

**Comment by DojoGeekRA** [comment]
@svpernova09 if no one takes the shoot or comes with a better idea, i can work on this over the weekend.

**Comment by svpernova09** [comment]
No rush at all.

One thing I want to avoid over-engineering a solution for this. If it's cleaner to keep separate files that's great. If we can implement changes in the make command that we can test and verify, without increasing overall complexity, that's even better.

**Comment by DojoGeekRA** [comment]
Yeah, you're right, let's keep it simple then and use separate files. Let's modify the `make` command to use those when appropriate.
