### ISSUE TITLE
Completely disable USB forward

### ISSUE THREAD

**Issue by pablopaul** [laravel/homestead#579]
When I plug my iPhone into USB to debug mobile Safari via Desktop Safari the device is just for some time available, after that, it disappears from Safari menu. 

I guess that the USB device gets forwarded to my Homestead box, even if VirtualBox GUI says "USB deactivated". When I shut down the box, the device does not disappear from Safari menu.

Any idea how to completely disable the USB forward to the Homestead box?

**Comment by svpernova09** [comment]
Unable to reproduce this with the following versions:

Homestead: v5.3.2
Virtualbox: Version 5.1.18 r114002 (Qt5.6.2)
Vagrant: 1.9.5

Please open a new issue with the and fill out the template including versions and replication instructions.
