### ISSUE TITLE
Homestead VM Public Key

### ISSUE THREAD

**Issue by codeguy** [laravel/homestead#58]
I see `~/.ssh/id_rsa`, but I don't see `~/.ssh/id_rsa.pub`. Is this expected behavior? I would like to have Homestead generate its own public/private key-pair so that I can setup communciation between Homestead VM and remote servers (in my case, for `drush` usage on Drupal sites).

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
