### ISSUE TITLE
Command "init" is not defined.

### ISSUE THREAD

**Issue by onlyshow** [laravel/homestead#587]
## Versions
  - Vagrant: Vagrant 1.9.5.
  - Provider: Virtualbox 版本 5.1.22 r115126 (Qt5.6.2).
  - Homestead: Laravel Homestead 5.3.2.

not use ```homestead init```
[refer to](http://laravelcoding.com/blog/laravel-5-beauty-setting-up-a-windows-machine)

**Comment by svpernova09** [comment]
I think you are trying to initialize homestead?Run the script 'init.sh'

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by onlyshow** [comment]
yes.Thank you very much!
