### ISSUE TITLE
CouchDB

### ISSUE THREAD

**Issue by JulioECastro** [laravel/homestead#590]
Any plan to include couchdb database similar to mongodb scripts?

**Comment by svpernova09** [comment]
If it's implemented in the same way as mongo I'm open to a PR

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by JulioECastro** [comment]
Ok, I will send you my code.

El 8 jun. 2017, a las 07:42, Joe Ferguson <notifications@github.com<mailto:notifications@github.com>> escribió:

If it's implemented in the same way as mongo I'm open to a PR

--
- Joe Ferguson
JoeFerguson.me<http://JoeFerguson.me>
MemphisPHP.org<http://MemphisPHP.org>
