### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jericopulvera** [laravel/homestead#598]
I updated my homestead to the latest release. and when I seed a large amount of data I started getting this error 
> segmentation fault (core dumped)

it's working before

**Comment by svpernova09** [comment]
No way of debugging this with such little info. Try seedling less data per seeder and run them multiple times? Might be running out of memory (but I'd expect a memory error).

May have to go inspect the core dump to see what happened.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by jericopulvera** [comment]
it work's when seeding less data. 
how do I see that core dump you're talking about?

**Comment by svpernova09** [comment]
Check out: https://ma.ttias.be/generate-php-core-dumps-segfaults-php-fpm/

**Comment by blacktrue** [comment]
@jericopulvera 
Did you solve it?

**Comment by jericopulvera** [comment]
@blacktrue turns out its a problem with vagrant latest version. I downgraded vagrant then it started working properly
