### ISSUE TITLE
Homestead on libvirt (kvm)

### ISSUE THREAD

**Issue by at-dmin** [laravel/homestead#607]
Hi,
I've written a post on laracasts.com on how to make the Homestead box work on libvirt (kvm)
https://laracasts.com/discuss/channels/laravel/howto-homestead-on-libvirt-kvm

Hoping this may inspire you :-)
In case of any questions, just let me know..

Thanks for a great piece of software.
Cheers

**Comment by svpernova09** [comment]
Thanks will check it out

**Comment by antimech** [comment]
@svpernova09 any updates on this topic?
