### ISSUE TITLE
Add CORS to apache

### ISSUE THREAD

**Issue by leandroruel** [laravel/homestead#614]
i'm not sure if i can request it here, but since every developer working with laravel + homestead are building apis or whatever, would be good set the apache header:
``` Header set Access-Control-Allow-Origin "*" ```
as explained here: https://enable-cors.org/server_apache.html
this will be a time saver for us

**Comment by svpernova09** [comment]
Hi, This is the right place to bring up such an issue.

if there's enough demand I'm all for it. Anyone who would like to see this can feel free to chime in. 

At the moment this can be done via the `after.sh` script (Which is executed after your apache host is setup and configured)

**Comment by iaK** [comment]
+1

**Comment by CaddyDz** [comment]
+1

**Comment by ipa1981** [comment]
+1

**Comment by MerrySean** [comment]
Any news about this? I'm trying to make this work with Nginx but it's really hard when everybody is saying that `If` is Evil inside the location block.
