### ISSUE TITLE
Additional NGINX config for `elgg` sites

### ISSUE THREAD

**Issue by hypeJunction** [laravel/homestead#615]
I am not sure if you accept additional configs, but I would be happy to make a PR:
https://gist.github.com/hypeJunction/846a3ebab798df83f35897e3e6b8eb26

**Comment by svpernova09** [comment]
Sure, drop it in the `scripts` folder and name it `serve-elgg.sh` and then you'll be able to use the site type `elgg`

**Comment by hypeJunction** [comment]
That's what I am doing. Do you want it as part of homestead /scripts directory? It's for https://github.com/elgg/elgg

**Comment by svpernova09** [comment]
Yep, it needs to be in the `scripts` folder to work as a site type
