### ISSUE TITLE
Improvement request - FlywayDB

### ISSUE THREAD

**Issue by davispeixoto** [laravel/homestead#618]
Hi all,

I'd like to see the [flywaydb](https://flywaydb.org/) into Homestead box.
Laravel seeding and migration are good, but when using homestead to develop to another frameworks, or independent libraries, it would be nice to count with this independent tool. So I'm asking this improvement for you.

Thank you and keep up with the great job!

**Comment by svpernova09** [comment]
Not seeing a clear install path, is this just a binary we'll add to the global path, or something else? Hard to tell if this is something you should bind to your application, or to your dev environment

**Comment by davispeixoto** [comment]
@svpernova09 , this is the same thing as ask if composer should be installed per project or globally. You can do it both ways. My suggestion is to install it globally (the cli version, without jre once homestead already comes with it).

Thus, on any project we would be able to:
1. Add a flyway.conf file on project root
2. Add directory migrations on project root
3. Add migration files (plain sql) inside it

A couple of links to help out:
https://flywaydb.org/documentation/commandline/
https://stackoverflow.com/questions/27916695/how-to-install-the-flyway-cli-globally-not-a-java-project

**Comment by davispeixoto** [comment]
Another insteresting point is to already add the JDBC drivers to the database you provide with homestead.

**Comment by svpernova09** [comment]
Gotcha. I'll have a look at those links. Thanks.

**Comment by svpernova09** [comment]
Will be in the next release of the Base box (likely later this month or early September)

**Comment by davispeixoto** [comment]
Thank you very much @svpernova09 . Keep up with the great work guys!

**Comment by svpernova09** [comment]
This has been released in the new base box: https://github.com/laravel/settler/releases/tag/v3.1.0
