### ISSUE TITLE
composer ^5.4 lost

### ISSUE THREAD

**Issue by artemsky** [laravel/homestead#619]
Whats wrong with `composer require laravel/homestead --dev`

Laravel 5.4

CLI Output
```bash
[InvalidArgumentException]
  Could not find package laravel/homestead at any version for your minimum-stability (stable). Check the package spel
  ling or your minimum-stability

```

And there is no 5+ branch  https://packagist.org/packages/laravel/homestead

**Comment by svpernova09** [comment]
Odd, the only thing I did earlier this morning was add a new test branch. I've just removed it, we'll give it a few minutes to see what happened on packagist fixes itself.

**Comment by artemsky** [comment]
nice, 5+ branch again there. thx.

**Comment by svpernova09** [comment]
Wow, that's odd. So sorry about that!
