### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by AdrianKuriata** [laravel/homestead#628]
## Versions
  - Vagrant: 1.9.7
  - Provider: 5.1.26 r117224
  - Homestead: laravel/homestead (virtualbox, 3.0.0)

## Host operating system
Fedora 26

## Homestead.yaml
[https://gist.github.com/AdrianKuriata/f35e009a5103a591aeebea2f202b3419](https://gist.github.com/AdrianKuriata/f35e009a5103a591aeebea2f202b3419)

## Vagrant up output
[https://gist.github.com/AdrianKuriata/c4b6e5cbe466f5349a1cb7e99014a196](https://gist.github.com/AdrianKuriata/c4b6e5cbe466f5349a1cb7e99014a196)

## Expected behavior
Page should be loaded.

## Actual behavior
Page is not loaded, i getting error `ERR_CONNECTION_REFUSED`. When i pinging page, everything is ok. Vagrant working normally. In Friday everything worked normally, after weekend i came to work, update system with VirtualBox and i can't access to pages. When i set in `/etc/hosts` for domain `127.0.0.1` everythink working with `8000 port.` After login to `vagrant ssh` and put `ifconfig` command i don't see `vboxnet0`. I reinstalled vagrant with destroy. I removed vagrant and VirtualBox and installed clear but this not helped me. This is really annoying, could you help me with that?

## Steps to reproduce
1. vagrant up.
2. Go to your page.
3. Get an error `ERR_CONNECTION_REFUSED`.

**Comment by svpernova09** [comment]
Try downgrading Virtualbox to the previous version. I've seen a lot of weirdness lately about Virtualbox not playing nice with connections.

**Comment by AdrianKuriata** [comment]
@svpernova09 Hi, i did it but still not working. I destroyed machine, reinstalled, i think i will need reinstall system and install it with fresh fedora...

**Comment by AdrianKuriata** [comment]
Any ideas?

**Comment by svpernova09** [comment]
I'm willing to bet it's a Fedora issue. I'll see if I can get 26 running on a local machine to reproduce the issue.

In the meantime please check this issue https://github.com/laravel/homestead/issues/534 and see if this is possibly related.

**Comment by svpernova09** [comment]
I'm unable to reproduce this.

* Fedora 26
* Virtualbox 5.1.26 r117224
* Vagrant 1.9.7

Vagrant up:

```
[halo@localhost homestead]$ vagrant destroy -f && vagrant up
==> homestead-7: Forcing shutdown of VM...
==> homestead-7: Destroying VM and associated drives...
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Importing base box 'laravel/homestead'...
==> homestead-7: Matching MAC address for NAT networking...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Setting the name of the VM: homestead-7
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7:
    homestead-7: Vagrant insecure key detected. Vagrant will automatically replace
    homestead-7: this with a newly generated keypair for better security.
    homestead-7:
    homestead-7: Inserting generated public key within guest...
    homestead-7: Removing insecure key from the guest if it's present...
    homestead-7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead-7: Machine booted and ready!
==> homestead-7: Checking for guest additions in VM...
==> homestead-7: Setting hostname...
==> homestead-7: Configuring and enabling network interfaces...
==> homestead-7: Mounting shared folders...
    homestead-7: /vagrant => /home/halo/homestead
    homestead-7: /home/vagrant/qs => /home/halo/quickstart-basic-5.3
==> homestead-7: Running provisioner: file...
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7:
==> homestead-7: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyPaigrObYNgiVNZPTH0GCQYpIOsUI5EOf+Ve1iK7rz32qy74eCojqwGmKMIU/Hdd6UxnTI/OzgOMBQaxS5UjBSZUKYzMz1dLRZe2Orqig5Ygm0fTGEEFWoFuQzHpSKGi6GeKI11d+JcRXiD7fBtROpu15xK49r3JTt2sEY/2srFpmzQbf3qchgh9qEOht5FLI9YBg8IIsSXsygnG8mJ/AEfP3NoHCKX8EBY61QQPB6jhPxYOFgr/sYyqcHGdZgtK7oPMkPn+aCDkAXLNR2Vdikfxg3czHxygLZB6qrpt5NL+VF+1O+g4TcfAcuShiIsBZXkwvx5Na4uBXQMQyf2WR halo@localhost.localdomain
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: /tmp/vagrant-shell20170804-24568-kwoxwh.sh
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Certificate: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Site: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Checking for old Schedule
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Certificate: homestead2.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Site: homestead2.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Checking for old Schedule
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Restarting Nginx
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating MySQL Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Postgres Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Clear Variables
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Update Composer
==> homestead-7: You are already using composer version 1.4.2 (stable channel).
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: /tmp/vagrant-shell20170804-24568-1toz1fb.sh
[halo@localhost homestead]$ vagrant ssh
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-81-generic x86_64)
 
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
 
3 packages can be updated.
0 updates are security updates.
```

Try doing a `vagrant destroy && vagrant up` and posting the entire output (the output in the original report is without any provisioning)

Unfortunately unless we can find a way to reproduce this there isn't anything we can do.

**Comment by AdrianKuriata** [comment]
@svpernova09 
I forgot to say, problems started on Fedora 24. I will show you logs from running vagrant in the Monday when i will be in work. But from what you show, my logs look exacly the same like yours after destroy machine.

With net-tools, i installed it but this not helped me. I mean you ran homestead on Fedora 26 and everything working?

**Comment by svpernova09** [comment]
I did a fresh install of Fedora 26. The only thing out of the ordinary was I had to use dnf to install the kernel devel packages but other than that everything was fine.

**Comment by AdrianKuriata** [comment]
So i will try on the Monday probably install fresh Fedora 26... I will give
you response.

05.08.2017 6:58 PM "Joe Ferguson" <notifications@github.com> napisał(a):

**Comment by AdrianKuriata** [comment]
@svpernova09 Awesome, after reinstall Fedora everything working really good!
