### ISSUE TITLE
MariaDB fails every restart (apparmor)

### ISSUE THREAD

**Issue by jordanramstad** [laravel/homestead#629]
This I noticed since back in Homestead 4.0 but just kind of dealt with it since it did not seem to happen in every app I have worked with and could not diagnose the actual cause until today.

Ubuntu AppArmor can cause mariadb to fail to restart with very little information, took a lot of digging for me to even notice that there was a denial from apparrmor.

Also a misleading piece is the profile for mariadb states it disables apparmor from running on itself.

I use Windows and tried Vagrant 1.9.2+ and both VMware and Virtualbox to get around this issue, neither worked, considering that it should be reproducible on macs as well.

Anyway after knowing what it is I did figure out a fix, by adding the following to my `after.sh` file
```
sudo service apparmor stop
sudo service apparmor teardown
sudo update-rc.d -f apparmor remove
```
This removes it entirely, for my purposes I see no problem with that, but there could be arguments against it.

https://bugs.launchpad.net/ubuntu/+source/mysql-5.7/+bug/1610765
Is where i noticed the bug.

https://support.plesk.com/hc/en-us/articles/213909965-How-to-disable-AppArmor-
helped me figure out how to remove it.

**Comment by svpernova09** [comment]
Thanks for the report. I saw something about this in relation to another issue but never got around to tracking it down.

I'm hesitant to say "lets just disable apparmor cause it's a dev environment" but I think we should see if this is going to be a long lasting MariaDB issue. If so maybe we remove apparmor before we install maria, that way only those users would be affected.

**Comment by svpernova09** [comment]
Closing for now, if this bug sticks around we'll implement ^

**Comment by jordanramstad** [comment]
Yea I figured this was something that removing app armor by force was not the best idea, but at least it has a solution to get around it if it plagues anyone for now.

Seems to be a bug in ubuntu based on the issue report I listed, but its one of those discussions that never end and never reach a resolution kind of issue since it seems specific to certain use cases....

Another solution might be implementing proper rules for apparmor, mariadb has a default that is just a comment saying that mariadb avoids apparmor unless you add anything to that file, clearly something can prevent that from working.

**Comment by kmark** [comment]
I've just run into this issue with box version 3 and Homestead 6.0.2. All is well until I do an `apt update`, `apt upgrade`, and a `vagrant reload`. Then \*poof\*, I have to disable ApprArmor to get MariaDB back.

**Comment by khalwat** [comment]
FWIW, this is definitely an issue, I've seen multiple people run into this when attempting to use MariaDB on Homestead.

**Comment by ademers** [comment]
I have repeatedly had this issue after `homestead reload`.

**Comment by svpernova09** [comment]
Resolved via https://github.com/laravel/homestead/releases/tag/v6.0.3

**Comment by kmark** [comment]
Thanks for the patch. I'm curious as to the underlying issue.
