### ISSUE TITLE
multiple php versions fails to map more than one site correctly

### ISSUE THREAD

**Issue by narration-sd** [laravel/homestead#630]
## Versions
  - Vagrant: Vagrant 1.9.6
  - Provider: Virtualbox 5.1.24
  - Homestead: Laravel Homestead 2.2.2 (but 6.0.2 via composer install/upgrade ????)

## Host operating system
  - Window 10 latest upgrades

## Homestead.yaml
ip: 192.168.10.15
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.vagrantssl/id_rsa.pub
keys:
    - ~/.vagrantssl/id_rsa
folders:
    - map: "C:/vagrant/gnu/staging_constantholidays_html"
      to: "/home/vagrant/staging_constantholidays_html"
      type: rsync
      options:
        # do build empty storage and cp_resources folders for Craft's needs
        # don't avoid uploading imagess, but do avoid disturbing their _*/ tranform folders
        rsync__exclude: [".git/", ".git*", ".vagrant/", "cp_resources/*", "_notes/",  ".idea/",
          "buildtools/", "node_modules/", "storage/*", "runtime/*", "scss/", ".sass-cache/",
          "vagrant.*"]
        rsync__args: ["--verbose", "--archive", "--delete", "-z", "--copy-links"]

sites:
    - map: sch.dev
      to: /home/vagrant/staging_constantholidays_html/public
      type: apache
      php: "5.6"
      params:
        - key: APP_ENV
          value: local

    - map: sch2.dev
      to: /home/vagrant/staging_constantholidays_html/public
      type: apache
      php: "7.0"
      params:
        - key: APP_ENV
          value: local

databases:
    - sch_db
name: sch.dev
hostname: sch.dev

## Vagrant up output
https://gist.github.com/narration-sd/21158af0a0aef7cd34834ca399901a0b

## Expected behavior
I should get two sites, sch.dev and sch2.dev, one  running  php5.6 apache, the other php7.0 apache

## Actual behavior
Both sites run php5.6 apache, according to phpinfo() and actual site content reaction

## Steps to reproduce
1. just try the sites, run a phpinfo() command from a tiny script on each.
2. I note this line in the vagrant up log; may be relevant or not:
> ==> sch.dev: libapache2-mod-php7.0: php5.6 module already enabled, not enabling PHP 7.0

## References
https://github.com/laravel/homestead/issues/625 
 -- using the workaround vaguely noted in #625, via some explanation of syntax here:  https://laravel.com/docs/5.4/homestead#site-parameters

**Comment by svpernova09** [comment]
unfortunately this is going to be an apache limitation since PHP version is a server configuration VS nginx a site configuration option.

We should get something added to the Docs that mentions this. (Probably). Sorry for the issues!

**Comment by narration-sd** [comment]
@svpernova09  Understood, as things stand, but here are several notes on people actually doing this, mostly around fastcgi.

It would certainly be great that Homestead supported this, hope you would agree, as people need to use it to try out deployment situations, many of which don't move from Apache,  however advantageous Nginx.

 I'll put the phpfarm one first; not sure if it isn't a simplifying layer for fastcgi:

- https://gist.github.com/ntopulos/3a492b3279f575d8ad4ddbea57e7d1bd
- https://oanhnn.github.io/2015-09-22/running-multiple-php-versions-on-single-apache-instance.html
- http://blog.servergrove.com/2011/08/22/how-to-setup-multiple-php-versions-on-apache/
- https://askubuntu.com/questions/50344/how-to-have-two-versions-of-php-installed-and-switch-easily-between-them

**Comment by svpernova09** [comment]
@narration-sd I totally get it, and I'm sorry for the frustration, but at the moment it's not an easily feasible option. Compiling PHP versions is just another step outside of what's going to be easy maintainable for me for Homestead. Sticking to PPAs is what makes this entire project a lot easier to handle.

My best recommendation would be installing Homestead per project per each version of PHP you need and run each of those on their own version of PHP.

**Comment by narration-sd** [comment]
@svpernova09  Ok, Joe, and do appreciate the profusion issue. 

What about just doing php5.6 plus whatever the latest php7 is?  That one is still quite important in view of legacy hosting sites, which move very slowly as you will know?

That Sury guy has a 5.6 ppa, and has been very good about keeping it up, even with sort of edge things as the php5.6-sybase (which is dblib to access mssql databases) that I need....

**Comment by svpernova09** [comment]
The primary thing I want to avoid is compiling PHP for Homestead. It's so much easier to debug knowing that PHP is coming from a PPA and Ondřej is the gold standard. Atm we're actually supporting old versions of PHP in 2 ways, old versions of PHP where I maintain a personal box for 5.x and official Homestead box versions for 7.0. 

I'm just at my limit it what I can support with the best user experience for Homestead.

**Comment by narration-sd** [comment]
Ok, thanks for listening, Joe, and very much appreciated to use Homestead, especially in its recent form. 

Not having a central vm has made matters much smoother, faster, and generally enjoyable -- thanks.

**Comment by svpernova09** [comment]
Thanks for the kind words, it certainly makes it worth it :D 

I hate to say no to stuff, especially knowing it'll help people, but we have to balance that with what keeps it easy to maintain across 3 OS's and 3 providers.

Cheers.

**Comment by narration-sd** [comment]
Yeah, I know :)  

You take care, Joe -- Clive

**Comment by piotr-cz** [comment]
Is the compiling step really required?
@narration-sd check my https://github.com/laravel/homestead/issues/756#issuecomment-350548939 to see how to switch default php version

**Comment by alpham8** [comment]
That's not true. You could run multiple php verisons inside different apache sites using php-fpm.

**Comment by svpernova09** [comment]
> We did it already in our production environment. So, please fix it in homestead, too.

Pull requests are always welcome.
