### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by blacktrue** [laravel/homestead#632]
Hi

I have homestead updated v5.3.2 and I have a lumen application, when the job queue receives a job after 1 minute I receive the error: **segmentation fault (core dumped)** only happens in homestead, in a productive environment with the same version of php 7.1 works well.

**Comment by svpernova09** [comment]
There is no way of knowing or even beginning to guess without you filling out the entire issue report. Please open a new issue and fill out all of the fields.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org
