### ISSUE TITLE
Issue when 'vagrant up' it get stucked at homesetad-7: SSH auth method: private key

### ISSUE THREAD

**Issue by katopenzz** [laravel/homestead#641]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
  - Provider: Virtualbox, VMWare or Parallels and it's version.
  - Homestead: Run `homestead --version` to show the version

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.1`. You *will* show as up-to-date from the `~5.0` branch when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```

## Vagrant up output
Provide a link to a GitHub Gist containing the complete output.
Do NOT paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
What should have happened?

## Actual behavior
What actually happened?

## Steps to reproduce
1.
2.
3.

## References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by svpernova09** [comment]
Please open a new issue with the requested information.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by andrewhood125** [comment]
@katopenzz ha! Close, but no cigar. Please go back to one of your issues and follow the instructions provided inside. Without this information it will be impossible for us to help you diagnose and identify any potential issues in Homestead. Thanks!

**Comment by svpernova09** [comment]
@katopenzz If you're having issues at the SSH key, make sure you have created a SSH key pair and the paths to them in your Homestead.yaml file are correct / working. After that, we can't be much help until you fill out all the info in the issue.

**Comment by Basil-Nasrallah** [comment]
333333
