### ISSUE TITLE
Mirrors/Torrents for Homestead

### ISSUE THREAD

**Issue by Angelo8828** [laravel/homestead#643]
I don't know where I can tell this request so I thought to write it here. I know that you guys have already very difficult work so I'm very sorry if I want to request this thing.

Can you guys make available current and future developments of Laravel homestead box as mirrors/torrents. I am a web developer in a country where the speed of the internet is very abysmal and annoying as ****. `vagrant box add laravel/homestead` is slow as **** in my place where 100-200 kB/s is the normal thing (considering I must still share that snail internet speed with my office colleagues).

Regards with love,

Angelo :+1:

**Comment by svpernova09** [comment]
Not sure about mirrors, but I'll look into getting a torrent up.

**Comment by lucasctd** [comment]
@Angelo8828 You can download it manually thorugh this [link](https://atlas.hashicorp.com/laravel/boxes/homestead/versions/3.0.0/providers/virtualbox.box)
It's actually better than using terminal (cmd).

You should add your laravel box as below:
`vagrant box add laravel/homestead (path to downloaded file)`

You can find more information about how to download homestead manually [here](https://laravel.io/forum/05-06-2015-how-to-download-vagrant-box-manually).

Hope it helps you. :D

**Comment by svpernova09** [comment]
Mentioned adding a torrent to Taylor, not sure if this is something we'll do or not. Thanks for the suggestion.

**Comment by Angelo8828** [comment]
Thanks guys for the reply!

**Comment by jimmerioles** [comment]
It would really be a great help if somebody would make their copy of latest homestead box available for torrent, it's so slow using the cmd and even downloading it directly through the direct download link gives me 100kb/s.

**Comment by lucasctd** [comment]
@jimmerioles I will upload it on my OneDrive account. Its download speed may be faster than 100kbps.
Does it help for you?

**Comment by lucasctd** [comment]
@jimmerioles Here it's 
https://1drv.ms/u/s!AuGGKC4Y6efKj4VSypvh_0_nsYOPIQ (virtualbox)
Btw, I got more than 100kbps (see below) downloading through hashcorp's website.

![capturar](https://user-images.githubusercontent.com/5876679/29772774-9858976e-8bd0-11e7-8b79-7dd829e49372.PNG)

**Comment by raniesantos** [comment]
@jimmerioles after downloading this (v3.0.0 for virtualbox) where do I put it?

I found this folder `~/VirtualBox VMs/homestead-7` that contains

- box-disk001.vmdk
- homestead-7.vbox ... and
- homestead-7.vbox-prev

None of them seem to match the `.box` extension, what now?

**Comment by svpernova09** [comment]
You need to run `vagrant box add laravel/homestead boxname.box --box-version VALUE` where boxname.box is the filename of the .box file and VALUE is the version of the box.

**Comment by raniesantos** [comment]
@svpernova09 I already have an existing 2.1.0 Homestead, I want to update the existing one now add a new one.

**Comment by svpernova09** [comment]
Updating a box creates a new version and downloads a new .box file. It doesn't alter any existing versions of .box files you've already added.

**Comment by raniesantos** [comment]
@svpernova09 so by executing that command it would actually *"update"* my current homestead box and it won't create a second one?

**Comment by svpernova09** [comment]
it will create a new version of the `laravel/homestead` box. But you'll need to specify the version of that box

**Comment by jimmerioles** [comment]
@lucasctd thanks man!

**Comment by lucasctd** [comment]
@yw. :D

**Comment by fide1** [comment]
They changed there servers to https://app.vagrantup.com/
Manually dowload here.
https://app.vagrantup.com/laravel/boxes/homestead/versions/5.1.0/providers/virtualbox.box

**Comment by huenisys** [comment]
anything new for version 6?
