### ISSUE TITLE
Description on laravel/settler

### ISSUE THREAD

**Issue by JorisDebonnet** [laravel/homestead#650]
Please provide a more useful description/readme on [laravel/settler](https://github.com/laravel/settler). Its version 3.0 was mentioned on the [release blog post](https://laravel-news.com/laravel-homestead-version-6-released) for Homestead 6.0, so I went looking, but I have absolutely no idea what it's for! Perhaps it's a sort of internal/integrated repository for this one? 
A slightly more expansive readme over there might prevent people like me from creating issues like this :D

**Comment by ricardoseriani** [comment]
I agree with you that laravel/settler needs a better README.md, but only to inform you, the laravel/settler its used to make the homestead box for vagrant.

Best Regards

**Comment by svpernova09** [comment]
As @ricardoseriani mentioned, Settler is the tools we use to build the base box that you download as laravel/homestead for Vagrant to use. We match Settler versions with versions of the boxes we release: The version numbers on the boxes https://app.vagrantup.com/laravel/boxes/homestead match up with https://github.com/laravel/settler/releases

**Comment by svpernova09** [comment]
Normally the average user does not need to care about Settler. Just know that when vagrant tells you that there is a newer base box, you should upgrade it (and Homestead).
