### ISSUE TITLE
Support for multiple versions of MySQL

### ISSUE THREAD

**Issue by elistone** [laravel/homestead#652]
Is it possible to do something simlar to the multiple versions of PHP but for MySQL?
So you would have the flexibility of both PHP & MySQL versions?

**Comment by svpernova09** [comment]
Unfortunately not since the different versions of mysql use the same paths. It works with PHP because all the binaries and configuration paths are per version.

**Comment by elistone** [comment]
Yeh I thought that might be the problem, thanks for getting back so fast though.
