### ISSUE TITLE
Set up for laravel training at phpworld

### ISSUE THREAD

**Issue by tracyaichele** [laravel/homestead#658]
## Versions
  - Vagrant: 1.9.8
  - Provider: Virtualbox
  - Homestead: 'homestead' is not recognized as an internal or external command, operable program or batch file
Virtualbox: 5.1.26 r117224 (Qt5.6.2)

## Host operating system
Windows 7 Professional, SP1

## Homestead.yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'C:\Users\Tracy Aichele\localdev2\joeferguson\Code\test-laravel'
        to: /home/vagrant/Code
sites:
    -
        map: homestead.app
        to: /home/vagrant/Code/public
databases:
    - homestead
name: test-laravel
hostname: test-laravel

## Vagrant up output
https://gist.github.com/tracyaichele/58b9be992faa63d99899b8761108463b

## Expected behavior
Have an instance on virtualbox running homestead setup.

## Actual behavior
At this point, vagrant ssh returns nothing - just get another command prompt to local machine.   Opening virtualbox, I see a machine called test-laravel, with status saved (not started).  Can ping local host. Ping to 192.168.10.10 times out.

## Steps to reproduce
1. Follow instructions at: https://www.joeferguson.me/phpworld-training-day-requirements/ , except
2. Substitute vendor\\bin\\homestead make for ./vendor/bin/homestead make (found at https://laravel.com/docs/5.4/homestead#configuring-homestead)
3.

**Comment by svpernova09** [comment]
Run this command and post a gist of the full output:

`vagrant destroy && vagrant up`

**Comment by tracyaichele** [comment]
Thank you - 

Bringing machine 'test-laravel' up with 'virtualbox' provider...
==> test-laravel: Checking if box 'laravel/homestead' is up to date...
==> test-laravel: Clearing any previously set forwarded ports...
==> test-laravel: Clearing any previously set network interfaces...
==> test-laravel: Preparing network interfaces based on configuration...
    test-laravel: Adapter 1: nat
    test-laravel: Adapter 2: hostonly
==> test-laravel: Forwarding ports...
    test-laravel: 80 (guest) => 8000 (host) (adapter 1)
    test-laravel: 443 (guest) => 44300 (host) (adapter 1)
    test-laravel: 3306 (guest) => 33060 (host) (adapter 1)
    test-laravel: 5432 (guest) => 54320 (host) (adapter 1)
    test-laravel: 8025 (guest) => 8025 (host) (adapter 1)
    test-laravel: 27017 (guest) => 27017 (host) (adapter 1)
    test-laravel: 22 (guest) => 2222 (host) (adapter 1)
==> test-laravel: Running 'pre-boot' VM customizations...
==> test-laravel: Booting VM...
==> test-laravel: Waiting for machine to boot. This may take a few minutes...
    test-laravel: SSH address: 127.0.0.1:2222
    test-laravel: SSH username: vagrant
    test-laravel: SSH auth method: private key
    test-laravel: Warning: Connection reset. Retrying...
    test-laravel: Warning: Remote connection disconnect. Retrying...
    test-laravel: Warning: Connection aborted. Retrying...
    test-laravel: Warning: Remote connection disconnect. Retrying...
==> test-laravel: Machine booted and ready!
==> test-laravel: Checking for guest additions in VM...
==> test-laravel: Setting hostname...
==> test-laravel: Configuring and enabling network interfaces...
==> test-laravel: Mounting shared folders...
    test-laravel: /vagrant => C:/Users/Tracy Aichele/localdev2/joeferguson/Code/
test-laravel
    test-laravel: /home/vagrant/Code => C:/Users/Tracy Aichele/localdev2/joeferg
uson/Code/test-laravel
==> test-laravel: Machine already provisioned. Run `vagrant provision` or use th
e `--provision`
==> test-laravel: flag to force provisioning. Provisioners marked to run always
will still run.

c:\Users\Tracy Aichele\localdev2\joeferguson\Code\test-laravel>vagrant destroy &
& vagrant up
    test-laravel: Are you sure you want to destroy the 'test-laravel' VM? [y/N]
y
==> test-laravel: Forcing shutdown of VM...
==> test-laravel: Destroying VM and associated drives...
Bringing machine 'test-laravel' up with 'virtualbox' provider...
==> test-laravel: Importing base box 'laravel/homestead'...
==> test-laravel: Matching MAC address for NAT networking...
==> test-laravel: Checking if box 'laravel/homestead' is up to date...
==> test-laravel: Setting the name of the VM: test-laravel
==> test-laravel: Clearing any previously set network interfaces...
==> test-laravel: Preparing network interfaces based on configuration...
    test-laravel: Adapter 1: nat
    test-laravel: Adapter 2: hostonly
==> test-laravel: Forwarding ports...
    test-laravel: 80 (guest) => 8000 (host) (adapter 1)
    test-laravel: 443 (guest) => 44300 (host) (adapter 1)
    test-laravel: 3306 (guest) => 33060 (host) (adapter 1)
    test-laravel: 5432 (guest) => 54320 (host) (adapter 1)
    test-laravel: 8025 (guest) => 8025 (host) (adapter 1)
    test-laravel: 27017 (guest) => 27017 (host) (adapter 1)
    test-laravel: 22 (guest) => 2222 (host) (adapter 1)
==> test-laravel: Running 'pre-boot' VM customizations...
==> test-laravel: Booting VM...
==> test-laravel: Waiting for machine to boot. This may take a few minutes...
    test-laravel: SSH address: 127.0.0.1:2222
    test-laravel: SSH username: vagrant
    test-laravel: SSH auth method: private key
    test-laravel: Warning: Connection reset. Retrying...
    test-laravel: Warning: Remote connection disconnect. Retrying...
    test-laravel: Warning: Connection reset. Retrying...
    test-laravel: Warning: Remote connection disconnect. Retrying...
    test-laravel: Warning: Connection aborted. Retrying...
    test-laravel:
    test-laravel: Vagrant insecure key detected. Vagrant will automatically repl
ace
    test-laravel: this with a newly generated keypair for better security.
    test-laravel:
    test-laravel: Inserting generated public key within guest...
    test-laravel: Removing insecure key from the guest if it's present...
    test-laravel: Key inserted! Disconnecting and reconnecting using new SSH key
...
==> test-laravel: Machine booted and ready!
==> test-laravel: Checking for guest additions in VM...
==> test-laravel: Setting hostname...
==> test-laravel: Configuring and enabling network interfaces...
==> test-laravel: Mounting shared folders...
    test-laravel: /vagrant => C:/Users/Tracy Aichele/localdev2/joeferguson/Code/
test-laravel
    test-laravel: /home/vagrant/Code => C:/Users/Tracy Aichele/localdev2/joeferg
uson/Code/test-laravel
==> test-laravel: Running provisioner: file...
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: inline script
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: inline script
==> test-laravel:
==> test-laravel: ssh-rsa A...Removed key here== tracy.aichele@gmail.com
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: inline script
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: C:/Users/TRACYA~1/AppData/Local/Temp/vagrant-shell201
70830-33440-emeo5d.sh
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Creating Certificate: homestead.app
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Creating Site: homestead.app
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Checking for old Schedule
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Restarting Nginx
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Creating MySQL Database: homestead
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Creating Postgres Database: homestead
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Clear Variables
==> test-laravel: Running provisioner: shell...
    test-laravel: Running: script: Update Composer
==> test-laravel: Updating to version 1.5.1 (stable channel).
==> test-laravel:
==> test-laravel: Downloading (connecting...)
==> test-laravel:
==> test-laravel: Downloading (100%)
==> test-laravel:
==> test-laravel:
==> test-laravel: Use composer self-update --rollback to return to version 1.4.2

==> test-laravel: Running provisioner: shell...
    test-laravel: Running: C:/Users/TRACYA~1/AppData/Local/Temp/vagrant-shell201
70830-33440-nx0klo.sh

**Comment by svpernova09** [comment]
What console application are you using? Is this in regular cmd.exe?

**Comment by svpernova09** [comment]
What's the output of `vagrant ssh`? According to the gist the VM looks like it's booted without any errors. 

Maybe try http://tech.osteel.me/posts/2015/01/25/how-to-use-vagrant-on-windows.html#enter-putty and using that to connect to vagrant?

**Comment by svpernova09** [comment]
@tracyaichele Please let us know if you need further help.

**Comment by tracyaichele** [comment]
Used advice at: 
 http://tech.osteel.me/posts/2015/01/25/how-to-use-vagrant-on-windows.html#enter-putty
https://stackoverflow.com/questions/9885108/ssh-to-vagrant-box-in-windows


using putty gui to ssh rather than "vagrant ssh".

Thank you for your help.
