### ISSUE TITLE
Mysql freeze after artisan migrate exception

### ISSUE THREAD

**Issue by nanoarmando** [laravel/homestead#659]
Hey guys, I hope you guys are okay. There is a issue when an exception occurs when php artisan migrate command is called. 
The mysql server hangs and needs to be restarted to solve the problem. 
I leave some screenshots.

....
![captura de pantalla de 2017-08-30 19-33-04](https://user-images.githubusercontent.com/21105862/29899934-58e2f514-8dbc-11e7-8ee6-c1d20f85ed4e.png)

2 minutes later... zzzZzzz :)
![captura de pantalla de 2017-08-30 19-33-17](https://user-images.githubusercontent.com/21105862/29899935-58e47150-8dbc-11e7-8355-b4b48a57d1d3.png)

## Versions
  - Vagrant: 1.9.7
  - Provider: Virtualbox 5.1.26
  - Homestead: 6.1.0

## Host operating system
Manjaro 17.0.2 Gnome

**Comment by svpernova09** [comment]
There is no way of telling what's going on with this little information. my guess is you're doing something to overpower MySQL and you should either back off how much your chunking at MySQL at a time, or you should give the VM more resources.
