### ISSUE TITLE
Object storage? *enhancement*

### ISSUE THREAD

**Issue by cocochepeau** [laravel/homestead#661]
Greetings,

Would you be willing to incorporate an object storage provider into Laravel Homestead? We're currently using [Minio](https://minio.io) and since one of its main purpose is to provide object storage within development environment I thought it was a good idea to include it in Laravel Homestead.

Somes notes:
* It's already used in [Laradock](https://github.com/laradock/laradock).
* And in a ["ready-to-use skeleton app"](https://github.com/sebastiaanluca/laravel-skeleton).

Please, tell me if you need anything.

Thanks.

**Comment by svpernova09** [comment]
Thanks for the suggestion, will look into it on the next round of Settler updates.
