### ISSUE TITLE
Vagrant 2.0

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/homestead#664]
[Vagrant 2.0](https://www.hashicorp.com/blog/hashicorp-vagrant-2-0/) has been released.

Key points:

> Since Vagrant 1.0, we've added support for multi-providers such as VMware and Docker, guests such as Windows, macOS, and complex workflows including snapshots. These major changes are followed by hundreds of improvements and bug fixes.

> Vagrant 2.0 supports provisioning development environments on VirtualBox, VMware, Hyper-V, Docker, AWS, GCP, and more. It can virtualize Windows, macOS, and a dozen other new operating systems. Vagrant 2.0 is paired with Vagrant Cloud for finding and consuming boxes. It has come a long way since Vagrant 1.0 when it only supported VirtualBox, and the community has grown significantly since then.

We need to check compatibility and see what we can add.

**Comment by svpernova09** [comment]
I just tested Homestead with Vagrant 2.0 on MacOS with no issues. If anyone comes up with issues please open a new issue.

**Comment by jeff-h** [comment]
Just wondering if this means Homestead now supports running on Docker instead of Virtualbox (etc), since Vagrant 2.0 supports Docker as a provider?

**Comment by svpernova09** [comment]
For Homestead to support Docker as a provider we'd have to build a base box from https://github.com/laravel/settler for Docker. I don't have any immediate plans to. I've not looked into it yet either so that could change.

**Comment by jeff-h** [comment]
Thanks for the reply — I'll keep an eye out on laravel/settler :)

**Comment by svpernova09** [comment]
Since Vagrant 2.0.0 uses boot2docker on Windows and Mac, I don't think we'll be supporting docker as a provider. It seems odd that Vagrant went boot2docker method instead of the newer native methods on those operating systems.
