### ISSUE TITLE
Proposal: Change .app TLD to .test

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#668]
Based on: https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

It's probably time to move to a reserved TLD instead of using `.app`

Looking for feedback on an idea about changing the `.app` TLD we use by default for local domains to `.test`. As it's the shortest reserved domain according to: https://en.wikipedia.org/wiki/.test

**Comment by svpernova09** [comment]
We could also change the default to `.localhost`

**Comment by andrewhood125** [comment]
Those are probably going to be the best future proof options. I really liked using `.dev` :( and I probably still will until something forces me to change. Whatever we do I'd like to see us be flexible. A configuration option may be a good thing here.

**Comment by svpernova09** [comment]
Leaning towards going to `.localhost` as the default

**Comment by jonnywilliamson** [comment]
Have to say I'd much prefer `.test`

It just takes so loooong for `.localhost`  so many typos....but maybe that's just me.😢

**Comment by svpernova09** [comment]
I get it, which is why I mentioned `.test` originally. But you can always change it. This is just the default that Homestead will start out with when you generate your `Homestead.yaml` file.

**Comment by browner12** [comment]
I would vote for `.localhost` as the default. With our default files we should definitely choose one of the 4 reserved TLDs. I think `.localhost` makes the most semantic sense, as I see `.test` as your testing environment, not your dev environment.

And since this is only a suggestion, people can continue to do whatever they want in their `Homestead.yaml` file. Personally, I'll probably stick with `.app` until it stops working.

**Comment by orottier** [comment]
I like the proposal, let's encourage best practises. I also think `.localhost` makes the most sense.
Don't forget to update https://github.com/laravel/docs/blob/5.5/homestead.md accordingly.

**Comment by svpernova09** [comment]
We're going to be defaulting to `.localhost`

**Comment by CydeWeys** [comment]
Thanks so much!

**Comment by lionslair** [comment]
.localhost doesn't work for me even after stuffing around and removing it from dnsmasq I still have issues but .test works.

OS: ubuntu

**Comment by svpernova09** [comment]
FYI Homestead defaults to `.test` since https://github.com/laravel/homestead/pull/697
