### ISSUE TITLE
Nginx option "sendfile on;" has some problems in Virtual Machines

### ISSUE THREAD

**Issue by casivaagustin** [laravel/homestead#670]
I just cross over an issue that I was not able to see my changes in a css files trough the web server (nginx), the only thing that I was able to see was some strange characters after I did some edit in the file.

Googling about it I found this posts https://jeremyfelt.com/2013/01/08/clear-nginx-cache-in-vagrant/

I don't know if is Homestead responsibility or not, however I think it would be nice to avoid this issue by default, if it is possible to make the provision with the option **sendfile off;** by default it can save a lot of headaches to the users.

Hope this help, thanks

**Comment by svpernova09** [comment]
Based on https://github.com/hashicorp/vagrant/issues/351#issuecomment-1339640 it's a Virtualbox bug that's being ignored by that team. Probably a big game of "No our problem". 

After reading a bit up on `sendfile` in nginx, (https://t37.net/nginx-optimization-understanding-sendfile-tcp_nodelay-and-tcp_nopush.html) I don't see any harm in defaulting it to off. 

Assuming it works the same way in apache we can default it off there as well.

**Comment by svpernova09** [comment]
We're already default to `sendfile off`: https://github.com/laravel/homestead/blob/master/scripts/serve-laravel.sh
