### ISSUE TITLE
Provisioning the Homestead box fails due to an inaccessible ~/.ssh directory

### ISSUE THREAD

**Issue by JackWH** [laravel/homestead#673]
## Versions
  - Vagrant: `v2.0.0`.
  - Provider: `Virtualbox v5.1.28`
  - Homestead Box: `v3.1.0`.
  - Homestead Repository: `master` (closest to `v6.2.2`)

## Host operating system
  - macOS Sierra: `v10.12.6`

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 8192
cpus: 4
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites
      to: /home/vagrant

sites:
    - map: mysite.app
      to: /home/vagrant/mysite/public

databases:
    - homestead
```

## Vagrant up output
[Click here for `vagrant up --provision` output](https://gist.github.com/JackWH/09e076c45bc2d1fcae2b0302394212fe). Note that right at the end, it outputs my public SSH key. Just prior to that, errors were thrown indicating `grep` and `tee` couldn't find any files in `/home/vagrant/.ssh`.

## Expected behavior
`vagrant up --provision` should provision a new Homestead box without failing.

## Actual behavior
The provisioning begins, and the various scripts start running. Eventually the provisioner attempts to read the authorized SSH keys, but hits an error. See the below extract from the Vagrant output:

```
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: grep:
==> homestead-7: /home/vagrant/.ssh/authorized_keys
==> homestead-7: : No such file or directory
==> homestead-7: tee:
==> homestead-7: /home/vagrant/.ssh/authorized_keys
==> homestead-7: : No such file or directory
==> homestead-7:
==> homestead-7: ssh-rsa [...my public SSH key...] me@my-email-address.com
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I tracked this part of the script down to this part of `homestead.rb`:

```rb
# Configure The Public Key For SSH Access
if settings.include? 'authorize'
    if File.exists? File.expand_path(settings["authorize"])
        config.vm.provision "shell" do |s|
            s.inline = "echo $1 | grep -xq \"$1\" /home/vagrant/.ssh/authorized_keys || echo \"\n$1\" | tee -a /home/vagrant/.ssh/authorized_keys"
            s.args = [File.read(File.expand_path(settings["authorize"]))]
        end
    end
end
```

But I'm kind of at a loss for why this can't read or access the SSH directory.

## Steps to reproduce
1. Install software versions as above
2. Configure `Homestead.yaml` as above
3. Try to run `vagrant up --provision`

**Comment by svpernova09** [comment]
Does the issue occur on https://github.com/laravel/homestead/releases/tag/v6.2.2 ?

Unable to replicate on MacOS, Virtualbox 5.1.28, and vagrant 2.0.0

**Comment by svpernova09** [comment]
Oh!

The problem is your folder mounts:

```
folders:
    - map: ~/Sites
      to: /home/vagrant
```

Your mounting your entire Sites folder to /home/vagrant. Which doesn't have a `.ssh` folder. 

Don't map entire folders. map project folders to subfolders in `/home/vagrant`

**Comment by JackWH** [comment]
@svpernova09 Bingo, you're correct - that's fixed the issue. Thanks for the speedy response.

Although I would just say, isn't this exactly what the [current default version of `Homestead.yaml` in this repository](https://github.com/laravel/homestead/blob/master/resources/Homestead.yaml) is already doing...?

```yaml
folders:
    - map: ~/code
      to: /home/vagrant
```

I'm not quite understanding how what I'm doing is any different here? Or is there a bug in the default `Homestead.yaml`? Thanks in advance!

**Comment by svpernova09** [comment]
Yeah, this is why we don't recommend you use master and use tagged versions instead. I'm poking at a few different things today.

**Comment by JackWH** [comment]
Understood. I’ll revert back to the closest tag. Appreciate your help!
