### ISSUE TITLE
Sudo tab completion broken on box 3.1.0

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#677]
Reported by @browner12 via Slack

Fix:

https://askubuntu.com/questions/874179/sudo-command-doesnt-autocomplete-anymore-on-files

**Comment by browner12** [comment]
@svpernova09 have you added a fix for this to the settler box yet, for the next release? otherwise, I can give it a shot.

or do we know what the upstream change was that caused this?

**Comment by svpernova09** [comment]
I assume the upstream change was in a box upgrade. Feel free to PR a fix to settler

**Comment by browner12** [comment]
https://github.com/laravel/settler/pull/118

**Comment by svpernova09** [comment]
This will be resolved in the next base box update
