### ISSUE TITLE
git user [feature request]

### ISSUE THREAD

**Issue by vladyslavstartsev** [laravel/homestead#679]
## Expected behavior
I can make commits with my git user in vagrant box
` Committer:  vladyslavstartsev <vladyslavstartsev@gmail.com>`

## Actual behavior
I do my development all in the box, but for git I have separate tab in cli in local machine. If I do `git commit` the vagrant user will be `vagrant`. What if there you'll copy `.ssh` folder from local machine to the host (for public key) and set `git config` user/email the same as local machine user.
` Committer: vagrant <vagrant@homestead>`

## Steps to reproduce
1.`homestead up && homestead ssh`
2.`cd ~/Code/someProject`
3.change file
4.git add . && git commit -m 'description' 
5. see something like 
```bash
[dev.some-feature 3423f3] description
 Committer: vagrant <vagrant@homestead>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 2 files changed, 2 insertions(+), 50 deletions(-)
```

**Comment by svpernova09** [comment]
Thanks for taking the time to open an issue.

This is not a bug, rather working as intended. If you really want to set up and use git from *inside* Vagrant `after.sh` is where you should set those commands.

**Comment by vladyslavstartsev** [comment]
Got it! Didn't look inside the folder, maybe it should be documented on the [homestead docs page](https://laravel.com/docs/homestead)?
