### ISSUE TITLE
CA Certificates in php.ini

### ISSUE THREAD

**Issue by Limych** [laravel/homestead#690]
## Versions
  - Vagrant: 1.9.8
  - Provider: Virtualbox 5.1.26
  - Homestead: 6.3.0

## Enhancement proposal

Please, add default options with paths to CA Certificates for SSL into `php.ini` files:

```ini
[openssl]
;...
openssl.cainfo = /etc/ssl/certs/ca-certificates.crt

[curl]
;...
curl.cainfo = /etc/ssl/certs/ca-certificates.crt
```

**Comment by svpernova09** [comment]
This would likely be implemented in https://github.com/laravel/settler/blob/master/scripts/provision.sh#L139-L194

**Comment by svpernova09** [comment]
Resolved via https://github.com/laravel/settler/pull/126 and will be in the next base box upgrade.
