### ISSUE TITLE
Cannot connect to MongoDB after provisioning (due to recent regression)

### ISSUE THREAD

**Issue by cbj4074** [laravel/homestead#703]
Please see:

https://github.com/laravel/homestead/commit/34e031513766205ce40021e13db05d5b270faa31?_pjax=%23js-repo-pjax-container#commitcomment-25080915

**Comment by cbj4074** [comment]
This should fix the issue:

https://github.com/laravel/homestead/pull/704

**Comment by svpernova09** [comment]
Can you verify #704 resolved this and close the issue if so? Thanks!
