### ISSUE TITLE
Error while booting the VM after Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by akimcsm** [laravel/homestead#706]
I realize this is not caused by Homestead, per se, but I imagine many people ran into this error after the latest Windows 10 update.
 
![homestead_error](https://user-images.githubusercontent.com/15095392/31809469-8f1ef4c0-b580-11e7-9b48-f44bd9703bd2.png)

It seems like running ``` vagrant reload ``` fixes it

**Comment by svpernova09** [comment]
Please fill out the entire issue template including the full output of ‘vagrant destroy && vagrant up’

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by durasj** [comment]
Hi @akimcsm,

how did you please resolve this issue? I've tried to update all parts involved and a bunch of other stuff but nothing helps.

Thank you

**Comment by akimcsm** [comment]
Hi @durasj 

Apart from running `vagrant reload` I don't remember trying anything else. Worst case scenario, you could try removing everything related to Vagrant, Homestead and VIrtual Box and reinstalling them.

**Comment by durasj** [comment]
Hi @akimcsm,

that didn't work but after some more attempts updating the homestead box and reinstalling the VirtualBox after that did the job.
