### ISSUE TITLE
elasticsearch doesn't work until java reinstallation

### ISSUE THREAD

**Issue by slillo** [laravel/homestead#707]
Elasticsearch doesn't work just adding in Homestead.yaml:

elasticsearch: true

I had to reinstall java

**Comment by svpernova09** [comment]
Yesterday morning (US Central time) the `webupd8team` Java repo was / is completely broken since Oracle released a new version and removed the old downloads. So it wouldn't surprise me if this was totally broken until the `webupd8team` team updates their repo.

**Comment by browner12** [comment]
yah, i noticed this when I built a box yesterday. something on their end, that we'll just have to wait a little for them to resolve I think.

**Comment by svpernova09** [comment]
Here's a workaround you can use in the meantime if you need it:

Either put the `jdk-8u151-linux-x64.tar.gz` on a http url somewhere or in your local repo:

```
# Manually install JAVA since it's currently broken in ppa:webupd8team/java
echo "Downloading and installing Java manually"
wget -q https://some/url/to/jdk-8u151-linux-x64.tar.gz
sudo mkdir -p /usr/lib/jvm
sudo tar -zxf jdk-8u151-linux-x64.tar.gz
sudo mv jdk1.8* /usr/lib/jvm/java-8-oracle
sudo rm -rf jdk-8u151-linux-x64.tar.gz
sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-oracle/jre/bin/java 1091
sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-8-oracle/bin/javac 1091
echo "export J2SDKDIR=/usr/lib/jvm/java-8-oracle" | sudo tee --append /etc/profile
echo "export J2REDIR=/usr/lib/jvm/java-8-oracle/jre" | sudo tee --append /etc/profile
echo "export PATH=$PATH:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/bin" | sudo tee --append /etc/profile
echo "export JAVA_HOME=/usr/lib/jvm/java-8-oracle" | sudo tee --append /etc/profile
echo "export DERBY_HOME=/usr/lib/jvm/java-8-oracle/db" | sudo tee --append /etc/profile
```

**Comment by sisve** [comment]
Couldn't we just use the openjdk-8-jre-headless package?

**Comment by jamesgraham** [comment]
Why is this closed? We are seeing this issue on 2 different machines now

**Comment by browner12** [comment]
i'm swamped at work right now, so my OSS work is going to take a hit.  If anyone wants to tackle this, go right ahead.

**Comment by svpernova09** [comment]
I just tested both versions of elasticsearch and they both installed with no issue. Considering this resolved unless someone can produce a new issue with repeatable steps to demonstrate failure.

**Comment by sisve** [comment]
How should we provide the steps? Is there a special Homestead.yaml template that shall be used? Specific versions?

**Comment by sisve** [comment]
It works for me now too. I guess we cannot trust it since the download urls seems finicky. Wouldn't it be easier to use the openjdk-8-jre-headless package and the existing apt-get mirrors, instead of a ppa that downloads from external urls?
