### ISSUE TITLE
Setting env variables does not work for PHP 5.6 any more

### ISSUE THREAD

**Issue by dakira** [laravel/homestead#710]
## Versions
  - Vagrant: 2.0.0
  - Provider: 5.1.30
  - Homestead: 6.5.0

## Host operating system
Ubuntu 17.10

## Homestead.yaml
```yaml
variables:
    - key: APP_ENV
      value: whatever
```

## Vagrant up output
```
Oct 24 17:55:48 homestead php-fpm5.6[4349]: [24-Oct-2017 17:55:48] ERROR: [/etc/php/5.6/fpm/php-fpm.conf:526] Array are not allowed in the global section
Oct 24 17:55:48 homestead php-fpm5.6[4349]: [24-Oct-2017 17:55:48] ERROR: failed to load configuration file '/etc/php/5.6/fpm/php-fpm.conf'
Oct 24 17:55:48 homestead php-fpm5.6[4349]: [24-Oct-2017 17:55:48] ERROR: FPM initialization failed
Oct 24 17:55:48 homestead systemd[1]: php5.6-fpm.service: Main process exited, code=exited, status=78/n/a
Oct 24 17:55:48 homestead systemd[1]: Failed to start The PHP 5.6 FastCGI Process Manager.
```
## Expected behavior
Environment variables should be set and all PHP-FPMs should load.

## Actual behavior
PHP 5.6 fails to load because suddenly arrays are not allowed anymore in the global section of php.ini or php-fpm.conf.

## Steps to reproduce
1. On a fresh Homestead, set an environment variable as seen in the snippet above
2. Run vagrant reload --provision

## Notes
This does work when the env array is instead added to */etc/php/5.6/fpm/pool.d/www.conf*. Maybe it should be added there in any case (e.g. for all PHP versions).

**Comment by svpernova09** [comment]
This is a known issue we came across. Check this for a solution: https://github.com/laravel/homestead/issues/625#issuecomment-319239219

**Comment by dakira** [comment]
Sure that works. It's still a bug, though, so no reason to close the issue. I do have a pull request if you want it. ;)

**Comment by svpernova09** [comment]
Certainly willing to take a look a PR.
