### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID in Linux Chrome 64

### ISSUE THREAD

**Issue by davidsierradz** [laravel/homestead#714]
> laravel.app normally uses encryption to protect your information. When Google Chrome tried to connect to laravel.app this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be laravel.app, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

> You cannot visit laravel.app right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

In Chrome 62:

> This server could not prove that it is laravel.app; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.

> Proceed to laravel.app (unsafe)

I can click `Proceed to laravel.app (unsafe)` and enter the site.

**Comment by davidsierradz** [comment]
Checking #668, I changed laravel.app to laravel.test and its working, sorry for noise.

**Comment by popstheman** [comment]
I changed .app to .test and .dev however, both didn't work for me. Any other suggestions ?

**Comment by svpernova09** [comment]
@popstheman I need more info to be of any help. Did you `vagrant destroy && vagrant up` after making the change to use .test?

**Comment by popstheman** [comment]
@svpernova09 Thanks. `vagrant destroy` and `vagrant up` solved the issue for me.

**Comment by netdesignr** [comment]
@svpernova09 Thank you!

**Comment by GeorgeGeorgiev** [comment]
svpernova09 Thanks!
