### ISSUE TITLE
Support for hyper-v provider

### ISSUE THREAD

**Issue by timo75** [laravel/homestead#717]
Would be nice to run Homestead on hyperv provider. Since Hyper-V is required  for Docker on Windows one has to disable Hyper-V & reboot and cannot run Homestead and Docker based projects in parallel.

**Comment by svpernova09** [comment]
https://gist.github.com/svpernova09/653271fbfaa3053da63eaecf84c1462d

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by timo75** [comment]
Thanks. I will try that.

**Comment by jurosh** [comment]
@svpernova09 should your hotfix work with latest version?

I can still see `The provider 'virtualbox' that was requested t...`
