### ISSUE TITLE
Could not login vagrant with vagrant ssh

### ISSUE THREAD

**Issue by chunkaiww** [laravel/homestead#723]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.0.1
  - Provider: 5.2.0
  - Homestead: 7

## Host operating system
windows 10

## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: c:/Users/Kai/.ssh/id_rsa.pub

keys:
    - c:/Users/Kai/.ssh/id_rsa

folders:
    - map: C:/code/tuanfit
      to: /home/vagrant/Code
    

sites:
    - map: tuanfit.app
      to: /home/vagrant/Code/laravel/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

## Vagrant up output
https://gist.github.com/chunkaiww/b98d4e0e03dbe04d474e523690b72014

## Expected behavior
I ran a command line vagrant ssh on homestead, expecting that I could link to the server (MySQL) with the login option.

## Actual behavior
After cmd the vagrant ssh, the command line stop at "3 packages can be updated.
0 updates are security updates" line. When I want to close git bash, it was showing that the processes are still running in the session. I wait around 3 hours and reboot a lot of times, it showed the same results. 

The result as shown below:

Kai@LAPTOP-UDO9ORL4 MINGW64 ~/homestead (master)
$ vagrant ssh
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-92-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

3 packages can be updated.
0 updates are security updates.

## References
Vagrant status- https://gist.github.com/chunkaiww/15a01912395a96a1c6a1732345d1777e
Vagrant provision - https://gist.github.com/chunkaiww/45c7208aa380b8fe31e8e622d8c35f28

**Comment by svpernova09** [comment]
Does `Provider: 5.2.0` Mean Virtualbox 5.2? We're not currently compatible with 5.2. This will require a base box update. 

Until we release a 5.2 compatible version you should stick with Virtualbox 5.1

**Comment by chunkaiww** [comment]
Yes, it shows version 5.2.
Ok, then I will re-install version 5.1

**Comment by chunkaiww** [comment]
I tried to use Vitualbox 5.18, 5.1.2, 5.1,30, however, it showed the error results as shown below.

$ vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Clearing any previously set forwarded ports...
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 4040 (guest) => 4040 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "8b1c823e-f60b-4501-bf1b-9cf136151708", "--type", "headless                                                                                            "]

Stderr: VBoxManage.exe: error: The virtual machine 'homestead-7' has terminated                                                                                             unexpectedly during startup with exit code 1 (0x1).  More details may be availab                                                                                            le in 'C:\Users\Kai\VirtualBox VMs\homestead-7\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap,                                                                                             interface IMachine

**Comment by svpernova09** [comment]
You'll want to ensure you've completely purged Virtualbox 5.2 and all the files that may have been left behind. Reboot, and do another install of the latest version of 5.1

**Comment by jordanramstad** [comment]
This is also happening on vmware workstation 12 as a provider.

Going to try to debug myself but it seems this is not specific to Virtualbox 5.2

**Comment by E-zh** [comment]
I have this problem too. I use vagrant 2.0.1 with Virtualbox 5.2.0
But I do not want to go back to Virtual 5.1. And how a temporary solution chose this:
`ssh vagrant@192.168.10.10`

**Comment by svpernova09** [comment]
@E-zh If you do not want to downgrade to Virtualbox 5.1 try these instructions: https://gist.github.com/svpernova09/8ffda2889c4cd957defc765dcfaaeec1

**Comment by svpernova09** [comment]
@chunkaiww 

Are you still having this problem? If so could you post the contents of `C:\Users\Kai\VirtualBox VMs\homestead-7\Logs\VBoxHardening.log` from your reply?

**Comment by svpernova09** [comment]
I've seen this myself (without realizing what it was at the time) last week at my php[world] training day. I assume it was Virtualbox 5.1 but it could have well been 5.2. I didn't try to debug very far.

What is troubling is it's happening on VMware's provider as well. I'm not sure anything in Homestead is actually causing this. I'm wondering if this is a bug somewhere in Vagrant 2.x

**Comment by E-zh** [comment]
@svpernova09
Thanks!

**Comment by chunkaiww** [comment]
@svpernova09
I used revo uninstaller to purged the visual box and tried different versions of it to run the homestead, but I still having this problem. So, I used the traditional way that using xampp and composer to install laravel. Anyway, thanks for your help!

**Comment by jordanramstad** [comment]
I have done some more testing and managed to recreated it on both Virtualbox 5.1 and Vmware Workstation 12, both on windows. 

I have tried it in powershell and got it to work on both, It seems it might be related to MINGW32, the default(only) shell of sourcetree. Changing the shell seems to work, but given that many applications, not just sourcetree bundle it as a shell, hopefully there is a way to bypass it because I doubt even if MINGW32 makes an update, the applications bundling it will update quickly as well.......

**Comment by svpernova09** [comment]
Thanks to @jordanramstad doing a ton of debugging for us on this issue.

It looks like this is an issue with MINGW32 and or Vagrant v 2.0.1 on Windows. He was able to confirm the behavior on Virtualbox 5.1 and VMware providers. 

Our recommendation is to downgrade to Vagrant 2.0.0 or try another shell application (I had him test CMDr and it worked)
