### ISSUE TITLE
Error when running `vagrant halt`

### ISSUE THREAD

**Issue by mikebronner** [laravel/homestead#728]
I received the following error after pulling the latest this morning.

```~/Homestead/scripts/homestead.rb:377: syntax error, unexpected end-of-input, expecting keyword_end```

(Checking out the latest tag had no issues: `git checkout v6.5.0`)

Thanks :)

**Comment by svpernova09** [comment]
Always fun to find the people brave enough to use `master`

Resolved via #730

**Comment by mikebronner** [comment]
Hehe, glad to help! :) Thanks for the quick fix :)
