### ISSUE TITLE
FR: Add support for vagrant-hostsupdater

### ISSUE THREAD

**Issue by viezel** [laravel/homestead#732]
https://github.com/cogitatio/vagrant-hostsupdater automatically updates hosts file to the homestead.yml file. This makes it even easier for newcommers to use Homestead.

**Comment by svpernova09** [comment]
Already supported: https://github.com/laravel/homestead/blob/master/Vagrantfile#L41

**Comment by viezel** [comment]
yeah, i meant that it gets installed when installing homestead. i had to install it manually to make it work.

**Comment by svpernova09** [comment]
Homestead should be plugin agnostic. It shouldn't require any 3rd party plugins (outside of provider specific ones for VMware, Parallels).

**Comment by viezel** [comment]
ok get it. Maybe add it to the docs then? :) 
im a senior developer, not a vagrant expert and I think this plugin is really nice to automate the mapping.

**Comment by DojoGeekRA** [comment]
@viezel neither is going to happen, someone already tried it in https://github.com/laravel/docs/pull/2357 and was rejected by Taylor.
