### ISSUE TITLE
Default PHP version selections are inconsistent (7.1/7.2)

### ISSUE THREAD

**Issue by bryandatanerds** [laravel/homestead#742]
## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox 5.1.26
  - Homestead: tag v6.6.0

## Host operating system
Gentoo amd64

## Homestead.yaml
```---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code
    - map: ~/data
      to: /home/vagrant/data
    - map: ~/bin/homestead-bin
      to: /home/vagrant/bin
```

(`sites` elided.)

## Vagrant up output
https://gist.github.com/bryandatanerds/8ab9503c04e0121ce18d5ef8116434ee

## Expected behavior
Installing PHP extensions with `pecl install` should work by default.

## Actual behavior
`pecl install` installs extensions into `/usr/lib/php/20170718` for PHP 7.2, instead of installing into `/usr/lib/php/20160303` for PHP 7.1.  This is because the alternatives selection on a new VM is wrong:

    vagrant@homestead:~$ update-alternatives --get-selections | grep -i php
    php                            manual   /usr/bin/php7.1
    php-config                     auto     /usr/bin/php-config7.2
    phpize                         auto     /usr/bin/phpize7.2

I can't see whether it's Homestead that's setting `php` to 7.1, but `php-config` and `phpize` should default to the same version.

## Steps to reproduce
1. `homestead up`, then in the VM:
2. `sudo pecl install stats-2.0.3`
3. `echo extension=stats.so | sudo tee /etc/php/7.1/{cli,fpm}/conf.d/99-stats.ini`
4. `php -r 'print_r(get_loaded_extensions());' | grep stats`

This last command prints out only a warning:
> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/stats.so' - /usr/lib/php/20160303/stats.so: cannot open shared object file: No such file or directory in Unknown on line 0

No stats package is present.  Also:

    $ ls /usr/lib/php/*/stats*
    /usr/lib/php/20170718/stats.so

**Comment by svpernova09** [comment]
Looks like `php-config` and `phpize` aren't respecting Ubuntu's `update-alternatives`. We install php 5.6, 7.0, 7.1, and 7.2 then we use `update-alternatives` to set the default to 7.1. (Which will change tomorrow when 7.2 goes GA) 

I'll have a look at this tomorrow when I'm building fresh boxes.

**Comment by svpernova09** [comment]
This is going to be resolved via an upstream change in https://github.com/laravel/settler Will fix t his tomorrow when I update that repo. Thanks for the report!

**Comment by bryandatanerds** [comment]
Sounds good, thanks for the fast response!

**Comment by alquesadilla** [comment]
I believe this is still broken...

**Comment by bryandatanerds** [comment]
Hm.  If I create a fresh VM currently (Homestead 5.0.1), all of the update-alternatives options are on 7.2 but Nginx is using PHP 7.1 FPM for my sites, so it does still look like there's a mismatch.

**Comment by svpernova09** [comment]
@bryandatanerds sounds like your Repo isn't at the latest version (but the box is). The site creation happens from the Homestead repo scripts. The update-alternatives is set in the base box.

**Comment by bryandatanerds** [comment]
Yep, that was it.  Upgraded git to tag v7.0.1 and I'm all on 7.2 now.  Sorry for the distraction and thanks!

**Comment by svpernova09** [comment]
@bryandatanerds no worries. Glad it was a simple fix.
