### ISSUE TITLE
Elasticsearch does not start as service.

### ISSUE THREAD

**Issue by dorin-niscu** [laravel/homestead#747]
Elasticsearch does not start as service when reloading the virtual machine.

curl: (7) Failed to connect to localhost port 9200: Connection refused.

This solves the problem.

sudo /bin/systemctl enable elasticsearch.service
sudo /bin/systemctl status elasticsearch.service

**Comment by browner12** [comment]
are you proposing something, or is this just informational?

after I created the Elasticsearch install script, I went back and debated if I needed to add some kind of supervisor to keep it up.  I felt that was overkill on a dev-machine, so I just left it out for people to restart if they needed.

```
sudo service elasticsearch start
```

**Comment by dorin-niscu** [comment]
It is informational for those who have the same problem as I had.
It might also be added in the script.

**Comment by svpernova09** [comment]
If a user goes through the trouble of installing elasticsearch we should probably ensure it's going to auto start. Resolved via #748
