### ISSUE TITLE
Default php version?

### ISSUE THREAD

**Issue by steveheinsch** [laravel/homestead#756]
I know you can set the php version on a per site basis, but is there a way to set the default php version for all sites to use so it doesn't use whatever is the most current version as default if you don't specify a version per site?

**Comment by svpernova09** [comment]
Not at this time.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by piotr-cz** [comment]
I'd find it very handy, as setting site-specific PHP version doesn't work for `apache` type (#630).
That way I could at least choose global version.

workaround, assuming you want switch to php 7.0:
1) add required php version to one of the sites and run provision which will install it: `vagrant reload --provision`
2) to change CLI, change symbolic link in `/etc/alternatives/php` to `/usr/bin/php7.0`
3) switch apache modules
```sh
sudo a2dismod php7.2
sudo a2enmod php7.0
sudo service apache2 restart
```

**Comment by piotr-cz** [comment]
This has been resolved by https://github.com/laravel/homestead/issues/892, but still on have to run `vagrant reload --provision` to recreate sites.
