### ISSUE TITLE
ERR_EMPTY_RESPONSE on secure pages

### ISSUE THREAD

**Issue by dorin-niscu** [laravel/homestead#766]
The secure pages do not work anymore.

I renamed .app into .test to make sure will fix the issue but the problem persists.

**Google Chrome**
This page isn’t working
homestead.test didn’t send any data.
ERR_EMPTY_RESPONSE

**Firefox**
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

http://homestead.test/ , http://192.168.10.10/ work fine.
https://homestead.test/, https://192.168.10.10/ do not work anymore.

**Comment by svpernova09** [comment]
Please see #758, #755, or #754
