### ISSUE TITLE
False reporting of installation

### ISSUE THREAD

**Issue by chinaobject** [laravel/homestead#768]
```
Fatal error: Cannot redeclare static Symfony\Component\Console\Command\Command::$defaultName as non static Laravel\Homestead\MakeCommand::$defaultName in /Users/object/.composer/vendor/laravel/homestead/src/MakeCommand.php on line 155
```

This is a mistake to install the homestead newspaper in an mac pro environment.
In the thirty-first line of MakeCommand.php, I tried to change defaultName's declarations to ‘protected static’, and I missed it.

**Comment by svpernova09** [comment]
Are you on an old version? it's near impossible to debug when you don't fill out the requested info in the issue template.
