### ISSUE TITLE
Script: import_vm_vmcx.ps1

### ISSUE THREAD

**Issue by bluegeek** [laravel/homestead#781]
## Versions
  - Vagrant: latest
  - Provider:hyperv
  - Homestead: latest but not master branch

## Expected behavior
just run vagrant up

## Actual behavior
```
Bringing machine 'homestead-7' up with 'hyperv' provider...
==> homestead-7: Verifying Hyper-V is enabled...
==> homestead-7: Importing a Hyper-V instance
    homestead-7: Cloning virtual hard drive...
    homestead-7: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

字符串缺少终止符: '。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```
### other
I just install it and run `vagrant up`.when I use virtualbox ,it works well.I think what happend to hyperv.
I have been admin,too.
### finally
Thank you for solve my question

**Comment by svpernova09** [comment]
This is likely a Vagrant issue. Homestead has nothing to do with `import_vm_vmcx.ps1`. Unfortunately the only advice I can offer is to downgrade to a lower version of Vagrant. I know 2.0.1 has been troublesome for many Windows users.

**Comment by strange-fish** [comment]
i got the same problem...
