### ISSUE TITLE
Who use ssl? 

### ISSUE THREAD

**Issue by Seaony** [laravel/homestead#785]
How can I add https for my homestead website? 
It always jumps to https when I use Chrome for development.
 I tried to set ssl connection using `ssl: true`, but it returned to me this error:

![image](https://user-images.githubusercontent.com/29486364/34554262-052c26e8-f167-11e7-951b-48bb80f51544.png)

![image](https://user-images.githubusercontent.com/29486364/34554266-082c541c-f167-11e7-9c01-0039cfb07e09.png)

Can you help me? thank you very much！

**Comment by svpernova09** [comment]
SSL is already on by default. The browser will the an error because the certificate is self signed.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by Seaony** [comment]
Thanks！I found this, it makes SSL work :) [Using self-signed SSL certificates with Postman](http://blog.getpostman.com/2014/01/28/using-self-signed-certificates-with-postman/)

**Comment by hfalucas** [comment]
This might be good too: https://github.com/FiloSottile/mkcert

**Comment by martijn94** [comment]
Homestead already signs all certificates with a CA cert that can be loaded in your Keychain (mac) and Firefox to have a green valid cert. These can be found in the folder `/etc/nginx/ssl`.

**Comment by hfalucas** [comment]
Nice! Thank you for the tip @martijn94 :)
