### ISSUE TITLE
after login to ssh, clear and other command looks like shit.

### ISSUE THREAD

**Issue by Richol55486** [laravel/homestead#792]
first: clear command not working.
please check image
http://prntscr.com/hzfx97
please help me

**Comment by svpernova09** [comment]
Downgrade vagrant to version 2.0.0 or use a different console app. Git bash and Cygwin have this issue on windows with vagrant 2.0.1

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by Richol55486** [comment]
thank you, downgraded, it's working.
thank you man
