### ISSUE TITLE
Composer update warning

### ISSUE THREAD

**Issue by it-can** [laravel/homestead#806]
## Versions
  - Vagrant: Vagrant 2.0.2
  - Provider: VMWare Fusion 10
  - Mac OS X High Sierra 10.13.3

I updated my Laravel Homestead box to ```laravel/homestead (vmware_desktop, 5.1.0)```

When running ```vagrant reload --provision``` I noticed a error thrown by Composer.

```
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Update Composer
    homestead-7: You are running composer as "root", while "/home/vagrant/.composer" is owned by "vagrant"
    homestead-7: You are already using composer version 1.6.3 (stable channel).
```

**Comment by svpernova09** [comment]
This is nothing to worry about. This is the result of an upstream change to ensure `.composer` is owned by the vagrant user.

**Comment by antoclk** [comment]
i get this error too and won't let me run correctly my homestead.test
