### ISSUE TITLE
There was a problem while downloading the metadata for your box

### ISSUE THREAD

**Issue by santoshachari** [laravel/homestead#807]
Hi, 

For past few days, Homestead is throwing this message every time I try to start it. I am on latest Vagrant, Virtual box. How can I fix it? 

```
🤘?~ homestead up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: There was a problem while downloading the metadata for your box
==> homestead-7: to check for updates. This is not an error, since it is usually due
==> homestead-7: to temporary network problems. This is just a warning. The problem
==> homestead-7: encountered was:
==> homestead-7: 
==> homestead-7: The requested URL returned error: 404 Not Found
==> homestead-7: 
==> homestead-7: If you want to check for box updates, verify your network connection
==> homestead-7: is valid and try again.
```
All seems fine  on my network

## Versions
  - Vagrant: 2.0.2
  - Provider: Virtualbox 5.2
  - Homestead: Run `homestead --version` to show the version, return''s vagrant's version? I've pulled the latest from master from git repo. 

## Host operating system
MacOS High Sierra 10.13.2

**Comment by svpernova09** [comment]
@browner12 is this what you’re seeing?

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by ricardoseriani** [comment]
I believe that this is due https://atlas.hashicorp.com/ being decomissioned (as you can see when you access https://atlas.hashicorp.com/laravel/boxes/homestead/ ) , please run
```sed -i -- 's/atlas.hashicorp/vagrantcloud/g' ~/.vagrant.d/boxes/*/metadata_url```
and check if this solves the problem
If you aren't on linux, open the file `~/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/metadata_url` using a text editor and change it's content to `https://vagrantcloud.com/laravel/homestead`

**Comment by santoshachari** [comment]
@ricardoseriani It did fix it. Thank you!
Just as note, the first time it threw this: 
```
==> homestead-7: There was a problem while downloading the metadata for your box
==> homestead-7: to check for updates. This is not an error, since it is usually due
==> homestead-7: to temporary network problems. This is just a warning. The problem
==> homestead-7: encountered was:
==> homestead-7: 
==> homestead-7: Illegal characters found in URL
==> homestead-7: 
==> homestead-7: If you want to check for box updates, verify your network connection
==> homestead-7: is valid and try again.
```

I opened the file: 

> ~/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/metadata_url

and deleted _trailing space/new line_.

**Comment by browner12** [comment]
yah, this was the error I was seeing.  I did a `vagrant box add laravel/homestead` which must have updated this file, and fixed it.

**Comment by kiwikefei** [comment]
thanks @bohraji 
`:set noeol` solve the `Illegal characters found in URL` issue.

**Comment by IllyaMoskvin** [comment]
Bash one-liner to fix trailing whitespace after running @ricardoseriani's `sed` command :

    perl -pi -e 'chomp if eof' ~/.vagrant.d/boxes/*/metadata_url

**Comment by dealonzo** [comment]
@ricardoseriani solution works fine for me, I'm in mac and edited the file with textEdit

**Comment by jimmymixer** [comment]
I'm on a Macbook.  I'm having a difficult time.  I originally upgraded the ubuntu after the vagrant up (which took a while), restarted my computer and now I have the same problem.  I tried running "sed -i -- 's/atlas.hashicorp/vagrantcloud/g' ~/.vagrant.d/boxes/*/metadata_url"  .  I'm getting Illegal characters found in the URL.  Time out is taking 2+ minutes.  Vagrant wont run.  If anyone has any advice, it would be much appreciated.

![screen shot 2018-06-11 at 6 42 53 pm](https://user-images.githubusercontent.com/17856353/41260878-4dd295e6-6da7-11e8-9519-a47e4c554644.png)

**Comment by jimmymixer** [comment]
@dealonzo how did you edit the file.  Where did you find the file to edit?

**Comment by ricardoseriani** [comment]
The file is usually in ~/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/metadata_url

**Comment by dealonzo** [comment]
@jimmymixer please see comment above
