### ISSUE TITLE
Warning at vagrant up - can't check for updates

### ISSUE THREAD

**Issue by LexBel-co** [laravel/homestead#816]
A few days ago, when i run vagrant up, i get this:

==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: There was a problem while downloading the metadata for your box
==> homestead-7: to check for updates. This is not an error, since it is usually due
==> homestead-7: to temporary network problems. This is just a warning. The problem
==> homestead-7: encountered was:
==> homestead-7:
==> homestead-7: The requested URL returned error: 404 Not Found
==> homestead-7:
==> homestead-7: If you want to check for box updates, verify your network connection
==> homestead-7: is valid and try again.

## Versions
  - Vagrant: Vagrant 1.9.3
  - Provider: Virtualbox

When i try to update de box with vagrant box update i get:

==> homestead-7: Checking for updates to 'laravel/homestead'
        homestead-7: Latest installed version: 5.0.1
        homestead-7: Version constraints: >= 4.0.0
        homestead-7: Provider: virtualbox
There was an error while downloading the metadata for this box.
The error message is shown below:
The requested URL returned error: 404 Not Found

Any help would be appreciate

**Comment by browner12** [comment]
This is due to Hashicorp changing up their URLs a little.

The easiest way I found to get around this is remove all of your Vagrant boxes, and then re-add the Laravel Homestead box.

If you feel comfortable messing around, you can try this suggestion from another issue as well.

> 
> I believe that this is due https://atlas.hashicorp.com/ being decomissioned (as you can see when you access https://atlas.hashicorp.com/laravel/boxes/homestead/ ) , please run
> sed -i -- 's/atlas.hashicorp/vagrantcloud/g' ~/.vagrant.d/boxes/*/metadata_url
> and check if this solves the problem
> If you aren't on linux, open the file ~/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/metadata_url using a text editor and change it's content to https://vagrantcloud.com/laravel/homestead

**Comment by LexBel-co** [comment]
Thank you @browner12

**Comment by Mark90** [comment]
Thanks @browner12.

This is the first search result so probably more people will end up here. If you're like me and you fired up Vim to edit metadata_url (hoping to save some time) make sure you disable Vim's automatic EOL. Otherwise Vagrant is hopelessly lost on parsing the URL saying "Illegal characters found in URL".

Open Vim in binary mode, e.g. `vim -b ~/.vagrant.d/boxes/debian-VAGRANTSLASH-jessie64/metadata_url`, type the Vim command `:set noeol`, edit the URL and save the file.

**Comment by eduardocruz** [comment]
Ok, so using vim as suggested above, didn't work for me on Mac. (I probably did something wrong) But this did. 
```
perl -pe 'chomp if eof' .vagrant.d/boxes//metadata_url > .vagrant.d/boxes//metadata_url2
mv ~/.vagrant.d/boxes//metadata_url2 ~/.vagrant.d/boxes//metadata_url
```
