### ISSUE TITLE
Use Mailhog by default with sendmail

### ISSUE THREAD

**Issue by adriandmitroca** [laravel/homestead#818]
Hey,

It would be pretty neat to have Mailhog by default attached for sendmail that right now is not working anyway, which can be done pretty quickly by using an alias:
```
/usr/sbin/sendmail -S mail:1025
```
This way simple sites like WordPress could have working mail catcher without any extra efforts.

**Comment by svpernova09** [comment]
We need to install & configure sendmail (in https://github.com/laravel/settler) to send mail via SMTP on port 1025 by default.
