### ISSUE TITLE
The box 'laravel/homestead' could not be found or could not be accessed in the remote catalog. If this is a private box on HashiCorp's Atlas

### ISSUE THREAD

**Issue by jericopulvera** [laravel/homestead#819]
The box 'laravel/homestead' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/laravel/homestead"]
Error: The requested URL returned error: 404 Not Found

Note from atlas.hashicorp.com.

The Packer, Artifact Registry and Terraform Enterprise (Legacy) features of Atlas will no longer be actively developed or maintained and will be fully decommissioned on Friday, March 30, 2018. Please see our guide on building immutable infrastructure with Packer on CI/CD for ideas on implementing Packer and Artifact Registry features yourself and the Upgrading From Terraform Enterprise (Legacy) guide to migrate to the new Terraform Enterprise.

**Comment by lloricode** [comment]
same as mine :|

![screenshot from 2018-02-19 09-12-13](https://user-images.githubusercontent.com/8251344/36359364-6d556880-1555-11e8-80e5-e7a59cb59784.png)

**Comment by svpernova09** [comment]
Please see https://github.com/laravel/homestead/issues/807#issuecomment-363751920

**Comment by jericopulvera** [comment]
@svpernova09 does not solve my issue. I am fresh installing homestead.

#807 (comment) did not work.

**Comment by svpernova09** [comment]
The problem was the URL changed, the solution is to change the download URL in the file or to remove and re-add the box.

**Comment by jericopulvera** [comment]
@svpernova09 I see thanks.

"vagrant box add laravel/homestead https://vagrantcloud.com/laravel/homestead" did this and it works now.

**Comment by davidlares** [comment]
I've been looking for this fix for weeks. It should be on the Laravel official Docs. Thanks a lot.

**Comment by jilster** [comment]
I ran into the same problem, and updating vagrant to the latest version (at the moment 2.0.2) fixed it for me. See: https://www.vagrantup.com/downloads.html

**Comment by Amyavow** [comment]
I just ran into the issue now and I am so glad your solution worked for me @jericopulvera .Thanks

**Comment by midhun1993** [comment]
Hi 
I ran into the same problem on fresh install. i added an additional line on my Vagrantfile
```
config.vm.box_url = "https://vagrantcloud.com/laravel/homestead"
````
above this 

```
Homestead.configure(config, settings)
````
this worked for me.

Thanks

**Comment by Ltmyth** [comment]
https://github.com/midhun1993
thanks that worked for me too

**Comment by brunoAzevedo1** [comment]
Its work for me
sudo ln -s /etc/ssl/cert.pem /opt/vagrant/embedded/cacert.pem

**Comment by sam-fls** [comment]
Okk

**Comment by emanmjr** [comment]
Thanks for this solutions Master @jericopulvera

**Comment by angelburov** [comment]
> 
> 
> I ran into the same problem, and updating vagrant to the latest version (at the moment 2.0.2) fixed it for me. See: https://www.vagrantup.com/downloads.html

 I wanted to confirm that this solution worked for me as well. Thank you!

**Comment by angelburov** [comment]
> 
> 
> I ran into the same problem, and updating vagrant to the latest version (at the moment 2.0.2) fixed it for me. See: https://www.vagrantup.com/downloads.html

 I wanted to confirm that this solution worked for me as well. Thank you @jilster!

**Comment by theshashiverma** [comment]
this issue can also be solved by updating vagrant to its latest version.

**Comment by IrfanGhouri** [comment]
I just uninstalled the vagrant 2.2.7 and re-installed it, my problem was resolved.

**Comment by nuryagdym** [comment]
worked for me thanks @IrfanGhouri

**Comment by abner-ujv** [comment]
In my case I paused my antivirus and it workeds.

```
OS: Windows 10
Antivirus: Kaspersky
```

**Comment by kichito** [comment]
> On my case I paused my antivirus and it worked.
> 
> ```
> OS: Windows 10
> Antivirus: Kaspersky
> ```

It works on win10 with avast antivirus
