### ISSUE TITLE
PostgreSQL 10.1 in Homestead?

### ISSUE THREAD

**Issue by alexagui** [laravel/homestead#820]
My Forge server provisioned with PostgreSQL 10.1 but Homestead is running PostgreSQL 9.5.10

I'm running Homestead v7.1.2 with Vagrant 2.0.0

Is there a way to specify database version for PostgreSQL?

**Comment by svpernova09** [comment]
This will require a base box update

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org
