### ISSUE TITLE
mount error(112): Host is down after vagrant up

### ISSUE THREAD

**Issue by ilarioengler** [laravel/homestead#826]
## Versions
  - Vagrant: 2.0.2
  - Provider: HyperV
  - Homestead: 7.2.0

## Host operating system
Windows: 10 Enterprise N
Version: 1709
OS Build: 16299.15

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 4
provider: hyperv

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/filecloud
      to: /home/vagrant/code/filecloud
      type: nfs

sites:
    - map: filecloud.test
      to: /home/vagrant/code/filecloud/public

databases:
    - homestead
```

## Vagrant destroy & up output

> Failed to mount folders in Linux guest. This is usually because
> the "vboxsf" file system is not available. Please verify that
> the guest additions are properly installed in the guest and
> can work properly. The command attempted was:
> 
> mount -t cifs -o sec=ntlmssp,credentials=/etc/smb_creds_vgt-50afedca901d3799e8ef23913e1eda0b-0b6bccc471df9bbb04fe66355c376193,uid=1000,gid=1000,actimeo=1,nolock //172.19.167.145/vgt-50afedca901d3799e8ef23913e1eda0b-0b6bccc471df9bbb04fe66355c376193 /home/vagrant/code/filecloud
> 
> The error output from the last command was:
> 
> mount error(112): Host is down
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

## Expected behavior
Folder should be mounted.

## Actual behavior
Error as pasted above in "Vagrant destroy & up output" section.
VM starts and is accessible over vagrant ssh, but without the folder mounted.

## Steps to reproduce
1. vagrant box add laravel/homestead
2. git clone https://github.com/laravel/homestead.git ~/Homestead
3. cd ~/Homestead
4. git checkout v7.2.0
5. init.bat
6. copy and paste content of Homestead.yaml
7. vagrant up

**Comment by svpernova09** [comment]
Please post the full output of ‘vagrant destroy && vagrant up’

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by ilarioengler** [comment]
> C:\Users\iengler\Homestead (HEAD detached at f42e0d4 -> origin)
> λ vagrant destroy && vagrant up
> ==> homestead-7: VM not created. Moving on...
> Bringing machine 'homestead-7' up with 'hyperv' provider...
> ==> homestead-7: Verifying Hyper-V is enabled...
> ==> homestead-7: Importing a Hyper-V instance
>     homestead-7: Cloning virtual hard drive...
>     homestead-7: Creating and registering the VM...
>     homestead-7: Setting VM Integration Services
>     homestead-7: Successfully imported a VM with name: ubuntu-16.04-amd64
> ==> homestead-7: Starting the machine...
> ==> homestead-7: Waiting for the machine to report its IP address...
>     homestead-7: Timeout: 120 seconds
>     homestead-7: IP: 172.19.167.156
> ==> homestead-7: Waiting for machine to boot. This may take a few minutes...
>     homestead-7: SSH address: 172.19.167.156:22
>     homestead-7: SSH username: vagrant
>     homestead-7: SSH auth method: private key
>     homestead-7:
>     homestead-7: Vagrant insecure key detected. Vagrant will automatically replace
>     homestead-7: this with a newly generated keypair for better security.
>     homestead-7:
>     homestead-7: Inserting generated public key within guest...
>     homestead-7: Removing insecure key from the guest if it's present...
>     homestead-7: Key inserted! Disconnecting and reconnecting using new SSH key...
> ==> homestead-7: Machine booted and ready!
> ==> homestead-7: Preparing SMB shared folders...
>     homestead-7: You will be asked for the username and password to use for the SMB
>     homestead-7: folders shortly. Please use the proper username/password of your
>     homestead-7: account.
>     homestead-7:
>     homestead-7: Username: iengler
>     homestead-7: Password (will be hidden):
> 
> Vagrant requires administator access to create SMB shares and
> may request access to complete setup of configured shares.
> 
> ==> homestead-7: Setting hostname...
> ==> homestead-7: Mounting SMB shared folders...
>     homestead-7: C:/Users/iengler/Projects/filecloud => /home/vagrant/code/filecloud
> Failed to mount folders in Linux guest. This is usually because
> the "vboxsf" file system is not available. Please verify that
> the guest additions are properly installed in the guest and
> can work properly. The command attempted was:
> 
> mount -t cifs -o sec=ntlmssp,credentials=/etc/smb_creds_vgt-50afedca901d3799e8ef23913e1eda0b-0b6bccc471df9bbb04fe66355c376193,uid=1000,gid=1000,actimeo=1,nolock //172.19.167.145/vgt-50afedca901d3799e8ef23913e1eda0b-0b6bccc471df9bbb04fe66355c376193 /home/vagrant/code/filecloud
> 
> The error output from the last command was:
> 
> mount error(112): Host is down
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

**Comment by svpernova09** [comment]
I can verify this happens. I also have the same issue without using `type: nfs`. Haven't found a fix so far.

**Comment by ilarioengler** [comment]
@svpernova09 yep same for me, I also tried without using `type: nfs`.

**Comment by svpernova09** [comment]
Ah ha, I always forget Vagrant + NFS on Windows won't work and Vagrant just ignores if you specify type NFS: 

https://www.vagrantup.com/docs/synced-folders/nfs.html

```
Windows users: NFS folders do not work on Windows hosts. Vagrant will ignore your request for NFS synced folders on Windows.
```

**Comment by svpernova09** [comment]
Using 

```
folders:
    - map: ~/Projects/filecloud
      to: /home/vagrant/code/filecloud
      type: "smb"
    - map: .
      to: /vagrant
      type: "smb"
```

Should resolve this for you.

**Comment by ilarioengler** [comment]
awesome,  this works! thank you very much :)
