### ISSUE TITLE
Creating certificate fails for map regex

### ISSUE THREAD

**Issue by powelski** [laravel/homestead#831]
In the older versions of Homestead, I was able to define dynamic sites like this:

```
sites:
    - map: ~^(?<project>.+\.test)$
      to: /home/vagrant/code/$project/public
```

Since a while ago, it fails on provisioning with the following error:

> homestead-7: Running: script: Creating Certificate: ~^(?<project>.+\.test)$
> The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Is there any alternative syntax now or one of the most useful features, dynamic mapping, just stopped working?

**Comment by browner12** [comment]
was this actually documented as a feature? I imagine it was just dumb luck that it worked.

**Comment by svpernova09** [comment]
100% fluke this ever worked. It's not something we'd be able to easily support.
