### ISSUE TITLE
 PHP to execute shell_exec is not environment.

### ISSUE THREAD

**Issue by wangwenfan** [laravel/homestead#832]
## Versions
-  vagrant 2.01
- homestead box 5.0.1
I can't use `sudo` permission when I use PHP to execute the `shell_exec()` function in my homestead environment. What's the reason?

Nginx is users are vagrant.

```
shell_exec(" sudo ./test.sh")
```
This sentence cannot be carried out.

**Comment by svpernova09** [comment]
If you're having to use `shell_exec` you should really consider refactoring the shell script into a job.
