### ISSUE TITLE
Unable to operate FTP service

### ISSUE THREAD

**Issue by lybc** [laravel/homestead#833]
when i use laravel storage system to put file in target ftp server, but get some error.

This problem also exists on other people's machines

So I think this may be a bug of homestead or vagrant?

I searched this question, the answer is to use a bridged network, but after configuring the bridged network, this problem still exists.

please help me, thanks !

## Versions
  - Vagrant: 1.9.5
  - Provider: Virtualbox
  - Homestead: 4.0.5

## Host operating system
Windows

## Homestead.yaml
```yaml
---
ip: "192.168.255.99"
memory: 4096
cpus: 1
provider: virtualbox
natdnshostresolver: off

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: E:\source-code
      to: /home/vagrant/source-code
      type: nfs
    - map: E:\resource
      to: /home/vagrant/resource
      type: nfs

sites:
    - map: homestead.ssc
      to: /home/vagrant/source-code/project/php/ssc/public
    - map: homestead.hr
      to: /home/vagrant/source-code/project/php/hr/public
    - map: homestead.soven
      to: /home/vagrant/source-code/project/php/soven/public
    - map: homestead.hp
      to: /home/vagrant/source-code/project/php/hp-report/public
    - map: homestead.admin
      to: /home/vagrant/source-code/project/php/maitrox-admin/public
    - map: homestead.weidiancan
      to: /home/vagrant/source-code/project/php/weidiancan/public
    - map: homestead.wdc_refactor
      to: /home/vagrant/source-code/project/php/weidiancan_refactor/public


databases:
    - homestead

networks:
    - type: "public_network"
      ip: "192.168.4.233"
      bridge: "en1: Wi-Fi (AirPort)"

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
Did not delete the box, just run `vagrant up`

```bash
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Clearing any previously set forwarded ports...
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Specific bridge 'en1: Wi-Fi (AirPort)' not found. You may be asked to specify
==> homestead-7: which network to bridge to.
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
    homestead-7: Adapter 3: bridged
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7: Warning: Remote connection disconnect. Retrying...
==> homestead-7: Machine booted and ready!
==> homestead-7: Checking for guest additions in VM...
==> homestead-7: Setting hostname...
==> homestead-7: Configuring and enabling network interfaces...
==> homestead-7: Exporting NFS shared folders...
==> homestead-7: Preparing to edit nfs mounting file.
[NFS] Status: running
==> homestead-7: Mounting NFS shared folders...
==> homestead-7: Mounting shared folders...
    homestead-7: /vagrant => E:/Homestead
==> homestead-7: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> homestead-7: flag to force provisioning. Provisioners marked to run always will still run.
```

## Expected behavior
create a file in target ftp server

## Actual behavior
error code:

```php
Storage::disk('ftp')->put('filt.txt', 'testtest');
```

outout:
PHP Warning:  ftp_chdir(): Failed to change directory. in /home/vagrant/source-code/project/php/car/code/vendor/league/flysystem/src/Adapter/Ftp.php on line 389

PHP Warning:  ftp_fput(): Illegal PORT command. in /home/vagrant/source-code/project/php/car/code/vendor/league/flysystem/src/Adapter/Ftp.php on line 263

## Steps to reproduce
1. `php artisan tinker`
2. `Storage::disk('ftp')->put('filt.txt', 'testtest');`

**Comment by svpernova09** [comment]
Homestead does not install or configure any FTP server. If possible you should use SFTP.

**Comment by lybc** [comment]
No, I mean I can't access other ftp services in homestead. My PHP website needs to get files via FTP.

**Comment by svpernova09** [comment]
Is the destination server on the same homestead box? What is the storage config settings?

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by lybc** [comment]
@svpernova09 No, With this configuration I can access the target server on the host, but not on the homestead box

```php
'smil_ftp' => [
    'driver'   => 'ftp',
    'host'     => 'test.gds.smil.com',
    'username' => 'ftpmaitrox',
    'password' => '********',
    'passive' => false,
    'timeout' => 30,
]
```

homesteaed box result: 
![image](https://user-images.githubusercontent.com/9601872/38005290-b6aaab96-3272-11e8-925f-3e45bb86db8d.png)

test server result:
![image](https://user-images.githubusercontent.com/9601872/38005300-bf26f4a0-3272-11e8-872d-c67692722769.png)

The weird thing is I can connect to the target FTP server in my homestead box and I can create folders in FTP, but I can't change directory and add files.

always get a warning

![image](https://user-images.githubusercontent.com/9601872/38005643-2a61ca28-3274-11e8-982d-351cd47c326c.png)

**Comment by lybc** [comment]
@svpernova09 please help...   thank you...

**Comment by svpernova09** [comment]
@lybc Sorry I'm not much help here. It's something breaking internall in Flysystem. I don't know enough about the package to debug. I would try opening an issue there. If it comes down to we need something in Homestead to make Flysystem work, I'm happy to investigate.

**Comment by lybc** [comment]
@svpernova09  Thanks for your help，I may know the cause of this problem

Because the vagrant default NAT network cannot access external FTP services

I created a new virtual machine，in the NAT network mode, using the default ftp command still can not connect, but can be connected normally when replaced with bridge network.

### NAT network mode:
![image](https://user-images.githubusercontent.com/9601872/38285412-a46d3040-37f2-11e8-807e-d1fb83fdac06.png)

### bridge network mode:
![image](https://user-images.githubusercontent.com/9601872/38285522-254717f8-37f3-11e8-81b5-d4350c938daf.png)

You can use any FTP server to reproduce the scenario I have described. I believe this problem still exists.

but i don't know how to change the default network mode as bridge, I tried to modify vagrant file and homestead.rb script, but they have no effect.

So I can't confirm whether this is a homestead issue or a vagrant issue or a virtual box issue.
