### ISSUE TITLE
MariaDB 10.2 not installed?

### ISSUE THREAD

**Issue by it-can** [laravel/homestead#853]
I updated my Homestead box to ```laravel/homestead (vmware_desktop, 6.0.0)``` machine runs ```Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64)```

Also added ```mariadb: true``` to Homestead.yaml

It installs MariaDB but only version 10.1.. Is there a way to get 10.2 ?

**Comment by it-can** [comment]
mmm I found this thread, https://askubuntu.com/questions/1033279/ubuntu-upgrade-17-10-to-18-04-moved-my-mariadb-database-to-folder-var-lib-mysql

Seems you can install it like this:

```
sudo apt install mariadb-server-10.2
```

**Comment by svpernova09** [comment]
Ah! it's because we need to update the PPA for 18.04.

**Comment by it-can** [comment]
thanks!
