### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

### ISSUE THREAD

**Issue by sunil-tamang** [laravel/homestead#860]
I installed homestead perfectly first time .
Once i deleted all virtual box, vagrant and homestead files i cant install it again  

What i did    ->   installed : virtual box , vagrant & GitBash then typed the following command  in git 

DexTop@DESKTOP-BV8OJSP MINGW64 ~vagrant box add laravel/homestead

and then i got  this error     OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

**Comment by anup4ranium** [comment]
@sunil-tamang  was you able to resolve this issue ?

**Comment by shallwe99** [comment]
@anup4ranium what need to do about it?

**Comment by anup4ranium** [comment]
I resolved it by copying vagrant box from my colleagues machine to my machine.
If you want to download it, you can run following commands:
vagrant init laravel/homestead -f --box-version 6.1.0
vagrant up
