### ISSUE TITLE
Npm Install failing on Homestead 

### ISSUE THREAD

**Issue by DevDwarf** [laravel/homestead#866]
## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox 5.2.12r122591
  - Homestead: 7.4.2

## Expected behavior
Actually Install packages

## Actual behavior
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! write after end
```
Then nothing.

## Steps to reproduce
1. Do clean install of Homestead
2. Startup Vagrant box
3. create new laravel instillation 
4. run npm install

## References
https://github.com/npm/npm/issues/19989
https://github.com/npm/node-tar/issues/180

## Current Solution
run `npm i -g npm@5.6.0` which downgrades your npm to version 5.6.0 and seems to work then

**Comment by svpernova09** [comment]
Nothing we can do at the Homestead level about NPM bugs (except wait for them to be fixed upstream).

**Comment by pajaro5** [comment]
Try with this:
$ composer update
$ sudo npm install --global cross-env
