### ISSUE TITLE
Cannot start Virtualbox VM on Windows 10 - "Warning: Remote connection disconnect. Retrying." 

### ISSUE THREAD

**Issue by ghost** [laravel/homestead#870]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox 5.2.12
  - Homestead: 7.6.1
(have also tried with VirtualBox 5.1.X and Homestead 7.3.0)

## Host operating system
Windows 10

## Homestead.yaml
```---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
- ~/.ssh/id_rsa

folders:
- map: C:/Workspaces
to: /home/vagrant/code

sites:
- map: homestead.test
to: /home/vagrant/code/public

databases:
- homestead
```

## Vagrant destroy & up output
See https://gist.github.com/KerryRitterWaa/5390afc5d993a33d3a730c5faec506cc for more logs

```
PS C:\Homestead> vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Running provisioner: file...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
PS C:\Homestead> vagrant destroy
    homestead-7: Are you sure you want to destroy the 'homestead-7' VM? [y/N] y
==> homestead-7: Forcing shutdown of VM...
==> homestead-7: Destroying VM and associated drives...
PS C:\Homestead> vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Importing base box 'laravel/homestead'...
==> homestead-7: Matching MAC address for NAT networking...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Setting the name of the VM: homestead-7
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 4040 (guest) => 4040 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7: Warning: Connection reset. Retrying...
    homestead-7: Warning: Connection aborted. Retrying...
    homestead-7: Warning: Remote connection disconnect. Retrying...
    [loops on this for a couple minutes or so]
    homestead-7: Warning: Remote connection disconnect. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

## Expected behavior
`vagrant up` and `vagrant provision` set up the VM and run headless.

## Actual behavior
The 'retry' message loops until 'up' crashes. I have tried running GUI mode. After it says "connection reset. retrying..." and I look at the GUI, it is stuck at the login screen (i tried using config.vm.password to use password auth instead of SSH but the issue persists).

## Steps to reproduce
1. Install Virtualbox v5.2.12.
2. Install Vagrant 2.1.1.
3. `git clone https://github.com/laravel/homestead.git C:/homestead/`, `cd C:/homestead`, `git checkout v7.6.1`
4. `./init.bat`
5. `vagrant up`

## References
I opened a vagrant issue as well at https://github.com/hashicorp/vagrant/issues/9883.

**Comment by svpernova09** [comment]
Can you downgrade to Vagrant 2.0.3 and see if that version works? There's several known issues with Vagrant on Windows that we (Homestead) can't do anything about.

**Comment by KerryRitterWaa** [comment]
I've downgraded Vagrant to 2.0.3. Same results, `Remote connection disconnect. Retrying...` over and over.

**Comment by svpernova09** [comment]
Thanks for trying the downgrade.

Try this (update the paths to your keys)

```
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: C:/Users/username/.ssh/id_rsa.pub

keys:
- C:/Users/username/.ssh/id_rsa

folders:
- map: C:/Workspaces
to: /home/vagrant/code

sites:
- map: homestead.test
to: /home/vagrant/code/public

databases:
- homestead
```

**Comment by KerryRitterWaa** [comment]
I did `vagrant reload --provision` after updating YAML file. I am seeing the same result.

One interesting note is that it says, "Guest communication could not be established! This is usually SSH is not running...", when restarting.

Other steps I have taken were to open port 2222 on my Windows Firewall. I also tried updating the Vagrant file to use usename/password.

**Comment by sfenelon** [comment]
I had the same remote connection problem with a Linux host last week. Never did figure it out.
This week I'm using Windows 10 as the host.

VirtualBox 5.2.12
Vagrant 2.1.1
Homestead v7.6.2
running from git-bash so used init.sh not init.bat

First run of 'vagrant up' failed immediately due to missing private key. 
Generated a private key and tried 'vagrant up' again.
This time it worked but complained about an "insecure key":

```
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7:
    homestead-7: Vagrant insecure key detected. Vagrant will automatically replace
    homestead-7: this with a newly generated keypair for better security.
    homestead-7:
    homestead-7: Inserting generated public key within guest...
    homestead-7: Removing insecure key from the guest if it's present...
    homestead-7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> homestead-7: Machine booted and ready!

```
Provisioning completed as expected.

**Comment by KerryRitterWaa** [comment]
No luck on gitbash :(

```
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
    homestead-7: Warning: Connection reset. Retrying...
    homestead-7: Warning: Connection aborted. Retrying...
    homestead-7: Warning: Connection reset. Retrying...
    homestead-7: Warning: Remote connection disconnect. Retrying...
    homestead-7: Warning: Connection reset. Retrying...
    homestead-7: Warning: Connection aborted. Retrying...
    homestead-7: Warning: Remote connection disconnect. Retrying...
    homestead-7: Warning: Remote connection disconnect. Retrying...
```

**Comment by svpernova09** [comment]
> I did vagrant reload --provision after updating YAML file. I am seeing the same result.

@KerryRitterWaa always destroy and up. provision can produce unreliable outcomes.

**Comment by svpernova09** [comment]
@ sfenelon & @KerryRitterWaa 

Try using Powershell or the basic terminal instead of using git bash.

**Comment by KerryRitterWaa** [comment]
I have tried Powershell, cmd, and git-bash but no luck on any. I have been doing `vagrant destroy` and `vagrant up` to test.

**Comment by svpernova09** [comment]
I see the connect errors (which isn't a Homestead problem, that's Vagrant's territory) but I'm unable to replicate the up command timing out

https://gist.github.com/svpernova09/2ae1ca446fb1d328ed292c80bc409857

Unless we can reliably reproduce I don't know what else we can do to help.

**Comment by leicamvb** [comment]
Se você estiver usando o Windows 10,
Maque "Detectar automaticamente a rede intranet" no Internet Explorer > Opções de Internet > Guia Segurança > Intranet Local > Sites
![local_intranet_automatically_detect_intranet_network_selected-ptbr](https://user-images.githubusercontent.com/10993514/42068057-16c3592e-7b20-11e8-9fba-4f2c2f34af15.png)

Caso não de certo, tente adicionar a rota: route -p add 192.168.10.0 mask 255.255.255.0 192.168.10.1

If you are using Windows 10,
check “Automatically detect intranet network” in Internet Explorer > Settings inside Tools > Intranet Options > Local Intranet > Sites
![local_intranet_automatically_detect_intranet_network_selected](https://user-images.githubusercontent.com/10993514/42068061-1f7e29cc-7b20-11e8-824b-0435cd3ed3c0.png)

If not, try adding the route: route -p add 192.168.10.0 mask 255.255.255.0 192.168.10.1

Resultado / Result
![laravel](https://user-images.githubusercontent.com/10993514/42068155-beb6cbc0-7b20-11e8-9c07-6bdbb362c526.png)

C:\Windows\System32\drivers\etc\hosts:
![host](https://user-images.githubusercontent.com/10993514/42068237-2a313476-7b21-11e8-883d-8f9c917fbea8.jpg)
