### ISSUE TITLE
PHP process error logging

### ISSUE THREAD

**Issue by bmcminn** [laravel/homestead#873]
## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox 5.1.30
  - Homestead: 6.5
  - Lumen: 5.3.3
  - PHP: 7.1

## Host operating system
Windows 10 Pro 64-bit

## General problem
Currently running a fairly outdated version of everything, but that's not the issue.

Looking for some direction on how to fix the lack of PHP logging to the filesystem.

I'm trying to debug a 500 response error due to a `Cannot use object of type stdClass as array` but the 500 response to the client does not return a line number, and I've commented out the contents of the offending route handler, and the error persists. I don't want the `lumen.log` because the PHP process is failing before the log provider is hit, so it's useless in this case.

## Steps taken

I have looked through a dozen different articles on Nginx PHP-FPM logging configs and tried the following:

- Update `/etc/php/7.1/fpm/pool.d/www.conf` error_log configs, `/var/log/php7.1-fpm.error.log` is never updated when PHP errors,
- Update `/etc/php/7.1/fpm/php.ini` since all logging definitions are commented out
    - tell PHP to log to `/var/log/php-fpm.error.log`
    - created log file, nothing...
    - changed permissions of log file, nothing... 
    - restart PHP FPM, nothing...

I'm at a loss for who to proceed in debugging this.

**Comment by svpernova09** [comment]
We wouldn't be able to try to debug this without seeing code, and while this doesn't seem be to a bug report on something in Homestead it sounds like you're better off searching for extra debug levels while in development to ensure everything you expect to find in the log files actually gets logged.

http://php.net/manual/en/function.error-reporting.php
