### ISSUE TITLE
Backup databases before shutdown and/or provision

### ISSUE THREAD

**Issue by gormus** [laravel/homestead#884]
I noticed the new addition via #883 Add support for database backup before destroying vm.

I think it's a great idea, and thank you for adding that feature.

Could that feature be extended to do database backups on each vm halt or provision? That way i can have regular backups of my projects complete with their databases.

**Comment by browner12** [comment]
I don't think we'd want them on `halt` or `provision`. Seems like unnecessary overhead, and neither of those commands will delete DBs.

If we were to do anything, I would say we extract the feature into a bash script the user can choose to execute at their leisure.

**Comment by svpernova09** [comment]
> I don't think we'd want them on halt or provision. Seems like unnecessary overhead, and neither of those commands will delete DBs.

Agreed

> If we were to do anything, I would say we extract the feature into a bash script the user can choose to execute at their leisure.

That's essentially what the export alias is for.
