### ISSUE TITLE
Ability to set php version for each site when using type:apache

### ISSUE THREAD

**Issue by terryupton** [laravel/homestead#890]
Is this a feature that might be implemented?
At the moment we do this on our live server using php-fpm and can set PHP per site.
As the config already allows to set a version, but this is only obeyed in nginx.

type: "apache"
php: "7.0"

type: "apache"
php: "7.1"

type: "apache"
php: "5.6"

As an example.

Also at the moment I am stuck on V6.6 as I need to keep PHP7.1 as the primary php version. Unless there is a way to upgrade but to set the PHP back to an older version.

But the ability to set the pHP version on a per site basis would be super helpful.

Thanks.

**Comment by svpernova09** [comment]
RE: apache + multiple PHP versions

This shouldn't be too hard. It's just finding the time to implement.

RE: Changing default PHP version

You should be able to run `php` + version number from the CLI to set the default PHP version for the CLI.

From the `aliases` file:

```
function php56() {
    sudo update-alternatives --set php /usr/bin/php5.6
}

function php70() {
    sudo update-alternatives --set php /usr/bin/php7.0
}

function php71() {
    sudo update-alternatives --set php /usr/bin/php7.1
}

function php72() {
    sudo update-alternatives --set php /usr/bin/php7.2
}
```

**Comment by svpernova09** [comment]
Resolved via https://github.com/laravel/homestead/releases/tag/v7.11.0
