### ISSUE TITLE
Add graphviz to the default install

### ISSUE THREAD

**Issue by vpratfr** [laravel/homestead#891]
Related to https://github.com/beyondcode/laravel-er-diagram-generator/issues/9

Would be nice to get graphviz installed by default when setting up a new box. That costs just a few MB.

**Comment by svpernova09** [comment]
Added to settler. Thanks!

**Comment by vpratfr** [comment]
Hi,

I am a little new to settler, sorry. 

As a basic Homestead user, does that mean that once I `vagrant box update` I will get the graphviz package already installed in the new VM?

**Comment by svpernova09** [comment]
@vpratfr 

You always want to run the most up to date base box (via `vagrant box update`) but this particular change hasn't made it into a released base box yet. You can see the base box versions here: https://github.com/laravel/settler/releases

**Comment by vpratfr** [comment]
Thanks a lot. No worries if it is not yet available in a box. Good to know it will be in the next release.

Thanks a lot! :)

**Comment by svpernova09** [comment]
yep it will be installed in the next base box update.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org
