### ISSUE TITLE
email not sending

### ISSUE THREAD

**Issue by mhardaniel123** [laravel/homestead#895]
ErrorException: stream_socket_enable_crypto(): SSL operation failed with code 1.

**Comment by svpernova09** [comment]
Unable to help you without all the information in the issue template, and even then, we'd have to see your app's mail settings.

**Comment by mhardaniel123** [comment]
below is my failed_jobs table.

![chrome_not_secure](https://user-images.githubusercontent.com/26666891/42672503-eaf1eac0-8698-11e8-9253-701b3039548c.png)
![failed_jobs_table](https://user-images.githubusercontent.com/26666891/42672504-eb2810e6-8698-11e8-931e-e879f7675f15.PNG)

**Comment by mhardaniel123** [comment]
this are the snippets of errors. pls. help tnx.

![chrome_not_secure](https://user-images.githubusercontent.com/26666891/43057758-a0965304-8e76-11e8-9772-a5eb359a1cbd.png)
![failed_jobs_table](https://user-images.githubusercontent.com/26666891/43057759-a0ca828c-8e76-11e8-929f-46280c746c99.PNG)

**Comment by svpernova09** [comment]
Homestead uses self signed certificates, this is a typical error when you're doing local development. If you review https://laravel.com/docs/5.6/homestead#configuring-mailhog you can see how to configure your app to have Mailhog catch local mail.
