### ISSUE TITLE
You are running Vagrant 2.0.1, which does not satisfy these requirements.

### ISSUE THREAD

**Issue by mohammad6006** [laravel/homestead#905]
I run vagrant box update and everything was ok
after vagrant up I run git pull origin master 

and after that 
 

> This Vagrant environment has specified that it requires the Vagrant
> version to satisfy the following version requirements:
> 
>   >= 2.1.0
> 
> You are running Vagrant 2.0.1, which does not satisfy
> these requirements. Please change your Vagrant version or update
> the Vagrantfile to allow this Vagrant version. However, be warned
> that if the Vagrantfile has specified another version, it probably has
> good reason to do so, and changing that may cause the environment to
> not function properly.
> 

what should I do after git pull?

I follow this document: https://laravel.com/docs/5.6/homestead#updating-homestead

vagrant -v show Vagrant 2.0.1

**Comment by browner12** [comment]
install Vagrant 2.1.0

https://www.vagrantup.com/

**Comment by raoulduke** [comment]
@browner12 `vagrant box update` should update your box to the latest version shouldn't it? I would expect it to update my box to version 2.2 which is the latest.

"This command updates the box for the current Vagrant environment if there are updates available."
- https://www.vagrantup.com/docs/cli/box.html#box-update

**Comment by browner12** [comment]
the Vagrant version is different than the version of the box you are installing.

`vagrant box update` updates this box, which is not what you're looking for in this case.

**Comment by svpernova09** [comment]
Holy Thread Necro.


`vagrant box update` updates the base box *on your system*. It does not update *the base box the current existing vm* (that's impossible). To *apply* the change you'll need to destroy & up.

**Comment by raoulduke** [comment]
Thanks for the info guys. I downloaded and installed 2.2 and was able to bring up my existing box without having to destroy it.
