### ISSUE TITLE
vagrant box add laravel/homestead :- GnuTLS recv error (-54): Error in the pull function.

### ISSUE THREAD

**Issue by hassanshahzadaheer** [laravel/homestead#906]
Hi! I face laravel homestead installation issue. I Install v-box and vagrant successfully on Linux machine ubuntu 16.4 when I add the homestead by running following command

`vagrant box add laravel/homestead` . It can take some time and show this error

`An error occurred while downloading the remote file. The error message, if any, is reproduced below. Please fix this error and try again. GnuTLS recv error (-54): Error in the pull function.`

I change the internet connect multiple time try some other command like vagrant up and vagrant box add laravel/homestead --clean but not get any success I also find some posted solution but not work for me. I also start lampp server but noting change same problem occur again.

can anyone guide what to do and how to install it or any other alternative way to install here is my terminal screenshot https://prnt.sc/k83ubx

thank you so much

**Comment by svpernova09** [comment]
Best I can tell you is it's either a temporary networking issue with your network / ISP, or it's something in your linux machine. Not anything we can do on the Homestead side.
