### ISSUE TITLE
Add vbox and other providers to latest release

### ISSUE THREAD

**Issue by CaddyDz** [laravel/homestead#926]
## Expected behavior
What should have happened?
Ask for the provider like you always did

## Actual behavior
What actually happened?
The latest release on vagrantup.com has vmware box only so vagrant downloaded that

# I lost 1.5 GB of mobile data plan and 1 hour wait time thanks to that so THANK YOU

**Comment by svpernova09** [comment]
Sorry for the troubles. New base box is coming soon™
