### ISSUE TITLE
SSH respond with a non-zero exit status

### ISSUE THREAD

**Issue by lovelamp** [laravel/homestead#931]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
  - Provider: Virtualbox, VMWare or Parallels and its version.
  - Homestead: Run `homestead --version` to show the version.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.
Mac OS 10.3.1 (High Sierra)
## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```
[Homestead copy.txt](https://github.com/laravel/homestead/files/2325003/Homestead.copy.txt)

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.
here is the debug output
using the following command
 vagrant up --debug > vagrant.txt 2>&1
[vagrant.txt](https://github.com/laravel/homestead/files/2325012/vagrant.txt)

## Expected behavior
What should have happened? Please include as much detail as possible.

## Actual behavior
What actually happened? Please include as much detail as possible.
i added the box as normal and run Vagrant up
## Steps to reproduce
1.
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by svpernova09** [comment]
Please fill out the entire issue template so someone has a chance of helping you.
