### ISSUE TITLE
Enable cgi.fix_pathinfo

### ISSUE THREAD

**Issue by ReactionCode** [laravel/homestead#947]
I noticed that latest homestead version have the cgi.fix_pathinfo disabled.

This causes blank page with **Access denied** or **No input file specified** message.

Please consider left it enabled by default on future versions.

For those ho have this issue, enable the fix_pathinfo on your PHP version.

Access into your homestead with vagrant ssh.
    $ sudo nano /etc/php/YOUR PHP VERSION NUMBER/fpm/php.ini 
look for **fix_pathinfo** an set it to **1**;
Save and restart PHP with 
    $ sudo service phpYOUR PHP VERSION NUMBER-fpm restart

**Comment by svpernova09** [comment]
Unless you've changed other settings (or there is a problem with your application) this setting shouldn't need to be changed.

http://php.net/manual/en/ini.core.php#ini.cgi.fix-pathinfo

**Comment by ReactionCode** [comment]
As you can see on your link, this setting should have to be enabled by default, but on latest homestead version comes disabled.

My enviroment is
laravel/homestead (virtualbox, 6.3.0)
Homestead 7.10

The fix_pathinfo are disabled on all PHP versions.

If you use Apache you will get blank page with Access denied or No input file specified message on urls with path_info as

http://demo.test/admin/index.php/configuration/orders?id_order=9

I know how to fix it, but I guess some other could have the same issue.

**Comment by svpernova09** [comment]
You should use `mod_rewrite` rules to get `/index.php/` out of your URL. (if that's a problem you're trying to solve). What I've read about `cgi.fix_pathinfo` that may be what's causing your issues. Not entirely sure.

I use Apache + Homestead everyday in the day job (as do most of my team) and we haven't run into any blank screens.
