### ISSUE TITLE
NPM is outdated

### ISSUE THREAD

**Issue by Doc1337** [laravel/homestead#956]
Sorry for not following the issue template, but in-short:

NPM is outdated there is a new version: 6.4.1 that needs to be installed otherwise NPM will not work.

   
![image](https://user-images.githubusercontent.com/15276167/46410898-981e4d80-c71a-11e8-96d3-4791f97d84cf.png)

**Comment by browner12** [comment]
I'm not following, why will NPM not work on 6.4.0?

You can run this yourself if you'd like, but we will not (can't) update the defaults until a new box is released.

Or you could add this to your `after.sh` script so it runs when you provision.

**Comment by Doc1337** [comment]
> I'm not following, why will NPM not work on 6.4.0?
> 
> You can run this yourself if you'd like, but we will not (can't) update the defaults until a new box is released.
> 
> Or you could add this to your `after.sh` script so it runs when you provision.

Sorry, I misread the part about NPM stopping working in the Terminal.
