### ISSUE TITLE
Run mysql command every reload/up

### ISSUE THREAD

**Issue by octoxan** [laravel/homestead#958]
Is it possible to run a mysql command on every `vagrant up` or `vagrant reload` with homestead?

If not, how hard would this be to implement and where would I start looking?

Reason is, we have to use some old websites that throw an error until you run `set @@global.show_compatibility_56=ON;` in mysql. And for some reason I have to run that every few reloads and it's driving me insane.

**Comment by svpernova09** [comment]
You can add the command to `after.sh` and it will run on every `vagrant up --provision` or if you destroy the box, it will run the next time you run `vagrant up`
