### ISSUE TITLE
install and enable cockroachdb

### ISSUE THREAD

**Issue by parsidev** [laravel/homestead#963]
Hello. 
in homestead i can enable mysql, mariadb, mongodb, elasticsearch, sqlite and postgresql.

How i can install cockroachdb and enable it like databases i wrote above in homestead?

Thanks

**Comment by svpernova09** [comment]
Hi @parsidev,

Take a look at the `install-couch.sh` and `create-couch.sh` files and their usages in `homestead.rb` for a guide on how to implement.

**Comment by parsidev** [comment]
Thanks @svpernova09 but i want to install cockroachdb, not couchdb ....

**Comment by browner12** [comment]
he's saying use that as a jumping off point for you to code your own installation of whichever specific DB you'd like.
