### ISSUE TITLE
A vagrant image takes up too much disk space

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/homestead#965]
## Versions
  - Vagrant: `2.2.0`
  - Provider: virtualbox
  - Homestead: `7.18.0`

## Host operating system
Windows 10 Pro x64

## Actual behavior
I need to process about 15,000 images using the http://image.intervention.io package. Before the operation began, the size of the image was about 10-15 gigabytes. After image processing, the image takes 56 gigabytes and, when the amount of free disk space is about 100 megabytes, virtualbox simply turns off the virtual system.
I am very weak in configuring Linux. Tell me how to reduce the file size. If I understand correctly, it keeps the cache somewhere inside, but I can not find where.

Image processing code:
```php
private function downloadPhotos(Car $car) {
  $car->images
    ->each(function(CarsImage $cars_image) {
      $this->optimizeImage($cars_image->source);
    });
}

private function optimizeImage(string $source) {
  $image = \Image::make($source);

  $image
    ->fit(1920, 1080, function($c) {
      $c->aspectRatio();
      $c->upsize();
    })
    ->save();

  $image->destroy();
}
```

The source files have a resolution of 6000x4000 pixels and a size of about 8 megabytes. After processing the files become in the resolution of 1920x1080 and weighing about 700 kilobytes.
BUT having processed about a couple of hundred files, the system overflows and shuts down.

For cleaning, I tried the following commands:
```
sudo apt autoclean
sudo apt autoremove
sudo rm -rf /tmp/*
```
Next:
```
vagrant reload --provision
```

Last week I was helped by the decision to delete the image and re-recreate it:
```
vagrant destroy homestead-7
vagrant up
```

But before that you have to manually create a backup of all databases, and then deploy them. This is at least inconvenient.

Command `vagrant reload --provision` doesn't help

Question: how to reduce the space occupied by the way?

![2018-10-23 13-12-15 vagrant homestead vagrant](https://user-images.githubusercontent.com/10347617/47354872-8c45fb80-d6c8-11e8-982b-222b7955105b.png)
![2018-10-23 13-12-27 andfeo - total commander x64 9 21a - aton gmbh](https://user-images.githubusercontent.com/10347617/47354873-8c45fb80-d6c8-11e8-9dc7-43f102882377.png)

**Comment by andrey-helldar** [comment]
Clean install after `vagrant destroy homestead-7 && vagrant up`:
![2018-10-23 14-35-47 vagrant homestead](https://user-images.githubusercontent.com/10347617/47358020-33c72c00-d6d1-11e8-8d36-8a12fd686863.png)

**Comment by andrey-helldar** [comment]
It was possible to solve part of the problem:

As it turned out, the configs were cached, so changing the driver to another did not show a difference.

That is, the memory leak problem is observed in imagick version 6.9.7.

And the question about where the data is stored in case of a memory leak is clearly not related to this package.

Therefore, the issue is closed.

**Comment by leejie8008** [comment]
Does it help to reduce the size after you `vagrant destroy homestead-7 && vagrant up`?

**Comment by andrey-helldar** [comment]
@leejie8008, yep.
But doing it every time tires.

**Comment by leejie8008** [comment]
Agree.

**Comment by leejie8008** [comment]
https://medium.com/laravel-news/backup-restore-all-databases-in-laravel-homestead-41475a3d7d7a

This help to export and import all database, might be helpful for you.

**Comment by andrey-helldar** [comment]
@leejie8008, thanks, but I solved this problem a long time ago by going to docker :)
