### ISSUE TITLE
Add domain for the host machine

### ISSUE THREAD

**Issue by olelis** [laravel/homestead#967]
It would be nice to easily connect to host machine from the homestead box. This is already possible, but it requires you to remember ip address of a machine.

One very easy solution is to add one row to /etc/hosts file when provisioning:
10.0.2.2       hostmachine

This way, you can easily refer to hostmachine in for example databse configurations. Instead of localhost, you will use hostmachine.

**Comment by svpernova09** [comment]
Not sure there's a big enough use case for this. Would be curious about implementations, but not clear on the why.
