### ISSUE TITLE
Invalid config file name

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/homestead#968]
## Versions
  - Vagrant: `2.2.0`
  - Provider: `virtualbox`
  - Homestead: `7.18.0`

## Actual behavior
I use the configuration file `Homestead.json`. When specifying a nonexistent path to the key file, the console displays an error:
```
Check your Homestead.yaml file, the path to your private key does not exist.
```
But I do not use the `Homestead.yaml` file ([see](https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L151)).
I do not know this markup language, so I can not send the PR :(

**Comment by svpernova09** [comment]
Thanks for the report, I've resolved this by updating the verbiage in the error: https://github.com/laravel/homestead/releases/tag/v7.19.1
