### ISSUE TITLE
.editorconfig should set indent_size = 2 for Ruby files

### ISSUE THREAD

**Issue by hagabaka** [laravel/homestead#978]
The project's .editorconfig file sets a default `indent_size` of 4 for all files, and adds an exception for *.yml files. It should also add an exception for *.rb files, since scripts/homestead.rb uses 2-space indentation.

**Comment by svpernova09** [comment]
Thanks for opening an issue!

While Ruby syntax *does* specify 2 spaces instead of 4 I have no interest in changing this. (I'm not a fan at all of 2 spaces).

**Comment by hagabaka** [comment]
However scripts/homestead.rb already uses indentation of 2 spaces.

It wouldn't involve changing indentation of other files, just adding overrides for .rb files in .editorconfig.
