### ISSUE TITLE
Add PhpMyAdmin

### ISSUE THREAD

**Issue by Paviluf** [laravel/homestead#987]
Hello,

Is it possible to add PhpMyAdmin please ? It's the only tool that I miss. I'm probably not the only one that miss it. I'm surprised that it's still not included, it's such a common tool.

Thanks and thank you so much for making Homestead !

**Comment by Byronsargeant** [comment]
Just needs to be installed... then dont forget to add the map to the directory in your homestead.yaml file.

**Comment by Paviluf** [comment]
Yeah, but I see no reason to not include it by default.

**Comment by Byronsargeant** [comment]
I agree! I thought you was asking how, read your question quickly! Took me 2 mins to add it!

**Comment by svpernova09** [comment]
With Homestead already exposing local ports for use with MySQL Workbench style tools going to hold off for now.

**Comment by Paviluf** [comment]
Ok I hope you consider it for the futur releases. Thanks.
